
=head1 NAME

mailfiler - rules file format

=head1 DESCRIPTION

The mailfiler(1cs) command's monitor watches Maildirs for newly
arrived messages and files them according to a sequence of rules.

=head1 SYNTAX

=head2 Comments

Blank lines and lines commencing with an octothorpe ('#') are ignored.

=head2 Include Files

A line commencing with a less-than symbol ('<') is an "include" directive.
The following word is the name of a file whose contents are read as though they
appeared at this point in the rules file.
If the filename is relative, it is resolved with respect to the
directory part of the filename of the current rules file.

=head2 Filing Rules

Other lines are mail filing rules, of the general form:

  [=][!]targets tag [!]condition

A line commencing with whitespace is considered to be an additional
condition to be ANDed with the preceeding line's rule conditions:

  [=][!]targets tag condition1
                    condition2
                    condition3

=head3 Delivery Flags

The following indicators may preceed, in order, the targets:

  = An equals symbol ('=') indicates that rule processing should
    cease at this rule if it matches. Normally all matching rules are
    applied.

  ! An exclaimation symbol ('!') indicates that an alert should be
    emitted at the end of filing if this rule was matched.

=head3 Targets

The "targets" is a comma separated list of mail destinations;
a target takes the form of a sequence of nonwhitespace non-comma
characters, or a string value in double quotes.
Note that a shell command in quotes will need any backslashes doubled,
as the quoted string parse strips one level of backslash escaping.

=head4 Variable Assignment

A target of the form:

  VARIABLE=value

or

  VARIABLE="quoted-value"

assigns the value to the named environment variable.
If unquoted, I<value> consists of nonwhitespace characters excluding the comma.
If quoted, I<quoted-value> is a slosh escaped string.
Note that the value is subject to paramater substitution and the
associated slosh escaping and therefore sloshes needed for that
latter phase will need doubling in the B<">I<quoted-value>B<"> form.

=head4 Header Substitution

A target of the form:

  [header:]s/this/that/

performs a regular expression match on the specified header
(by default the "Subject:" header)
and replaces the match with the second string, subject to parameter substitution.
Named subexpressions in the regular expression are available as parameter names in the replacement.

=head4 Functions on Headers

A target of the form:

  header[,header...]:function[(arg,...)]

applies the named I<function> to each instance of the named headers.
If there are no I<arg>s then the parentheses may be omitted.

The I<function> may be either a dotted name of the form I<module_name>B<.>I<function_name> or a simple I<function_name>.

With the former form, the Python module named I<module_name> is imported and the name I<function_name> obtained from it.

For convenience, each I<arg> may take the following forms:

=over 6

=item I<NAME>

An uppercase identifier such as a group name, passed in as a string.

=item B<@>I<domain>

An at symbol ("@") followed by a domain name, passed in as a string.

=item I<number>

A nonnegative integer, passed in as an integer.

=item B<">I<quoted-value>B<">

A quoted value subject to parameter substitution.
The value after substitution is passed in as a string.

=back

The function obtained is called as follows:

  I<function_name>(I<filer>, I<header_names>, *I<args>)

where I<filer> is the internal MessageFiler instance associated with this message,
I<header_names> and I<args> the list of headers and the I<args> supplied with the target respectively.

The following simple function names are supported:

=head4 Message Flags

A target consististing a single capital letter specifies a flag to be applied 
to the message. Supported flags are:

  D Draft
  F Flagged
  P Passed
  R Replied
  S Seen
  T Trashed

=head4 Deliver to Program

A target commencing with a pipe symbol ('|') is considered a command
to run with the message text on its standard input.
If the command exits with a zero exit status is it considered to have run successfully.

=head4 Deliver to Email Address

Otherwise, a target containing an "at" symbol ('@') is considered
an email address to which to send a copy of the message.
If the mail system accepts the message it is considered to have been dispatched successfully.

=head4 Deliver to Mail Folder

Otherwise, a target is considered to indicate a Maildir or a UNIX mbox
into which the message should be placed.

=head3 Delivery

The message must be successfully delivered to all targets of all matching
rules for the filter run to be considered successfully filtered.
If the message matches no rules, delivery is attempted to the targets
specified by the $DEFAULT environment variable.

If all delivery attempts succeed, the original message is removed from the Maildir.
Otherwise the message remains in the Maildir and is ignored on subsequent polls.

=head3 Conditions

A condition may be preceeded by an exclaimation symbol ('!') to invert its meaning.
Example:

  !from:cs@zip.com.au

matches a message not from "cs@zip.com.au".

Conditions are tested against specific message headers.
Unless specified, these headers are the 'To:', 'CC:' and 'BCC:' headers.
Example:

  cs@zip.com.au

matches a message addressed to "cs@zip.com.au".

A condition may be preceeded by a comma separated list of headers.
Example:

  to,from:cs@zip.com.au

matches a message from "cs@zip.com.au" or addressed to "cs@zip.com.au" in the 'To:' header.

A header may be tested against a regular expression instead of by email address:
Example:

  subject:/icewm-Bugs

matches a message with the string "icewm-Bugs" in the 'Subject:' header.

A header may be tested against a variety of special purpose functions
accepting a double quoted string.
Example:

  list-id.contains("<squid-users.squid-cache.org>")

matches a message with the string "<squid-users.squid-cache.org>" in the 'List-ID:' header.

The list of available functions is as follows: B<contains>. (More to come.)

=head1 SEE ALSO

mailfiler(1cs)

=head1 AUTHOR

Cameron Simpson E<lt>cs@zip.com.auE<gt>

