#!/bin/sh
#
# Read a mail folder with mutt.
#	- Cameron Simpson <cs@zip.com.au>
#

case "$HOST@$SYSTEMID" in
    zapff@cisra|amadeus@home)
	;;
    *)	echo "$0: must be on zapff@cisra or amadeus@home" >&2
	exit 1
	;;
esac

[ $# = 0 ] && set attn
[ $# = 1 ] || { echo "Usage: $0 [mutt-folder]" >&2; exit 2; }
folder=$1; shift
case "$folder" in
    +*)		mfolder=$folder ;;
    *.*)	mfolder=nntp://$NNTPSERVER/$folder ;;
    *)		mfolder=+$folder ;;
esac

cd || exit 1
exec term +ip -n "mutt $folder" scrif "mutt_$folder" mutt -f "$mfolder"
