#!/bin/sh
#
# Read a mail folder with mutt.
#	- Cameron Simpson <cs@zip.com.au>
#

[ $# = 0 ] && set attn

if lock -q "mail/$1"
then  echo "mail/$1 already locked" >&2
      exit 1
fi

cd || exit 1
RXVTOPTS=+ip GUI=lean rterm zapff@cisra -n "mutt +$1" lock "mail/$1" mutt -f "+$1"
