#!/bin/sh
#
# Search for stuff with mairix and then run up the result in mutt.
#	- Cameron Simpson <cs@zip.com.au> 01jan2003
#

cmd=`basename "$0"`
usage="Usage:     $cmd    Update mairix index.
	$cmd mairix-search-args... Search and display."

mairix=/opt/mairix/bin/mairix
rc=$HOME/rc/mairix.$SYSTEMID

# help?
[ "x$*" = x-h -o "x$1" = 'x-?' ] && { echo "$usage"; exit 0; }

[ $# = 0 ] && exec mrx-update "$MAILDIR/"*

res=`mrx-query "$@"` || exit 1

term -n "++ $*" -e + -f +t -R "$res"
rm -rf "$res"

exit 0
