#!/bin/sh -u
#
# Connect to my IMAP folder.
#	- Cameron Simpson <cs@zip.com.au> 09sep2003
#

cmd=`basename "$0"`
usage="Usage: $cmd [[user:pass@]server]"

server=zipworld-direct
fmrc=$HOME/.fetchmailrc
trace=set-x

[ $# = 0 ] || { server=$1; shift; }

sv_user=
sv_pass=
case "$server" in
  *:*@*)
    sv_user=`expr "x$server" : 'x\([^:]*\):.*'`
    sv_pass=`expr "x$server" : 'x[^:]*:\([^@]*\)@.*'`
    server=`expr "x$server" : 'x[^:]*:[^@]*@\(.*\)'`
    ;;
esac

[ -s "$fmrc" ] || { echo "$cmd: no $fmrc" >&2; exit 1; }

fm_user=
fm_pass=
fm_host=$server
eval `fetchmailclause -f "$fmrc" "$server" | detab | sed -n 's/^\([^ ][^ ]*\) /sv_\1=/p'`
[ -n "${sv_user:=}" ] && fm_user=$sv_user
[ -n "${sv_pass:=}" ] && fm_pass=$sv_pass
[ -n "${sv_via:=}"  ] && fm_host=$sv_via

exec $trace + +s +t \
	-e "set imap_pass=\"$fm_pass\"" \
	--pre='set-x fmprod -STOP' \
	--post='set-x fmprod -CONT' \
	imaps://$fm_user@$fm_host/INBOX
