#!/bin/sh
#
# Connect to my IMAP folder.
#	- Cameron Simpson <cs@zip.com.au> 09sep2003
#

cmd=`basename "$0"`
usage="Usage: $cmd [[user:pass@]server]"

server=mail.zipworld.com.au

[ $# = 0 ] || { server=$1; shift; }

sv_user=
sv_pass=
case "$server" in
  *:*@*)
    sv_user=`expr "x$server" : 'x\([^:]*\):.*'`
    sv_pass=`expr "x$server" : 'x[^:]*:\([^@]*\)@.*'`
    server=`expr "x$server" : 'x[^:]*:[^@]*@\(.*\)'`
    ;;
esac

fm_user=
fm_pass=
eval `fetchmailclause -f $HOME/var/fetchmail/fetchmailrc "$server" | sed 's/^\([^ ][^ ]*\) /fm_\1=/'`
[ -n "$sv_user" ] && fm_user=$sv_user
[ -n "$sv_pass" ] && fm_pass=$sv_pass

tunnel=
case "$server" in
  mail.zipworld.com.au)
    tunnel="sshb zip nc $server imap" ;;
esac

set -x
exec + \
	-e "set imap_force_ssl=no" \
	-e "set imap_pass=\"$fm_pass\"" \
	-e "set tunnel=\"$tunnel\"" \
	imap://$fm_user@$server/INBOX
