#!/bin/sh
#
# Connect to my IMAP folder.
#	- Cameron Simpson <cs@zip.com.au> 09sep2003
#

server=mail.zipworld.com.au

eval `fetchmailclause -f $HOME/private/fetchmailrc "$server" | sed 's/^\([^ ][^ ]*\) /fm_\1=/'`

tunnel=
case "$server" in
  mail.zipworld.com.au)
    tunnel="exec ssh zip nc $server imap" ;;
esac

exec + \
	-e "set imap_force_ssl=no" \
	-e "set imap_pass=\"$fm_pass\"" \
	-e "set tunnel=\"$tunnel\"" \
	imap://$fm_user@$server/INBOX
