#!/bin/sh
#
# Convert input to PostScript.
#	- Cameron Simpson <cs@zip.com.au> 12dec1996
#
# Convert to MIME basis. - cameron 29apr2004
#

me=$0
cmd=`basename "$0"`
usage="Usage: $cmd [-i itype] [-T title] [file]"

aspect=-R

title=
badopts=
mtype=
while :
do  case $1 in
	-T)	title=$2; shift ;;
	-L)	aspect=-r ;;
	-P)	aspect=-R ;;
	-i)	mtype=$2; shift
		case "$mtype" in
		    any)		mtype= ;;
		    ps|postscript)	mtype=application/postscript ;;
		    pdf)		mtype=application/pdf ;;
		    mentor)		mtype=application/mentor ;;
		    text)		mtype=text/plain ;;
		    */*)		;;
		    *)			echo "$cmd: unrecognised file type \"$mtype\"" >&2
					badopts=1
					;;
		esac
		;;
	--)	shift; break ;;
	-*)	echo "$cmd: unrecognised option: $1" >&2
		badopts=1
		;;
	*)	break ;;
    esac
    shift
done

txtconv="$txtconv $aspect"
[ -n "$title" ] && txtxconv="$txtconv \"--footer=\$title\""

if [ $# = 0 ]
then
  file=-
else
  file=$1; shift
  [ $# = 0 ] || { echo "$cmd: extra arguments after file: $*" >&2; badopts=1; }
fi

[ $badopts ] && { echo "$usage" >&2; exit 2; }

tmpfile=${TMPDIR:-/tmp}/$cmd$$
filetitle=$file
if [ "x$file" = x- ]
then
    filetitle=stdin
    trap 'rm -f "$tmpfile"' 0 1 15
    cat >"$tmpfile" || exit 1
    file=$tmpfile
fi

[ -n "$title" ] || title=$filetitle
[ -n "$mtype" ] || mtype=`file2mime "$file"` || exit 1

case "$mtype" in
    application/pdf)	conv='pdf2ps /dev/fd/0' ;;
    application/postscript) conv=cat ;;
    application/mentor)	conv=mentor2ps ;;
    text/plain)		conv='a2ps -1 -o- -b "$title" -T 8 -i --borders=no -b $aspect --medium=A4 -f 10' ;;
    text/html)		conv=unhtml ;;
    image/*)		conv='convert - ps:-' ;;
    *)			echo "$cmd: supported input type \"$mtype\"" >&2
			exit 1
			;;
esac

## echo "title=[$title], conv=[$conv]" >&2
## set | egrep -i '(asp|conv)' >&2
##set -vx
eval "exec <\"\$file\"; $conv"
