#!/bin/sh
#
# Open fresh shell on target machine in new window.
#	- Cameron Simpson <cs@zip.com.au> 23oct2001
#

cmd=$0
usage="Usage: $cmd [hosts...]"

if [ $# = 0 ]
then
  case $HOST@$SYSTEMID in
    kaper@cisra)
	set cage,ferrari,linux,solaris,cass,sweet,screen:root@ivory,screen:elph,screen:root@sunny ;;
    amadeus@home)
	set jekyll,janus,alpha ;;
    newt@home)
	set amadeus,janus ;;
    *)	echo "$0: no default host list for SYSTEMID == \"$SYSTEMID\"" >&2
	exit 1
    ;;
  esac
fi

host=$1; shift

case "$host" in
    *,*)
	[ -n "$DISPLAY" ] || { echo "$cmd: can't do multiple sessions without a \$DISPLAY" >&2
			       exit 1
			     }
	for h in `echo "$host" | tr , ' '`
	do  "$0" "$h" ${1+"$@"}
	done
	exit 0
	;;
    root@*)
	exec root@ "$host"
	;;
    screen:root@*)
	name=`expr "$host" : 'screen:\(.*\)'`
	host=`expr "$name" : 'root@\(.*\)'`
	exec term -e scr "$name" nox root@ "$host"
	;;
    screen:*)
	host=`expr "$host" : 'screen:\(.*\)'`
	exec rterm "$host" -s ${1+"$@"}
	;;
    bos)exec "$0" screen:lexx,screen:moya,screen:sv1,screen:sv2,screen:sv3 ;;
    rita)
	set -x
	rdesktop -g "${X11_BGX}x${X11_Y}" -K -T "$host rdesktop" "$host" &
	;;
    *)	exec rterm "$host" ${1+"$@"}
	;;
esac
