#!/bin/sh
#
# Take the environment $CLASSPATH and resolve into absolute classpath
# using $CLASSPATHPATH envvar.
#	- Cameron Simpson <cs@zip.com.au> 14feb2003
#

CLASSPATHPATH=${CLASSPATHPATH:-"$HOME/rc/java $JAVA_HOME/jre/lib/ext"}
export CLASSPATHPATH

cpath=
for cp in `unpath "$CLASSPATH"`
do
  case "$cp" in
    /*)	;;
    *)
	for cpp in `unpath "$CLASSPATHPATH"`
	do
	  if [ -f "$cpp/$cp" ]
	  then
	    cp="$cpp/$cp"
	    break
	  fi
	done
	;;
  esac

  [ -n "$cpath" ] && cpath=$cpath:
  cpath=$cpath$cp
done

CLASSPATH=$cpath
export CLASSPATH

[ $# = 0 ] && { echo "$CLASSPATH"; exit 0; }
exec "$@"
