#!/bin/sh
#
# Read a mailbox naively made by a procmail which doesn't stash From_ lines,
# and add From_ lines.
#	- Cameron Simpson <cs@zip.com.au> 08nov2002
#


from=`set \`date\`; echo "From $EMAIL $1 $2 $3 $4 $6"`

##set -x
exec sed -ne "
1{
  i\\
$from
  p
  n
}
:top
/^\$/b empty
p
d
:empty
p
n
/^Received:/!b top
i\\
$from
p
d" ${1+"$@"}
