#!/bin/sh
#
# Put up a new ISO on the jukebox server.
#	- Cameron Simpson <cs@zip.com.au> 18sep2002
#

src=/dev/cdrom
dest=/home/ferrari/cdroms

cmd=`basename "$0"`
usage="Usage: $cmd [-f file] [-d dir] vendor appname version
	-f file	Source file. Default: $src
	-d dir	Destination directory. Default: $dest"

badopts=
while :
do  case $1 in
	-f)	src=$2; shift ;;
	-d)	dest=$2; shift
		[ -d "$dest/." ] || { echo "$cmd: no such directory: $d" >&2
				      badopts=1
				    }
		;;
	--)	shift; break ;;
	-?*)	echo "$cmd: unrecognised option: $1" >&2
		badopts=1
		;;
	*)	break ;;
    esac
    shift
done

if [ $# = 3 ]
then
    vendor=$1 appname=$2 version=$3
    shift; shift; shift
    case "$vendor$appname$version" in
	*/*)	echo "$cmd: no slashes permitted in vendor, appname or version" >&2
		badopts=1
		;;
    esac
else
    echo "$cmd: missing vendor, appname or version" >&2
    badopts=1
fi

[ $badopts ] && { echo "$usage" >&2; exit 2; }

umask 2
target=$dest/$vendor
[ -d "$target/." ] || (set -x; mkdir "$target") || exit 1

iso=$target/$appname-$version.iso
[ -s "$iso" ] && { echo "$cmd: already exists: $iso" >&2
		   exit 1
		 }

prcat "$src" >"$iso"
xit=$?

ls -ld "$iso"
exit $xit
