#!/bin/sh
#
# Add a link page URL to a list of link pages.
#	- Cameron Simpson <cs@zip.com.au> 04aug2000
#

cmd=$0

: ${LINKPAGEPATH:=$HOME/.linkpages}

verbose=1
##[ -t 0 ] && verbose=1

usage="Usage: $cmd [-d dir] [topic] [urls...]"

badopts=

[ "x$1" = x-d ] && { LINKPAGEPATH=$2; shift; shift
		     export LINKPAGEPATH
		   }

topic=
case $1 in
    ''|*://*)	topic=$LINKPAGETOPIC ;; # URL - take default topic
    *)		topic=$1; shift ;;
esac

[ -n "$topic" ] || topic=`lastvalue addlinkpage`
if [ -z "$topic" ]
then
    echo "$cmd: missing topic and no \$LINKPAGETOPIC envvar" >&2
    badopts=1
fi

if [ $# = 0 ]
then
  [ -n "$DISPLAY" ] && { set -- `xclip -o` || exit 1; }
  [ $# = 0 ] && { echo "$cmd: no args and nothing from xclip" >&2
		  badopts=1
		}
fi

case "$topic" in
    */*)	echo "$cmd: bad topic \"$topic\"" >&2
		badopts=1
		;;
esac

[ $badopts ] && { echo "$usage" >&2; exit 2; }

topicfile=
for dir in `unpath "$LINKPAGEPATH"`
do  for subdir in urls/ ''
    do  topicfile=$dir/$subdir$topic
	[ -f "$topicfile" ] && break
    done
    [ -f "$topicfile" ] && break
done

[ -f "$topicfile" ]  || { echo "$cmd: can't find topic \"$topic\" in \$LINKPAGEPATH" >&2
			  exit 1
			}

lastvalue addlinkpage "$topic"

for url
do  [ $verbose ] && echo "$url >> $topicfile" >&2
    if [ "x$url" = x- ]
    then  cat
    else  echo "$url"
    fi >>"$topicfile"
done
