#!/bin/sh
#
# Add a link page URL to a list of link pages.
#	- Cameron Simpson <cs@zip.com.au> 04aug2000
#

cmd=$0

LINKPAGEPATH=${LINKPAGEPATH:-$HOME/.linkpages}
export LINKPAGEPATH

verbose=1
##[ -t 0 ] && verbose=1

usage="Usage: $cmd [-d dir] [topic] [urls...]"

badopts=

[ "x$1" = x-d ] && { LINKPAGEPATH=$2; shift; shift
		     export LINKPAGEPATH
		   }

topic=
case $1 in
    ''|*://*)	topic=$LINKPAGETOPIC ;; # URL - take default topic
    *)		topic=$1; shift ;;
esac

[ -n "$topic" ] || topic=`lastvalue addlinkpage`
if [ -z "$topic" ]
then
    echo "$cmd: missing topic and no \$LINKPAGETOPIC envvar" >&2
    badopts=1
fi

if [ $# = 0 ]
then
  if [ -t 0 ]
  then
      [ -n "$DISPLAY" ] && { set x `cutbuffer`; shift; }
  else
      set x `cat`; shift
  fi
fi
[ $# = 0 ] && { echo "$cmd: no URLs and no X clipboard" >&2
		badopts=1
	      }

case "$topic" in
    */*)	echo "$cmd: bad topic \"$topic\"" >&2
		badopts=1
		;;
esac

[ $badopts ] && { echo "$usage" >&2; exit 2; }

topicfile=
for dir in `unpath "$LINKPAGEPATH"`
do  for subdir in urls/ ''
    do  topicfile=$dir/$subdir$topic
	[ -f "$topicfile" ] && break
    done
    [ -f "$topicfile" ] && break
done

[ -f "$topicfile" ]  || { echo "$cmd: can't find topic \"$topic\" in \$LINKPAGEPATH" >&2
			  exit 1
			}

lastvalue addlinkpage "$topic"

[ $# = 0 ] && { [ $verbose ] && echo "Reading URLs from stdin..." >&2
		set -- `cat`;
	      }

for url
do  [ $verbose ] && echo "$url >> $topicfile" >&2
    echo "$url" >>"$topicfile"
done
