#!/bin/sh
#
# Run app-helper with the autoview mode on, defaulting to view-unknown.
#	- Cameron Simpson <cs@zip.com.au> 17dec2002
#

cmd=$0
if [ $# = 0 ]
then
    if [ -n "$DISPLAY" ]
    then
	set -- "`xclip -o`" || exit 1
    else
	echo "Usage: $cmd file [command [args...]]" >&2
	exit 2
    fi
fi

[ $# = 1 ] && { set x "$1" view-unknown; shift; }
file=$1; shift
exec apphelper "$file" -y "$@"
