#!/bin/sh
#
# Run app-helper with the autoview mode on, defaulting to view-unknown.
#	- Cameron Simpson <cs@zip.com.au> 17dec2002
#

cmd=$0

unlink=
ahopts=
while :
do
  case "$1" in
    -u)		unlink=1 ;;
    -[nyNYAX])	ahopts="$ahopts $1" ;;
    *)		break ;;
  esac
  shift
done

if [ $# = 0 ]
then
    if [ -n "$DISPLAY" ]
    then
	set -- "`xclip -o`" || exit 1
    else
	echo "Usage: $cmd file [command [args...]]" >&2
	exit 2
    fi
fi

[ $# = 1 ] && set -- "$1" view-unknown
file=$1; shift
##set -x
apphelper "$file" -y $ahopts "$@" || exit 1

# unlink old copy?
[ $unlink ] || exit 0
[ -s "$file" ] || exit 0
loc=`fileloc "$file"` || exit 1
[ "x$loc" = "x$file" ] && exit 0
exec rm -- "$file"
