#!/bin/sh

: ${LOGDIR:=$HOME/var/log}

tty=`tty`
[ -n "$tty" ] && echo "$tty" >"$LOGDIR/alertlog-$DISPLAY@$HOST"

cd "$LOGDIR"
ctrl=tailf-fvwm-$HOST
>$ctrl
exec tailf -c "$ctrl" -i 1 alert vpnlog-*-alert
