#!/bin/sh

LOGDIR=${LOGDIR:-$HOME/var/log}
export LOGDIR

tty=`tty`
[ -n "$tty" ] && echo "$tty" >"$LOGDIR/alertlog-$DISPLAY@$HOST"

cd "$LOGDIR"
ctrl=tailf-fvwm-$HOST
>$ctrl
exec tailf -c "$ctrl" -i 1 alert vpnlog-*-alert
