#!/bin/sh
#
# Run command asynchronously with output to a logfile.
#	- Cameron Simpson <cs@zip.com.au> 09feb2002
#

: ${LOGDIR:=$HOME/var/log}

cmd=$0
usage="Usage: $cmd logfile cmd [args...]"

badopts=
case $# in
    0)	echo "$cmd: missing logfile" >&2; badopts=1 ;;
    1)	echo "$cmd: missing cmd" >&2; badopts=1 ;;
esac

[ $badopts ] && { echo "$usage" >&2; exit 2; }

logfile=$1; shift
case "$logfile" in
    /*)	;;
    *)	logfile=$LOGDIR/$logfile ;;
esac

exec </dev/null
exec >>"$logfile" 2>&1
ignhup "$@" &

exit 0
