#!/bin/sh
#
# Read an email message from stdin, announce to alert log.
#	- Cameron Simpson <cs@zip.com.au> 28mar2002
#

folder=$1
summary=`email-summary-line`
exec alert -c yellow "`timecode` $folder $summary"
