#!/bin/sh
#
# Offer a list of background images.
# Mostly used by Eterm (via et) to pick a background.
#	- Cameron Simpson <cs@zip.com.au> 10may1999
#
# Use an INDEX file instead of find.	- cameron 15aug2000
#

random=
n=0
tall=
wide=
gotptns=

cmd=$0
usage="Usage: $cmd [-t] [-w] [-r] [-n count] [ptns... [-- directories...]]
	-r	Randomise output.
	-n count Choose the first count items.
	-t	Choose tall images (eg for tty backgrounds).
	-w	Choose wide images (eg for wallpaper)."

badopts=
while :
do
    case $1 in
      -n)	n=$2; shift ;;
      -r)	random=1 ;;
      -t)	tall=1 ;;
      -w)	wide=1 ;;
      --)	gotptns=1; shift; break ;;
      -?*)	echo "$cmd: unrecognised option: $1" >&2
		badopts=1
		;;
      *)	break ;;
    esac
    shift
done

[ $badopts ] && { echo "$usage" >&2; exit 2; }

ptns=

if [ -z "$gotptns" ]
then
    while [ $# -gt 0 ]
    do  case "$1" in
	  --)	gotptns=1; shift; break ;;
	  *)	ptns="$ptns '$1'"; shift ;;
	esac
    done
fi

# no dirs?
[ $# = 0 ] && { set x `bgdirs`; shift; }

filter="awk '{ print \$3 }'"
if [ $tall ]
then
    filter="awk '\$1 <= \$2 { print \$3 }'"
else
    if [ $wide ]
    then
	filter="awk '\$1 >= \$2 { print \$3 }'"
    fi
fi

[ -n "$ptns" ] && filter="$filter | grepall $ptns"

[ $random ] && filter="$filter | shuffle"
[ "x$n" = x0 ] || filter="$filter | sed '${n}q'"

for dir
do
    ndx=$dir/INDEX
    if [ -s "$ndx" ]
    then  sed "s;^[1-9][0-9]*  *[1-9][0-9]*  *;& $dir/;" <"$ndx"
    else  if [ -s "$ndx.gz" ]
	  then  gunzip < "$ndx.gz" | sed "s;^[1-9][0-9]*  *[1-9][0-9]*  *;& $dir/;"
	  else  if [ -s "$ndx.bz2" ]
		then  bunzip2 < "$ndx.bz2" | sed "s;^[1-9][0-9]*  *[1-9][0-9]*  *;& $dir/;"
		fi
	  fi
    fi
done \
| ( : set -x; eval "$filter"; cat >/dev/null )
