#!/bin/sh
#
# Background command but keep attached to stdin.
#	- Cameron Simpson <cs@zip.com.au> 12sep2000
#

: ${VARLOG:=$HOME/var/log}
: ${CONSOLE:=$VARLOG/console}

cmd=$0
usage="Usage: $cmd [-s|-C] command [args...] <input
	-s	Silent. Send stdout and stderr to /dev/null.
	-C	Console. Send stdout and stderr to \$CONSOLE."

output=
case $1 in
  -s)	output=/dev/null; shift ;;
  -C)	output=$CONSOLE; shift ;;
esac

[ $# = 0 ] && { echo "$usage" >&2; exit 2; }

exec 3<&0
( exec 0<&3 3<&-
  [ -n "$output" ] && exec >>"$output" 2>&1
  exec "$@"
) &

exit 0
