#!/bin/sh -u
#
# Dispatch my preferred browser.
# Compare to $BROWSER, which is for opening a fresh window in the browser.
#	- Cameron Simpson <cs@zip.com.au> 08aug2004
#

: ${VARRUN:="$HOME/var/run"}
: ${BROWSER_PROFILE:=$USER@$HOST}

url=
profile=$BROWSER_PROFILE
##br=/opt/firefox-1.5.0.7-enGB/firefox
##br=/opt/firefox-2.0-enGB/firefox
br=/opt/firefox-2.0.0.1-enGB/firefox

cmd=$0
usage="Usage: $cmd [-f] [-q] [url]
	-P profile	Select desired profile.
			Default from \$BROWSER_PROFILE: $profile"

badopts=

while [ $# -gt 0 ]
do
  case "$1" in
    -P)	profile=$2; shift ;;
    --)	shift; break ;;
    -?*)echo "$cmd: unrecognised option: $1" >&2; badopts=1 ;;
    *)	break ;;
  esac
  shift
done

[ $# = 0 ] || { url=$1; shift; }

[ $# = 0 ] || { echo "$cmd: extra argments after URL: $*" >&2; badopts=1; }

[ $badopts ] && { echo "$usage" >&2; exit 2; }

[ -n "$url" ] && set -- "$url"

set -x
histbackup -x --delete-excluded "$HOME/var/firefox" "$HOME/var/backup/firefox"
bsed '/^user_pref("permissions.default.image"/d; $a\
user_pref("permissions.default.image", 2);' "$HOME/.mozilla/firefox/subdir/prefs.js"
acon "$br" -width "$FULLX" -height "$PIX_HIGH" -P "$profile" ${1+"$@"} &
