#!/bin/sh -u
#
# Dispatch my preferred browser.
# Compare to $BROWSER, which is for opening a fresh window in the browser.
#	- Cameron Simpson <cs@zip.com.au> 08aug2004
#

: ${VARRUN:="$HOME/var/run"}
: ${BROWSER_PROFILE:=$USER@$HOST}

url=
profile=$BROWSER_PROFILE
br=${FIREFOX_BIN:-/opt/firefox/firefox}
prefs=$HOME/.mozilla/firefox/subdir/prefs.js

cmd=$0
usage="Usage: $cmd [-f] [-q] [url]
	-P profile	Select desired profile.
			Default from \$BROWSER_PROFILE: $profile"

badopts=

while [ $# -gt 0 ]
do
  case "$1" in
    -P)	profile=$2; shift ;;
    --)	shift; break ;;
    -?*)echo "$cmd: unrecognised option: $1" >&2; badopts=1 ;;
    *)	break ;;
  esac
  shift
done

[ $# = 0 ] || { url=$1; shift; }

[ $# = 0 ] || { echo "$cmd: extra argments after URL: $*" >&2; badopts=1; }

[ $badopts ] && { echo "$usage" >&2; exit 2; }

[ -n "$url" ] && set -- "$url"

echo >>"$prefs"
histbackup -x --delete-excluded \
        "$HOME/var/firefox" "$HOME/var/backup/firefox" \
        '--exclude=/*/Cache' '--exclude=/*/browserstate-logs' '--exclude=/*/*.mfasl' '--exclude=/*/urlclassifier2.sqlite'

bsed '/^user_pref("permissions.default.image"/d
      /^user_pref("extensions.tabmix.progressMeter"/d
      /^user_pref("javascript.enabled"/d
$a\
user_pref("javascript.enabled", false);\
user_pref("extensions.tabmix.progressMeter", false);\
user_pref("permissions.default.image", 2);' "$prefs"

exec "$br" -width "$FULLX" -height "$PIX_HIGH" -P "$profile" ${1+"$@"}
