#!/bin/sh
#
# Log a fresh bug in the specified bug system.
# Default: the first supported bug in the $BUGSYSTEMS envvar, defaulting to mailto:$USER.
#	- Cameron Simpson <cs@zip.com.au>
#

sev=2

cmd=$0
usage="Usage: $cmd [-B bugsystem] [severity] title-words...
	-B bugsystem	Specify the bugsystem.
			Supported: ddts, mailto:addr.
	severity	A number in the range 1-5. Default: $sev"

case "$1" in [1-5]) sev=$1; shift ;; esac
[ $# = 0 ] && { echo "Usage: $0 bug [severity] title" >&2; exit 2; }

( exec 3>&1
  if [ -t 0 ]
  then
      echo
  else
      [ -t 3 ] && echo "Reading bug details from stdin ..." >&3
      exec cat
  fi
) \
| \
{
  xit=1
  for bugsystem in $BUGSYSTEMS "mailto:$USER"
  do
    case "$bugsystem" in
      ddts)
	pro=sa.maintenance
	exec 3>&1
	if [ -t 0 ]
	then
	    echo
	else
	    [ -t 3 ] && echo "Reading bug details from stdin ..." >&3
	    cat
	fi | mkddtsrq -S "$sev" -p "$pro" "$*"
	xit=$?
	break
	;;
      tdl)
	td --add "$*"
	xit=$?
	break
	;;
      mailto:*)
	buglog "$*"
	xit=$?
	break
	;;
    esac
  done
  exit "$xit"
}
