#!/bin/sh
#
# Log a fresh bug in the specified bug system.
# Default: the first supported bug in the $BUGSYSTEMS envvar, defaulting to mailto:$USER.
#	- Cameron Simpson <cs@zip.com.au>
#

: ${USER:=`whoami`}
: ${BUGSYSTEMS:=`bugsystems`}

sev=2

cmd=$0
usage="Usage: $cmd [-B bugsystem] [severity] title-words...
	-B bugsystem	Specify the bugsystem.
			Supported: ddts, mailto:addr.
	severity	A number in the range 1-5. Default: $sev"

[ "x$1" = x-B ] && { BUGSYSTEMS=$2; shift; }
case "$1" in [1-5]) sev=$1; shift ;; esac
[ $# = 0 ] && { echo "Usage: $0 bug [severity] title" >&2; exit 2; }

exec 3>&1

(
  if [ -t 0 ]
  then
      echo
  else
      [ -t 3 ] && echo "Reading bug details from stdin ..." >&3
      exec cat
  fi
) \
| \
{
  xit=1
  for bugsystem in $BUGSYSTEMS "mailto:$USER"
  do

    case "$bugsystem" in
      /?*/?*)
	pfxre=`expr "$bugsystem" : '/\([^/][^/]*\)/.*'` || { xit=1; continue; }
	sfxbugsys=`expr "$bugsystem" : '/[^/][^/]*/\(.*\)'` || { xit=1; continue; }
	expr "x$headline" : "x$pfxre" >/dev/null || continue
	bugsystem=$sfxbugsys
	;;
    esac

    case "$bugsystem" in
      csbug)
	bugnum=`csbug NEW "$@" </dev/null` || exit 1
	( echo "From: $EMAIL"
	  echo "Subject: $*"
	  echo
	  exec cat
	) | csbug -b "$bugnum" COMMENT
	exit $?
	;;
      ddts)
	pro=sa.maintenance
	exec mkddtsrq -S "$sev" -p "$pro" "$*"
	;;
      tdl)
	exec td --add "$*"
	;;
      mailto:*)
	exec env BUGSYSTEMS=$bugsystem buglog "new bug: $*"
	;;
    esac
  done
  exit 1
}
