#!/bin/sh
#
# Take a log message and an attachment data on stdin
# and log it appropriately.
#	- Cameron Simpson <cs@zip.com.au> 09jul2004
#

: ${TMPDIR:=/tmp}

cmd=`basename "$0"`
usage="Usage: $cmd logline < attachment-data"

[ $# = 1 ] || { echo "$usage" >&2; exit 2; }
logmsg=$1; shift

[ -n "$BUGSYSTEMS" ] || BUGSYSTEMS=dlog

tmpf=$TMPDIR/bugids$$
trap 'rm -f "$tmpf"' 0 1 15
detab | unbs | unctrl >"$tmpf" || exit 1

case " $BUGSYSTEMS " in
  *' dlog '*)	dlog "$logmsg" ;;
esac
case " $BUGSYSTEMS " in
  *' ddts '*)	ddtsids=`echo "$logmsg" | ddtsids`
		[ -n "$ddtsids" ] && mailif -s "$logmsg" $ddtsids < "$tmpf"
		;;
esac

exit 0
