#!/bin/sh -u
#
# Run command, log output to bug system, discard log file.
#	- Cameron Simpson <cs@zip.com.au> 22mar2005
#

: ${TMPDIR:=/tmp}

trace=	##set-x

cmd=`basename "$0"`
usage="Usage: $cmd [-m msg] [{-c shcmd | cmd [args...]}]"

msg=
[ $# -gt 0 ] && [ "x$1" = x-m ] && { msg=$2; shift; shift; }

logfile=$TMPDIR/$cmd.$$.log
set logscript +z -m "$msg" "$logfile" ${1+"$@"}

$trace "$@"
xit=$?
rm "$logfile"
exit $xit
