#!/bin/sh
#
# Output all the numerically named files in the named directories
# in UNIX mail file format.
#	- Cameron Simpson <cs@zip.com.au> 27mar2000
#

[ $# = 0 ] && set .

xit=0
first=1
for dir
do
    if [ $first ]
    then first=
    else echo
    fi

    ( cd "$dir" || exit 1
      xit=0
      for file in `ls | egrep '^[0-9].(z|Z|gz|bz2)$'`
      do  case "$file" in
	      *.z)	unpack "$file" || xit=1 ;;
	      *.Z)	uncompress "$file" || xit=1 ;;
	      *.gz)	gunzip "$file" || xit=1 ;;
	      *.bz2)	bunzip2 "$file" || xit=1 ;;
	      *)	echo "$0: what to do with $dir/$file?" >&2
			xit=1
			;;
	  esac
      done
      [ $xit = 0 ] || exit 1
      for file in `ls | grep '^[0-9]' | sort -n`
      do  
	  maildiritem2fileitem "$file"
      done
      exit $xit
    ) || xit=1
done

exit $xit
