#!/usr/bin/perl
#
# Extract discid and track info from a CD as a preliminary to
# constructing a FreeDB CDDB entry. Used by cdsubmit.
#	- Cameron Simpson <cs@zip.com.au> 14mar2001
# 

use strict qw(vars);

use cs::CDDB;

my $dev;

($::cmd=$0) =~ s:.*/::;
$::Usage="Usage: $::cmd [cd-device]\n";

if (@ARGV)
{ $dev=shift(@ARGV);
}

die $::Usage if @ARGV;

my $CD = new cs::CDDB;
$CD->Device($dev) if defined $dev;

print $CD->DiscId(), "\n";
my(@t)=$CD->Tracks();
print scalar(@t), "\n";

for my $T (@t)
{ print "$T->{TRACK} $T->{LENGTH} $T->{OFFSET}\n";
}

exit 0;
