#!/usr/bin/perl
#
# Emit a table of contents for a CD.
#	- Cameron Simpson <cs@zip.com.au> 14mar2001
# 

use strict qw(vars);

use cs::CDDB;
use cs::Hier;

my $dev = '/dev/cdrom';

($::cmd=$0) =~ s:.*/::;
$::Usage="Usage: $::cmd [cd-device]\n";

if (@ARGV)
{ $dev=shift(@ARGV);
}

die $::Usage if @ARGV;

my $CD = new cs::CDDB;
die "$::cmd: can't make new cs::CDDB object\n" if ! defined $CD;

my($artist,$title)=($CD->Artist(), $CD->Title());

print "$artist\n$title\n";
# print cs::Hier::h2a($CD,1),"\n";
# exit 0;

# track info
my @T = $CD->TrackInfo();
my $T;

for my $i (0..$CD->NTracks()-1)
{ $T=$T[$i];

   print $i+1, " ", $T->{LENGTH}, " ", $T->{OFFSET}, "\n";
   print $T->{TTITLE}, "\n";
   print $T->{EXTT}, "\n";
}
