#!/usr/bin/perl
#
# Emit a table of contents for a CD.
#	- Cameron Simpson <cs@zip.com.au> 14mar2001
# 

use strict qw(vars);

use cs::CDDB;
use cs::Hier;

my $dev = '/dev/cdrom';

($::cmd=$0) =~ s:.*/::;
$::Usage="Usage: $::cmd [cd-device]\n";

if (@ARGV)
{ $dev=shift(@ARGV);
}

die $::Usage if @ARGV;

my $CD = new cs::CDDB;
die "$::cmd: can't make new cs::CDDB object\n" if ! defined $CD;

my $discid = $CD->DiscId();

my @q = $CD->Query();
if (@q < 1)
{ die "$::cmd: no matches for $discid\n";
}

if (@q > 1 || @q > 0 && $q[0]->[2] ne $discid)
{ warn "$::cmd: multiple matches for discid $discid:\n";
  my $m;
  for my $i (1..@q)
  { $m = $q[$i-1];
    warn "$i\t$m->[2]  $m->[0]\t$m->[1]\n";
  }

  exit 1 if ! -t STDIN || ! -t STDERR;

  print STDERR "Select? ";
  exit 1 if ! defined($_=<STDIN>);
  chomp;
  exit 1 if ! length;
  if (! /^\d+/ || $_ < 1 || $_ > @q)
  { die "bad response: $_\n";
  }

  my($cat,$discid)=($q[$_-1]->[0], $q[$_-1]->[2]);
  $CD->SetCategory($cat);
  $CD->SetDiscId($discid);
}

my($artist,$title)=($CD->Artist(), $CD->Title());
die "no artist!" if ! defined $artist;
die "no title!" if ! defined $title;

print "$artist\n$title\n";
# print cs::Hier::h2a($CD,1),"\n";
# exit 0;

# track info
my @T = $CD->TrackInfo();
my $T;

for my $i (0..$CD->NTracks()-1)
{ $T=$T[$i];

   print $i+1, " ", $T->{LENGTH}, " ", $T->{OFFSET}, "\n";
   print $T->{TTITLE}, "\n";
   print $T->{EXTT}, "\n";
}
