#!/bin/sh
#
# Wrapper for CGI scripts which sets environment and captures and
# reports errors.
# For any perl CGI, move the real .cgi to .cgi-pl and copy cgiwrap-stub to
# the old .cgi name.
# For any shell CGI, move the real .cgi to .cgi-sh and copy cgiwrap-stub to
# the old .cgi name.
#	- Cameron Simpson <cs@zip.com.au> 03mar1999
#
# Make single wrapper for pl and sh.	- cameron 12feb2001
#

SCRIPT_FILENAME=${SCRIPT_FILENAME:-$0}
export SCRIPT_FILENAME
if [ "x$1" = "x-0" ]
then
    SCRIPT_FILENAME=$2; shift; shift
else
    echo "$0: missing mandatory -0 option" >&2
    exit 2
fi

# snapshot errors and attach to output bottom
STDERR=/tmp/stderr.$USER.$$
DEBUG=1; export DEBUG
trap 'exec 2>&1
      if [ -n "$DEBUG" -a -s "$STDERR" ]
      then
	  echo "Content-Type: text/html"
	  echo
	  echo "<TITLE>Debugging Info for $0</TITLE>"
	  echo "<BR><HR><B>Debugging Info</B><P>"
	  echo "<B>STDERR of $0 $*</B><BR><PRE><SMALL>"
	  fold <"$STDERR"
	  echo "</SMALL></PRE>"
	  echo "<P><B>Environment</B><BR><PRE><SMALL>"
	  pwd; id; echo
	  env | sort
	  echo "</SMALL></PRE>"
      fi
      rm -f "$STDERR"' 0
exec 2>"$STDERR"

if [ -s "$SCRIPT_FILENAME-pl" ]
then  perl -I$HOME/rc/perl "$SCRIPT_FILENAME-pl" ${1+"$@"}
else  if [ -s "$SCRIPT_FILENAME-sh" ]
      then  /bin/sh "$SCRIPT_FILENAME-sh" ${1+"$@"}
      else  if [ -s "$SCRIPT_FILENAME-ici" ]
	    then  ici "$SCRIPT_FILENAME-ici" ${1+"$@"}
	    else  echo "$0: can't find $SCRIPT_FILENAME-{sh,pl,ici}" >&2
	    fi
      fi
fi

exit $?
