#!/bin/sh
#
# Simple check and report failed metadevices from /proc/mdstat.
#	- Cameron Simpson <cs@zip.com.au> 27jun2005
#

if [ $# -gt 0 ] && [ "x$1" = x-q ]
then
  shift
  out=`"$0"` && [ -z "$out" ]
  exit $?
fi

exec sed -n '/^[^ ]/{
		h
		b test
	     }
	     H
	     :test
	     /^  *[0-9][0-9]* blocks \[[0-9][0-9]*\/[0-9][0-9]*\] \[.*_.*\]$/{
		x
		p
	     }' /proc/mdstat
