#!/bin/sh -u
#
# Simple check and report failed metadevices from /proc/mdstat.
#	- Cameron Simpson <cs@zip.com.au> 27jun2005
#

if [ $# -gt 0 ] && [ "x$1" = x-q ]
then
  shift
  exec sed -n '/^[^ ]/{
		  h
		  b test
	       }
	       H
	       :test
	       /^  *[0-9][0-9]* blocks \[[0-9][0-9]*\/[0-9][0-9]*\] \[.*_.*\]$/{
		  x
		  p
	       }' /proc/mdstat
fi

out=`"$0" -q` || exit 1
[ -n "$out" ] && printf '%s\n' "$out"
[ -z "$out" ]
