#!/bin/sh
#
# Highlight content matching sed regexps with a colour.
#	- Cameron Simpson <cs@zip.com.au> 22sep99
#

usage="Usage: $0 colour regexps..."

[ $# -ge 2 ] || { echo "missing regexps" >&2; echo "$usage" >&2; exit 2; }

colour=$1; shift
eval "in=\$tty_$colour out=\$tty_normal"

sedf=
for regexp
do  sedf="$sedf
          s$regexp$in&$outg"
done

exec sed "$sedf"
