#!/bin/sh
#
# Perform a typical colourisation: stderr -> cyan.
#	- Cameron Simpson <cs@zip.com.au> 06may1999
#

cmd=$0

[ "x$1" = x-f ] && { IS_COLOURISED=; export IS_COLOURISED; shift; }

[ $# = 0 ] && { echo "Usage: $cmd [-f] cmd [args...]" >&2; exit 2; }

[ -z "$IS_COLOURISED" ] || exec "$@"

IS_COLOURISED=1
export IS_COLOURISED

exec filter_fd 2 "colour_highlight cyan '.*'" "$@"
