#!/bin/sh -ue
#
# Echo in colour.       - Cameron Simpson <cs@zip.com.au>
#

case $1 in
    -n)	echo=necho; shift ;;
    *)	echo=echo ;;
esac
colour=$1
shift
exec with-colour "$colour" "$echo" ${1+"$@"}
