#!/bin/sh
#
# Copy a directory tree - refuse if target exists as safety measure.
# Faster, safer, more accurate and more informative than "cp -rp".
#	- Cameron Simpson <cs@zip.com.au>
#

tar=gnutar
buffer="buffer -m 1M"	# just use "cat" if you lack buffer

[ $# = 2 ] || { echo "Usage: $0 fromdir todir" >&2
		exit 2
	      }

from=$1
to=$2

case $ARCH in
    *.*.domainos) # preserve ACLs
	exec /com/cpt "$from" "$to" -pdt -sacl -ld
	;;
    *)	set -x
	( cd "$from/." && $tar -cf - .
	) \
	| $buffer \
	| ( mkdir "$to" && cd "$to" && untar )
	;;
esac

sync &
