#!/bin/sh -u
#
# Copy a directory tree - refuse if target exists as safety measure.
# Faster, safer, more accurate and more informative than "cp -rp".
#	- Cameron Simpson <cs@zip.com.au>
#

cmd=`basename "$0"` || exit 1
####buffer="buffer -m 1M"	# just use "cat" if you lack buffer

[ $# = 2 ] || { echo "Usage: $cmd fromdir todir" >&2
		exit 2
	      }

from=$1
to=$2

[ -d "$to/." ] && { echo "$cmd: $to already exists!" >&2; exit 1; }
[ -d "$from/." ] || { echo "$cmd: $from missing!" >&2; exit 1; }

case $ARCH in
    *.*.domainos) # preserve ACLs
	exec /com/cpt "$from" "$to" -pdt -sacl -ld
	;;
    *)	( cd "$from/." && tar -cf - .
	) \
	| ( mkdir "$to" && cd "$to" && untar )
	;;
esac

sync &
