#!/bin/sh
#
# Copy a directory tree - refuse it target exists as safety measure.
# Faster, safer, more accurate and more informative than "cp -rp".
#	- Cameron Simpson <cs@zip.com.au>
#

tar=gnutar
buffer="buffer -m 1M"	# just use "cat" if you lack buffer

[ $# = 2 ] || { echo "Usage: $0 fromdir todir" >&2
		exit 2
	      }

case $ARCH in
    *.*.domainos) # preserve ACLs
	exec /com/cpt "$1" "$2" -pdt -sacl -ld
	;;
    *)	[ -d "$2/." ] && { echo "$0: $2 already exists" >&2
			   exit 1
			 }

	( cd "$1/." && $tar -cf - .
	) \
	| $cat \
	| ( mkdir "$2" && cd "$2" && untar )
	;;
esac

sync &
