#!/usr/bin/perl
#
# Copy file modes from one file to another.
#	- Cameron Simpson <cs@zip.com.au> 05jan99
#

use strict qw(vars);

($::cmd=$0) =~ s:.*/::;
$::Usage="Usage: $::cmd srcfile [targetfiles]\n";

{ my $badopts = 0;

  if (@ARGV)
  { $::srcfile=shift(@ARGV);
  }
  else
  { warn "$::cmd: missing srcfile\n";
    $badopts=1;
  }

  die $::Usage if $badopts;
}

my @s;

if (! (@s=stat($::srcfile)))
{ die "$::cmd: stat($::srcfile): $!\n";
}

my $mode = $s[2] & 07777;

$::Xit=0;

if (@ARGV)
{ for my $target (@ARGV)
  { cpmod($mode,$target)
  }
}
else
{ while (defined ($_=<STDIN>))
  { chomp;
    cpmod($mode,$_);
  }
}

exit $::Xit;

sub cpmod
{ my($mode,$target)=@_;

  if (-l $target)
  { warn "$::cmd: $target: is a symbolic link, skipped\n";
    $::Xit=1;
  }
  elsif (! chmod($mode,$target))
  { warn "$::cmd: $target: chmod: $!\n";
    $::Xit=1;
  }
}
