#!/bin/sh
#
# Commit changes, using commit-editor to make the log more helpful to its author.
#	- Cameron Simpson <cs@zip.com.au> 12apr1997
#

: ${TMPDIR:=/tmp}

diffs=$TMPDIR/cvd$$
CVS_COMMIT_DIFFS=$diffs
CVS_COMMIT_FILES=$*
CVS_COMMIT_EDITOR=$EDITOR
EDITOR=$0-editor
export CVS_COMMIT_FILES CVS_COMMIT_EDITOR CVS_COMMIT_DIFFS EDITOR

trap 'rm -f "$diffs"' 0 1 2 13 15
cvs -q diff $CVS_COMMIT_FILES >$diffs 2>&1

cvs commit -l ${1+"$@"}
exit $?
