#!/bin/sh -u
#
# Wrapper for $EDITOR for cvs commits to append the changes for inquisition
# in the change report.
#	- Cameron Simpson <cs@zip.com.au> 09mar2002
#

: ${TMPDIR:=/tmp}

[ -f "$CVS_COMMIT_DIFFS" ] || { echo "$0: \$CVS_COMMIT_DIFFS ($CVS_COMMIT_DIFFS) missing!" >&2
				 exit 1
			       }
[ $# = 1 ] || { echo "Usage: $0 filename (argv=[$*])" >&2; exit 2; }

report=$1; shift

sed 's/^/CVS: /' "$CVS_COMMIT_DIFFS" >>"$report"

EDITOR=$CVS_COMMIT_EDITOR
export EDITOR

$EDITOR "$report"
xit=$?

# toss blank lines and CVS: comments
bsed -s '/^CVS:/d; /^[ 	]*$/d' "$report"

if [ -s "$report" ]
then
    headline=`sed 1q "$report"`
    ( cat "$report"
      echo
      cat "$CVS_COMMIT_DIFFS"
    ) \
    | buglog "$CVS_COMMIT_FILES: $headline"
fi

exit $xit
