#!/bin/sh
#
# Update a file, edit it, run a commit, commit the file.
#	- Cameron Simpson <cs@zip.com.au> 05mar1997
#

cmd=`basename "$0"`
usage="Usage: $cmd [-f] [-m logmessage] file [command [args...]]
	Normally the filename will be appended as the last argument to the
	  supplied command. The -0, -1 and -f options affect this.
	-0		The filename will not be attached to the command,
			which is assumed to be complete.
	-1		The filename will be inserted as the first argument
			to the command.
	-f		Command is a filter.
			The file will be edited with filteredit,
			with the current content of the file available on stdin.
			The filename will not be attached to the command.
	-m logmessage	Specify log message.
			Default from \$CVSEDIT_MSG."

cameron= cisra=
[ "x$USER" = xcameron ] && cameron=1
[ "x$SYSTEMID" = xcisra ] && cisra=1

msg=$CVSEDIT_MSG
if [ -n "$msg" ]
then  havemsg=1
else  havemsg=
fi

dodl=$cameron
dodiff=1

fposarg=
filepos=end

isfilter=

badopts=

while :
do  case $1 in
	-0)	fposarg=$1 filepos= ;;
	-1)	fposarg=$1 filepos=first ;;
	-f)	isfilter=1 fposarg=-0 filepos= ;;
	-m)	havemsg=1 msg=$2; shift ;;
	--diff)	dodiff=1 ;;
	--no-diff) dodiff= ;;
	--dl)	dodl=1 ;;
	--no-dl) dodl= ;;
	-?*)	echo "$cmd: unrecognised option: $1" >&2; badopts=1 ;;
	--)	shift; break ;;
	*)	break ;;
    esac
    shift
done

if [ $# = 0 ]
then  echo "$cmd: missing file" >&2
      badopts=1
else  file=$1
      shift
fi

[ $badopts ] && { echo "$usage" >&2; exit 2; }

if [ ! -f "$file" ]
then
      echo "$cmd: $file: not a regular file" >&2
      exit 1
fi

ifcvs "$file" || exit $?

umask 2

dir=`dirname "$file"`
base=`basename "$file"`

editcmd=$*
[ $# = 0 ] && { set x "${EDITOR-vi}"; shift; }

( cd "$dir" || exit 1
  cvs update "$base" || exit $?
  cvs diff "$base" || { echo "Uncommited changes already exist in $base." >&2
			echo "Please commit them before proceeding." >&2
			exit 1
		      }

  [ ! -d CVS/Base ] || cvs edit "$base" || exit $?
  chmod +w "$base"
) || exit 1

if [ $isfilter ]
then
  set filteredit $fposarg -- "$file" "$@"; exec <"$file"
else
  case "$filepos" in
    '')		;;
    end)	set x "$@" "$file"; shift ;;
    first)	zero=$1; shift; set x "$zero" "$file" ${1+"$@"}; shift ;;
    *)		echo "$cmd: unsupported \$filepos \"$filepos\"" >&2; exit 1 ;;
  esac
fi
(set -x; "$@")
editxit=$?

[ $dodiff ] \
&& ( cd "$dir" || exit 1
     cvs diff "$base"
   )

[ $editxit = 0 ] \
|| { [ -t 0 ] && ask "$* failed - really commit the file"; } \
|| exit 1

[ $havemsg ] \
|| { [ -t 0 ] && { msg=`readline "Log message> "` && [ -n "$msg" ]; }; } \
|| { echo "$cmd: commit cancelled - file in modified state" >&2
     exit 1
   }

# log the change and diff appropriately
cvs diff "$file" | buglog "cvsedit $base: $msg"

( cd "$dir" || exit 1
  exec cvs commit -m "$msg" "$base"
)
