#!/bin/sh
#
# Update a file, edit it, run a commit, commit the file.
#	- Cameron Simpson <cs@zip.com.au> 05mar1997
#

usage="Usage: $0 [-m logmessage] file [command [args...]]
	-m logmessage	Specify log message."

cameron=
[ "x$USER" = xcameron ] && cameron=1

msg=
dodl=$cameron

badopts=

while :
do  case $1 in
	-m)	msg=$2; shift ;;
	--no-dl)dodl= ;;
	--dl)	dodl=1 ;;
	-?*)	echo "$0: unrecognised option: $1" >&2; badopts=1 ;;
	--)	shift; break ;;
	*)	break ;;
    esac
    shift
done

if [ $# = 0 ]
then  echo "$0: missing file" >&2
      badopts=1
else  file=$1
      shift
fi

[ $badopts ] && { echo "$usage" >&2; exit 2; }

if [ ! -f "$file" ]
then
      echo "$0: $file: not a regular file" >&2
      exit 1
fi

umask 2

dir=`dirname "$file"`
base=`basename "$file"`

[ $# = 0 ] && { set x "${EDITOR-vi}" "$file"; shift; }

( cd "$dir" || exit 1
  cvs update "$base" || exit $?

  [ ! -d CVS/Base ] || cvs edit "$base" || exit $?
  chmod +w "$base"
) || exit 1

"$@"
editxit=$?

( cd "$dir" || exit 1
  cvs diff "$base"
)
[ $editxit = 0 ] || ask "$* failed - really commit the file" || exit 1

[ -n "$msg" ] || { necho "Log message? "
		   read msg
		 } || { echo "commit cancelled - file in modified state" >&2
			exit 1
		      }

[ $dodl ] && dl "cvsedit $file $*: $msg"
( cd "$dir" || exit 1
  exec cvs commit -m "$msg" "$base"
)
