#!/bin/sh
#
# Connect to our Cyclades console server.
#	- Cameron Simpson <cs@zip.com.au> 18dec2002
#

cycuser=${USER:-`id -un`}

cmd=`basename "$0"`
usage="Usage: $cmd [-l user] console-name
	-l user	Specify user name (from \$USER, default $cycuser)."

badopts=

while :
do  case $1 in
	-l)	cycuser=$2; shift ;;
	--)	shift; break ;;
	-?*)	echo "$cmd: unrecognised option: $1" >&2
		badopts=1 ;;
	*)	break ;;
    esac
    shift
done

if [ $# = 0 ]
then
    echo "$cmd: missing port" >&2
    badopts=1
else
    console=$1; shift
    [ $# = 0 ] || { echo "$cmd: extra arguments: $*" >&2
		    badopts=1
		  }
fi

mapfile=/u/network/cyclades/map
cychost=`awk "\\\$1 == \"$console\" { print \\\$2 }" "$mapfile"`
cycport=`awk "\\\$1 == \"$console\" { print \\\$3 }" "$mapfile"`
session=$cychost-$console

[ -n "$cychost" ] || { echo "$cmd: no console named \"$console\" in $mapfile" >&2
		       badopts=1
		     }

[ $badopts ] && { echo "$usage" >&2; exit 2; }

set -x
exec scr "$session" \
	logscript "$session" \
	ssh -t -l "$cycuser:$cycport" "$cychost"
