#!/bin/sh
#
# Manage named desktops for a session.
# Allocate (or reuse) a named desk, returning its number.
#	- Cameron Simpson <cs@zip.com.au> 18jul2002
#
# Method:
# We keep a directory of desk numbered subdirs.
# Each subdir has a "name" file.
#

cmd=$0
usage="Usage: $cmd [-a] [-d statedir] [[-r] deskname [param [value]]]"

badopts=

all=
statedir=$HOME/var/desktop/$HOST
deskname=
rmdesk=

while :
do
  case $1 in
    -a)	all=1 ;;
    -d)	statedir=$2; shift ;;
    -r)	rmdesk=1 ;;
    -?*)echo "$cmd: unrecognised option: $1" >&2; badopts=1 ;;
    --)	shift; break ;;
    *)	break ;;
  esac
  shift
done

deskname=$1; shift
if [ $# = 0 ]
then  param=
else  param=$1; shift
      case "$param" in
	*/* | . | ..) echo "$cmd: bad parameter name \"$param\"" >&2
		      badopts=1 ;;
      esac
      if [ $# = 0 ]
      then haspvalue=
	   pvalue=
      else haspvalue=1
	   pvalue=$1; shift
	   [ $rmdesk ] && { echo "$cmd: can't use -r with parameter values" >&2
			    badopts=1
			  }
	   [ $# = 0 ] || { echo "$cmd: extra arguments: $*" >&2; badopts=1; }
      fi
fi

[ $badopts ] && { echo "$usage" >&2; exit 2; }

[ -d "$statedir/." ] || mkdir -p "$statedir" || exit 1
cd "$statedir" || exit 1

if [ -z "$deskname" ]
then
    if [ $rmdesk ]
    then
	echo "$cmd: -r: missing deskname" >&2
	echo "$usage" >&2
	exit 2
    fi

    # list desks
    grep . [1-9]*/name /dev/null 2>/dev/null \
    | sed 's|/name:| |' \
    | if [ $all ]
      then  sed 's/^\([0-9][0-9]* \)\./\1/'
      else  sed '/^[0-9][0-9]* \./d'
      fi
    exit 0
fi

deskdir=
case "$deskname" in
    *[^0-9]*)
	for namefile in [1-9]*/name
	do  [ -s "$namefile" ] || continue

	    tryname=$(<$namefile) || continue
	    if [ "x$deskname" = "x$tryname" ] \
	    || [ -n "$all" -a "x.$deskname" = "x$tryname" ]
	    then
		deskdir=`dirname "$namefile"`
		break
	    fi
	done
	;;
    *)	deskdir=$deskname
	needdir "$deskdir" || exit 1
	;;
esac

if [ -z "$deskdir" ]
then
    if [ $rmdesk ]
    then
      echo "$cmd: -r: no desk named \"$deskname\"" >&2
      exit 1
    fi

    deskdir=`mkdirn ''` || exit 1
    echo "$deskname" >"$deskdir/name"
    echo "$deskdir"
fi

if [ $rmdesk ]
then
  if [ -n "$param" ]
  then rm "$deskdir/$param" || exit 1
  else rm -r "$deskdir" || exit 1
  fi
else
  if [ -n "$param" ]
  then
    pfile=$deskdir/$param
    if [ $haspvalue ]
    then
      # store new parameter
      echo "$pvalue" >"$pfile"
      # some parameters have side effects
      case "$param" in
	  name)	if [ -n "$DISPLAY" ]
		then
		  case "$pvalue" in
		    .*)	name=`expr "x$pvalue" : 'x.\(.*\)'` ;;
		    *)	name=$pvalue ;;
		  esac
		  fvwmcmd "DesktopName $deskdir $name" &
		fi
		;;
      esac
    else
      if [ -s "$pfile" ]
      then echo "$(<$deskdir/$param)"
      else echo
      fi
    fi
  else
    echo "$deskdir"
  fi
fi
