#!/bin/sh
usage="Usage: $0 [-d desk] [job]"

desk=.
[ "x$1" = x-d ] && { desk=$2; shift; shift; }
[ "x$desk" = x. ] && desk=`currentdesk`

[ $# = 0 ] && exec desktop "$desk" job

job=$1; shift
[ $# = 0 ] || { echo "$cmd: extra arguments after job name: $*" >&2
		echo "$usage" >&2
		exit 2
	      }

isjob "$job" || { echo "$cmd: unknown job \"$job\"" >&2; exit 2; }

job "$job"
exec desktop "$desk" job "$job"
