#!/bin/sh -u
#
# Set the root background on per-desktop basis.
#	- Cameron Simpson <cs@zip.com.au> 02feb2004
#

: ${DESKTOPSET:=desktop}

cmd=$0
usage="Usage: $cmd [-] [-d desk] imagefiles...
	-	Do nothing. Recite fvwm commands.
	-d desk	Specify desk number to affect.
		Default desk is the current desk.
		The desk \"-\" means the global default (desk 1).
	The imagefile \"\" means remove the per desk setting for this desk."

desk=
doit=1 dasharg= towm=fvwmcmd

badopts=

[ $# -gt 0 ] && [ "x$1" = x-  ] && { doit=; dasharg=$1; towm=echo; shift; }
[ $# -gt 0 ] && [ "x$1" = x-d ] && { desk=$2; shift; shift; }
[ $# -gt 0 ] && [ "x$1" = x-- ] && shift

if [ $# = 0 ]
then
    echo "$cmd: missing imagefile" >&2
    badopts=1
fi

[ $badopts ] && { echo "$usage" >&2; exit 2; }

cmdesk=
case "$desk" in
  ''|.)	desk=`currentdesk` || exit 1 ;;
  -)	desk=1 ;;
esac

if [ -z "$*" ]
then
    # flush background
    [ $doit ] && exec desktop -r "$desk" rootbg
    exit $?
fi

# transmute args to cache filenames
srcargs=$*
first=1
for arg
do
  [ $first ] && { set --; first=; }
  cached=`filecache "$arg"` || cached=$arg
  set -- ${1+"$@"} "$cached"
done

# compute new background
rootbg=`mkwall "$@"` || exit 1

# note supplied images
if [ $doit ]
then
  ( desktop "$desk" rootbg "$*"
    desktop "$desk" rootbg_src "$srcargs"
  ) &
fi

# apply new background, set desktop to use it
cset=`expr 1024 + $desk` || exit 1
$towm "ColorSet $cset Pixmap $rootbg"
[ $desk = 1 ] || $towm "*FvwmBacker: Command (Desk $desk) colorset $cset"
