#!/bin/sh -u
#
# Incant basic desktop settings except for backgrounds for FVWM.
#	- Cameron Simpson <cs@zip.com.au> 24mar2003
#

: ${DESKTOPSET:=desktop}

fvwmcmd 'Colorset 1023 Foreground Green, Background Black'

( seq 0 63 \
  | awk '{print "*FvwmBacker: Command (Desk " $1 ") colorset 1023" }'

  idsetlist "$DESKTOPSET" name \
  | awk '$2 != "." { print "DesktopName", $1, $2 }'
) \
| fvwmcmd
