#!/bin/sh -u
#
# Set the root background on per-desktop basis.
#	- Cameron Simpson <cs@zip.com.au> 02feb2004
#

: ${DESKTOPSET:=desktop}

cmd=$0
usage="Usage: $cmd [-d desk] imagefiles...
	Default desk is the current desk.
	The desk \"-\" means the global default.
	The imagefile \"\" means remove the per desk setting for this desk."

desk=

badopts=

[ $# -gt 0 ] && [ "x$1" = x-d ] && { desk=$2; shift; shift; }
[ $# -gt 0 ] && [ "x$1" = x-- ] && shift

if [ $# = 0 ]
then
    echo "$cmd: missing imagefile" >&2
    badopts=1
fi

[ $badopts ] && { echo "$usage" >&2; exit 2; }

perdesk=1
case "$desk" in
  ''|.)	desk=`currentdesk` || exit 1 ;;
  -)	desk= perdesk= ;;
esac

if [ -z "$*" ]
then
    # flush background
    bg=
    if [ $perdesk ]
    then desktop -r "$desk" rootbg
    else lastvalue "rootbg" ""
    fi
else
    first=1
    for arg
    do
      if [ $first ]
      then
	set --
	first=
      fi
      set -- ${1+"$@"} `filecache "$arg"` || xit 1
    done

    # compute new background
    rootbg=`set-x mkwall "$@"` || exit 1

    # note supplied images
    if [ $perdesk ]
    then desktop "$desk" rootbg "$*"
    else lastvalue "rootbg" "$*"
    fi

    bg=$rootbg
fi

[ -n "$bg" ] || exit 0

if [ $perdesk ]
then
    # apply new background, set desktop to use it
    cset=`expr 1024 + $desk`
    echo "ColorSet $cset Pixmap $rootbg"
    echo "*FvwmBacker: Command (Desk $desk) colorset $cset"
else
    # apply new default background
    echo "Colorset 1023 AspectPixmap $bg"
fi \
| fvwmcmd
