#!/bin/sh
#
# Set the root background on per-desktop basis.
#	- Cameron Simpson <cs@zip.com.au> 02feb2004
#

: ${DESKTOPSET:=desktop}
: ${DESKTOPSET_SIZED:=$DESKTOPSET-${X11_X}x${X11_Y}}
DESKTOPSET=$DESKTOPSET_SIZED	# backgrounds are sized
export DESKTOPSET

cmd=$0
usage="Usage: $cmd [-d desk] imagefiles...
	Default desk is the current desk.
	The desk \"-\" means the global default.
	The imagefile \"\" means remove the per desk setting for this desk."

desk=

badopts=

[ "x$1" = x-d ] && { desk=$2; shift; shift; }

if [ $# = 0 ]
then
    echo "$cmd: missing imagefile" >&2
    badopts=1
fi

[ $badopts ] && { echo "$usage" >&2; exit 2; }

perdesk=1
case "$desk" in
  ''|.)	desk=`currentdesk` || exit 1 ;;
  -)	desk= perdesk= ;;
esac

if [ -z "$*" ]
then
    # flush background
    bg=
    if [ $perdesk ]
    then desktop -r "$desk" rootbg
    else lastvalue "desk_dfltrootbg" ""
    fi
else
    # set new background
    rootbg=`set-x mkwall "$@"` || exit 1
    bg=$rootbg
    if [ $perdesk ]
    then desktop "$desk" rootbg "$rootbg"
    else lastvalue "desk_dfltrootbg" "$rootbg"
    fi
fi

if [ $perdesk ]
then
    # apply new background, set desktop to use it
    echo "$desk" $bg | desktop-incant-bg
else
    # apply new default background
    [ -n "$bg" ] && echo "Colorset 1023 AspectPixmap $bg"
fi \
| fvwmcmd
