#!/bin/sh -u
#
# Incant desktop background stuff for FVWM.
#	- Cameron Simpson <cs@zip.com.au> 28oct2004
#

: ${DESKTOPSET:=desktop}

cmd=$0
usage="Usage: $0"

[ $# = 0 ] || { echo "$cmd: extra arguments: $*" >&2
		echo "$usage" >&2
		exit 2
	      }

dfltbg=`rootbg` && fvwmcmd "ColorSet 1023 AspectPixmap $dfltbg"

idsetlist "$DESKTOPSET" rootbg \
| awk '$2 != "." { print }' \
| while read -r desk bg
  do
    deskbg -d "$desk" $bg
  done
