#!/bin/sh
#
# HTML index of a directory.
#	- Cameron Simpson <cs@zip.com.au> 09oct96
#

dir=.
[ $# = 0 ] || { dir=$1; shift; }

cd "$dir" || exit $?
wd=`pwd`

[ $# = 0 ] && { set x *; shift; }

echo "<HEAD>"
echo "  <TITLE>Index of $wd</TITLE>"
echo "</HEAD>"

echo "<BODY>"
echo "  <H1>Index of $wd</H1>"

for n
do  if [ -f 
    fi
done

echo "</BODY>"
