#!/bin/sh -u
: ${LOGDIR:=$HOME/var/log}
: ${DLOG_WHEN:=now}
logname=dlog
[ $# -gt 0 ] && [ "x$1" = x-l ] && { logname=$2; shift; shift; }
case "$logname" in /*) ;; *) logname=$LOGDIR/$logname ;; esac
[ $# = 0 ] && exec pageif cat "$logname"
exec note -d "$DLOG_WHEN" "$logname" "$*"
