#!/bin/sh -u
#
# Run getmail once, like dofetchmail.
#	- Cameron Simpson <cs@zip.com.au> 18mar2006
#

: ${LOGDIR:=$HOME/var/log}
: ${VARRUN:=$HOME/var/run}

trace=set-x

cmd=`basename "$0"` || cmd=$0
usage="Usage: $cmd [getmail-options...]"

eval "`syncenv -`"
: ${GM_OPTS:=-v}

for acct in $GM_ACCOUNTS
do
  set -- -r "$acct" ${1+"$@"}
done

exec getmail ${1+"$@"}
