#!/bin/sh
#
# Sync hosts from master.
#	- Cameron Simpson <cs@zip.com.au> 14jan2004
#

cmd=`basename "$0"`
usage="Usage: $cmd [-s] [-x] [hosts...]"

needhost $HOMEHOST@home || exit 1
ask "Is $HOST@$SYSTEMID up to date" || exit 1

trace=set-x
sync=
[ "x$1" = x-s ] && { shift; sync=1; }

[ $# = 0 ] && set newt jekyll

xit=0

for rhost
do
  cf=$HOME/rc/sync/cf.$rhost
  [ -s "$cf" ] || { echo "$cmd: no cf for $rhost at $cf" >&2; xit=1; continue; }
done

exit $xit


$trace \
pfx work:opt/redhat.x86.linux \
rsync -avHP --rsync-path='$HOME/bins/rrsync kaper' /u/syncopt/redhat.x86.linux/HOME/. work:/cameron/opt-HOME/. &
[ $sync ] && wait

( # prepare the way
  $trace snarfaddrs &
  [ $sync ] && wait
  for subdir in scripts im \
		there/cs@zip.com.au/html \
		there/cskk.ezoshosting.com/html/cs \
		there/cskk.ezoshosting.com/html/cs/moto \
		there/adzapper.sourceforge.net/html
  do ( cd "$HOME/$subdir" || exit 1
       exec $trace myke _all
     ) &
     [ $sync ] && wait
  done
  wait
  $trace updsysscripts
)

# push real accounts
$trace pfx work syncwork &
[ $sync ] && wait
$trace pfx newt syncnewt &
[ $sync ] && wait
$trace pfx jekyll syncjekyll &
[ $sync ] && wait
$trace pfx small syncsmall &
[ $sync ] && wait

$trace pfx sf syncsf &
[ $sync ] && wait
$trace pfx ezos syncezos &
[ $sync ] && wait
$trace pfx zip synczip &
[ $sync ] && wait

wait
