#!/bin/sh

[ "x$HOST@$SYSTEMID" = xamadeus@home ] \
|| { echo "$0: must be on amadeus@home" >&2
     exit 2
   }

ask "Is $HOST@$SYSTEMID up to date" || exit 1

rsync -avHP --rsync-path='$HOME/scripts/rrsync zapff' /u/syncopt/redhat.x86.linux/HOME/. work:/cameron/opt-HOME/redhat.x86.linux/. &

( # prepare the way
  snarfaddrs &
  for subdir in scripts im \
		there/cs@zip.com.au/html  there/cs@zip.com.au/html/moto \
		there/adzapper.sourceforge.net/html
  do ( cd "$HOME/$subdir" && myke _all ) &
  done
  wait
)

# push
syncwork &
synczip &
syncnewt &
##synctw &
syncjekyll &
syncsf &

wait
