#!/bin/sh

case "$HOST@$SYSTEMID" in
    amadeus@home)	ask "Is amadeus up to date" || exit 1
			snarfaddrs &
			( cd $HOME/scripts && myke ) &
			( cd $HOME/public && myke _cvslogs _tarballs ) &
			wait
			syncwork &
			synczip &
			wait
			exit
			;;
esac

echo "$0: must be on amadeus@home" >&2
exit 2
