#!/bin/sh -u
#
# Dump the databases from a MySQL database.
#	- Cameron Simpson <cs@zip.com.au>
#

set -u

trace=set-x
user=
password=
host=localhost
dir=.
dohistbackup=
keepn=14
pcntfree=20
bytable=

cmd=$0
usage="Usage: $cmd [-u user] [-p password] [-h host] [databases...]
	-u user		Specify user name.
	-p password	Specify user password.
	-h host		Specify MySQL host. Default: $host
	-S secret	Get user/password/host from the named secret.
        -T              Dump individual tables instead of databases.
	-d dir		Target directory for dumps. Default: $dir
	-H		Target directory is a histbackup directory.
	databases	Database names to dump. Default: all of them."

badopts=

while [ $# -gt 0 ]
do
  case $1 in
    -u)	user=$2; shift ;;
    -p)	password=$2; shift ;;
    -h)	host=$2; shift ;;
    -S)	eval `secret "$2"` || exit 1; shift
	user=$secretLOGIN
	password=$secretPASSWORD
	host=$secretHOST
	;;
    -d)	dir=$2; shift ;;
    -T) bytable=1 ;;
    -H)	dohistbackup=1 ;;
    --)	shift; break ;;
    -?*)echo "$cmd: unrecognised option: $1" >&2
	badopts=1
	;;
    *)	break ;;
  esac
  shift
done

[ -d "$dir/." ] || { echo "$cmd: $dir: not a directory" >&2; badopts=1; }

[ $badopts ] && { echo "$usage" >&2; exit 2; }

[ $dohistbackup ] && { dir=$dir/`histbackup --no-rsync "$dir"` || exit 1; }
cd "$dir" || exit 1

if [ $# = 0 ]
then
  echo show databases \
  | mysql -h "$host" "-u$user" "-p$password" \
  | sed 1d \
  | if [ $bytable ]
    then
      while read db
      do
        echo show tables \
        | mysql -h "$host" "-u$user" "-p$password" "$db" \
        | sed "1d; s/^/$db /"
      done
    else
      cat
    fi
else
  for arg
  do
    case "$db" in
      *.*)
        db=`expr "x$arg" : 'x\([^.]*\)\..*'` || exit 1
        tbl=`expr "x$arg" : 'x[^.]*\.\(.*\)'` || exit 1
        echo "$db $tbl"
        ;;
      *)
        db=$arg
        echo "$db"
        ;;
    esac
  done
fi \
| sort \
| while dbname= tblname=
        read dbname tblname
  do
    if [ -n "$tblname" ]
    then  squiz=$dbname.$tblname.sql.gz
    else  squiz=$dbname.sql.gz
    fi
    rm -f "$squiz"
    $trace mysqldump -h "$host" "-u$user" "-p$password" --opt "$dbname" $tblname \
    | gzip -n --fast >"$squiz"
  done

[ $dohistbackup ] && $trace mklinks -newer ..

exit 0
