#!/bin/sh -u
#
# Notice changes in disc usage.
#	- Cameron Simpson <cs@zip.com.au>
#
# Timestamping.	- cameron, 21mar1999
# Async multidir mode. - cameron 23mar2007
# .gz mode. - cameron 07may2007
# Expect .du-a,.du-s subdirs, get new files from dusum output. - cameron 20jun2007
#

cmd=$0
usage="Usage: $cmd [-a] [dirs...]"

zmode=gz
async=
[ $# -gt 0 ] && [ "x$1" = x-a ] && { async=1; shift; }

[ $# = 0 ] && set -- .

now=`datecode`

xit=0

for dir
do
  ( cd "$dir" || exit 1

    # locate older du summaries
    olddua=`ls -ldt .du-a/* | sed -n 's/^-.* //p' | sed 1q`
    [ -n "$olddua" ] || olddua=/dev/null
    olddus=`ls -ldt .du-s/* | sed -n 's/^-.* //p' | sed 1q`
    [ -n "$olddus" ] || olddus=/dev/null

    dusum NOW \
    | \
    { read -r dua || exit 1
      read -r dus || exit 1
      dudiff "$olddua" "$dua" | gzip --fast >.du-a/diff.gz
      dudiff "$olddus" "$dus" | gzip --fast >.du-s/diff.gz
    }
  ) &
  [ $async ] || wait
done

wait

exit $xit
