#!/bin/sh -u
#
# Notice changes in disc usage.
#	- Cameron Simpson <cs@zip.com.au>
#
# Timestamping.	- cameron, 21mar1999
# Async multidir mode. - cameron 23mar2007
# .gz mode. - cameron 07may2007
#

cmd=$0
usage="Usage: $cmd [-a] [dirs...]"

zmode=gz
async=
[ $# -gt 0 ] && [ "x$1" = x-a ] && { async=1; shift; }

[ $# = 0 ] && set -- .

now=`datecode`

xit=0

for dir
do
  ( cd "$dir" || exit 1
    dusum "$now"

    dua=.du-a.$now.gz

    if [ -f .du-a.gz ]
    then olddua=.du-a.gz
    elif [ -f .du-a ]
    then olddua=.du-a
    else olddua=/dev/null
    fi
    rm -f .du-a.diff
    dudiff "$olddua" "$dua" | gzip --fast > .du-a.diff.gz
    rm -f .du-a .du-a.gz;ln -s "$dua" .du-a.gz

    dus=.du-s.$now.gz
    if [ -f .du-s.gz ]
    then olddus=.du-s.gz
    elif [ -f .du-s ]
    then olddus=.du-s
    else olddus=/dev/null
    fi
    rm -f .du-s.diff
    dudiff "$olddus" "$dus" | gzip --fast > .du-s.diff.gz
    rm -f .du-s .du-s.gz;ln -s "$dua" .du-s.gz
  ) &
  [ $async ] || wait
done

wait

exit $xit
