#!/bin/sh -u
#
# Produce disc usage summaries.
#	- Cameron Simpson <cs@zip.com.au>
#
# Extensions and usage.	- cameron, 21mar1999
#

ext=
[ $# -gt 0 ] && { ext=.$1; shift; }
[ $# = 0 ] || { echo "Usage: $0 [ext]" >&2; exit 2; }

out=".du-a$ext .du-s$ext"
trap 'rm -f $out" 1 2 13 15


dufs ${1+"$@"} \
| sed 's/^\([0-9][0-9]*\)	\.\/\/*/\1	/' \
| tee .du-a$ext \
| fgrep -v / > .du-s$ext
