#!/bin/sh
#
# Edit a file, making a template if needed.
#	- Cameron Simpson <cs@zip.com.au> 27oct95
#

cmd=`basename "$cmd"`
usage="Usage: $cmd [-e editor] file"

EDITOR=${EDITOR:-vi}
case "$1" in -e) EDITOR=$2; shift; shift ;; esac
export EDITOR

[ $# = 1 ] || { echo "$usage" >&2; exit 2; }
file=$1; shift

case "$file" in
    *.pgp) exec pgpedit "$file" ;;
esac

# make templates
[ -s "$file" ] || { tplt "$file" >>"$file"
		    [ -s "$file" ] || rm "$file"
		  }

[ -s .exrc ] && { EXINIT="$EXINIT|source .exrc"
		  NEXINIT="$NEXINIT|source .exrc"
		  export EXINIT NEXINIT
		}

exec "$EDITOR" "$file"
