#!/bin/sh
#
# Edit a file, making a template if needed.
#	- Cameron Simpson <cs@zip.com.au> 27oct95
#

cmd=`basename "$cmd"`
usage="Usage: $cmd files..."

[ $# = 0 ] && { echo "$usage" >&2; exit 2; }

EDITOR=${EDITOR:-vi}
case "$1" in -e) EDITOR=$2; shift; shift ;; esac
export EDITOR

case "$#,$1" in 1,*.pgp) exec pgpedit "$1" ;; esac

# make templates
for arg
do  [ -s "$arg" ] || template "$arg" >>"$arg"
done

[ -s .exrc ] && { EXINIT="$EXINIT|source .exrc"
		  NEXINIT="$NEXINIT|source .exrc"
		  export EXINIT NEXINIT
		}

exec "$EDITOR" ${1+"$@"}
