#!/bin/sh
#
# Operations to perform when entering a desktop.
#	- Cameron Simpson <cs@zip.com.au> 24mar2003
#

exec </dev/null
exec >>$HOME/var/log/console
exec 2>&1

thisdesk=$1
lastdesk=`currentdesk`

if [ "x$thisdesk" != "x$lastdesk" ]
then
    currentdesk "$thisdesk"

    desktop "$thisdesk" shcmds | sh -x &
    desktop "$thisdesk" wmcmds | fvwmcmd &

    if [ "x$XSESSIONMODE" != xvnc ]
    then
	# check root backdrop
	rootbg=`desktop "$thisdesk" rootbg`
	if [ -n "$rootbg" -a -s "$rootbg" ]
	then
	    ##con echo choose bg for desk $thisdesk: $rootbg
	    perdeskbg=1
	else
	    # no valid per-desk background - use global default
	    perdeskbg=
	    rootbg=`lastvalue "defaultrootbg-$HOST"`
	    ##con echo choose bg for all desks $rootbg
	fi

	if [ -n "$rootbg" -a -s "$rootbg" ]
	then
	  # valid background image? compare and change if necessary
	  lastrootbg=`lastvalue "rootbg-$HOST"`
	  if [ "x$rootbg" != "x$lastrootbg" ]
	  then
	      if [ $perdeskbg ]
	      then
		  deskbg -d "$thisdesk" "$rootbg"
	      else
		  rootbg "$rootbg"
	      fi
	  fi
	else
	  fvwm-root --dummy
	  xsetroot -solid darkblue
	  lastvalue "rootbg-$HOST" ""
	fi &

    #    # menu backdrop
    #    Dflag=-D
    #    menubg=`desktop "$thisdesk" menubg`
    #    if [ -z "$menubg" -o ! -s "$menubg" ]
    #    then
    #	Dflag=
    #	menubg=`lastvalue "defaultmenubg-$HOST"`
    #    fi
    #
    #    if [ -n "$menubg" -a -s "$menubg" ]
    #    then
    #      lastmenubg=`lastvalue menubg`
    #      [ "x$menubg" != "x$lastmenubg" ] && menubg $Dflag "$menubg"
    #    else
    #      fvwm-root --dummy
    #      xsetroot -solid black
    #    fi

    fi &

    ( deskjob=`deskjob -d "$thisdesk"`
      case "$deskjob" in
	''|.|idle)	;;
	*)		job "$deskjob" ;;
      esac
    ) &
fi
