#!/bin/sh
#
# Ssh, obtain normal env, run command.
#	- Cameron Simpson <cs@zip.com.au>
#

cmd=`basename "$0"`
usage="Usage: $cmd [-o sshopt] [-[xX] [-l login] [-a] [-n] [-v] [-x] host command [args...]
	-l login	Specify remote login name.
	-o sshopt	Pass option to ssh.
	-n		Input from /dev/null.
	-t		Require a tty.
	-x -X		Passed to ssh.
	-v		Verbose."

rsh=ssh
trace=

badopts=

sshopts=
async=
nflag=
tflag=
xset=:
vecho=:

eval `rigSOURCE_DISPLAY`
passvars='DISPLAY_SYSTEMID SOURCE_HOST SOURCE_DISPLAY'

while :
do
    case $1 in
	-[lo])	sshopts="$sshopts $1 '$2'"; shift ;;
	-[ntfxX])sshopts="$sshopts $1" ;;
	-v)	setx='set -x' trace=set-x sshopts="$sshopts -v"
		vecho=echo
		set -x ;;
	--)	shift; break ;;
	-?*)	echo "$cmd: unrecognised option: $1" >&2; badopts=1 ;;
	*)	break ;;
    esac
    shift
done

if [ $# = 0 ]
then
    echo "$cmd: missing hostname" >&2 ; badopts=1
else
    host=$1; shift
fi

[ $# = 0 ] && { echo "$cmd: missing command" >&2; badopts=1; }

[ $badopts ] && { echo "$usage" >&2; exit 2; }

passenv=
for var in $passvars
do  eval "val=\$$var"
    passenv="$passenv
	$var='$val'; export $var"
done

umask=`umask`
rcmd="$xset
      umask $umask
      $passenv
      env=\$HOME/rc/shell/rigenv
      [ -s \"\$env\" ] || env=\$HOME/.profile
      $vecho loading environment ...
      [ -s \"\$env\" ] && . \"\$env\"
      $vecho running ...
      $setx
      $*"

eval "$xset; exec ssh $sshopts $host \"\$rcmd\""
