#!/bin/sh

: ${TMPDIR:=/tmp}

mkdir Restored && cd Restored
tmp=$TMPDIR/fetchback.$$
/HOME/backups/bin/find_backup $* >$tmp
vi $tmp
/HOME/backups/bin/restore_backup <$tmp
pax -r -v < $TMPDIR/Restored
rm $TMPDIR/Restored
rm $tmp
