#!/bin/sh -u
#
# Read mail item from stdin, file in a folder.
# Tries to be pretty fast.
#	- Cameron Simpson <cs@zip.com.au> 20apr2001
#

: ${MAILDIR:=$HOME/mail}
: ${TMPDIR:=/tmp}
: ${LOGDIR:=$HOME/var/log}

mode=maildir

cmd=$0
usage="Usage: $cmd [-auto] folder <mailitem
	-auto	Figure out the folder type.
		Default: $mode"

badopts=

[ "x$1" = x-auto ] && { mode=auto; shift; }

if [ $# = 0 ]
then
    echo "$cmd: missing folder" >&2
    badopts=1
else
    folder=$1; shift
    [ $# = 0 ] || { echo "$cmd: extra arguments after folder: $*" >&2
		    badopts=1
		  }
fi

if [ -t 0 ]
then
    echo "$cmd: stdin may not be a tty; I expect a mail item" >&2
    badopts=1
fi

[ $badopts ] && { echo "$usage" >&2; exit 2; }

tmpf=$TMPDIR/fmi$$
trap 'rm -f "$tmpf"' 0 1 2 13 15
cat >"$tmpf" || exit 1
[ -s "$tmpf" ] || exit 1
exec <"$tmpf"
rm -f "$tmpf" || exit 1
# $tmpf now available for reuse

fpath=

# figure out the folder type if asked to guess
if [ "x$mode" = xauto ]
then
    fpath=`mailfolderpath "$folder"` || exit 1
    [ -n "$fpath" ] || { echo "$cmd: can't figure out pathname for folder \"$folder\"" >&2
			 exit 1
		       }
    if [ -f "$fpath" ]
    then
      mode=mbox
    else
      if maildir "$fpath"
      then mode=maildir
      else mode=mh
      fi
    fi
fi

# compute fpath if needed
[ -n "$fpath" ] || [ "x$mode" = xmh ] \
|| { fpath=`mailfolderpath "$folder"` || exit 1
     [ -n "$fpath" ] \
     || { echo "$cmd: can't figure out pathname for folder \"$folder\"" >&2
	  exit 1
	}
   }

# deliver
case "$mode" in
    mbox)
	exec cat >>"$fpath"
	;;
    mh)	unfrom_ | /usr/lib/nmh/rcvstore "$1" -unseen -nocreate
	;;
    maildir)
	maildir "$fpath" || exit 1
	cat >"$tmpf" <<X || exit 1
	MAILDIR=$MAILDIR
	DEFAULT=$fpath/
	LOGFILE=$LOGDIR/procmail
X
	procmail "$tmpf"
	exit $?
	;;
    *)	echo "$cmd: unsupported mode: $mode" >&2
	exit 2
	;;
esac

exit $?
