#!/bin/sh -u
#
# Read mail item from stdin, file in a folder.
# Tries to be pretty fast.
#	- Cameron Simpson <cs@zip.com.au> 20apr2001
#

: ${MAILDIR:=$HOME/mail}
: ${TMPDIR:=/tmp}
: ${LOGDIR:=$HOME/var/log}

mode=maildir

cmd=$0
usage="Usage: $cmd [-auto] folders... <mailitem
	-auto	Figure out the folder type.
		Default: $mode"

badopts=

[ $# -gt 0 ] && [ "x$1" = x-auto ] && { mode=auto; shift; }

[ $# = 0 ] && { echo "$cmd: missing folders" >&2
                badopts=1
              }

if [ -t 0 ]
then
    echo "$cmd: stdin may not be a tty; I expect a mail item" >&2
    badopts=1
fi

[ $badopts ] && { echo "$usage" >&2; exit 2; }

tmpf=$TMPDIR/fmi$$
trap 'rm -f "$tmpf".*' 0 1 2 13 15
msg=$tmpf.msg
prc=$tmpf.prc

cat >"$msg"   || exit 1
[ -s "$msg" ] || exit 1
exec </dev/null

xit=0

for folder
do
  case "$folder" in
    /*) fpath=$folder ;;
    *)  fpath=`mailfolderpath "$folder"` || exit 1
        [ -n "$fpath" ] || exit 1
        [ -f "$fpath" -o -d "$fpath/." ] \
        || maildir "$fpath" \
        || { xit=1; continue; }
        ;;
  esac

  # figure out the folder type if asked to guess
  if [ "x$mode" = xauto ]
  then
      if [ -f "$fpath" ]
      then
        mode=mbox
      else
        if maildir "$fpath"
        then mode=maildir
        else mode=mh
        fi
      fi
  fi

  # deliver
  case "$mode" in
      mbox)
          case "$fpath" in
            *.gz) gzip -n <"$msg" >>"$fpath" ;;
            *)    cat <"$msg" >>"$fpath" ;;
          esac
          ;;
      mh) unfrom_ <"$msg" | /usr/lib/nmh/rcvstore "$1" -unseen -nocreate
          ;;
      maildir)
          maildir "$fpath" || { xit=1; continue; }
          cat >"$prc" <<X || { xit=1; continue; }
          MAILDIR=$MAILDIR
          DEFAULT=$fpath/
          LOGFILE=$LOGDIR/procmail
X
          procmail -p "$prc" <"$msg" || xit=1
          ;;
      *)  echo "$cmd: $folder: unsupported mode: $mode" >&2
          exit 1
          ;;
  esac || xit=1
done

exit $xit
