#!/bin/sh
#
# Deduce MIME type from file(1) output.
#	- Cameron Simpson <cs@zip.com.au> 14nov2002
#

cmd=$0
usage="Usage: $cmd filename
	Exit status 0 => Output is MIME type.
	Exit status 1 => Output is file(1) output."

[ $# = 1 ] || { echo "$usage" >&2; exit 2; }
file=$1; shift

type=`file -L "$file"` || exit 1

mtype=
case "$type" in
    *': '*'Bourne shell script'*)	mtype=application/x-sh ;;
    *': '*'JPEG image data'*)		mtype=image/jpeg ;;
    *': '*'GIF image data'*)		mtype=image/gif ;;
    *': '*'PNG image data'*)		mtype=image/png ;;
    *': '*'PDF document'*)		mtype=application/pdf ;;
    *': '*'RPM v'*)			mtype=application/x-redhat-package-manager ;;
    *': '*'HTML document text'*)	mtype=text/html ;;
    *': '*'gzip compressed data'*)	mtype=application/x-gzip ;;
    *': '*'bzip2 compressed data'*)	mtype=application/x-bzip ;;
    *': '*'Zip archive data'*)		mtype=application/zip ;;
    *': '*'tar archive'*)		mtype=application/x-tar ;;
    *': '*'RAR archive data'*)		mtype=application/x-rar ;;
    *': '*'ASCII cpio archive'*)	mtype=application/x-cpio-c ;;
    *': '*'Ogg-Vorbis compressed sound file'*) mtype=application/x-ogg ;;
    *': '*'MPEG system stream data'*) mtype=video/mpeg ;;
    *': '*'Microsoft Office Document'*) mtype=application/msword ;;
    *': '*'RIFF (little-endian) data, AVI') mtype=video/avi ;;
    *': '*'PGP armored data signed message'*)
					mtype=text/plain ;;
    *': '*'ASCII '*)			mtype=text/plain ;;
    *': '*'program text'*)		mtype=text/plain ;;
    *': '*'text'*)			mtype=text/plain ;;
esac

# unrecognised - just recite "file"  output
[ -z "$mtype" ] && { echo "$type"; exit 1; }

echo "$mtype"
exit 0
