#!/bin/sh
#
# Read mail item from stdin, file in MH folder.
# I can never remember just how to invoke rcvstore...
#	- Cameron Simpson <cs@zip.com.au> 20apr2001
#

[ $# = 1 ] || { echo "Usage: $0 folder <mailitem" >&2; exit 2; }

exec /usr/lib/nmh/rcvstore "$1" -unseen
