#!/usr/bin/perl
#
# Print file age in seconds: now-mtime(file).
#	- Cameron Simpson <cs@zip.com.au> 18mar2005
#

($cmd=$0) =~ s:.*/::;

if (!@ARGV)
{ die "Usage: $cmd pathnames...\n";
}

$xit=0;

for my $file (@ARGV)
{
  if (@s=stat($file))
  { print time-$s[9];
    if (@ARGV > 1) { print "\t$file"; }
    print "\n";
  }
  else
  { warn "$cmd: stat($file): $!\n";
    $xit=1;
  }
}

exit $xit;
