#!/bin/sh
#
# Run a file through a filter and rewrite the file.
# Do not rewrite if error or unchanged or empty result.
#	- Cameron Simpson <cs@zip.com.au> 16jun99
#

usage="Usage: $0 file filter [filterargs...]"

badopts=
if [ $# = 0 ]
then
    echo "$0: missing file" >&2
    badopts=1
else
    file=$1; shift
    if [ $# = 0 ]
    then
	echo "$0: missing filter" >&2
    fi
fi

[ $badopts ] && { echo "$usage" >&2; exit 2; }

tmp=/tmp/filter$$
bak=/tmp/bak$$

"$@" <"$file" >"$tmp" || { rm -f "$tmp"; exit $?; }

[ -s "$tmp" ] || { echo "$0: empty result, aborting" >&2
		   rm -f "$tmp"
		   exit 1
		 }

xit=0
if cmp -s "$tmp" "$file"
then
    :
else
    if cp "$file" "$bak"
    then
	
	if cat <"$tmp" >"$file"
	then
	    rm "$bak"
	else
	    echo "$0: couldn't copy new content back onto $file" >&2
	    if cat <"$bak" >"$file"
	    then
		echo "$0: restored original content from backup" >&2
		rm "$bak"
		exit 1
	    else
		echo "$0: can't restore content from backup; original content left in $bak" >&2
		exit 1
	    fi
	fi
    else
	echo "$0: can't backup $file, aborting" >&2
	rm -f "$bak"
	xit=1
    fi
fi

rm -f "$tmp"

exit $xit
