#!/bin/sh
#
# Examine the named files and attach correct extensions to misnamed ones.
#	- Cameron Simpson <cs@zip.com.au> 22feb1999
#
# Base entirely on file2mime and mimeext now. - cameron 24jul2003
#

[ $# = 0 ] && { set x `cat`; shift; }

xit=0

for f
do  ## echo "$f ..."

    [ -f "$f" ] || { echo "$cmd: $f: not a regular file" >&2
		     xit=1; continue;
		   }
    [ -s "$f" ] || { echo "$cmd: $f: empty file!" >&2
		     xit=1; continue;
		   }

    type=`file2mime "$f"` || { echo "$cmd: can't deduce MIME type of \"$f\"" >&2
			       xit=1
			       continue
			     }

    prefext=`mimeext "$type"` || { echo "$cmd: no preferred extension for $type" >&2
				   xit=1
				   continue
				 }

    # see if ext is ok already
    fbase=`basename "$f"`
    case "$fbase" in
      *".$prefext")	continue ;;
    esac

    fdir=`dirname "$f"`
    case "$fdir" in
	.)	fdir= ;;
	*)	fdir=$fdir/ ;;
    esac

    case $f in
	*.*)	newf=$fdir`expr "x$fbase" : 'x\(.*\)\..*'`.$prefext ;;
	*)	newf=$fdir$fbase.$prefext ;;
    esac

    echo "$f -> $newf"
    mv -i -- "$f" "$newf" || xit=1
done

exit $xit
