#!/bin/sh
#
# Read some input and make sure it has a trailing newline.
# Why? Sed has historically discarded unterminated last lines,
# and I've just discovered that bash does so too in backticks.
# Which is slack.
#	- Cameron Simpson <cs@zip.com.au> 31may2002
#

( cat; echo ) | sed -e '$!b ok' -e '/^$/d' -e ':ok'
