#!/bin/sh

cmd=`basename "$0"`

if [ $# -gt 0 ]
then
    for h
    do  ssh "$h" "'/opt/script/$cmd'"
    done
    exit 0
fi

echo nsr local >>/opt/.syncopt
/opt/script/syncopt -x

cd /opt/nsr || exit 1
for f in etc/*.d/*
do rm -f /$f && ln -s /opt/nsr/$f /$f
done

/etc/init.d/networker start
