#!/bin/sh

cmd=`basename "$0"`

if [ $# -gt 0 ]
then
    for h
    do  ssh "$h" "'/opt/script/$cmd'"
    done
    exit 0
fi

echo nsr local >>/opt/.syncopt
/opt/script/syncopt -x

if [ ! -d /nsr/. ]
then
  (
    cd /
    tar xvf /u/network/nsr/platform/solaris-lgtonsr.tar
  )
fi

/etc/init.d/networker start
