#!/bin/sh
#
# Recent menu backgrounds.
#	- Cameron Simpson <cs@zip.com.au>
#

FVWM_MENU_IMLIST_OP=${FVWM_MENU_IMLIST_OP:-"menubg"}
export FVWM_MENU_IMLIST_OP
exec fvwm-menu-recent-imlist ${1-0} ${1-40} ${1+"$@"} <"$HOME/var/log/menubg"
