#!/bin/sh
#
# List known jobs not in CLOSED state.
#	- Cameron Simpson <cs@zip.com.au>
#

joblist name category state title \
| awk '-F	' '$4 != "CLOSED" { print }' \
| while read id name category state title
  do
      label=$name
      [ -n "$title" ] && label="$label: $title"
      [ -n "$category" ] && label="$label	$category"
      echo "\"$label\" Exec exec job $name"
  done \
| sort
