#!/bin/sh
#
# Generate menu for an image directory, with thumbnails.
#	- Cameron Simpson <cs@zip.com.au> 19oct2002
#

cmd=$0

##alert "#=$# $0 $*"
##exec 2>>$HOME/var/log/alert

##thsize=16x16
##thsize=32x32
thsize=48x48

##alert "DFLT=[$FVWM_MENU_IMLIST_OP]"
##env|grep FVWM >>$HOME/var/log/alert
imop=${FVWM_MENU_IMLIST_OP:-"xv"}

filelist=
inter=
dir=

usage="Usage: $cmd [-l filelist] [-o image-op] [XxY] dir [files/dirs...]]"

badopts=

while :
do
  case $1 in
    -o) imop=$2; shift ;;
    -l)	filelist=$2; shift ;;
    [1-9]|[1-9][0-9]|[1-9][0-9][0-9]) thsize=${1}x${1} ;;
    [1-9]*x[1-9]*) thsize=$1 ;;
    --) shift; break ;;
    -?*)echo "$cmd: unrecognised option: $1">&2
	badopts=1
	;;
    *)	break ;;
  esac
  shift
done

if [ $# = 0 ]
then
    echo "$cmd: missing dir" >&2
    badopts=1
else
    dir=$1; shift
    cd "$dir" || exit 1
fi

[ $badopts ] && { echo "$usage" >&2; exit 2; }

if [ -n "$filelist" ]
then
    set x ${1+"$@"} `cat "$filelist"` || exit 1
    shift
else
    # no args? pick parent, subdirs, *.* (image files)
    [ $# = 0 ] && set .. */. *.*
fi

wd=`pwd`
thdir=.thumbnails/$thsize

thumblist=${TMPDIR:-/tmp}/imlist$$th

exec 3>"$thumblist"

##echo "entries=[$*]" >&2
for entry
do
    if [ -d "$entry/." ]
    then
      # directory pathname
      path=`cd "$entry" || exit 1; pwd` || continue

      # menu entry tag
      case "$entry" in
	  .|*/*)tag=`basename "$path"` ;;
	  *)	tag=$entry ;;
      esac

      ##alert "\"$tag\" PopImDir $path $imop"
      echo "\"$tag\" PopImDir $path $imop"
    else
      f=$entry
      [ -s "$f" ] || continue;

      case "$entry" in
	  $HOME/*)	tag='~/'`expr "x$entry" : "x$HOME/\\(.*\\)"` ;;
	  *)		tag=$entry ;;
      esac

      d=`dirname "$f"`
      case "$d" in
	  /*)	;;
	  *)	d=$wd/$d ;;
      esac
      case "$f" in
	  */*)	fbase=`basename "$f"` ;;
	  *)	fbase=$f ;;
      esac
      case "$f" in
	  /*)	;;
	  *)	f=$d/$fbase ;;
      esac

      case "$f" in
	  *[A-Z]*) lcf=`echo "$f" | tr '[A-Z]' '[a-z]'` ;;
	  *)	   lcf=$f ;;
      esac

      thumb=$thdir/$fbase.png
      fthumb=$d/$thumb
      if [ -s "$fthumb" ]
      then echo  "\"%$fthumb%$tag\" Exec $imop $f"
      else echo  "\"$tag\" Exec $imop $f"
           echo "$f" >&3	# to the thumb maker ...
      fi ## | tee -a $HOME/imlist.out
    fi
done

exec 1>&2

(
  exec <"$thumblist"
  rm -f "$thumblist"
  while read f
  do
    mkthumb "$f"
  done
) &
renice +10 -p $! >/dev/null 2>&1
