#!/bin/sh
#
# Generate a self generating FVWM menu.
#	- Cameron Simpson <cs@zip.com.au> 18may2002
#

##alert "$0 $*"

noentries=
noauto=

cmd=$0
usage="Usage: $cmd [-1] [-n] menu title cmd [args...]
	-n	Don't geneate any menu entries (bootstrap).
	-1	Don't give this menu a DynamicPopUpAction."

while :
do
  case $1 in
    -n) noentries=1 ;;
    -1) noauto=1 ;;
    *)  break ;;
  esac
  shift
done

[ $# -ge 3 ] || { echo "$usage" >&2; exit 2; }

menu=$1
title=$2
shift; shift

( [ $noentries ] || exec "$@" ) \
| ( echo "DestroyMenu $menu"
    echo "AddToMenu $menu \"$title\" Title"
    [ $noauto ] || echo "AddToMenu $menu DynamicPopUpAction Piperead '$0 $menu \"$title\" $*'"
    exec sed "s/^/AddToMenu $menu /"
  )
