#!/bin/sh
#
# Recite the named URLs map as an FVWM menu.
#	- Cameron Simpson <cs@zip.com.au> 14feb2003
#

echo "\"Hi\" PopHiMenu"
echo "\"\" Nop"

while read title && read url
do
  echo "\"$title\" Exec us $url"
done <$HOME/rc/urlmap \
| sort -d
