#!/bin/sh
#
# Emit my FVWM RC file.
#	- Cameron Simpson <cs@zip.com.au> 19aug2002
#

. $HOME/rc/x11/xenv.sh

(
  uncurly $HOME/rc/x11/fvwm/rc-curly
  desktop-incant -
  desktop-incant-bg - -q
  desktop-incant-names -
  fvwm-deskkeys
  echo SwitchToDesk 1
) \
| tee $HOME/tmp/fv.rc-$HOST-$DISPLAY
