#!/bin/sh

##[ -n "$FVWMCMDLOG" ] || { echo "$0: no \$FVWMCMDLOG envvar" >&2; exit 1; }
##[ -f "$FVWMCMDLOG" ] || { echo "$0: $FVWMCMDLOG missing!" >&2; exit 1; }
##exec >>"$FVWMCMDLOG"

if [ $# = 0 ]
then
    # don't use "cat" because I want unbuffered output
    FvwmCommand -c
else
    for arg
    do  FvwmCommand "$arg"
	##sleep 1
    done
fi
