#!/bin/sh
newdesk \
| sort +1 \
| awk '{ desks++
         print "\"" $2 "	switch to\" SwitchToDesk 0 " ($1+13)
         print "\"	push\" PushToDesk 0 " ($1+13)
       }
       END { if (desks == 0) print "\"no named desktops\" Nop" }'
