#!/bin/sh
#
# Recite the named URLs map as an FVWM menu.
#	- Cameron Simpson <cs@zip.com.au> 14feb2003
#

echo "\"Hi\" PopHiMenu"
echo "\"\" Nop"

exec <$HOME/rc/urlmap
while read title && read url shcmd
do
  doqcmd=
  [ -n "$shcmd" ] && { shcmd="; $shcmd" doqcmd=1; }
  case "$url" in
    *[^a-zA-Z0-9:/.]*)	qurl=`shqstr "$url"` doqcmd=1 ;;
    *)			qurl=$url ;;
  esac
  shcmd="us $qurl $shcmd"
  [ $doqcmd ] && shcmd=`shqstr "$shcmd"`
  echo "\"$title\" Exec sh -c $shcmd"
done \
| tee -a $CONSOLE \
| sort -d
