#!/bin/sh
#
# List known jobs not in CLOSED state.
#	- Cameron Simpson <cs@zip.com.au>
#

joblist name category state title \
| awk '-F	' '$4 != "CLOSED" { print "\"" $2 ": " $5 "\t" $3 "\" Exec exec deskjob " $2 }' \
| sort
