#!/bin/sh
: ${LOGDIR:=$HOME/var/log}
: ${URLLOG:=$LOGDIR/urllog}
sed -n 's:^search  *::p' <"$URLLOG" \
| keeplast \
| tail -40 \
| sort -u \
| awk '{ engine=$1
	 query=$2
         for (i=3; i<=NR; i++) { query=query " " $i }
	 print "\"" engine ": " query "\" Exec search -t " engine " " query
       }'
