#!/bin/sh -u
#
# Generate menu for a bookmark directory.
#	- Cameron Simpson <cs@zip.com.au> 02mar2003
#
# Updated to use bmk bookmarks. - cameron 19apr2005
#

: ${BMK_DIR:=$HOME/rc/bmk}

dir=$BMK_DIR

cmd=$0
usage="Usage: $cmd [dir]"

badopts=

while [ $# -gt 0 ]
do
  case $1 in
    --) shift; break ;;
    -?*)echo "$cmd: unrecognised option: $1">&2
	badopts=1
	;;
    *)	break ;;
  esac
  shift
done

[ $# -gt 0 ] && { dir=$1; shift; }

[ $# = 0 ] || { echo "$cmd: extra arguments after dir: $*" >&2; badopts=1; }

[ $badopts ] && { echo "$usage" >&2; exit 2; }

cd "$dir"		|| exit 1
wd=`pwd`		|| exit 1
nd=`basename "$wd"`	|| exit 1
##echo "\"$nd\" Title"

pd=`dirname "$wd"`	|| exit 1
pnd=`basename "$pd"`	|| exit 1
echo "\"<-- $pnd\" PopBmDir $pd"

xit=0

dirs=
dsep=
urls=
usep=
for bm in *
do
  if [ -d "$bm/." ]
  then
      dirs="$dirs$dsep\"$bm ->\" PopBmDir \"$wd/$bm\""
      dsep='
'
      continue
  fi
  
  if [ -s "$bm" ]
  then
      url=`sed -n -e '/^$/q' -e '/^[Uu][Rr][Ll]:/{ s/^[^:]*: *//p; q; }' <"$bm"`
      [ -n "$url" ] || url=file://$wd/$bm
      title=`sed -n -e '/^$/q' -e '/^[Ss][Uu][Bb][Jj][Ee][Cc][Tt]:/{ s/^[^:]*: *//p; q; }' <"$bm"`
      [ -n "$title" ] || title=$bm

      urls="$urls$usep\"$title\" Exec us '$url'"
      usep='
'
      continue
  fi
done

[ -n "$dirs" ] && echo "$dirs"
[ -n "$dirs" -a -n "$urls" ] && echo "\"\" Nop"
[ -n "$urls" ] && echo "$urls"

exit $xit
