#!/bin/sh
: ${LOGDIR:=$HOME/var/log}
: ${URLLOG:=$LOGDIR/urllog}
sed -n 's;^urlshow  *http://;;p' <"$URLLOG" \
| keeplast \
| tail -400 \
| reverse \
| awk '{ print "\"" $0 "\" Exec us \"http://"$0"\"" }'
