#!/bin/sh
#
# Recent menu backgrounds.
#	- Cameron Simpson <cs@zip.com.au>
#

: ${LOGDIR:=$HOME/var/log}

FVWM_MENU_IMLIST_OP=${FVWM_MENU_IMLIST_OP:-"menubg"}
export FVWM_MENU_IMLIST_OP
exec fvwm-menu-recent-imlist ${1-0} ${1-40} ${1+"$@"} <"$LOGDIR/lastvalue/menubg"
