#!/bin/sh
URLLOG=${URLLOG:-$HOME/var/log/urllog}
export URLLOG
sed -n 's;^urlshow  *http://;;p' <"$URLLOG" \
| keeplast \
| tail -400 \
| reverse \
| awk '{ print "\"" $0 "\" Exec us \"http://"$0"\"" }'
