#!/bin/sh
#
# Emit my FVWM RC file.
#	- Cameron Simpson <cs@zip.com.au> 19aug2002
#

. $HOME/rc/x11/xenv.sh

: ${X11_COMPOSITE:=''}
case "$X11_COMPOSITE" in
  '')	fvwm_Transparent=Transparent
	fvwm_RootTransparent=RootTransparent
	fvwm_ParentalRelativity=ParentalRelativity
	;;
  *)	fvwm_Transparent=
	fvwm_RootTransparent=
	fvwm_ParentalRelativity=
	;;
esac
export fvwm_Transparent fvwm_RootTransparent fvwm_ParentalRelativity

(
  uncurly $HOME/rc/x11/fvwm/rc-curly
  desktop-incant -
  desktop-incant-names -
  fvwm-deskkeys
  echo SwitchToDesk 1
) \
| tee $HOME/tmp/fv.rc-$HOST-$DISPLAY
