#!/bin/sh
#
# Generate menu for a bookmark directory.
#	- Cameron Simpson <cs@zip.com.au> 02mar2003
#

cmd=$0
usage="Usage: $cmd dir"

badopts=

while :
do
  case $1 in
    --) shift; break ;;
    -?*)echo "$cmd: unrecognised option: $1">&2
	badopts=1
	;;
    *)	break ;;
  esac
  shift
done

if [ $# = 0 ]
then
    echo "$cmd: missing dir" >&2
    badopts=1
else
    dir=$*; shift
    cd "$dir" || exit 1
fi

[ $badopts ] && { echo "$usage" >&2; exit 2; }

wd=`pwd`
nd=`basename "$wd"`
##echo "\"$nd\" Title"

pd=`dirname "$wd"`
pnd=`basename "$pd"`
echo "\"<-- $pnd\" PopBmDir $pd"

dirs=
dsep=
urls=
usep=
for bm in *
do
  if [ -d "$bm/." ]
  then
      dirs="$dirs$dsep\"$bm ->\" PopBmDir \"$wd/$bm\""
      dsep='
'
  else
      exec <"$bm"
      if read url
      then
	  urls="$urls$usep\"$bm\" Exec us '$url'"
	  usep='
'
      else
	  : echo "\"--$bm--\" Nop"
      fi
  fi
done

[ -n "$dirs" ] && echo "$dirs"
[ -n "$dirs" -a -n "$urls" ] && echo "\"\" Nop"
[ -n "$urls" ] && echo "$urls"
