#!/bin/sh -u
#
# Toss all chains, remake LOG* and FW_* chains.
#	- Cameron Simpson <cs@zip.com.au> 18oct2003
#

cmd=$0
usage="Usage: $cmd"

[ $# = 0 ] || { echo "$usage" >&2; exit 2; }

iptables -L -n \
| awk '/^Chain [A-Z]/ {print $2}' \
| ( set -x
    while read chain
    do  iptables -F "$chain"
    done
  )
set -x
iptables -X

iptables -N LOGREJECT
iptables -N JUSTREJECT
iptables -N LOGACCEPT
iptables -N FW_INPUT
iptables -N FW_OUTPUT
iptables -N FW_FORWARD

iptables -A INPUT -j FW_INPUT
iptables -A OUTPUT -j FW_OUTPUT
iptables -A FORWARD -j FW_FORWARD

iptables -A LOGREJECT -j LOG --log-prefix 'REJECT: '
iptables -A LOGREJECT -j JUSTREJECT

iptables -A JUSTREJECT -p tcp -m tcp -j REJECT --reject-with tcp-reset
iptables -A JUSTREJECT -p udp -m udp -j REJECT
iptables -A JUSTREJECT -j DROP

iptables -A LOGACCEPT -j LOG --log-prefix 'ACCEPT: '
iptables -A LOGACCEPT -j ACCEPT
iptables -A LOGACCEPT -j DROP
