#!/bin/sh-u
#
# Set policies.
#	- Cameron Simpson <cs@zip.com.au> 18oct2003
#

cmd=$0
usage="Usage: $cmd policy [chains...]"

trace=

if [ $# = 0 ]
then  echo "$cmd: missing policy" >&2
      echo "$usage" >&2
      exit 2
fi
policy=$1; shift

[ $# = 0 ] && set INPUT OUTPUT FORWARD

xit=0

for chain
do $trace iptables -P "$chain" "$policy" || xit=1
done

exit $xit
