#!/bin/sh -u
#
# Permit outgoing traffic for a service to specified hosts (or "ALL").
#	- Cameron Simpson <cs@zip.com.au> 18oct2003
#

: ${FW_CHAIN_INPUT:=INPUT}
: ${FW_CHAIN_OUTPUT:=OUTPUT}
: ${FW_CHAIN_FORWARD:=FORWARD}

cmd=$0
usage="Usage: $cmd [-l] dest-port {ALL | hosts...}"

badopts=

dolog=1
[ $# -gt 0 ] && [ "x$1" = x-l ] && { dolog=1; shift; }
[ $# -gt 0 ] && [ "x$1" = x+l ] && { dolog=; shift; }

if [ $# = 0 ]
then
    echo "$cmd: missing dest-port" >&2
    badopts=1
else
    dport=$1; shift
    if [ $# = 0 ]
    then
	echo "$cmd: missing ALL or hosts" >&2
	badopts=1
    fi
fi

[ $badopts ] && { echo "$usage" >&2; exit 2; }

if [ "x$*" = xALL ]
then
    set -x
    [ $dolog ] && iptables -I "$FW_CHAIN_OUTPUT" -p tcp --destination-port "$dport" --syn -j LOGACCEPT
    iptables -I "$FW_CHAIN_OUTPUT" -p tcp --destination-port "$dport" -j ACCEPT
    iptables -I "$FW_CHAIN_INPUT" -p tcp --source-port "$dport" ! --syn -j ACCEPT
else
    set -x
    for host in `hostips "$@"`
    do
      [ $dolog ] && iptables -I "$FW_CHAIN_OUTPUT" -p tcp -d "$host" --destination-port "$dport" --syn -j LOGACCEPT
      iptables -I "$FW_CHAIN_OUTPUT" -p tcp -d "$host" --destination-port "$dport" -j ACCEPT
      iptables -I "$FW_CHAIN_INPUT" -p tcp -s "$host" --source-port "$dport" ! --syn -j ACCEPT
    done
fi
