#!/bin/sh
#
# Permit incoming UDP traffic for a service from specified hosts (or "ALL").
#	- Cameron Simpson <cs@zip.com.au> 18oct2003
#

cmd=$0
usage="Usage: $cmd [-l] dest-port {ALL | hosts...}"

badopts=

dolog=
[ "x$1" = x-l ] && { dolog=1; shift; }

if [ $# = 0 ]
then
    echo "$cmd: missing dest-port" >&2
    badopts=1
else
    dport=$1; shift
    if [ $# = 0 ]
    then
	echo "$cmd: missing ALL or hosts" >&2
	badopts=1
    fi
fi

[ $badopts ] && { echo "$usage" >&2; exit 2; }

target=ACCEPT
[ $dolog ] && target=LOGACCEPT

set -x
if [ "x$*" = xALL ]
then
    iptables -A INPUT -p udp --destination-port "$dport" -j "$target"
    iptables -A OUTPUT -p udp --source-port "$dport" -j "$target"
else
    set -x
    for host
    do
      iptables -A INPUT -p udp -s "$host" --destination-port "$dport" -j "$target"
      iptables -A OUTPUT -p udp -d "$host" --source-port "$dport" -j "$target"
    done
fi
