#!/bin/sh
#
# Asynchronous getpageurls.	- Cameron Simpson <cs@zip.com.au>
#

async=1
if [ "x$1" = x-s ]
then  shift; async=
fi

# hack to permit leading subdir prefix
case $1 in
    ''|-*|*://*)	;;
    *)		dirpfx=$1; shift
		if subdir=`mkdirn "$dirpfx/$dirpfx"`
		then
		    cd "$subdir" || exit 1
		fi
		colour_echo white "`pwd`"
		L
		;;
esac

[ $# = 0 ] && { set x "`xunclip`"; shift; }

ulimit -d 16384	## 16M process data limit

set -x
[ $async ] || exec getpageurls -L download ${1+"$@"}
ignhup getpageurls -L download ${1+"$@"} &
