#!/bin/sh
#
# Asynchronous getpageurls.	- Cameron Simpson <cs@zip.com.au>
#

# hack to permit leading subdir prefix
case $1 in
    ''|-*|*://*)	;;
    *)		dirpfx=$1; shift
		if subdir=`mkdirn "$dirpfx/$dirpfx"`
		then
		    cd "$subdir" || exit 1
		fi
		colour_echo white "`pwd`"
		L
		;;
esac

umlimit -d 16384	## 16M process data limit

if [ "x$1" = x-s ]
then  shift
      exec getpageurls -L download ${1+"$@"}
else
      [ $# = 0 ] && { set x "`xunclip`"; shift; }
fi

set -x
ignhup getpageurls -L download ${1+"$@"} &
