#!/bin/sh
#
# Asynchronous getpageurls.	- Cameron Simpson <cs@zip.com.au>
#

: ${TMPDIR:=/tmp}

cmd=$0
usage="Usage: $cmd [-s] [dirpfx] pageurl"

async=1
if [ "x$1" = x-s ]
then  shift; async=
fi

# hack to permit leading subdir prefix
case $1 in
    ''|-*|*://*)	;;
    *)		dirpfx=$1; shift
		case "$dirpfx" in
		  */*?)	;;
		  *)	dirpfx=$dirpfx/ ;;
		esac
		subdir=`mkdirn "$dirpfx"` || exit 1
		cd "$subdir" || exit 1
		colour_echo white "`pwd`"
		L
		;;
esac

if [ $# = 0 ]
then
  [ -n "$DISPLAY" ] && { set -- `xclip -o` || xit 1; }
  if [ $# = 0 ]
  then
    echo "$cmd: missing pageurl and no default" >&2
    exit 2
  fi
fi

ulimit -d 16384	## 16M process data limit

tmp=$TMPDIR/gpu$$
for arg
do  echo "$arg"
done >"$tmp"
exec <"$tmp"
cat "$tmp"
rm "$tmp"
set getpageurls -q "$HOME/var/queue/httpgetd"
set -x
[ $async ] || exec "$@"
exec bgstdin "$@"
