#!/bin/sh
#
# Collect stdin and bg the named command, sending output to the
# console log, IGNHUPed.
#	- Cameron Simpson <cs@zip.com.au> 16sep98
#

cons=`logpath console`

tmp=/tmp/grabstdin.$$

cat >"$tmp" || { rm -f "$tmp" 2>/dev/null; exit 1; }

exec >>"$cons" 2>&1

(
  rm "$tmp"
  trap '' 1	# ignore SIGHUP
  exec "$@"
) <"$tmp" &

exit 0
