#!/bin/sh -u
#
# Read mail item, grab unknown addresses, prepend to mutt aliases file, edit.
#	- Cameron Simpson <cs@zip.com.au> 10dec2005
#

: ${TMPDIR:=/tmp}
: ${GRABALIASES_CATEGORIES:=$SYSTEMID}

mailcfg=$HOME/rc/mail
aliasfile=$mailcfg/aliases

cmd=`basename "$0"` || cmd=grabaliases
usage="Usage: $cmd [options...] [mailitem]
	-q	Quick. Skip edit and myke.
        -C      Specify alias categories.
                Default from \$GRABALIASES_CATEGORIES: $GRABALIASES_CATEGORIES
	-M	Run a myke to rebuild.
	-t	Open a new term.
	-T	Attach to /dev/tty."

domyke=
useterm=
usetty=
quick=

badopts=

while [ $# -gt 0 ]
do
  case $1 in
    -q)	quick=1 ;;
    -C) GRABALIASES_CATEGORIES=$2; shift ;;
    -M)	domyke=1 ;;
    -t)	useterm=1 ;;
    -T)	usetty=1 ;;
    --)	shift; break ;;
    -?*)echo "$cmd: unrecognised option: $1" >&2
	badopts=1
	;;
    *)	break ;;
  esac
  shift
done

if [ $# = 0 ]
then
  mailitem=-
else
  mailitem=$1; shift

  [ $# = 0 ] || { echo "$cmd: extra arguments: $*" >&2; badopts=1; }
fi

[ $badopts ] && { echo "$usage" >&2; exit 2; }

if [ "x$mailitem" = x- ]
then  exec 3<&0
      usetty=1
else  exec 3<"$mailitem"
fi

[ $usetty ] && exec </dev/tty >/dev/tty 2>&1

tmpaliases=$TMPDIR/$cmd$$aliases
trap 'rm -f "$tmpaliases"' 0 1 2 13 15

( sed -n 's/.*<\([^<>@]*@[^<>]*\)>.*/\1/p' "$aliasfile"
  echo NEW
  grabaddrs-all <&3
) \
| awk 'BEGIN		{ part=1 }
       $1 == "NEW"	{ part=2 }
       $1 != "NEW"	{ if (part == 2 && !seen[$1])
			  { print
			  }
			  seen[$1]=1
			}
      ' \
| sed '	y/\t/ /
	s/   */ /g
	h
	s/ .*//
	s/^/</
	s/$/>/
	x
	s/^[^ ]* //
	G
	s/\n/ /
	h
	s/ <[^ ]*>$//
	y/ /./
	s/[^a-zA-Z0-9.-]/./g
	s/\.\.\.*/./g
	G
	s/\n/ /
	'"s^$GRABALIASES_CATEGORIES " \
| colpad 16 40 \
> "$tmpaliases"

cat "$aliasfile" >>"$tmpaliases" || exit 1

set -- "$EDITOR" "$tmpaliases"
[ $useterm ] && set -- term -e "$@"
[ $quick ] || "$@" || exit 1

rewriteif "$aliasfile" <"$tmpaliases" && { [ $quick ] || mutt-refile; }
