#!/bin/sh
#
# Grep all lines from stdin containing all the command line regexps.
#	- Cameron Simpson <cs@zip.com.au> 12nov2001
#

cmd=$0

[ $# = 0 ] && { echo "Usage: $cmd regexps..." >&2; exit 2; }

ok=1

first=1
for word
do
  [ $first ] && { set x; shift; first=; }

  case "$word" in
    */*)	echo "$cmd: can't do slashes: $word" >&2
		ok=
		continue
		;;
  esac

  set x ${1+"$@"} -e "/$word/!d"; shift
done

[ $ok ] || exit 1

exec sed "$@"
