#!/bin/sh
#
# List images whose width > height, eg to pick some wallpaper.
#	- Cameron Simpson <cs@zip.com.au> 28feb2001
#

if [ $# = 0 -o "x$*" = x- ]
then
    set x `cat`
    shift
fi

imsize ${1+"$@"} /dev/null 2>/dev/null \
| awk '$2 > $3 { print $1 }'
