#!/bin/sh
#
# Grep all lines from stdin containing all the command line regexps.
#	- Cameron Simpson <cs@zip.com.au> 12nov2001
#

cmd=$0

[ $# = 0 ] && { echo "Usage: $cmd [-o] sed-regexps..." >&2; exit 2; }

any=
[ "x$1" = x-o ] && { any=1; shift; }

if [ $# = 0 ]
then
    echo "$cmd: missing sed-regexps" >&2
    echo "$usage" >&2
    exit 2
fi

ok=1

first=1
for word
do
  [ $first ] && { set x; shift; first=; }

  case "$word" in
    */*)	echo "$cmd: can't do slashes: $word" >&2
		ok=
		continue
		;;
  esac

  if [ $any ]
  then set x ${1+"$@"} -e "/$word/b ok"; shift
  else set x ${1+"$@"} -e "/$word/!d"; shift
  fi
done

[ $ok ] || exit 1

[ $any ] && { set x ${1+"$@"} -e d -e ':ok'; shift; }

exec sed "$@"
