#!/bin/sh
#
# Configure directory trees for group sharing:
#	- chgrp to named group
#	- group r/w
#	- setgid dirs
# - Cameron Simpson <cs@zip.com.au> 27sep2000
#

cmd=`basename "$0"`
usage="Usage: $cmd [-a] group dirs..."

badopts=

all=
[ "x$1" = x-a ] && { all=1; shift; }

if [ $# = 0 ]
then
  echo "$cmd: missing group" >&2
  badopts=1
else
  group=$1; shift
  if [ $# = 0 ]
  then
    echo "$cmd: missing dirs" >&2
    badopts=1
  fi
fi

[ $badopts ] && { echo "$usage" >&2; exit 2; }

grep "^$group:" /etc/group \
|| ypmatch "$group" group \
|| ask "Can't look up group \"$group\", proceed anyway" \
|| exit 1

for dir
do
  [ -f "$dir" ] && continue
  ( cd "$dir" || exit 1
    exec /bin/pwd
  ) || exit 1
done

ask "Proceed with groupshare on the above directories" || exit 1

for dir
do
  [ -f "$dir" ] && { echo "SKIPPING $dir" >&2; continue; }
  ( cd "$dir" || exit 1
    /bin/pwd || exit 1

    set -x
    find . ! -type l ! -group "$group" -print \
    | xxargs set-x chgrp "$group"

    if [ $all ]
    then
	find . ! -type l -print \
	| xxargs set-x chmod go=u

	find . ! -type l -print \
	| xxargs set-x chmod o-w
    else
	find . ! -type l -print \
	| xxargs set-x chmod g=u
    fi

    find . -type d -print \
    | xxargs set-x chmod g+s
  ) || break
done
