#!/bin/sh
#
# Configure a directory tree for group sharing:
#	- chgrp to named group
#	- group r/w
#	- setgid dirs
# - Cameron Simpson <cs@zip.com.au> 27sep2000
#

all=
[ "x$1" = x-a ] && { all=1; shift; }

[ $# = 0 ] && { echo "Usage: $0 [-a] group [dirs...]" >&2; exit 2; }

group=$1; shift
grep "^$group:" /etc/group || ypmatch "$group" group || exit 1

[ $# = 0 ] && set .

pwd
ask "Proceed with groupshare on $*" || exit 1

for dir
do  ( cd "$dir" || exit 1
      pwd
      set -x
      find . ! -type l ! -group "$group" -print \
      | xxargs set-x chgrp "$group"
      if [ $all ]
      then
	  find . ! -type l -print \
	  | xxargs set-x chmod go=u

	  find . ! -type l -print \
	  | xxargs set-x chmod o-w
      else
	  find . ! -type l -print \
	  | xxargs set-x chmod g=u
      fi
      find . -type d -print \
      | xxargs set-x chmod g+s
    )
done
