#!/bin/sh
#
# Quick'n'dirty upload from Canon digital camera.
#	- Cameron Simpson <cs@zip.com.au> 12aug2001
#

cmd=`basename "$0"`

[ -n "$S10PORT" ] || { S10PORT=/dev/ttyS1; export S10PORT; }
[ -n "$S10SPEED" ] || { S10SPEED=115200; export S10PORT; }

exec set-x s10sh -d "$S10PORT" -s "$S10SPEED" -g -L ${1+"$@"}
