#!/bin/sh
#
# The good morning stuff.	- Cameron Simpson <cs@zip.com.au>
#

: ${TMPDIR:=/tmp}

cmd=`basename "$0"`
hi=$HOME/rc/hi
pickn=

eval `datevars`
weekly=
mode=normal
noop=
nogrep=

[ "x$wdayname" = xMon ] && weekly=1

while :
do
  case $1 in
    -html)	mode=html ;;
    -normal)	mode=normal ;;
    -w)		weekly=1 ;;
    -n)		noop=1 ;;
    -q)		nogrep=1 ;;
    -[0-9]*)	pickn=`expr "x$1" : 'x-\([0-9]*\).*'` ;;
    --)		shift; break ;;
    *)		break ;;
  esac
  shift
done

if [ $# = 0 ]
then
    set .hi
    ##set space science eco chores "$SYSTEMID" weather news-au
    ## [ -n "$mode" ] || mode=html
    ## set rterm `cd "$hi" || exit 1
    ##     ls -d [a-z]*|sed -e '/^cvs$/d' -e '/^Mykefile$/d' -e 's/\.weekly$//'|sort -u`
    ## shift
else
    [ -n "$mode" ] || mode=normal
fi

for task
do
  case "$task" in
    /*)	task=`expr "x$task" : 'x/\(.*[^/]\)/*$'`
	echo "# $task"
	ls -d "$hi/"[a-z]* \
	| grep -v '\.html$' \
	| xxargs cat \
	| egrep "$task"
	;;
    *)	sfxs=; [ $weekly ] && sfxs="$sfxs .weekly"
	for sfx in '' $sfxs
	do  for f in "$hi/$task$sfx" "$hi/$task-"*".$sfx"
	    do  [ -s "$f" ] && cat "$f"
	    done
	done
	;;
  esac \
  | grep '^[^#]' \
  | if [ -n "$pickn" ]; then pickn "$pickn"; else cat; fi \
  | { xvlist=$TMPDIR/xv$cmd$$
      exec 3>&1 1>&2 4>"$xvlist"
      while read url grep
      do  if [ -n "$nogrep" -o -z "$grep" ]
	  then  echo "$url" >&3
	  else  echo "$url" >&2
		pageurls -i "$url" \
		| egrep -i "$grep" \
		| ( hit=
		    while read -r gurl
		    do  ( exec >&2
			  cd $HOME/4h/im/comics || exit 1
			  base=`basename "$gurl"` || exit 1
			  httpget "$gurl" && echo "$HOME/4h/im/comics/$base" >&4
			) &
			echo "$gurl" >&2
			hit=1
		    done
		    [ $hit ] || { echo "no hits grepping $url for \"$grep\"" >&2
				  echo "$url" >&3
				}
		    wait
		  )
	  fi &
      done
      exec 3>&- 4>&-
      wait
      [ -s "$xvlist" ] && ( set -- `sort -u "$xvlist"`; rm "$xvlist"; exec xv "$@" ) &
    } \
  | urlshow \
  &
done
