#!/bin/sh
#
# The good morning stuff.	- Cameron Simpson <cs@zip.com.au>
#

: ${TMPDIR:=/tmp}

cmd=`basename "$0"`
hi=$HOME/rc/hi
pickn=

eval `datevars`
weekly=
mode=normal
noop=
nogrep=

[ "x$wdayname" = xMon ] && weekly=1

while :
do
  case $1 in
    -html)	mode=html ;;
    -normal)	mode=normal ;;
    -w)		weekly=1 ;;
    -n)		noop=1 ;;
    -q)		nogrep=1 ;;
    -[0-9]*)	pickn=`expr "x$1" : 'x-\([0-9]*\).*'` ;;
    --)		shift; break ;;
    *)		break ;;
  esac
  shift
done

if [ $# = 0 ]
then
    set .hi
    ##set space science eco chores "$SYSTEMID" weather news-au
    ## [ -n "$mode" ] || mode=html
    ## set rterm `cd "$hi" || exit 1
    ##     ls -d [a-z]*|sed -e '/^cvs$/d' -e '/^Mykefile$/d' -e 's/\.weekly$//'|sort -u`
    ## shift
else
    [ -n "$mode" ] || mode=normal
fi

for task
do
  case "$task" in
    /*)	task=`expr "x$task" : 'x/\(.*[^/]\)/*$'`
	echo "# $task"
	ls -d "$hi/"[a-z]* \
	| grep -v '\.html$' \
	| xxargs cat \
	| egrep "$task"
	;;
    *)	sfxs=; [ $weekly ] && sfxs="$sfxs .weekly"
	for sfx in '' $sfxs
	do  for f in "$hi/$task$sfx" "$hi/$task-"*".$sfx"
	    do  [ -s "$f" ] && cat "$f"
	    done
	done
	;;
  esac \
  | grep '^[^#]' \
  | if [ -n "$pickn" ]; then pickn "$pickn"; else cat; fi \
  | ( set --
      exec 4>&1 1>&2
      while read -r url grep savedir
      do
	[ $nogrep ] && { echo "$url" >&4; continue; }
	[ -n "$grep" ] || { echo "$url" >&4; continue; }

	hits=`set -x; pageurls -i "$url" | egrep -i "$grep"`
	[ -n "$hits" ] || { echo "$url" >&4; continue; }

	[ -n "$savedir" ] || savedir=.
	case "$savedir" in
	  /*) ;; *) savedir=$HOME/im/comics/$savedir ;;
	esac

	for url
	do
	  if cached=`set-x fileof "$gurl"` \
	  && set-x ifnewfile "$cached"
	  then
	    set -- ${1+"$@"} "$cached"
	    ( gbase=`basename "$gurl"`
	      saveas=$savedir/$gbase
	      set-x lncp "$cached" "$saveas" && set-x fileloc -a "$saveas"
	    ) &
	  else
	    echo "SEEN $gurl" >&2
	  fi
	done
      done
      [ $# = 0 ] || xvmax "$@" &
    ) \
  | urlshow \
  &
done
