#!/bin/sh
#
# Read hostnames or ips on stdin or from command line, recite their IPs on stdout.
# NB: doesn't complain if there are no matches.
#	- Cameron Simpson <cs@zip.com.au> 31jul2004
#

if [ $# -gt 0 ]
then for host
     do echo "$host"
     done
else cat
fi \
| while read host
  do  case "$host" in
	[0-9]*.[0-9]*.[0-9]*.[0-9]* | *:* )
	  echo "$host"
	  ;;
	*)
	  awk "BEGIN	{ hit=0
			  host=\"$host\"
			}
	      "'
	       /^[0-9]/ { yes=0;
			  for (n=2; n<=NF; n++)
			  { if ($n == host) { yes=1; break }
			  }
			  if (yes) { print $1; hit=1 }
			}
	      END	{ if (!hit) exit 1 }' /etc/hosts \
	  || host "$host"
	  ;;
      esac
  done \
| sed -n 's/^[^ ]* has address \([0-9][.0-9]*\).*/\1/
	  /^\([0-9][0-9]*\)\.\([0-9][0-9]*\)\.\([0-9][0-9]*\)\.\([0-9][0-9]*\)$/p' \
| sort -u
