#!/bin/sh
#
# Read hostnames or ips on stdin or from command line, recite their IPs on stdout.
#	- Cameron Simpson <cs@zip.com.au> 31jul2004
#

if [ $# -gt 0 ]
then for host; do echo "$host"; done
else cat
fi \
| while read host
  do  case "$host" in
	[0-9]*.[0-9]*.[0-9]*.[0-9]* | *:* )
	  echo "$host"
	  ;;
	*)host "$host"
	  ;;
      esac
  done \
| sed -n 's/^[^ ]* has address \([0-9][.0-9]*\).*/\1/
	  /^\([0-9][0-9]*\)\.\([0-9][0-9]*\)\.\([0-9][0-9]*\)\.\([0-9][0-9]*\)$/p'
