#!/bin/sh
#
# Read hostnames on stdin or from command line, recite their IPs on stdout.
#	- Cameron Simpson <cs@zip.com.au> 31jul2004
#

if [ $# -gt 0 ]
then
    for host
    do  host "$host"
    done
else
    while read host
    do  host "$host"
    done
fi | sed -n 's/^[^ ]* has address \([0-9][.0-9]*\).*/\1/p'
