#!/bin/sh
#
# Backup my current hotsync and then sync from my palm.
#	- Cameron Simpson <cs@zip.com.au> 03apr2000
#

: ${PILOTPORT:=/dev/pilot}
: ${USER:=`id -un`} || exit 1
: ${HOTSYNC_HISTBACKUP:=$HOME/backup/t5}
export PILOTPORT USER

cmd=`basename "$0"`

needhost $HOMEHOST@home || exit 1
[ -d "$HOTSYNC_HISTBACKUP/." ] || { echo "$cmd: $HOTSYNC_HISTBACKUP: not a directory" >&2; exit 1; }
[ -c "$PILOTPORT" ] || { echo "$cmd: $PILOTPORT: not a tty" >&2; exit 1; }
id=`ls -ldL "$PILOTPORT" | awk '{print$3}'`
[ "x$id" = "x$USER" ] || { echo "$cmd: $PILOTPORT: not owned by \"$USER\" (owner is $id)" >&2
			   exit 1
			 }

histbackup -x --inplace --symlink PREVIOUS "$HOTSYNC_HISTBACKUP" \
|| { echo "$cmd: $HOTSYNC_HISTBACKUP: backup fails, aborting sync" >&2
     exit 1
   }

echo
set -x
exec pilot-xfer -p "$PILOTPORT" -s "$HOTSYNC_HISTBACKUP/current"
