#!/usr/bin/perl
#
# Stash a login/password for use at a web site.
# Naturally this is mega insecure (depending on cs::HTTP::Auth, but that
# happens to be just a cleartext file) and so not for more that trivial uses.
#	- Cameron Simpson <cs@zip.com.au>
#

use cs::HTTP::Auth;

{ my $ADB = new cs::HTTP::Auth(undef,1);

  # host realm userid password
  if (@ARGV != 4)
  { die "Usage: $0 host realm userid password\n";
  }

  my($host,$realm,$userid,$password)=@ARGV;
  $ADB->SaveAuth(BASIC,$host,$realm,$userid,$password);
}

exit 0;
