#!/usr/bin/perl
#
# Do various scourings of input HTML.
#	- Cameron Simpson <cs@zip.com.au> 03mar99
#

use strict qw(vars);

use cs::Misc;
use cs::Source;
use cs::SGML;
use cs::URL;
use Getopt::Std;

## open(STDERR,">> /tmp/htclean.err");

$::CleanTypes='text/html,image/gif';

$::Usage="Usage: $::cmd [-T types] [-fhH] [-t dflttype] [[tag/]attr=n...]
	-b url	Base URL of input.
	-f	Force. Scour input even if type ne text/html.
	-h	Read and emit headers before content.
	-H	Drop leading HTTP response.
	-p port:proxy[:proxyport]
		Listen on port as web proxy.
	-u cgi	URL of scouring CGI script.
	-r	Recurse - prefix HREFs with \"cgi/\".
	-t dflttype Change default type.
	-T types List of types to clean.
		Default: $::CleanTypes.
	tag/attr=n If n!=0, drop attr from <tag>, or from all tags
		if no tag specified.
";

# default: strip colours and fonts
$::Scour={ BGCOLOR => 1,
	   BORDERCOLOR => 1,
	   BACKGROUND => 1,
	   TEXT => 1,
	   LINK => 1,
	   ALINK => 1,
	   VLINK => 1,
	   'LINK/REL' => 1,
	   'FONT/FACE' => 1,
	   'FONT/SIZE' => 1,
	   'FONT/COLOR' => 1,
	   'LAYER/LEFT' => 1,
	   'LAYER/RIGHT' => 1,
	   'LAYER/TOP' => 1,
	   'LAYER/BOTTOM' => 1,
	   'LAYER/WIDTH' => 1,
	   'TABLE/WIDTH' => 1,
	   'TABLE/CELLPADDING' => 1,
	   'TABLE/SPACING' => 1,
	   'TD/WIDTH' => 1,
	   'TD/HEIGHT' => 1,
	   'P/ALIGN' => 1,
	 };

my $badopts = 0;
my $baseURL;
my $dropHTTPresponse = 0;
my $hasHeaders = 0;
my $refpfx = '';
my $recurse = 0;
my $servePort;
getopts('b:fhHp:u:rt:T:') || ($badopts=1);
$baseURL=$::opt_b if defined $::opt_b;
$::Force=1 if defined $::opt_f;
$dropHTTPresponse=1 if defined $::opt_H;
$hasHeaders=1 if defined $::opt_h;
$servePort=$::opt_p if defined $::opt_p;
$refpfx=$::opt_u if defined $::opt_u;
$recurse=1 if defined $::opt_r;
$::DfltType=lc($::opt_t) if defined $::opt_t;
$::CleanTypes=$::opt_T if defined $::opt_T;
@::CleanTypes=map(lc, grep(length, split(/[,\s]+/, $::CleanTypes)));

if (defined $servePort)
{
  if ($servePort !~ /^(\w+):([-.\w]+(:(\w+))?)$/)
  { warn "$::cmd: bad syntax for port:proxy[:proxyport]\n";
    $badopts=1;
  }
  else
  { $::ListenOn=$1;
    
    my $upstream=$2;
    if ($upstream =~ /:/)
    { $::UpstreamPort=$';
      $::UpstreamHost=$`;
    }
    else
    { $::UpstreamPort=8080;
      $::UpstreamHost=$upstream;
    }
  }
}

# grab extra scouring tags
for (@ARGV)
{ if (/^([a-z_]\w*)(=(\d+))?$/)
  { my $tag = $1;

    my $set = 1;
    if (length $2)
    { $set=$3+0;
    }

    ## print "{$tag}=$set\n";
    $::Scour->{uc($tag)}=$set;
  }
  else
  { warn "$::cmd: bad argument: $_\n";
    $badopts=1;
  }
}

die $::Usage if $badopts;

$::TagScour={};
for my $pt (grep(m:/:, keys %$::Scour))
{ my($tag,$attr)=($pt =~ m:([^/]*)/+(.*):);
  $tag=uc($tag);
  $attr=uc($attr);

  ## print "{$tag}/{$attr}=$::Scour->{$pt}\n";
  $::TagScour->{$tag}={} if ! exists $::TagScour->{$tag};
  $::TagScour->{$tag}->{$attr}=$::Scour->{$pt};
}

if (! defined $servePort)
{ exit htclean(STDIN,$dropHTTPresponse,$hasHeaders,$refpfx,$baseURL);
}

# run as proxy server
::need(cs::Net::TCP);
my $this = cs::Net::TCP->new($::ListenOn);
die "$::cmd: can't bind to port $::ListenOn: $!" if ! defined $this;
$this->Serve(($cs::Net::TCP::F_FORK|$cs::Net::TCP::F_FORK2),SERVICE);
# NOTREACHED
exit 1;

#sub SERVICE	# (CONN,peer)
#{ local($CONN,$peer)=@_;
#  local($OUT)=select;
#
#  close($OUT) || warn "$cmd: can't close($OUT): $!\n";
#
#  my $outfh = $CONN->SourceHandle();
#  open(STDOUT,">&$outfh")
#	|| die "$cmd: can't attach stdout to $outfh\n";
#
#  exit htclean($CONN->SourceHandle(), 
#}

sub htclean
{ my($FILE,$dropHTTPresponse,$hasHeaders,$refpfx,$baseURL)=@_;
## warn "htclean(@_)";

  local($::Xit)=0;

  my $s = new cs::Source (FILE,$FILE);

  if ($dropHTTPresponse)
  { length $s->GetLine()
	  || die "$::cmd: unexpected EOF looking for leading HTTP response\n";
  }

  my $type = $::DfltType;
  if ($hasHeaders)
  {
    HDR:
    while (defined ($_=$s->GetLine()))
    { print unless /^content-length:/i;	# hah!
      if (/^content-type:\s+([^;\s]+)/i)
      { $type=lc($1);
      }
      elsif (/^\r?$/)
      { last HDR;
      }
    }
  }

  ## warn "type=[$type]";

  # short circuit if wrong type
  if (! $::Force && !grep($type eq $_, @::CleanTypes))
  {
    while (length ($_=$s->Read()))
    { print;
    }
    return 0;
  }

  if ($type eq 'image/gif')
  { if (open(GIFSICLE,"| exec gifsicle '#0'"))
    { select(GIFSICLE);
    }

    while (length ($_=$s->Read()))
    { print;
    }
    return 0;
  }

  # assume text/html

  my $parse = new cs::SGML $s;
  my $base;

  if (defined $baseURL)
  { $base = new cs::URL $baseURL;
    print cs::SGML::tok2a({ TAG => A,
			    START => 1,
			    ATTRS => { HREF => $baseURL },
			  }), "Unscour $baseURL", "<BR>\n";
    print cs::SGML::tok2a({ TAG => A,
			    START => 1,
			    ATTRS => { HREF => ("$refpfx/"
					       .($recurse
						 ? "ONCE"
						 : "ALL"
						)."/$baseURL") },
			  }), "Recursion ".($recurse?"off":"on"), "<BR>\n";
    print "<HR>\n";
  }

  { my $t; my $atok;
    while (defined ($t=$parse->Tok()))
    { $t=scour($t,$refpfx,$base,$recurse);
      print cs::SGML::tok2a($t);
    }
  }

  return 0;
}

sub scour($$$$)
{ my($t,$refpfx,$base,$recurse)=@_;

  if (ref $t)
  { my $tag = uc($t->{TAG});

    # disable STYLE tags
    if ($tag eq STYLE)
    { $t->{TAG}=NOSTYLE;
    }

    my $A = $t->{ATTRS};
    my @a = keys %$A;

    if ($tag eq BLINK)
    { $t->{TAG}=EM;
    }
    elsif ($tag eq NOBR)
    { $t->{TAG}=BR;
    }
    elsif ($tag eq LAYER)
    { $t->{TAG}=DIV;
    }
    elsif ($tag eq EMBED)
    { $t->{TAG}=A;
      $A->{HREF}=$A->{SRC};
      unshift(@{$t->{TOKENS}}, "[ EMBEDment of $A->{HREF} ]");
    }
      

    for my $a (@a)
    { my $uca = uc($a);
      if (exists $::Scour->{$uca} && $::Scour->{$uca}
       || exists $::TagScour->{$tag} && exists $::TagScour->{$tag}->{$uca})
      { delete $A->{$a};
	## print "remove $a from $t->{TAG}\n";
      }
    }

    if (defined $base)
    { for my $a (HREF,SRC,ACTION)
      { if (exists $A->{$a})
	{ $A->{$a}=$base->Abs($A->{$a})->Text();
	}
      }
    }

    if (length $refpfx)
    { if ($recurse && exists $A->{HREF}
       && $A->{HREF} =~ /^(http|ftp):\/\//i
	 )
      { $A->{HREF}="$refpfx/$A->{HREF}";
      }

      if ( ($tag eq FRAME || $tag eq IMG)
	&& exists $A->{SRC}
        && $A->{SRC} =~ /^(http|ftp):\/\//i
	 )
      { $A->{SRC}="$refpfx/$A->{SRC}";
      }
    }
  }

  $t;
}
