#!/bin/sh
#
# Save a web page for future reference.
#	- Cameron Simpson <cs@zip.com.au> 05jan2003
#

: ${TMPDIR:=/tmp}
: ${MAILDIR:=$HOME/mail}
export MAILDIR

folder=+SAVED/web

cmd=$0
usage="Usage: $cmd [+folder] [{-|URL}...]
	+folder	File in specified folder (default: $folder)."

badopts=
while :
do  case $1 in
      +)	folder=+attn ;;
      +*)	folder=$1 ;;
      --)	shift; break ;;
      -?*)	echo "$cmd: unrecognised option: $1" >&2
		badopts=1 ;;
      *)	break ;;
    esac
    shift
done

if [ $# = 0 ]
then
    echo "$cmd: no URLs" >&2
    badopts=1
fi

[ $badopts ] && { echo "$usage" >&2; exit 2; }

xit=0

tmpf=$TMPDIR/htsave$$
trap 'rm -f "$tmpf"' 0 1 2 13 15

for url
do
  if [ "x$url" = x- ]
  then
      "$0" "$folder" `cat` || xit=1
      continue
  fi

  httpget -h -o "$tmpf" "$url" \
  || { xit=1; continue; }

  (
    echo "X-URL: $url"
    echo "X-Fetch-Date: `date`"
    unhdr "$tmpf" | html-title | sed -n '1s/^/Subject: /p'
    exec cat "$tmpf"
  ) \
  | filemailitem "$folder" \
  || xit=1
done

exit $xit
