#!/bin/sh
#
# Save a web page for future reference.
#	- Cameron Simpson <cs@zip.com.au> 05jan2003
#

: ${TMPDIR:=/tmp}
: ${MAILDIR:=$HOME/mail}
export MAILDIR

folder=+SAVED/web

cmd=$0
usage="Usage: $cmd [+folder] [{-|URL}...]
	+folder	File in specified folder (default: $folder)."

badopts=
while :
do  case $1 in
      +)	folder=+attn ;;
      +*)	folder=$1 ;;
      --)	shift; break ;;
      -?*)	echo "$cmd: unrecognised option: $1" >&2
		badopts=1 ;;
      *)	break ;;
    esac
    shift
done

if [ $# = 0 ]
then
    [ -n "$DISPLAY" ] && { set -- `xclip -o` || exit 1; echo "$*" >&2; }
    [ $# = 0 ] && { echo "$cmd: no URLs and no default" >&2; badopts=1; }
fi

[ $badopts ] && { echo "$usage" >&2; exit 2; }

xit=0

tmpf=$TMPDIR/htsave$$
trap 'rm -f "$tmpf"' 0 1 2 13 15

for url
do
  if [ "x$url" = x- ]
  then
      "$0" "$folder" `cat` || xit=1
      continue
  fi

  httpget -h -o "$tmpf" "$url" \
  || { xit=1; continue; }

  (
    echo "X-URL: $url"
    echo "X-Fetch-Date: `date`"
    ( 
      sed -n -e 'y/	/ /' \
	     -e 's/.*<[Tt][Ii][Tt][Ll][Ee]>\([^< ][^<]*\).*/Subject: \1/p' \
	     -e 'T nope; q; :nope; d' \
	     "$tmpf"
      sed -n -e 'y/	/ /' \
	     -e 's/.*<[Hh]1>\([^< ][^<]*\).*/Subject: \1/p' \
	     -e 'T nope; q; :nope; d' \
	     "$tmpf"
    ) \
    | sed -e 's/\&lt;/</g;' \
	  -e 's/\&gt;/>/g' \
	  -e 's/\&nbsp;/ /g' \
	  -e 's/\&quot;/"/g' \
	  -e 's/\&amp;/\&/g' \
	  -e 1q
    exec cat "$tmpf"
  ) \
  | filemailitem "$folder" \
  || xit=1
done

exit $xit
