#!/bin/sh
#
# Save a web page for future reference.
#	- Cameron Simpson <cs@zip.com.au> 05jan2003
#

folder=saved

cmd=$0
usage="Usage: $cmd -f folder [URLs...]
	-f folder	File in specified folder (default: $folder)."

badopts=
while :
do  case $1 in
      -f)	folder=$2; shift ;;
      --)	shift; break ;;
      -?*)	echo "$cmd: unrecognised option: $1" >&2
		badopts=1 ;;
      *)	break ;;
    esac
done

[ $badopts ] && { echo "$usage" >&2; exit 2; }

[ $# = 0 ] && { set x `xclip -o`; shift; echo "use xclip $*" >&2; }

xit=0

tmpf=${TMPDIR:-/tmp}/htsave$$
trap 'rm -f "$tmpf"' 0 1 15

for url
do
  if [ "x$url" = x- ]
  then
      "$0" -f "$folder" `cat` || xit=1
      continue
  fi

  (set -x; exec httpget -h -o "$tmpf" "$url") \
  || { xit=1; continue; }

  ( echo "X-URL: $url"
    echo "X-Fetch-Date: `date`"
    sed -n 's/.*<[Tt][Ii][Tt][Ll][Ee]>\(.*\)<\/[Tt][Ii][Tt][Ll][Ee]>.*/Subject: \1/p' <"$tmpf"
    exec cat "$tmpf"
  ) \
  | /usr/lib/nmh/rcvstore "+$folder" -unseen || xit=1
done

exit $xit
