#!/bin/sh
#
# Test if a particular file is CVS maintained.
#	- Cameron Simpson <cs@zip.com.au> 23feb2003
#
# If command supplied, run it with cvsedit (if needed).
#	- Cameron Simpson <cs@zip.com.au> 27jun2003
#

cmd=$0
usage="Usage: $cmd [-f] [-m msg] filename [command [args...]]
	-f	Supplied command is a filter.
	-m msg	CVS log message."

badopts=
msg=
isfilter=
cveopts=
fposarg=

while :
do
  case $1 in
    -0|-1|-end) fposarg=$1 ;;
    -f)	isfilter=1 cveopts="$cveopts $1" ;;
    -m)	msg=$2; shift ;;
    --)	shift; break ;;
    -?*)echo "$cmd: unrecognised option: $1" >&2; badopts=1 ;;
    *)	break ;;
  esac
  shift
done

if [ $# = 0 ]
then
    echo "$cmd: missing filename" >&2
    badopts=1
else
    file=$1; shift
fi

[ $badopts ] && { echo "$usage" >&2; exit 2; }

[ -f "$file" ] || { echo "$cmd: $file: not a file" >&2; exit 1; }

# no command? just run the test
if [ $# = 0 ]
then
    dir=`dirname "$file"`
    base=`basename "$file"`
    cvsdir=$dir/CVS
    entries=$cvsdir/Entries

    [ -s "$entries" ] && grep "^/$base/" "$entries" >/dev/null 2>/dev/null
    exit $?
fi

# just exec command if not CVSing
ifcvs -- "$file" || { [ $isfilter ] && set filteredit $fposarg "$file" "$@"; exec "$@"; }

exec cvsedit $cveopts $fposarg -m "$msg" "$file" "$@"
