#!/bin/sh -u
#
# Run command if specified file not known to "fileloc". With no args, just test.
#	- Cameron Simpson <cs@zip.com.au> 19may2005
#

cmd=$0
usage="Usage: $cmd [-v] [args1options...] filename [command [args...]]"

arg1opts=
verbose= trace=

badopts=

while [ $# -gt 0 ]
do
  case "$1" in
    -v)	verbose=1 trace=set-x ;;
    -stdin | -discard | -end | -[0-9]*)
	arg1opts="$arg1opts $1" ;;
    -x) trace=set-x arg1opts="$arg1opts $1" ;;
    --)	shift; break ;;
    -?*)echo "$cmd: unrecognised option: $1" >&2
	badopts=1
	;;
    *)	break ;;
  esac
  shift
done

[ $# = 0 ] && { echo "$cmd: missing filename" >&2; echo "$usage" >&2; exit 2; }
file=$1; shift

[ $badopts ] && { echo "$usage" >&2; exit 2; }

loc=`fileloc "$file" 2>/dev/null` && { [ $verbose ] && echo "$file: $loc"; exit 0; }
[ $# -gt 0 ] && exec $trace arg1 $arg1opts "$file" "$@"
[ $verbose ] && echo "$file: new file"
