#!/usr/bin/perl -w
#
# Read image paths on stdin, update index file.
#	- Cameron Simpson <cs@zip.com.au> 19jun2004
#

use strict qw(vars);

use cs::Misc;
use cs::Upd;
use cs::Shell;
use Getopt::Std;

$ENV{TMPDIR}='/tmp' if ! exists $ENV{TMPDIR} || ! length $ENV{TMPDIR};

my $upd = -t STDOUT;
my $indexfile = "INDEX";
my $mode = APPEND;
my @exts = (JPG,PNG,GIF);

$::Usage="Usage: $::cmd [-apu] [-e exts] [-f file] [{-|dirs...}]
	-a	Append mode - just append to the existing list.
	-p	Prune mode - drop images from the list now missing or empty.
	-u	Update mode - update the size data for existing list.
		Default mode: $mode
	-e exts	Comma separated list of case insensitive file extensions.
		Default: @exts
	-f file	Index filename. Default: $indexfile
		\"-\" means just write the index data to stdout.
	Saying \"-\" instead of dirs... reads paths from stdin.
";

{ my $badopts=0;
  my %opt;

  if (! getopts('apuef:',\%opt))
  { warn "$::cmd: bad options\n";
    $badopts=1;
  }

  if ($opt{'a'})	{ $mode=APPEND; }
  if ($opt{'p'})	{ $mode=PRUNE; }
  if ($opt{'u'})	{ $mode=UPDATE; }
  if (defined $opt{'e'}){ @exts=map(uc,grep(length,split(/[,\s]+/,$opt{'e'})));
			  die "$::cmd: can't have an empty extension list!"
				if ! @exts;
			}
  if (defined $opt{'f'}){ $indexfile=$opt{'f'}; }

  if (! @ARGV)
  { @ARGV=('.');
  }

  if ("@ARGV" ne '-')
  { open(STDIN,'-|','find',@ARGV,'(','-type','d','-name','.?*','-prune',')','-o','(','-type','f','-size','+0','-print',')')
	|| die "$::cmd: can't pipe from find: $!";
  }

  die $::Usage if $badopts;
}

%::IMX=();
%::IMY=();

my @stdin=();

nl("read new image list ...") if $upd;
INPUT:
while (defined($_=<STDIN>))
{
  chomp;
  s:^\./+::;
  next INPUT unless m:\.([^./]+)$:;	# skip stuff with no extension
  my $ext = uc($1);
  next INPUT unless grep($_ eq $ext, @exts); # skip unsupported extensions
  out($_) if $upd;
  push(@stdin,$_);
}
##close(STDIN); # trips "STDIN reopened" warning later:-(
out('') if $upd;

if (! @stdin)
{ nl("no new files from stdin") if $upd;
  exit 0;
}

my($err,$x,$y,$impath,@s);

if ($indexfile ne '-')
{
  nl("loading existing list ...") if $upd;
  if (-f "$indexfile.gz"
	  ? open(INDEX,"gunzip <'$indexfile.gz' |")
	  : open(INDEX,"< $indexfile\0")
     )
  {
    OLDINDEX:
    while (defined($_=<INDEX>))
    { chomp;
      out("$indexfile, $.: $_") if $upd && $. % 10 == 0;

      # skip bad lines
      next OLDINDEX if !/^(\d+) (\d+) (\S.*)/;

      if ($mode eq APPEND)
      { $::IMX{$3}=$1+0;
	$::IMY{$3}=$2+0;
      }
      else
      # append index files to list to examine
      { push(@stdin,$3);
      }
    }
    close(INDEX);
    out('') if $upd;
  }
  else
  { $err = "$!";
    if (-e $indexfile || -e "$indexfile.gz")
    { die "$::cmd: can't read $indexfile: $err";
    }
  }
}

@stdin=sort &::uniq(grep(! exists $::IMX{$_}, @stdin));
if (! @stdin)
{ nl("nothing to update") if $upd;
  exit 0;
}

nl("create list to scan ...") if $upd;
my $tmpf = "$ENV{TMPDIR}/$::cmd.$$";
die "$::cmd: can't write temp file $tmpf: $!" if ! open(TMPF,"> $tmpf\0");
for my $f (@stdin)
{ print TMPF $f, "\n" if ! exists $::IMX{$f};
}
close(TMPF);

nl("update new images ...") if $upd;

die "$::cmd: can't pipe from imsize-gm: $!" if !open(TMPF,"exec < '$tmpf'; rm '$tmpf'; exec xxargs  imsize-gm |");

my $n=0;
my $nn=@stdin;

NEWIMAGE:
while (<TMPF>)
{
  chomp;
  if (! /^(\d+) (\d+) (.*\S)/)
  { warn "$::cmd: bad data from imsize-gm: $_\n";
    next NEWIMAGE;
  }

  ($x,$y,$impath)=($1,$2,$3);
  $n++;

  $impath=normpath($impath);
  out(int($n*100/$nn)."%: $impath") if $upd && $n % 10 == 0;

  $::IMX{$impath}=$x;
  $::IMY{$impath}=$y;
}
out('') if $upd;

out("update $indexfile ...") if $upd;
if ($indexfile eq '-')
{ if (!open(INDEX,">&STDOUT"))
  { die "$::cmd; dup(STDOUT,INDEX): $!";
  }
}
else

{
  if (-f "$indexfile.gz")
  { if (!open(INDEX,"| gzip -9 ".($mode eq APPEND ? ">>" : ">")." $indexfile.gz"))
    { die "$::cmd: open($indexfile.gz): $!\n";
    }
  }
  else
  { if (!open(INDEX,($mode eq APPEND ? ">>" : ">")." $indexfile.gz"))
    { die "$::cmd: open($indexfile): $!\n";
    }
  }
}

for $impath (sort keys %::IMX)
{ print INDEX "$::IMX{$impath} $::IMY{$impath} $impath\n";
}
close(INDEX);
exit 0;

sub safepath
{ local($_)=@_;
  s:^[^/\w]:./$&:;
  $_;
}
sub normpath
{ local($_)=@_;
  s:^(\.\/+)+::;
  return $_;
}
