#!/usr/bin/perl
#
# Report image sizes.
#	- Cameron Simpson <cs@zip.com.au> 01jun1999
#
# Usage: imsize [filenames...]
#
# Output is
#	filename x y
# for each supplied name.
#

use strict qw(vars);
use Image::Size;

$::Xit=0;

($::cmd=$0) =~ s:.*/::;

my($x,$y,$err);

if (@ARGV)
{ for (@ARGV)
  { doimsize($_);
  }
}
else
{ while (defined($_=<STDIN>))
  { chomp;
    doimsize($_);
  }
}

exit $::Xit;

sub doimsize($)
{ my($f)=@_;

  my($x,$y,$err)=imgsize($f eq '-' ? '/dev/fd/0' : $f);
  if (defined $x)
  { print "$f $x $y\n";
  }
  else
  { warn "$::cmd: $f: $err (maybe errno \"$!\")\n";
    $::Xit=1;
  }
}
