#!/usr/bin/perl
#
# Report image sizes.
#	- Cameron Simpson <cs@zip.com.au> 01jun1999
#
# Usage: imsize [filenames...]
#
# Output is
#	x y filename
# for each supplied name.
#

use strict qw(vars);
use Image::Size;

$::Xit=0;

($::cmd=$0) =~ s:.*/::;

my($x,$y,$err);

if (@ARGV)
{ for (@ARGV)
  { doimsize($_);
  }
}
else
{ while (defined($_=<STDIN>))
  { chomp;
    doimsize($_);
  }
}

exit $::Xit;

sub doimsize($)
{ my($f)=@_;

  local($::imf)=($f eq '-' ? '/dev/fd/0' : $f);

  my($x,$y,$err);
  ($x,$y,$err)=eval { imgsize($::imf) };

  if ($@)
  { warn "$::cmd: $f: $@\n";
  }
  elsif (defined $x)
  { print "$x $y $f\n";
  }
  else
  { warn "$::cmd: $f: $err (maybe errno \"$!\")\n";
    print STDERR "    "; system("file '$f' >&2"); ## FIXME - security hole!
    $::Xit=1;
  }
}
