#!/bin/sh -u
#
# Run command in a temporary checkout.
#	- Cameron Simpson <cs@zip.com.au> 04jul2003
#

: ${SHELL:=/bin/sh}

cmd=`basename "$0"`
usage="Usage: $cmd [-f] [-r rev] module command [args...]"

badopts=

withcoopts=
while :
do
  case $1 in
    -f)	withcoopts="$withcoopts $1" ;;
    -r) withcoopts="$withcoopts $1 $2"; shift ;;
    --)	shift; break ;;
    -?*)echo "$cmd: unrecognised option: $1" >&2; badopts=1 ;;
    *)  break ;;
  esac
  shift
done

if [ $# = 0 ]
then
  echo "$cmd: missing module" >&2
  badopts=1
else
  module=$1
  shift
  if [ $# = 0 ]
  then
    if [ -t 0 -a -t 1 -a -t 2 ]
    then
      set -- "$SHELL"
    else
      echo "$cmd: missing command" >&2
      badopts=1
    fi
  fi
fi

[ $badopts ] && { echo "$usage" >&2; exit 2; }

exec withco $withcoopts -- "$module" incd -p "$@"
