#!/bin/sh
#
# Cd somewhere and run a command.
#	- Cameron Simpson <cs@zip.com.au> 21jul2002
#

cmd=$0
[ $# -gt 1 ] || { echo "Usage: $cmd dir cmd [args...]" >&2; exit 2; }

dir=$1; shift
cd "$dir" || exit 1
exec "$@"
