#!/bin/sh
#
# Record build timestamp in suitable .java file for use as a String.
#	- Cameron Simpson <cs@zip.com.au> 19dec2002
#

cmd=$0
usage="Usage: $cmd [--no-cvs] javafiles..."

usecvs=1
[ "x$1" = x--no-cvs ] && { usecvs=; shift; }
[ $# = 0 ] && { echo "$usage" >&2; exit 2; }

xit=0

now=`datecode` || exit 1

tag=AUTOBUILDTIMESTAMP

for file
do
  fgrep "$tag" <"$file" >/dev/null || continue
  ( set bsed "s#\"[^\"]*\";\\([ 	]*// $tag\\)\$#\"$now\";\\1#"
    if ifcvs "$file"
    then
	exec cvsedit --no-log --no-diff -m "" "$file" "$@"
    else
	exec "$@" "$file"
    fi
  ) || { xit=1; break; }
done

exit $xit
