#!/bin/sh
#
# Report the specified fields from all jobs.
# This is really a speed thing for scripts wanting several attributes from several jobs.
# See fvwm-menu-jobs for example use.
#	- Cameron Simpson <cs@zip.com.au> 14jul2003
#

dir=$HOME/var/idsets/$SYSTEMID/timer

cmd=$0
usage="Usage: $cmd [-d idsetdir] fields...
	-d	Specify idsetdir.
		Default: $dir"

[ "x$1" = x-d ] && { dir=$2; shift; shift; }

[ $# = 0 ] && { echo "$cmd: missing fields..." >&2; echo "$usage" >&2; exit 2; }

exec idsetlist "$dir" "$@"
