#!/bin/sh
#
# Report time for jobs by category.
#	- Cameron Simpson <cs@zip.com.au> 01jul2003
#

joblist name category total title \
| sort -t'	' +2 +1 -n +0 \
| awk -F'	' \
      'BEGIN	{ nids=0 }
       		{ id=$1; name=$2; cat=$3; total=$4; title=$5
		  if (total == "") total=0;
		  ids[nids++]=id
		  names[id]=name
		  cats[id]=cat
		  totals[id]=total
		  titles[id]=title

		  cat_totals[cat]+=total
		}
       END	{ for (cat in cat_totals)
		  { print cat "\t" cat_totals[cat]
		    for (nid=0; nid<nids; nid++)
		    { id=ids[nid]
		      if (cats[id] == cat)
		      { print ".\t" totals[id] "\t" names[id] ": " titles[id]
		      }
		    }
		  }
		}
      ' \
| while read cat total etc
  do
    [ "$total" -gt 0 ] || continue
    htotal=`humantime "$total"`
    if [ "x$cat" = x. ]
    then
	printf "%9s %-11s %s\n" "$htotal" "" "$etc"
    else
	printf "%9s %-11s\n" "$htotal" "$cat"
    fi
  done
