#!/bin/sh
#
# Report time for jobs by category.
#	- Cameron Simpson <cs@zip.com.au> 01jul2003
#

dir=timer
scale=1.0

cmd=$0
usage="Usage: $cmd [-d dir] [scale]"

[ "x$1" = x-d ] && { dir=$2; shift; shift; }

case "$1" in
  [0-9].[0-9])	scale=$1; shift ;;
esac

joblist -i "$dir" name category total title \
| sort -t'	' +2 +1 -n +0 \
| awk -F'	' \
      "BEGIN	{ nids=0; scale=$scale }
      "'	{ id=$1; name=$2; cat=$3; total=$4; title=$5
		  if (total == "") total=0;
		  if (cat == "") cat="HELPDESK"
		  ids[nids++]=id
		  names[id]=name
		  cats[id]=cat
		  totals[id]=total
		  titles[id]=title

		  cat_totals[cat]+=total
		}
       END	{ for (cat in cat_totals)
		  { print cat "\t" int(cat_totals[cat]*scale)
		    for (nid=0; nid<nids; nid++)
		    { id=ids[nid]
		      if (cats[id] == cat)
		      { print ".\t" int(totals[id]*scale) "\t" names[id] ": " titles[id]
		      }
		    }
		  }
		}
      ' \
| while read cat total etc
  do
    [ "$total" -gt 0 ] || continue
    htotal=`humantime "$total"`
    if [ "x$cat" = x. ]
    then
	printf "%9s %-11s %s\n" "$htotal" "" "$etc"
    else
	printf "%9s %-11s\n" "$htotal" "$cat"
    fi
  done
