#!/usr/bin/awk -f
#
# Keep last instances of lines.
# - Cameron Simpson <cs@zip.com.au>
#
# Converted to awk, made simple filter. - cameron
#

	{ lines[NR-1]=$0
	  key="x"$0
	  if (pos[key] > 0)
	  { i=pos[key]-1
	    skip[i]=1
	    lines[i]="SKIP"
	  }
	  pos[key]=NR
	}
END	{ for (i=0; i<NR; i++)
	  { if (!skip[i]) print lines[i]
	    i++
	  }
	}
