#!/bin/sh -u
#
# Emit a KML GroundOverley section.
#       - Cameron Simpson <cs@zip.com.au> 18jan2007
#

visibility=1

cmd=$0
usage="usage: $cmd [-i] title URL w e s n < html-description
        -i      Invisible: set visibility=0."

[ $# -gt 0 ] && [ "x$1" = x-i ] && { visibility=0; shift; }
[ $# = 6 ] || { echo "$usage" >&2; exit 2; }
title=$1 url=$2 west=$3 east=$4 south=$5 north=$6

desc=`tidy 2>/dev/null | sed '1,/^<body>$/d; /^<\/body>$/,$d'`

cat <<X
<GroundOverlay>
  <name>$title</name>
  <visibility>$visibility</visibility>
  <description><![CDATA[$desc]]></description>
  <Icon>
    <href>$url</href>
  </Icon>
  <LatLonBox>
    <north>$north</north>
    <south>$south</south>
    <east>$east</east>
    <west>$west</west>
  </LatLonBox>
</GroundOverlay>
X
