#!/bin/sh -u

##url128=http://mirror.bom.gov.au/radar/IDR033.gif?x
url128=http://www.cskk.ezoshosting.com/cs/test/bom128.png
[ $# -gt 0 ] && { url128=$1; shift; }
##url256=http://mirror.bom.gov.au/radar/IDR032.gif?x
url256=http://www.cskk.ezoshosting.com/cs/test/bom256.png
[ $# -gt 0 ] && { url256=$1; shift; }

cat <<X
<?xml version="1.0" encoding="UTF-8"?>
<kml xmlns="http://earth.google.com/kml/2.1">
<Document>
X

kml-go 'BOM 128km Sydney Radar' \
       "$url128" \
       149.51 152.25 -35.41 -33.12 <<X
Sydney Australia 128km Rainfall Radar<br>
Full services at <a href="http://mirror.bom.gov.au/products/IDR033.loop.shtml">the BOM site</A>.
X

##kml-go -i 'BOM 256km Sydney Radar' \
##       "$url256" \
##       148.1 153.67 -36.56 -31.98 <<X
##Sydney Australia 256km Rainfall Radar<br>
##Full services at <a href="http://mirror.bom.gov.au/products/IDR032.loop.shtml">the BOM site</A>.
##X

cat <<X
</Document>
</kml>
X
