#!/bin/sh
#
# Stash or report the last value of some parameter.
#	- Cameron Simpson <cs@zip.com.au> 02dec2002
#

dir=$HOME/var/log/lastvalue

cmd=$0
Usage="Usage: $cmd [-d dir] param [value|-]"

badopts=

[ "x$1" = x-d ] && { dir=$2; shift; shift; }

if [ $# = 0 ]
then
    echo "$cmd: missing param" >&2
    badopts=1
else
    param=$1; shift
    case "$param" in
	''|*/*)	echo "$cmd: bad param \"$param\"" >&2
		badopts=1
		;;
    esac
    [ $# -gt 1 ] && { echo "$cmd: extra arguments after value" >&2; badopts=1; }
fi

[ $badopts ] && { echo "$usage" >&2; exit 2; }

[ $# = 0 ] && exec cat "$dir/$param"

needdir "$dir" || exit 1

if [ "x$1" = x- ]
then
    cat
else
    echo "$1"
fi >"$dir/$param"
