#!/bin/sh
#
# Lowercase a bunch of pathnames.
#	- Cameron Simpson <cs@zip.com.au>
#

rnopts=
while :
do
  case $1 in
    --)		shift; break ;;
    -?*)	rnopts="$rnopts $1" ;;
    *)		break ;;
  esac
  shift
done

exec lwrename2 $rnopts -- \
	'if (m:[^/]+$:)
	 { $lhs=$`; $rhs=$&;
	   $rhs =~ s/\%([0-9a-f][0-9a-f])/chr(hex($1))/ieg;
	   $rhs =~ tr/_&A-Z/-+a-z/;
	   $rhs =~ s/[-\s]+/-/g;
	   $rhs =~ s/^-/_/;
	   $_=$lhs.$rhs;
	 }
	' ${1+"$@"}
