#!/bin/sh -u
#
# Load up a mysql server from scratch, using dumped tables from another db.
#	- Cameron Simpson <cs@zip.com.au> 04aug2005
#

trace=set-x
sqldir=.
datadir=/var/lib/mysql
rawmysqld=/usr/libexec/mysqld
initmysqld=/etc/init.d/mysqld
newgrants=

cmd=`basename "$0"` || cmd=$0
usage="Usage: $cmd [--datadir=...] [--new-grant-tables]
	--datadir		Specify datadir. Default: $datadir
	--new-grant-tables	Reset the grant tables.
				Loads mysql.sql.gz and runs mysql_fix_privilege_tables.
				Normally the mysql db itself is skipped."

badopts=

while [ $# -gt 0 ]
do
  case $1 in
    --datadir=*)
	datadir=`expr "x$1" : 'x--datadir=\(.*\)'`
	;;
    --new-grant-tables)
	newgrants=1
	;;
    --)	shift; break ;;
    -?*)echo "$cmd: unrecognised option: $1" >&2
	badopts=1
	;;
    *)	break ;;
  esac
  shift
done

[ $# = 0 ] || { echo "$cmd: extra arguments: $*" >&2; badopts=1; }

[ $badopts ] && { echo "$usage" >&2; exit 2; }

cd "$sqldir" || exit 1
[ -s "mysql.sql.gz" ] || { echo "$cmd: no mysql.sql.gz, aborting" >&2; exit 2; }

$trace "$initmysqld" stop || { echo "WARNING: no MySQL to stop!?!" >&2
			       ask "Proceed anyway" || exit 1
			     }

if [ $newgrants ]
then
    [ -d "$datadir/mysql" ] || exit 1
    $trace rm -rf "$datadir/mysql" || exit 1
    $trace su mysql -c "mysql_install_db '--datadir=$datadir'" || exit 1
    $trace $rawmysqld -u mysql "--datadir=$datadir" --skip-grant-tables --bind-address=127.0.0.1 &
    $trace sleep 5
    gunzip < mysql.sql.gz | $trace mysql -h 127.0.0.1 mysql || exit 1
    $trace mysql_fix_privilege_tables -h 127.0.0.1 || xit=1
fi

$trace "$initmysqld" start || exit 1

xit=0

for squiz in *.sql.gz
do
  case "$squiz" in
    mysql.sql.gz|test.sql.gz)
      continue
      ;;
  esac

  [ -s "$squiz" ] || { echo "$cmd: $squiz: no data!" >&2; xit=1; continue; }

  dbname=`expr "x$squiz" : 'x\(.*\).sql.gz'` || exit 1
  $trace echo "create database $dbname;" | $trace mysql -h 127.0.0.1
  gunzip < "$squiz" | $trace mysql -h 127.0.0.1 "$dbname"
done

exit $xit
