#!/bin/sh -ue
#
# Record a Mercurial commit.
#       - Cameron Simpson <cs@zip.com.au> 25apr2007
#

hg log -r "$HG_NODE" --limit 1 \
| sed '1,/^description:/d; s/\t/ /g; s/\r$//; /^ *$/d' \
| { read -r headline
    exec buglog "commit $HG_NODE: $headline"
  }
