#!/bin/sh
#
# Run a new shell inside a script command, logging to the file
#	$HOME/var/log/build/pkg-arch-host-date.gz
# Too often was I building things and losing the details.
#	- Cameron Simpson <cs@zip.com.au> 28aug2000
#

cmd=`basename "$0"`
usage="Usage: $cmd pkgdir"

[ $# = 1 ] || { echo "$usage" >&2; exit 2; }
pkgdir=$1; shift

cd "$pkgdir" || { echo "$cmd: chdir($pkgdir) fails" >&2; exit 1; }

cwd=`pwd` || exit 1
pkg=`basename "$cwd"`

logbase=$pkg-$ARCH-$HOST-`datecode`

umask 2
screen -h 102400 -S "$cmd-$pkg-$ARCH-$HOST" \
    buildenv env ps1pfx=":$ps1pfx" ps2pfx=" $ps2pfx" \
    logscript "$logbase"
