#!/bin/sh
# Hack to log all my email while I debug my delivery scripts.

: ${TMPDIR:=/tmp}

logf=$HOME/procmail.everything
tmpf=$TMPDIR/lpm$$

cat >"$tmpf" || exit 1
cat "$tmpf" >>"$logf"
exec <"$tmpf"
rm "$tmpf"
exec procmail
