#!/bin/sh
#
# Modify something and record the diff.
#	- Cameron Simpson <cs@zip.com.au> 04aug2004
#

: ${TMPDIR:=/tmp}

cmd=`basename "$0"`
usage="Usage: $cmd [args1-opts...] -r report-command [-m message] \
		itemname editcommand [editargs...]
	arg1opts	Used to control passing itemname to editcommand.
	-r report-command Shell command to report on itemname.
			%s within the string will be replaced by quoted itemname.
	-m message	Supply change log line."

badopts=

reportcmd=
args1opts=-end
message=

while :
do
  case $1 in
    -r)	reportcmd=$2; shift ;;
    -m)	message=$2; shift ;;
    -[0-9]*|-end|-discard)
      arg1opts="$arg1opts $1"
      ;;
    --)	shift; break ;;
    -?*)echo "$cmd: unrecognised option: $1" >&2; badopts=1 ;;
    *)	break ;;
  esac
  shift
done

[ -z "$reportcmd" ] || { echo "$cmd: missing report-command" >&2; badopts=1; }

if [ $# = 0 ]
then
  echo "$cmd: missing itemname" >&2
  badopts=1
else
  itemname=$1; shift
  if [ $# = 0 ]
  then
    echo "$cmd: missing editcommand" >&2
    badopts=1
  fi
fi

[ $badopts ] && { echo "$usage" >&2; exit 2; }

tmpf=$TMPDIR/$cmd$$
trap 'rm -f "$tmpf"' 0 1 15

if [ -z "$message" ]
then
  [ -t 0 ] || { echo "$cmd: stdin must be a tty" >&2; exit 1; }
  echo "Please enter the reason and bug id for this change."
  message=`readline "> "` || exit 1
fi
[ -n "$message" ] || { echo "$cmd: empty message rejected" >&2; exit 1; }

case "$reportcmd" in
  *'%s'*)
    reportcmd=`reportcmd=$reportcmd q=$itemname perl -e '
		use cs::Shell;
		$q=cs::Shell::quote($ENV{q});
		$ENV{reportcmd} =~ s/%s/$q/g;
		print $ENV{reportcmd}, "\n";
	       '
	      `
		;;
esac

sh -c "$reportcmd" >"$tmpf" || exit 1

arg1 $arg1opts "$itemname" "$@"
xit=$?

sh -c "$reportcmd" | diffu "$tmpf" - | buglog "$message"

exit $xit
