#!/bin/sh
#
# Modify something and record the diff.
#	- Cameron Simpson <cs@zip.com.au> 04aug2004
#

: ${TMPDIR:=/tmp}

cmd=`basename "$0"`
usage="Usage: $cmd [args1-opts...] -r report-command itemname editcommand [editargs...]"

badopts=

reportcmd=
args1opts=-end

while :
do
  case $1 in
    -r)	reportcmd=$2; shift ;;
    -[0-9]*|-end|-discard)
      arg1opts="$arg1opts $1"
      ;;
    --)	shift; break ;;
    -?*)echo "$cmd: unrecognised option: $1" >&2; badopts=1 ;;
    *)	break ;;
  esac
  shift
done

[ -z "$reportcmd" ] || { echo "$cmd: missing report-command" >&2; badopts=1; }

if [ $# = 0 ]
then
  echo "$cmd: missing itemname" >&2
  badopts=1
else
  itemname=$1; shift
  if [ $# = 0 ]
  then
    echo "$cmd: missing editcommand" >&2
    badopts=1
  fi
fi

[ $badopts ] && { echo "$usage" >&2; exit 2; }

[ -t 0 ] || { echo "$cmd: stdin must be a tty" >&2; exit 1; }

tmpf=$TMPDIR/$cmd$$
trap 'rm -f "$tmpf"' 0 1 15

echo "Please enter the reason and bug id for this change."
reason=`readline "> "` || exit 1
[ -n "$reason" ] || { echo "$cmd: empty reason rejected" >&2; exit 1; }

case "$reportcmd" in
  *'%s'*)
    reportcmd=`reportcmd=$reportcmd q=$itemname perl -e '
		use cs::Shell;
		$q=cs::Shell::quote($ENV{q});
		$ENV{reportcmd} =~ s/%s/$q/g;
		print $ENV{reportcmd}, "\n";
	       '
	      `
		;;
esac

sh -c "$reportcmd" >"$tmpf" || exit 1

"$@" "$itemname"
xit=$?

sh -c "$reportcmd" | diffu "$tmpf" - | buglog "$reason"

exit $xit
