#!/bin/sh
#
# Send mail only if input is not empty.
#	- Cameron Simpson <cs@zip.com.au>
#
# Usage: mailif [-s subject] addresses...
#
# Break into execif and mailsubj. - cameron, 23jun1998
#

execif mailsubj ${1+"$@"}
