#!/bin/sh -u
#
# Convert a maildir into a compressed mbox file.
# Intended for archived email.
#       - Cameron Simpson <cs@zip.com.au> 04nov2006
#

: ${TMPDIR:=$HOME/tmp}

trace=set-x

cmd=`basename "$0"` || exit 1
usage="Usage: $cmd maildirs..."

[ $# = 0 ] && { echo "$usage" >&2; exit 2; }

xit=0

for omaildir
do
  obase=`basename "$omaildir"` || exit 1
  odir=`dirname "$omaildir"`   || exit 1
  mbox=$odir/$obase
  tmpmaildir=$odir/$obase-md-$cmd$$
  tmpmbox=$odir/$obase-mbox-$cmd$$

  ismaildir "$omaildir" \
  || { echo "$cmd: $omaildir: not a maildir, skipped" >&2
       : xit=1
       continue
     }
  ismaildir "$tmpmaildir" \
  && { echo "$cmd: $tmpmaildir: already exists" >&2
       xit=1
       continue
     }

  $trace mv "$omaildir" "$tmpmaildir" || { xit=1; continue; }

  $trace maildir-cat "$tmpmaildir" >>"$tmpmbox" \
  || { $trace rm "$tmpmbox" && $trace mv "$tmpmaildir" "$mbox"
       exit 1
     }

  $trace rm -r "$tmpmaildir" || xit=1
  $trace gzip -v -n -9 "$tmpmbox" || exit 1

  { [ ! -f "$mbox.gz" ] && $trace mv "$tmpmbox.gz" "$mbox.gz"; } \
  || { $trace cat "$tmpmbox.gz" >>"$mbox.gz" && $trace rm "$tmpmbox.gz"; } \
  || exit 1
done

exit $xit
