#!/bin/sh
#
# Extract all components of an email message with munpack into the specified
# directory.
# Extraction actually happens in a new subdirectory of the target.
# After extraction, _within_ that subdirectory:
#   If a command is supplied, run that after extraction.
#   If no command is supplied and if the shell script autoexec.sh is present in
#   the directory, run that after extraction.
#   Otherwise use "mrg" to merge the files into the target directory.
#	- Cameron Simpson <cs@zip.com.au> 03dec2001
#

target=`lastvalue mailunpack`

cmd=$0
usage="Usage: $cmd [-d unpackdir] [command [args...]] <mailitem
	-d unpackdir		Specify unpack directory.
				Default from last mailunpack run: $target
	command [args...]	Command to run.
				Default: \"basedir/autoexec.sh key\" if present."

[ "x$1" = x-d ] && { target=$2; shift; shift; }

[ -n "$target" ] || { echo "$cmd: no unpackdir and no default, aborting" >&2; exit 1; }

needdir "$target" || exit 1
cd "$target"      || exit 1

lastvalue mailunpack "`pwd`"

wkdir=`mkdirn .mailunpack` || exit 1
cd "$wkdir"	  || xit 1
wkdir=`pwd`       || exit 1

munpack || exit 1

if [ $# = 0 ]
then
    if [ -s "$base/autoexec.sh" ]
    then
	set /bin/sh "$base/autoexec.sh"
    else
	set mrg .. *
    fi
fi

xit=0
echo "$wkdir"
(set -x; exec "$@") || xit=1
cd .. || exit 1
rmdir "$wkdir"
exit $xit
