#!/bin/sh -u
#
# Extract all components of an email message with munpack into the specified
# directory.
# Extraction actually happens in a new subdirectory of the target.
# After extraction, _within_ that subdirectory:
#   If a command is supplied, run that after extraction.
#   If no command is supplied and if the shell script autoexec.sh is present in
#   the directory, run that after extraction.
#   Otherwise use "mrg" to merge the files into the target directory.
#	- Cameron Simpson <cs@zip.com.au> 03dec2001
#

usemunpack=
usemetamail=1
trace=set-x
target=`lastvalue mailunpack`

cmd=`basename "$0"` || exit 1
usage="Usage: $cmd [-d unpackdir] [command [args...]] <mailitem
	-d unpackdir		Specify unpack directory.
				Default from last mailunpack run: $target
	command [args...]	Command to run.
				Default: \"basedir/autoexec.sh key\" if present."

[ $# -gt 0 ] && [ "x$1" = x-d ] && { target=$2; shift; shift; }

[ -n "$target" ] || { echo "$cmd: no unpackdir and no default, aborting" >&2; exit 1; }

needdir "$target" || exit 1
cd "$target"      || exit 1

lastvalue mailunpack "`pwd`"

wkdir=`mkdirn .mailunpack` || exit 1
cd "$wkdir"	  || xit 1
wkdir=`pwd`       || exit 1

if [ $usemunpack ]
then
  $trace munpack || exit 1
else
  if [ $usemetamail ]
  then
    $trace metamail -w -x | sed -n 's/^Wrote file //p' | xxargs $trace mrg .
  else
    echo "$0: don't know how to unpack MIME messages :-(" >&2
    exit 1
  fi
fi

set -x

if [ $# = 0 ]
then
    if [ -s "$target/autoexec.sh" ]
    then
	set /bin/sh "$target/autoexec.sh"
    else
	set mrg .. *
    fi
fi

xit=0
echo "$wkdir"
$trace "$@" || xit=1

cd .. || exit 1
$trace rmdir "$wkdir"
exit $xit
