#!/bin/sh
#
# Handler for email delivered to mailman.
# Invoked from procmail.
#   mailman		-> postmaster
#   mailman-list	-> wrapper post list
#   mailman-list-*	-> wrapper * list
#	- Cameron Simpson <cs@zip.com.au> 16may2001
#

exec 2>>/var/mailman/procmail.out

: ${TMPDIR:=/tmp}

PATH=$PATH:/opt/script
export PATH

wrapper=/var/mailman/mail/mailman

PATH=/bin:/usr/bin:/usr/sbin:$PATH
export PATH

tmp=$TMPDIR/mmprcm$$

formail -R Received: X-PreMailman-Received: >$tmp || exit 1

xit=0

<$tmp \
sed -n -e '/^$/q' -e 's/@.*//' -e 's/^Delivered-To: *//p' \
| sed 1q \
| { read delivery || exit 1

    xit=0
    dowrap=
    set -x
    case "$delivery" in
	mailman)
		sendmail -oi postmaster <$tmp || xit=$?
		;;

	mailman+*-admin \
	| mailman+*-bounces \
	| mailman+*-confirm \
	| mailman+*-join \
	| mailman+*-leave \
	| mailman+*-owner \
	| mailman+*-request \
	| mailman+*-subscribe \
	| mailman+*-unsubscribe )
		list=`expr "$delivery" : 'mailman+\(.*\)-.*'`
		op=`expr "$delivery" : 'mailman+.*-\(.*\)'`
		"$wrapper" "$op" "$list" <$tmp || xit=$?
		;;

	mailman+* )
		list=`expr "$delivery" : 'mailman+\(.*\)'`
		wrapfor=post
		if sed '/^$/q' $tmp | grep '^X-Spam-Status: Yes,'
		then
		    sed -e '/^$/,$b ok' \
			-e "s/^[Ss][Uu][Bb][Jj][Ee][Cc][Tt]:/& SPAM to list \"$list\":/" \
			$tmp \
		    | sendmail -oi "mailman+$list-owner" 
		else
		    "$wrapper" post "$list" <"$tmp" || xit=$?
		fi
		;;
	*)	echo "$0: don't known what to do with email for \"$delivery\"" >&2
		cat $tmp >&2
		xit=1
		;;
    esac

    ## echo "delivery=[$delivery] wrapfor=[$wrapfor] list=[$list]" >>"$TMPDIR/mm.log"
    
    rm -f $tmp

    exit $xit
  }
