#!/bin/sh
#
# Change the image menu backdrop image for the running FVWM.
#	- Cameron Simpson <cs@zip.com.au> 18oct2002
#

cmd=$0
call="$0 $*"

domenu=
aspect=-t
strippfx=
pickn=1
thisdesk= Dflag=

usage="Usage: $cmd [-M] [ imagefile | bglist-args... ]
	-D	Set the menu backdrop only for this desktop.
	-M	Popup FVWM menu to pick from choices."

badopts=
subopts=

while :
do
  case $1 in
    -D)	thisdesk=1 Dflag=$1 ;;
    -M)	subopts="$subopts -M" pickn=20 aspect= domenu=1 strippfx=$HOME ;;
    -?*)echo "$cmd: unrecognised option: $1" >&2; badopts=1 ;;
    --)	shift; break ;;
    *)	break ;;
  esac
  shift
done

[ $badopts ] && { echo "$usage" >&2; exit 2; }

##set -x
if [ $# = 1 -a -f "$1" -a -s "$1" ]
then
    # one argument which is a file pathname
    domenu=
else
    case "$#,$1" in
      1,http://*)
	# one argument which is a URL
	exec withurl -C "$1" "$0"
	;;
    esac

    # presume search args instead
    set x `set -x; pickim -P "$strippfx" -n $pickn -r $aspect ${1+"$@"} | sort -u` || exit 1
    shift
    [ $# = 0 ] && { echo "$cmd: no image files chosen!" >&2; exit 1; }
    ##[ $# = 1 ] && domenu=
fi

##set +x
##echo "*=[$*]" >&2

if [ $domenu ]
then
    tmpf=/tmp/menubg$$
    for arg
    do  echo "$arg"
    done >"$tmpf"
    fvwmcmd \
	  "Piperead 'fvwm-menu -1 ImDirMenu \"$cmd $call\" fvwm-menu-imlist -o menubg -l $tmpf .; rm $tmpf'" \
	  "Popup ImDirMenu"
    exit $?
fi

imagefile=$1

setpix()
{ dorm=
  [ "x$1" = x-r ] && { dorm=1; shift; rmwhat=$1; shift; }
  set "ColorSet 2 Tint rgb:00/00/20 50, AspectPixmap \"$1\""
  fvwmcmd "$@"
  [ dorm ] && fvwmcmd "Exec rm -rf \"$rmwhat\""
}

case "$bright,$imagefile" in
    *.png|*.xpm)
	# no format conversion needed
	setpix "$imagefile"
	exit $?
	;;
esac

wkdir=`mkdirn "${TMPDIR:-/tmp}/menubg"` || exit 1
cp "$imagefile" "$wkdir/." || exit 1

echo "$imagefile" >>$HOME/var/log/menubg
lastvalue menubg "$imagefile" &
if [ $thisdesk ]
then  thisdesk=`lastvalue "enterdesk-$HOST"`
      desktop "$thisdesk" menubg "$imagefile"
else  lastvalue "defaultmenubg-$HOST" "$imagefile"
fi &

cd "$wkdir"
imagefile=`basename "$imagefile"`
impng=`echo "$imagefile" | sed 's/\\(.*\\.\)[^.]*$/\\1PNG/'`

##mogrify -geometry "$geom" -modulate 70 -despeckle -format PNG "$imagefile"
if /opt/ImageMagick/bin/mogrify -format PNG "$imagefile"
then
    # horrible workaround for mogrify bug
    rm -f "$imagefile"
    mv ./* "$impng"
    setpix -r "$wkdir" "$wkdir/$impng"
else
    L "$wkdir" >&2
    exit 1
fi
