#!/bin/sh
#
# Change the image menu backdrop image for the running FVWM.
#	- Cameron Simpson <cs@zip.com.au> 18oct2002
#

cmd=$0

geom=300x600

usage="Usage: $cmd [XxY] [ imagefile | bglist-args... ]
	XxY	Max XxY geometry of scaled image. Default: $geom"

badopts=

case "$1" in
    [1-9]*x[1-9]*)
	geom=$1; shift ;;
esac

if [ $# = 0 ]
then
    # random tall image
    set x `bglist -r -n 1`; shift
    if [ $# = 0 ]
    then
	echo "$cmd: nothing found by bglist" >&2
	badopts=1
    else
	echo "$1"
    fi
else
    if [ ! -s "$1" ]
    then
	# random tall image by keyword
	args=$*
	set x `bglist -r -n 1 "$@"`; shift
	if [ $# = 0 ]
	then
	    echo "$cmd: nothing found by bglist for \"$args\"" >&2
	    badopts=1
	else
	    echo "$1"
	fi
    else
	[ $# = 1 ] || { shift; echo "$cmd: extra arguments: $*" >&2; badopts=1; }
    fi
fi
imagefile=$1; shift

[ -s "$imagefile" ] || { echo "$cmd: missing imagefile: $imagefile" >&2
			 badopts=1
		       }

[ $badopt ] && { echo "$usage" >&2; exit 2; }

wkdir=`mkdirn "${TMPDIR:-/tmp}/menubg"` || exit 1
trap 'cd;(sleep 5; rm -rf "$wkdir")&' 0 1 2 15

cp "$imagefile" "$wkdir/." || exit 1

cd "$wkdir"
imagefile=`basename "$imagefile"`
impng=`echo "$imagefile" | sed 's/\\(.*\\.\)[^.]*$/\\1PNG/'`

mogrify -geometry "$geom" -modulate 70 -despeckle -format PNG "$imagefile"

fvwmcmd "MenuStyle '*' MenuFace TiledPixmap \"$wkdir/$impng\""
