#!/bin/sh
#
# Change the image menu backdrop image for the running FVWM.
#	- Cameron Simpson <cs@zip.com.au> 18oct2002
#

: ${TMPDIR:=/tmp}

cmd=`basename "$0"`
call="$0 $*"

domenu=
aspect=-t
strippfx=
pickn=1
desk=

usage="Usage: $cmd [-M] [ imagefile | bglist-args... ]
	-t	Choose tall images.
	-w	Choose wider images.
	-d n	Set the menu backdrop for the specified desktop.
		Default: the current desktop."

badopts=
opts=

while :
do
  case $1 in
    -d)	desk=$2; shift
	opts="$opts -d $desk" ;;
    -[tw]) aspect=$1 ;;
    -?*)echo "$cmd: unrecognised option: $1" >&2; badopts=1 ;;
    --)	shift; break ;;
    *)	break ;;
  esac
  shift
done

[ $badopts ] && { echo "$usage" >&2; exit 2; }

thisdesk=`currentdesk`
[ -n "$desk" ] || desk=$thisdesk

# A URL? Fetch and use.
case "$#,$1" in
  1,http://*)
    set -x
    exec withurl "$1" "$0" $opts ;;
esac

if [ "x$*" = xnone ]
then
    desktop "$desk" menubg '' || exit 1
else
    if [ $# != 1 ] || [ ! -f "$1" -o ! -s "$1" ]
    then
      # presume search args
      set -- `pickim -P "$strippfx" -n $pickn $aspect ${1+"$@"} | sort -u` || exit 1
      [ $# = 0 ] && { echo "$cmd: no image files chosen!" >&2; exit 1; }
      if [ -t 1 ]; then  cd; ls -ld "$@"; fi &
      
      if [ $# -gt 1 ]
      then
	tmpf=$TMPDIR/menubg$$
	for arg
	do  echo "$arg"
	done >"$tmpf"
	fvwmcmd \
	      "SetEnv FVWM_MENU_IMLIST_OP \"menubg $opts\"" \
	      "Piperead 'fvwm-menu -1 ImDirMenu \"$cmd $call\" fvwm-menu-imlist -l $tmpf .; rm $tmpf'" \
	      "Popup ImDirMenu" \
	      "UnSetEnv FVWM_MENU_IMLIST_OP"
	exit $?
      fi
    fi

    # set image directly

    srcimage=$1; shift
    cachefile=`filecache "$srcimage"` || exit 1
    imagefile=`pngof "$cachefile"` || exit 1
    desktop "$desk" menubg "$imagefile" || exit 1
    lastvalue menubg "$cachefile" &
    lastvalue menubg-pngof "$imagefile" &
fi

exec enterdesk -f
