#!/bin/sh
#
# Invoke mutt to send several files.
#	- Cameron Simpson <cs@zip.com.au> 28apr2001
#

[ $# -lt 2 ] && { echo "Usage: $0 address filenames..." >&2; exit 2; }

addr=$1; shift
subj="files: $*"

first=1
for file
do [ $first ] && { set x; shift; first=; }
   set x ${1+"$@"} -a "$file"; shift
done

exec mutt -s "$subj" ${1+"$@"} "$addr"
