#!/bin/sh
#
# Make a mailbox folder and .mh_sequences (so mutt recognises it).
#	- Cameron Simpson <cs@zip.com.au> 11oct1999
#

xit=0
for d
do  [ -d "$d/." ] || mkdir "$d" || continue
    [ -s "$d/.mh_sequences" ] || ( echo "unseen:"; echo "replied:"; echo "flagged:"; ) >>"$d/.mh_sequences"
done

exit $xit
