#!/bin/sh
#
# Make a mailbox folder and .mh_sequences (so mutt recognises it).
#	- Cameron Simpson <cs@zip.com.au> 11oct1999
#

xit=0
for d
do  needdir "$d" || { xit=1; continue; }
    mh=$d/.mh_sequences
    >>"$mh"
    for seq in unseen replied flagged
    do  grep "^$seq: *[1-9]" <"$mh" >/dev/null || echo "$seq: 1" >>"$mh"
    done
    >>"$d/.msgid.cache"
done

exit $xit
