#!/bin/sh
#
# Make a mailbox folder and .mh_sequences (so mutt recognises it).
#	- Cameron Simpson <cs@zip.com.au> 11oct1999
#

xit=0
for d
do  [ -d "$d/." ] || mkdir "$d" || continue
    mh=$d/.mh_sequences
    >>"$mh"
    for seq in unseen replied flagged
    do  grep "^$seq:" <"$mh" >/dev/null || echo "$seq:" >>"$mh"
    done
done

exit $xit
