#!/usr/bin/perl

($cmd=$0) =~ s:.*/::;
$usage="Usage: $cmd [-sh] <mail-item\n";

$#shmode=0;
if (@ARGV && $ARGV[0] eq '-sh')
{ $shmode=1;
  shift(@ARGV);
  eval 'use cs::Shell';
}

if (@ARGV)
{ warn "$cmd: extra arguments: @ARGV\n";
  die $usage;
}

HDR:
while (<STDIN>)
{ chomp;
  last HDR if /^$/;

  if ( /^([a-z][-\w]*):[ 	]*/i )
  {
    $body=$';
    $hdr=uc($1);
    $hdr=~s/-/_/g;

    if ($shmode)
    { print "$hdr=", cs::Shell::quote($body), "\n";
    }
    else
    { print "$hdr $body\n";
    }
  }
}
