#!/usr/bin/python
#
# Make the next directory in a sequence.
#	- Cameron Simpson <cs@zip.com.au> 28jun2000
#
# Dash suffix if numeric prefix. - cameron 03sep2000
# Limit on number of directory tries. - cameron 05sep2000
# Move to python. - cameron, 25jul2005
#

import sys
import cs.misc

if len(sys.argv) != 2:
  sys.stderr.write("Usage: mkdirn dirpfx\n")
  sys.stderr.flush()
  sys.exit(2)

dir=cs.misc.mkdirn(sys.argv[1])
if dir is None:
  sys.stderr.write("mkdirn: can't make next in sequence for prefix "+sys.argv[1]+"\n")
  sys.stderr.flush()
  sys.exit(1)

print dir
