#!/bin/sh
#
# Make the next directory in a sequence.
# Lifted from my cdfn shell function.
#	- Cameron Simpson <cs@zip.com.au> 28jun2000
#
# Dash suffix if numeric prefix. - cameron 03sep2000
# Limit on number of directory tries. - cameron 05sep2000
#

[ $# = 1 ] || { echo "Usage: $0 dirpfx" >&2; exit 2; }

maxtries=20

pfx=$1
case "$pfx" in *[0-9]) pfx=$pfx- ;; esac

up=`dirname "$pfx"`
base=`basename "$pfx"`

# check out existing directories
n=`exec 2>/dev/null
   cd "$up" || exit 1
   ls \
   | sed -n "/^$base"'0*[1-9][0-9]*/s/.*[^0-9]0*\([1-9][0-9]*\)$/\1/p' \
   | sort -n \
   | tail -1`

# nothing? start at 1
if [ -n "$n" ]
then
    n=`expr $n + 1`
else
    n=1
fi

# scan for a new slot
maxtries=16
while ndir=$pfx$n
      :
do
  if [ -d "$ndir/." ]
  then  :
  else  if mkdir -p "$ndir"
	then  break
	else  [ "$maxtries" -gt 1 ] || exit 1
	      maxtries=`expr $maxtries - 1`
	fi
  fi

  n=`expr $n + 1`
  ## echo "[n=$n maxtries=$maxtries]" >&2
done

# report
echo "$ndir"
