#!/bin/sh
#
# Make 640x480 14 colour gzipped XPM image from a JPEG for use as grub splash
# backdrop.
#	- Cameron Simpson <cs@zip.com.au> 15jul2002
#
# See also:
#	http://ruslug.rutgers.edu/~mcgrof/grub-images/
#

cmd=$0
usage="Usage: $cmd imagefile >splash.xpm.gz"

[ $# = 1 ] || { echo "$cmd: missing imagefile" >&2
                echo "$usage" >&2
                exit 2
	      }
file=$1; shift

set -x
gm convert - <"$file" -geometry 640x480 -colors 14 xpm:- \
| gzip -v -9
