#!/bin/sh
#
# Read
#	login:blah
# files and emit with password crypts from NIS database.
#	- Cameron Simpson <cs@zip.com.au>13feb2003
#

oIFS=$IFS

sed 's/:/ /' \
| while read who etc
  do  ypmatch "$who" passwd
  done \
| sed 's/^\([^:]*:[^:]*\):.*/\1/'
