#!/bin/sh
#
# Generate a list of images with their sizes.
#	- Cameron Simpson <cs@zip.com.au> 09jan2002
#

justprint=
[ "x$1" = x-n ] && { shift; justprint=1; }

set \
  find . \
    -follow \
    \( -type d ! -name . -name '.*' -prune \) \
 -o \( -type f -size +0 \
	\( -name \*.png -o -name \*.jpg \) \
	${1+"$@"} \
       -print \)

set -x
[ $justprint ] && exec "$@"

"$@" \
| sed 's;^\./;;' \
| xxargs imsize-gm
