#!/bin/sh
#
# Create a simple index of every HTML file that should be made from the PODs
# in the current directory.
#	- Cameron Simpson <cs@zip.com.au> 01jul2003
#

cmd=$0
usage="Usage: $cmd [-t title] [podfiles...]"

indextitle="Index of `pwd`"

[ "x$1" = x-t ] && { title=$2; shift; shift; }

[ $# = 0 ] && { set x *.pod; shift; }

# style sheet for "terse" button
cat <<-'X'
	<SCRIPT><!--
	var displaymode;
	function tersify()
	{
	  if (displaymode == "none")
	    displaymode="inline";
	  else
	    displaymode="none";
	  bquotes=document.getElementsByTagName("SPAN");
	  for (i=0; i<bquotes.length; i++)
	  { el=bquotes[i];
	    if (el.className == "overview-para")
	      el.style.display=displaymode;
	  }
	}
	document.write("[&nbsp;<A HREF=\"javascript:tersify()\">Terse</A>&nbsp;]<BR>\n");
	--></SCRIPT>
X

echo "<UL>"
for podfile
do
  title=`sed -n 's/^=head1  *//p' "$podfile" | sed 1q`
  [ -n "$title" ] || title="[$podfile]"

  author=`awk '/^=author /{print$2}' "$podfile" | sed 1q`
  [ -n "$author" ] || author=`ls -ld "$podfile" | awk '{print$3}'`

  echo "$podfile $author $title"
done \
| sort +1 \
| while read podfile author title
  do
    htfile=`basename "$podfile" .pod`.html

    ## dbuser "$author" FULLNAME
    fullname=`{ grep "^$author:" /etc/passwd || ypmatch "$author" passwd; } | awk -F: '{print$5}' | sed 's/,.*//'`
    [ -n "$fullname" ] || fullname=author

    modtime=`ls -ld "$podfile" | awk '{print $6, $7, $8}'`

    echo "    <LI><A HREF=\"$htfile\">$title</A>"
    echo "        <SMALL>- last change $modtime, author <A HREF=\"mailto:$author\">$fullname</A></SMALL>"

    overview=`sed -n -e '1,/^=head2 Overview/d; :para; n; /^$/q; p; b para' <"$podfile"`
    if [ -n "$overview" ]
    then
      necho "	<SPAN CLASS=\"overview-para\"><BR><SMALL>"
      ( echo "=for html"
	echo
	echo "$overview"
	echo
      ) \
      | pod2html "--title=$indextitle" - \
      | sed -n '1,/^<!-- INDEX END -->/d; /^<p>/,/<\/p>$/p' \
      | sed -e 's/^<p>//' -e 's/<\/p>$//'
      echo "</SMALL></SPAN>"
    fi
  done

echo "</UL>"
