#!/bin/sh
#
# Create a simple index of every HTML file that should be made from the PODs
# in the current directory.
#	- Cameron Simpson <cs@zip.com.au> 01jul2003
#

cmd=$0
usage="Usage: $cmd [-j] [-t title] [podfiles...]
	-j	Skip JavaScript tersify() function.
		Useful if you're making several indices in one file.
	-t title Set title."

indextitle="Index of `pwd`"
dotersefn=1

[ "x$1" = x-j ] && { dotersefn=; shift; }
[ "x$1" = x-t ] && { title=$2; shift; shift; }

[ $# = 0 ] && { set x *.pod; shift; }

# javascript for "terse" button
if [ $dotersefn ]
then
  cat <<-'X'
	<SCRIPT><!--
	var displaymode;
	function tersify()
	{
	  if (displaymode == "none")
	    displaymode="inline";
	  else
	    displaymode="none";
	  bquotes=document.getElementsByTagName("SPAN");
	  for (i=0; i<bquotes.length; i++)
	  { el=bquotes[i];
	    if (el.className == "overview-para")
	      el.style.display=displaymode;
	  }
	}
	document.write("[&nbsp;<A HREF=\"javascript:tersify()\">Terse</A>&nbsp;]<BR>\n");
	--></SCRIPT>
X
fi

echo "<UL>"
for podfile
do
  title=`sed -n 's/^=head1  *//p' "$podfile" | sed 1q`
  [ -n "$title" ] || title="[$podfile]"

  author=`awk '/^=author /{print$2}' "$podfile" | sed 1q`
  [ -n "$author" ] || author=`ls -ld "$podfile" | awk '{print$3}'`

  echo "$podfile $author $title"
done \
| sort +2 \
| while read podfile author title
  do
    htfile=`basename "$podfile" .pod`.html

    ## dbuser "$author" FULLNAME
    fullname=`{ grep "^$author:" /etc/passwd || ypmatch "$author" passwd; } | awk -F: '{print$5}' | sed 's/,.*//'`
    [ -n "$fullname" ] || fullname=author

    modtime=`ls -ld "$podfile" | awk '{print $6, $7, $8}'`

    echo "    <LI><A HREF=\"$htfile\">$title</A>"
    echo "        <SMALL>- last change $modtime, author <A HREF=\"mailto:$author\">$fullname</A></SMALL>"

    overview_cache=.cache/overview/`basename "$podfile" .pod`.html
    [ -s "$overview_cache" -a "$overview_cachemyke" -nt "$podfile" ] || myke "$overview_cache" >&2

    if [ -s "$overview_cache" ]
    then
      cat "$overview_cache"
    fi
  done

echo "</UL>"
