#!/bin/sh -u
#
# Make thumbnail of image, report pagename.
#	- Cameron Simpson <cs@zip.com.au> 19feb1995
#
# Prefer PNG to GIF, handle other input types. - cameron, 26may1999
# Prefer JPG to PNG, handle other input types. - cameron, 26nov2005
#

thsize=128x128
trace=	##set-x

cmd=$0
usage="Usage: $cmd [-g geometry] srcimage
	-g XxY		Set max X and Y. Default: $thsize
	srcimage	Input image."

badopts=
while [ $# -gt 0 ]
do  case $1 in
	-g)	thsize=$2; shift ;;
	--)	shift; break ;;
	-?*)	echo "$cmd: unrecognised option: $1" >&2; badopts=1 ;;
	*)	break ;;
    esac
    shift
done

if [ $# = 0 ]
then
  echo "$cmd: missing srcimage" >&2
  badopts=1
else
  srcimage=$1; shift
  [ $# = 0 ] || { echo "$cmd: extra arguments after srcimage: $*" >&2; badopts=1; }
fi

[ $badopts ] && { echo "$usage" >&2; exit 2; }

thsize=${maxx}x${maxy}

exec $trace convof -C "jpgof/$thsize" -discard <"$srcimage" "$srcimage" gm convert -geometry "$thsize" - jpg:-
