#!/usr/bin/perl
#
# Update the mailist list DB from an Hier made from Carl's list.
#	- Cameron Simpson <cs@zip.com.au> 21jul95
#

($cmd=$0) =~ s:.*/::;

use cs::Hier;

$Dir='mailing-lists';	# directory holding known lists

opendir(DIR,$Dir) || die "$cmd: can't opendir($Dir): $!";
@entries=grep(/^\w/,<DIR>);
closedir(DIR);

$lists=&Hier::a2h(join('',<STDIN>));

$xit=0;
LIST:
  for $list (sort keys %$lists)
	{ ($file=$list) =~ tr:/:-:;
	  if (! open(LIST,"> $Dir/$file\0"))
		{ print STDERR "$cmd: can't write to $Dir/$file: $!\n";
		  $xit=1;
		  next LIST;
		}

	  print LIST &Hier::h2a($lists->{$list}), "\n";
	  close(LIST);
	}

for $key (sort @entries)
	{ if (! defined $lists->{$key})
		{ print "$key not updated\n";
		}
	}

exit $xit;
