#!/bin/sh
#
# Create a mairix rc file for the specified MH folder directory.
#	- Cameron Simpson <cs@zip.com.au> 17mar2004
#

vfolder=.mairix-result

cmd=`basename "$0"`
usage="Usage: $cmd [-r resdir] mail-folder
	-r resdir	Specify result directory.
			Default: $vfolder"

badopts=

[ "x$1" = x-r ] && { vfolder=$2; shift; shift; }

if [ $# = 1 ]
then
    dir=$1; shift
    case "$dir" in
	/*)	;;
	*)	echo "$cmd: mail-folder must be a full path" >&2
		badopts=1
		;;
    esac
else
    echo "$cmd: missing mail-folder" >&2
    badopts=1
fi

[ $badopts ] && { echo "$usage" >&2; exit 2; }

folder_directive=
if ismhdir "$dir"
then folder_directive=mh_folders
else
  if ismaildir "$dir"
  then folder_directive=folders
  else
    echo "$dir: not an MH or Maildir folder" >&2
    exit 1
  fi
fi

cd "$dir" || exit 1

exec >".mairixrc"
echo "base=$dir"
echo "$folder_directive=."
echo "vfolder=$vfolder"
echo "vfolder_format=mh"
echo "database=$dir/.mairix.db"
