#!/bin/sh
#
# Look up the mairix indices of the specified folders,
# report mairix-result folder path.
#	- Cameron Simpson <cs@zip.com.au> 17mar2004
#

# catch accidental stdout
exec 3>&1 1>&2

: ${MAILDIR:=$HOME/mail}
: ${TMPDIR:=/tmp}

silent=
trace=

cmd=`basename "$0"`
usage="Usage: $cmd [+folder[,folder...]] [--] keywords..."

badopts=

folders=
case "$1" in
    +*)	for folder in `echo "$1" | sed -e 's/^.//' -e 'y/,/ /'`
	do
	  folder=$MAILDIR/$folder
	  if ismhdir "$folder" || ismaildir "$folder"
	  then
	      folders="$folders $folder"
	  else
	      echo "$cmd: $MAILDIR/$folder: not an MH or Maildir folder" >&2
	      badopts=1
	  fi
	done
	shift
	;;
esac

if [ $# = 0 ]
then  echo "$cmd: missing keywords" >&2
      badopts=1
fi

[ $badopts ] && { echo "$usage" >&2; exit 2; }

[ -n "$folders" ] || folders=`echo "$MAILDIR"/* "$MAILDIR"/[A-Z]*/*`

xit=0

# create result folder
res=`mkdirn "$TMPDIR/mrx"` || exit 1
$trace mhdir "$res"        || exit 1

for folder in $folders
do
  ismhdir "$folder" || ismaildir "$folder" || continue

  db=$folder/.mairix.db
  [ -f "$db" ] || { echo "$cmd: no index for $folder" >&2
		    continue
		  }
  [ -s "$db" ] || continue

  [ $silent ] || necho "Seach $folder "
  $trace mrx-mkrc -r "$res" -t mh "$folder" || { xit=1; continue; }
  $trace mairix -f "$folder/.mairixrc" -a -t "$@" || xit=1
done

echo "$res" >&3

exit $xit
