#!/bin/sh
#
# Shell to run a command from a mykefile.
# Colourises the output.
#	- Cameron Simpson <cs@zip.com.au>
#

cmd=$0
[ $# = 0 ] && { echo "$cmd: missing arguments"; >&2; exit 2; }

##MYKE_STARTDIR=${MYKE_STARTDIR:-`pwd`}
##export MYKE_STARTDIR

set /bin/sh "$@"

##if [ -n "$DISPLAY" ]
##then
##    TMPDIR=${TMPDIR:-/tmp}
##    tmp=$TMPDIR/err$$
##    set filter_fd 2 "tee $tmp" "$@"
##fi

[ -t 1 ] || exec "$@"

set colourise "$@"

"$@"
xit=$?

##[ -f "$tmp" -a -s "$tmp" ] && ( lastvalue -d "$MYKE_STARTDIR" myke_err - <"$tmp"
##				rm "$tmp"
##			      ) &

exit $xit
