#!/bin/sh
#
# Connect to default MySQL database.
#	- Cameron Simpson <cs@zip.com.au>
#

eval `secret "mysql@$SYSTEMID"` || exit 1
exec mysql "-h$secretHOST" "-u$secretLOGIN" "-p$secretPASSWORD" ${1+"$@"}
