#!/bin/sh
#
# Manipulate FVWM named desktops from command line.
#	- Cameron Simpson <cs@zip.com.au> 18jul2002
#

cmd=$0
usage="Usage: $cmd [-r] [desktop]
  -r    Remove named desktop."

rmdesk=
[ "x$1" = x-r ] && { rmdesk=1; shift; }

if [ $# = 0 ]
then
    if [ $rmdesk ]
    then echo "$cmd: you must supply desktop with -r" >&2
	 echo "$usage" >&2
	 exit 2
    else deskname=`lastvalue desktop-$HOST-previous`
    fi
else
    deskname=$1; shift
    case "$deskname" in
	*[a-z]*) deskname=`echo "$deskname" | tr '[a-z]' '[A-Z]'` ;;
    esac
fi

[ $# = 0 ] || { echo "$cmd: extra arguments: $*" >&2
		echo "$usage" >&2
		exit 2
	      }

incant=1
if [ $rmdesk ]
then
  desktop -r "$deskname" || exit 1
else
  case "$deskname" in
    [0-9]|[1-9][0-9]|[1-9][0-9][0-9]|[1-9][0-9][0-9][0-9])
      desknum=$deskname
      incant=
      ;;
    *)desknum=`desktop "$deskname"`	|| exit 1
      ;;
  esac
  set -x
  fvwmcmd "GotoDesk 0 $desknum" &
fi

[ $incant ] || exit 0
desktop-incant-names &
