#!/bin/sh
#
# Manipulate FVWM named desktops from command line.
#	- Cameron Simpson <cs@zip.com.au> 18jul2002
#

cmd=$0
usage="Usage: $cmd [-r] [desktop]"

rmdesk=
[ "x$1" = x-r ] && { rmdesk=1; shift; }

if [ $# = 0 ]
then
    if [ $rmdesk ]
    then echo "$cmd: must supply desktop with -r" >&2
	 echo "$usage" >&2
	 exit 2
    else deskname=`lastvalue desktop-$HOST-previous`
    fi
else
    deskname=$1; shift
    case "$deskname" in
	*[a-z]*) deskname=`echo "$deskname" | tr '[a-z]' '[A-Z]'` ;;
    esac
fi

[ $# = 0 ] || { echo "$cmd: extra arguments: $*" >&2
		echo "$usage" >&2
		exit 2
	      }

[ $rmdesk ] && exec desktop -r "$deskname"

case "$deskname" in
  [0-9]|[1-9][0-9]|[1-9][0-9][0-9]|[1-9][0-9][0-9][0-9])
    desknum=$deskname
    ;;
  *)desknum=`desktop "$deskname"`	|| exit 1
    ;;
esac
set -x
( fvwmcmd "GotoDesk 0 $desknum" "DesktopName $desknum '$deskname'"
  desktop-incant-names
) &
( lastdesk=`lastvalue "desktop-$HOST"`
  if [ "x$lastdesk" != "x$desknum" ]
  then
      lastvalue "desktop-$HOST-previous" "$lastdesk"
      lastvalue "desktop-$HOST" "$desknum"
  fi
) &
