#!/bin/sh
#
# Portable echo without trailing newline.
#	- Cameron Simpson <cs@zip.com.au>
#

sysv=
case $ARCH in
    sun.*.solaris)	sysv=1 ;;	# AIX too?
esac

if [ $sysv ]
then  echo "$*\\c"
else  echo -nE "$*"
fi
