#!/bin/sh
#
# Require existence of directory, creating it if needed.
#	- Cameron Simpson <cs@zip.com.au> 04may2002
#

[ $# = 0 ] && { echo "Usage: $0 dirs..." >&2; exit 2; }

for d
do
    [ -d "$d/." ] || mkdir -p "$d" || exit 1
done

exit 0
