#!/bin/sh -u
#
# Sorted tidy recursive netgroup listing.
#	- Cameron Simpson <cs@zip.com.au>
#

sedcmd=`printf "%s\n" "$HOSTDOMAIN" | sed 's/\./\\\\&/g'`
sedcmd="s/\\.$sedcmd\$//"

if [ "x$1" = x-a ]
then  shift
      filt=cat
else  filt='sed "$sedcmd"'
fi

netgroup -r ${1+"$@"} \
| eval "$filt" \
| sort -u
