#!/bin/sh
#
# Verify authentication using UNIX NIS crypt password.
#	- Cameron Simpson <cs@zip.com.au> 15feb2001
#
# Exit status:
#	0	Login and password match.
#	1	Mismatch or lookup failure.
#	2	Usage (invocation error).
#

cmd=$0
usage="Usage: $cmd login password [crypt]"

case $# in
    2)	login=$1 password=$2
	crypt=`ypmatch "$login" passwd|cut -d: -f 2`
	[ -n "$crypt" ] || { echo "$cmd: crypt lookup failure for $login" >&2
			     exit 1
			   }
	;;
    3)	login=$1 password=$2
	crypt=$3
	;;
    *)	echo "$usage" >&2
	exit 2
	;;
esac

check=`echo "$password"|pwcrypt "$crypt"`
[ "x$check" = "x$crypt" ] && echo "$login"
