#!/bin/sh
#
# Insert a new pattern in the adzapper config file.
#	- Cameron Simpson <cs@zip.com.au> 28feb2003
#

needhost $HOMEHOST@home		|| exit 1
cd $HOME/@/adzapper.sf/html	|| exit 1
umask 22
withjob adzap cvsedit rc/patterns || exit 1
myke _script
