#!/bin/sh
#
# Insert a new pattern in the adzapper config file.
#	- Cameron Simpson <cs@zip.com.au> 28feb2003
#

needhost amadeus@home 				|| exit 1
cd $HOME/there/adzapper.sourceforge.net/html	|| exit 1
umask 22
cvsedit rc/patterns				|| exit 1
myke _all
