#!/bin/sh
#
# Reconfigure for a new network location.
#	- Cameron Simpson <cs@zip.com.au> 23dec2004
#

trace=set-x
cf=/etc/rc.mobile/conf
envfile=/etc/rc.mobile/env.sh

cmd=`basename "$0"`
usage="Usage: $cmd location"

[ $# = 1 ] || { echo "$cmd: missing location" >&2
		echo "$usage" >&2
		exit 2
	      }
loc=$1; shift

[ -s "$cf" ] || { echo "$cmd: missing config file: $cf" >&2
		  exit 1
		}

if [ "x$loc" != "xoff" ]
then
  clausename=net-$loc
  grep "^\[ *$clausename *\]$" "$cf" >/dev/null \
  || { echo "$cmd: no clause named \"$clausename\" in $cf" >&2
       echo "  Known clause names:" >&2
       sed -n 's/^\[ *net-\(.*[^ ]\) *\].*/\1/p' "$cf" | sort | fmt | sed 's/^/    /'
       exit 1
     }
fi

# stop any dhclients and their interfaces
for pidf in /var/run/dhclient-*.pid
do
  [ -s "$pidf" ] || continue
  pid=`cat "$pidf"` || continue
  $trace kill "$pid"
  iface=`expr "x$pidf" = 'x/var/run/dhclient-\(..*\).pid'` || continue
  $trace ifconfig "$iface" down
done

# drop default route
$trace route del default

[ "x$loc" = xoff ] && exec $trace ifconfig eth0 down

# configure for new location
exec $trace env "NET=$loc" rc.mobile start -r -f "$cf" -E "$envfile" on-net
