#!/bin/sh -u
#
# Reconfigure for a new network location.
#	- Cameron Simpson <cs@zip.com.au> 23dec2004
#

: ${LOCATION:=''}

trace=set-x
cf=/etc/rc.mobile/conf
envfiles='/etc/rc.mobile/env.sh /u/cameron/var/env.sh'

cmd=`basename "$0"`
usage="Usage: $cmd location"

badopts=

if [ $# = 1 ]
then
  loc=$1
  shift
  [ -n "$loc" ] || { echo "$cmd: location may not be empty" >&2
		     badopts=1
		   }
else
  echo "$cmd: missing location" >&2
  badopts=1
  loc=
fi

[ -s "$cf" ] || { echo "$cmd: missing config file: $cf" >&2
		  badopts=1
		}

if [ -n "$loc" -a "x$loc" != "xoff" ]
then
  clausename=@$loc
  grep "^\[ *$clausename *\]$" "$cf" >/dev/null \
  || { echo "$cmd: no clause named \"$clausename\" in $cf" >&2
       badopts=1
     }
fi

if [ $badopts ]
then
  echo "$usage" >&2
  echo "  Known clause names:" >&2
  sed -n 's/^\[ *net-\(.*[^ ]\) *\].*/\1/p' "$cf" | sort | fmt | sed 's/^/    /'
  exit 2
fi

# stop any dhclients and their interfaces
for pidf in /var/run/dhclient-*.pid
do
  [ -s "$pidf" ] || continue
  pid=`cat "$pidf"` || continue
  $trace kill "$pid"
  iface=`expr "x$pidf" = 'x/var/run/dhclient-\(..*\).pid'` || continue
  $trace ifconfig "$iface" down
done

# kill network sensitive processes
killpidfile -u -w -d /var/run dhclient-eth0.pid dhclient-eth1.pid ntpd.pid

# drop default route
$trace route del default

# drop interfaces
$trace ifconfig eth0 down
$trace ifconfig eth1 down

[ "x$loc" = xoff ] && exit 0

# configure for new location
set -- $trace env "NET=$loc" rc.mobile start -r -f "$cf"
for envfile in $envfiles
do  set -- "$@" -E "$envfile"
done

exec "$@" env_all "$clausename"
