#!/bin/sh
#
# Wrapper for potrace.
#	- Cameron Simpson <cs@zip.com.au> 14jul2004
#

cmd=`basename "$0"`
usage="Usage: $cmd <image >outlined-image"

[ $# = 0 ] || { echo "$usage" >&2; exit 2; }

gm convert -edge 3 - pbm:-  | potrace -t 6 -O 4 -s
