#!/bin/sh
#
# Overlay one dir on another, prune first one.
#	- Cameron Simpson <cs@zip.com.au> 22jul2004
#

cmd=$0
usage="Usage: $cmd [-d] srcdir destdir
	-d	Make destdir if missing."

needdest=1
[ "x$1" = x-d ] && { needdest=; shift; }

[ $# = 2 ] || { echo "$usage" >&2; exit 2; }
srcdir=$1 destdir=$2

[ -d "$srcdir/." ] || { echo "$cmd: not a directory: $srcdir" >&2; exit 1; }

if [ ! -d "$destdir/." ]
then
  [ $needdest ] && { echo "$cmd: not a directory: $destdir" >&2; exit 1; }
  [ -e "$destdir" ] && { echo "$cmd: not a directory: $destdir" >&2; exit 1; }
  set -x
  exec mv -i "$srcdir" "$destdir"
fi

set -x
overlay "$srcdir" "$destdir"
pruneleafdirs "$srcdir"
exit 0
