#!/bin/sh -u
#
# Overlay the contents of one directory on another.
#	- Cameron Simpson <cs@zip.com.au> 07feb2003
#

cmd=$0
usage="Usage: $cmd [-n] [-z] srcdir destdir [findopts...]"

mrgopts=

badopts=

while [ $# -gt 0 ]
do
  case $1 in
    -n|-z)	mrgopts="$mrgopts $1" ;;
    --)		shift; break ;;
    -?*)	echo "$cmd: unrecognised option: $1" >&2; badopts=1 ;;
    *)		break ;;
  esac
  shift
done

if [ $# -lt 2 ]
then
    echo "$cmd: missing srcdir or destdir" >&2
    badopts=1
else
    src=$1 dest=$2
    shift; shift
fi

[ $badopts ] && { echo "$usage" >&2; exit 2; }

dest=`cd "$dest" || exit 1; pwd` || exit 1

set -x
cd "$src" || exit 1
find . -type f ${1+"$@"} -print | xxargs mrg -rp $mrgopts "$dest/."
