#!/bin/sh
#
# Complete rewrite by Cameron.
# Moved much stuff into user db.	- cameron 20nov97
#

[ $# = 0 ] && { echo "Usage: phone name..." >&2; exit 2; }

phtmp=/tmp/ph$$

cat $HOME/.phone /home/docs/misc/phonedir.auto /home/docs/misc/phonedir \
	>$phtmp 2>/dev/null

for ptn
do
    grep -i "$ptn" <$phtmp
done

rm $phtmp
