#!/bin/sh
#
# Do the common image selection bit from rootbg/menubg.
#	- Cameron Simpson <cs@zip.com.au>
#

cmd=`basename "$0"`
usage="Usage: $cmd [-P strippfx] [imlist-search-args...]"

strippfx=
[ "x$1" = x-P ] && { strippfx=$2; shift; shift; }

if [ -n "$strippfx" ]
then
  ##set -vx
  "$0" ${1+"$@"} | sed "s;^$strippfx/;;"
  exit 0
fi

for d in `bgdirs`
do
  sed -n "s:^\\([0-9][0-9]*  *[0-9][0-9]*\\)  *:\\1 $d/:p" "$d/INDEX"
done \
| imlist-search ${1+"$@"}
