#!/bin/sh
#
# Pick some lines at random from the input, by default 1.
#	- Cameron Simpson <cs@zip.com.au> 19jul2000
#
# Pattern match for selection.	- cameron 12sep2000
#

n=1
case $1 in
    [1-9]*)	n=$1; shift ;;
esac

ptn=.
vflag=
iflag=-i
case "$1" in
    /*/)	ptn=`expr "x$1" : '..\(.*\).'`; shift ;;
    /*)		ptn=`expr "x$1" : '..\(.*\)'`; shift ;;
    !/*/)	vflag=-v ptn=`expr "x$1" : '...\(.*\).'`; shift ;;
    !/*)	vflag=-v ptn=`expr "x$1" : '...\(.*\)'`; shift ;;
esac

[ $# = 0 ] || { echo "Usage: $0 [n] [/ptn/]" >&2; exit 2; }

egrep $iflag $vflag "$ptn" | shuffle | sed "${n}q"
