#!/bin/sh -u
#
# Create a full colour PNG of the specified image file.
#	- Cameron Simpson <cs@zip.com.au> 19may2005
#

: ${TMPDIR:=/tmp}

cmd=$0
usage="Usage: $cmd imagefile"

[ $# = 1 ] || { echo "$usage" >&2; exit 2; }
imagefile=$1; shift

imtype=`file2mime "$imagefile"` || exit 1
[ "x$imtype" = 'ximage/png' ] && exec echo "$imagefile"

tmpf=$TMPDIR/gm$$.png
trap 'rm -f "$tmpf"' 0 1 2 13 15

gm convert "$imagefile" "png:$tmpf" || exit 1
saved=`filecache "$tmpf"` || exit 1
exec printf "$saved\n"
