#!/bin/sh -u
#
# Create a full colour PNG of the specified image file.
#	- Cameron Simpson <cs@zip.com.au> 19may2005
#

: ${TMPDIR:=/tmp}

cmd=$0
usage="Usage: $cmd imagefile"

[ $# = 1 ] || { echo "$usage" >&2; exit 2; }
imagefile=$1; shift

imtype=`file2mime "$imagefile"` || exit 1
[ "x$imtype" = 'ximage/png' ] && exec echo "$imagefile"

exec convof -C pngof -discard -x "$imagefile" gm convert "$imagefile" "png:-"
