#!/bin/sh
#
# Restore $SHELL from saved setting then run $popSHELLcmd.
# This is really an ugly hack to get the script(1) command
# to run something arbitrary rather than the user's shell
# since for some unknown reason is just execs $SHELL.
# Sad but true. Hence this script.
#	- Cameron Simpson <cs@zip.com.au> 18may2002
#

cmd=$0

[ -n "$popSHELL" ] \
	|| { echo "$cmd: no \$popSHELL set, aborting" >&2
	     exit 2
	   }

[ -n "$popSHELLcmd" ] \
    || { echo "$cmd: no \$popSHELLcmd, aborting" >&2
	 exit 2
       }

shcmd=$popSHELLcmd
SHELL=$popSHELL
export SHELL
unset popSHELL popSHELLcmd

##set -x
exec "$SHELL" -c "$shcmd"
