#!/bin/sh
#
# Establish ssh tunnels as needed.
#	- Cameron Simpson <cs@zip.com.au> 05may2004
#

case "$HOST.$SYSTEMID@$LOCATION" in
  newt.home@cisra|kirsty.home@cisra)
    set -x
    acon lock -1 portfwd-kaper \
	sh -c 'set -x
	       ssh -f -L 6009:127.0.0.1:6000 kaper exec ./bin/redhat.x86.linux/pause
	       exec x2x -west -to localhost:9'
    ;;
esac
