#!/bin/sh -u
#
# Process the mail item on stdin as spam.
#	- Cameron Simpson <cs@zip.com.au>
#

: ${LOGDIR:=$HOME/var/log}
: ${ALERTLOG:=$LOGDIR/alert}
: ${TMPDIR:=/tmp}

tmpf=$TMPDIR/procspam$$
trap 'rm -f "$tmpf"' 0
trap 'rm -f "$tmpf"; exit 1' 1 2 13 15
cat >"$tmpf" || exit 1
exec </dev/null

bogof -Ns <"$tmpf"
bogof <"$tmpf" \
|| { # not spam yet? file for recount
     exec 3<"$tmpf"
     ( exec <&3 3<&- >>"$ALERTLOG" 2>&1
       filemailitem +spam-redo
     ) &
   }

exit 0
