#!/bin/sh -u
#
# Recite procmail log in one-line form.
#       - Cameron Simpson <cs@zip.com.au> 05nov2006
#

cmd=`basename "$0"` || exit 1
usage="Usage: $cmd logfile"

if [ $# = 0 ]
then
  exec sed -e '
    y/	/ /
    /^ Subject: */{
      s/^ Subject: *//
      h
      d
    }
    /^  Folder: */{
      s/^  Folder: *//
      /^\/dev\/null /d
      G
      s/\n/ /
      s/   */ /g
      p
      d
    }
    w /dev/fd/2
    d
  '
fi

tail -f "$1" | "$0"
