#!/bin/sh
: ${LOGDIR:=$HOME/var/log}
: ${CONSOLE:=$LOGDIR/console}
: ${TMPDIR:=/tmp}
exec >>"$CONSOLE" 2>&1
tmp=$TMPDIR/procspam$$
cat >"$tmp" || exit 1
exec </dev/null
( bogofilter -Ns <"$tmp"
  filemailitem +spam-corpus <"$tmp"
  ##procmail <"$tmp"
  rm "$tmp"
) &
