#!/bin/sh
#
# Process the mail item on stdin as spam.
#	- Cameron Simpson <cs@zip.com.au>
#

: ${LOGDIR:=$HOME/var/log}
: ${ALERTLOG:=$LOGDIR/alert}

exec 3<&0 >>"$ALERTLOG" 2>&1
bogof -Ns <&3 3<&- &
exit 0
