#!/bin/sh -ue

ptopts=
while [ $# -gt 0 ]
do  case $1 in
      +?*)	ptopts="$ptopts $1" ;;
      *)	break ;;
    esac
    shift
done

case $OS in
    solaris)	        exec pt -e  $ptopts ;;
    darwin|*bsd|linux)  exec pt wwwax $ptopts ;;
    ultrix|domainos|sunos)
			exec ps agxuww ;;
    *)			echo "$0: don't know how to psa when OS=\"$OS\"" >&2
			exit 1
			;;
esac \
| entilde
