#!/bin/sh
#
# Rebuilt the css kit, put to EZOS, also push account and css to named hosts.
#	- Cameron Simpson <cs@zip.com.au> 09jul2004
#

umask 22
updcss

set -x

syncezos &

for xtra
do  sleep 1; putacc $xtra &
    sleep 1; putcss $xtra &
done

wait
