#!/bin/sh

needhost $HOMEHOST@home || exit 1

hARCH=$ARCH

[ $# -ge 1 ] || { echo "Usage: $0 [login@]hostname" >&2; exit 2; }
host=$1; shift

cd || exit 1
set -x
exec rsync -avHP --delete \
	'--include=/.bash_logout' \
	'--include=/.bash_profile' \
	'--include=/.bashrc' \
	'--include=/.less' \
	'--include=/.lesskey' \
	'--include=/.mailcap' \
	'--include=/.muttrc' \
	'--include=/.profile' \
	'--include=/.secret' \
	'--include=/.setvar' \
	'--include=/.xinitrc' \
	'--include=/.xsession' \
	'--include=/.zshenv' \
	'--include=/bin' \
	'--include=/rc' \
	'--include=/rc/env' \
	'--include=/rc/mail' \
	'--include=/rc/mail/mailcap' \
	'--include=/rc/mail/mutt*' \
	'--include=/rc/mail/signature' \
	'--exclude=/rc/mail/*' \
	'--include=/rc/myke' \
	'--include=/rc/nvi' \
	'--include=/rc/perl' \
	'--include=/rc/shell' \
	'--include=/rc/ssh' \
	'--include=/rc/vi' \
	'--include=/rc/x11' \
	'--exclude=/rc/*' \
	'--include=/scripts' \
	'--include=/there' \
	'--include=/there/cameron@cskk.homeip.net' \
	'--include=/there/cameron@cskk.homeip.net/bin' \
	"--include=/there/cameron@cskk.homeip.net/bin/$hARCH" \
	'--exclude=/there/cameron@cskk.homeip.net/bin/*' \
	'--include=/there/cameron@cskk.homeip.net/scripts' \
	'--include=/there/cameron@cskk.homeip.net/scripts/cs/' \
	'--include=/there/cameron@cskk.homeip.net/scripts/stubs/' \
	'--include=/there/cameron@cskk.homeip.net/scripts/synonyms/' \
	'--exclude=/there/cameron@cskk.homeip.net/scripts/*/' \
	'--exclude=/there/cameron@cskk.homeip.net/*' \
	'--include=/there/home' \
	'--exclude=/there/*' \
	'--include=/var' \
	'--include=/var/*/' \
	'--exclude=/var/*/*' \
	'--exclude=/var/*' \
	'--exclude=/*' \
	. "$host:."
