#!/bin/sh

[ $# -ge 1 ] || { echo "Usage: $0 [login@]hostname" >&2; exit 2; }
host=$1; shift

cd || exit 1

hasrsync=1
rrsync=rsync

if [ $# = 0 ]
then
    set .profile .zshenv .setvar \
		  rc/ssh rc/shell rc/env rc/perl rc/vi rc/nvi rc/x11 \
		  .less .lesskey rc/less rc/lesskey \
		  .xinitrc .xsession \
		  there/cameron@cskk.homeip.net/scripts \
		  there/cameron@cskk.homeip.net/bin/$hARCH \
		  there/home \
		  scripts bin
    hARCH=$ARCH
fi

for arg
do  echo "rm -rf $arg"
done | ssh "$host" sh -x

set -x
tar cf - "$@" | ssh "$host" tar xvf -
