#!/bin/sh

cd || exit 1

[ $# -ge 1 ] || { echo "Usage: $0 [login@]hostname" >&2; exit 2; }
host=$1; shift

[ $# = 0 ] && set scripts .profile .zprofile .zshrc .zshenv .setvar \
		  rc/shell rc/env rc/perl rc/vi rc/nvi rc/x11 \
		  .less .lesskey rc/less rc/lesskey \
		  .xinitrc .xsession

case "$host" in
    agricola|tw|barstool)
	first=1
	for arg
	do  [ $first ] && { set rsync -avHPC --rsh=ssho --include=rc
			    first=
			  }
	    set "$@" "--include=/$arg"
	done
	set -x
	"$@" '--exclude=/rc/*' '--exclude=/*' "$HOME/." "$host:."
	;;
    *)	set -x
	tar cf - "$@" | ssho "$host" exec tar xf -
	;;
esac
