#!/bin/sh -u
#
# Look up bookmarks and pop up matching URLs.
#	- Cameron Simpson <cs@zip.com.au> 24jan2006
#

: ${BMK_DIR:=$HOME/rc/bmk}

cmd=$0
usage="Usage: $cmd [-d dir] words..."

[ $# -gt 0 ] && [ "x$1" = x-d ] && { BMK_DIR=$2; shift; shift; }
if [ $# = 0 ]
then
  echo "$cmd: missing words" >&2
  exit 2
fi

word1=$1; shift
sedf='/^URL: *[^ ]/{s/^URL: *\([^ ][^ ]*\).*/\1/p;q;}'

fgrep -ilr -- "$word1" "$BMK_DIR" \
| while read -r file
  do
    ok=1
    for word
    do fgrep -iq -- "$word" "$file" || { ok=; break; }
    done
    [ $ok ] && sed -n '/^URL: *[^ ]/{s/^URL: *\([^ ][^ ]*\).*/\1/p;q;}' "$file"
  done \
| sort -u \
| us -
