#!/bin/sh
#
# Take argument as a $QUERY_STRING CGI parameter and emit shell to
# turn the values into PARAM_x for each parameter x.
#	- Cameron Simpson <cs@zip.com.au> 11aug1999
#
# Use $QUERY_STRING itself if no arg.
#

[ $# -le 1 ] || { echo "Usage: $0 [query_string]" >&2; exit 2; }
qs=${1-"$QUERY_STRING"}

printf "%s\n" "$qs" \
| tr '&+' '\012 ' \
| sed -n 's/^\([A-Za-z_][A-Za-z0-9_]*\)=/\1 /p' \
| while read var value
  do value=`echo "$value" | unhexify | sed "s/'/'\\\\\\''/g"`
     echo "PARAM_$var='$value'"
  done
