#!/bin/sh -u

: ${DISPLAY:=''}

cmd=$0
usage="Usage: $cmd [-r rdisplay] host [cmd [args...]"

case "$DISPLAY" in
  :*)	rdisplay=$HOST$DISPLAY ;;
  localhost:* | 127.0.0.1:* )
	rdisplay=$HOST`expr "x$DISPLAY" : 'x.*\(:.*\)'` ;;
  *)	rdisplay=$HOST:0 ;;
esac

badopts=

[ $# -gt 0 ] && [ "x$1" = x-r ] && { rdisplay=$2; shift; shift; }

if [ $# = 0 ]
then
  echo "$cmd: missing host" >&2
  badopts=1
else
  host=$1
  shift
fi

[ $# = 0 ] && set -- /bin/sh -c 'exec "${SHELL:-/bin/sh}"'

[ $badopts ] && { echo "$usage" >&2; exit 2; }

rcmd=`shqstr env "DISPLAY=$rdisplay" term -keepio -e "$@"` || exit 1

for h in `echo "$host" | tr , ' '`
do
  set-x envssh -f "$h" "$rcmd"
done
