#!/bin/sh
#
# Set the root background, update state files to match.
#	- Cameron Simpson <cs@zip.com.au>
#

: ${TMPDIR:=/tmp}
: ${RBG_PICKIM:='-w -x "$HALFX" -y "$HALFY"'}

cmd=$0
usage="Usage: $cmd [-d desk] [-n] [imlist-search-args...]
	-d desk	Set the background for the specified desk.
	-n	No action. Just print the chosen image(s)."

[ -n "$DISPLAY" ] || { echo "$cmd: no \$DISPLAY!" >&2; exit 1; }

badopts=

opts=
pickn=20
perdesk=
aspect=-w
pickopts=
strippfx=
bgop=rootbg
bgdesk=-

while :
do  case $1 in
	-d)	bgdesk=$2; shift ;;
	-n)	doit= ;;
	-1)	pickn=1 ;;
	*)	break ;;
    esac
    shift
done

if [ $# = 1 ]
then
  case "$1" in
    http://* | ftp://* )
      exec withurl -C "$1" deskbg -d "$bgdesk"
      ;;
    X:* | 1,- | 1,*:- | 1,\|* )
      # one argument which is a GraphicsMagick-ish name
      exec deskbg -d "$bgdesk" "$1"
      ;;
  esac

  # a file?
  [ -f "$1" -a -s "$1" ] && exec deskbg -d "$bgdesk" "$1"
fi

tmpf=$TMPDIR/rbg$$
eval "pickim -P \"\$strippfx\" -n \"\$pickn\" $RBG_PICKIM "'${1+"$@"}' | sort -u >"$tmpf"
[ -s "$tmpf" ] || { echo "$cmd: no image files chosen!" >&2
		    rm "$tmpf"
		    exit 1
		  }

[ $doit ] || { cat "$tmpf"; xit=$?; rm "$tmpf"; exit $xit; }

# pop up menu choice
exec fvwmcmd \
  "SetEnv FVWM_MENU_IMLIST_OP \"acon set-x deskbg -d $bgdesk $opts\"" \
  "Piperead 'fvwm-menu -1 ImDirMenu \"$cmd $call\" fvwm-menu-imlist -l $tmpf .; rm $tmpf'" \
  "Popup ImDirMenu" \
  "UnSetEnv FVWM_MENU_IMLIST_OP"
