#!/bin/sh

cmd=$0
usage="Usage: $cmd [-D] [-d desk] [imlist-search-args...]
	-d desk	Set the background for the specified desk.
	-D	The background is per-desk, not global."

[ -n "$DISPLAY" ] || { echo "$cmd: no \$DISPLAY!" >&2; exit 1; }

badopts=

opts=
pickn=20
perdesk=
aspect=-w
pickopts=
strippfx=
bgop=rootbg

while :
do  case $1 in
	-d)	bgop="deskbg -d $2"; shift ;;
	-D)	bgop="deskbg -d `currentdesk`" ;;
	*)	break ;;
    esac
    shift
done

tmp=${TMPDIR:-/tmp}

dopick=1
case "$#,$1" in
  1,http://*)
    # one argument which is an URL
    exec withurl -C "$1" $bgop
    ;;
  1,X:* | 1,- | 1,*:- | 1,\|* )
    # one argument which is a GraphicsMagick-ish name
    dopick=
    ;;
esac

[ $dopick ] || exec $bgop ${1+"$@"}

set -- `pickim -P "$strippfx" -n "$pickn" ${1+"$@"} | sort -u`
if [ $# = 0 ]
then
  echo "$cmd: no image files chosen!" >&2
  exit 1
fi

# pop up menu choice
set -x
tmpf=$tmp/rbg$$
for arg
do  echo "$arg"
done >"$tmpf"
exec fvwmcmd \
  "SetEnv FVWM_MENU_IMLIST_OP \"$bgop $opts\"" \
  "Piperead 'fvwm-menu -1 ImDirMenu \"$cmd $call\" fvwm-menu-imlist -l $tmpf .; rm $tmpf'" \
  "Popup ImDirMenu" \
  "UnSetEnv FVWM_MENU_IMLIST_OP"
