#!/bin/sh -u
#
# Read a line using the GNU readline stuff, for file completion.
# Would that there was a way to supply come initial content...:-(
#	- Cameron Simpson <cs@zip.com.au> 22feb2004
#

cddir=
doblank=

{ [ -t 0 ] && cmd=`basename "$0"`; } || cmd=$0
usage="Usage: readline [-d dir] prompt
        -B      Blank out the line with some spaces first.
	-d dir	Resolve completions in dir."

badopts=

while [ $# -gt 0 ]
do
  case "$1" in
    -B) doblank=1 ;;
    -d) cddir=$2; shift ;;
    --) shift; break ;;
    -?*)echo "$cmd: unrecognised option: $1" >&2
        badopts=1
        ;;
    *)  break ;;
  esac
  shift
done

if [ $# = 0 ]
then
    echo "$cmd: missing prompt" >&2
    badopts=1
else
    prompt=$1; shift
    [ $# = 0 ] || { echo "$cmd: extra arguments after prompt: $*" >&2; badopts=1; }
fi

[ $badopts ] && { echo "$usage" >&2; exit 2; }

[ -t 0 ] || { echo "$0: stdin must be a tty" >&2; exit 1; }

[ $doblank ] && printf '\015                                                            \015' >&2

if [ -x "/bin/bash" ]
then
    export prompt
    [ -n "$cddir" ] && [ -d "$cddir/." ] && cd "$cddir"
    exec bash -c 'read -p "$prompt" -r -e line >&2 || exit 1; printf "%s\n" "$line"'
else
    printf "%s" "$prompt" >&2
    read line || exit 1
    printf "%s\n" "$line"
fi
