#!/bin/sh
#
# Prompt for a change log line for a bug report.
#	- Cameron Simpson <cs@zip.com.au> 10aug2004
#

prompt="Please enter the reason and bug id for this session."

cmd=$0
usage="Usage: $cmd [prompt]"

[ $# = 0 ] || prompt=$*

[ -t 0 ] || { echo "$cmd: stdin must be a tty" >&2; exit 1; }
echo "$prompt" >&2
msg=`readline "> "` || exit 1
[ -n "$msg" ] && echo "$msg"
