#!/bin/sh
#
# Read a line using the GNU readline stuff, for file completion.
# Would that there was a way to supply come initial content...:-(
#	- Cameron Simpson <cs@zip.com.au> 22feb2004
#

cmd=$0
usage="Usage: readline prompt"

badopts=

if [ $# = 0 ]
then
    echo "$cmd: missing prompt" >&2
    badopts=1
else
    prompt=$1; shift
    [ $# = 0 ] || { echo "$cmd: extra arguments after prompt: $*" >&2; badopts=1; }
fi

[ $badopts ] && { echo "$usage" >&2; exit 2; }

[ -t 0 ] || { echo "$0: stdin must be a tty" >&2; exit 1; }

if [ -x "/bin/bash" ]
then
    export prompt
    exec bash -c 'set -o no_empty_cmd_completion; read -p "$prompt" -r -e line >&2 || exit 1; echo "$line"'
else
    necho "$prompt"
    read line || exit 1
    echo "$line"
fi
