#!/bin/sh -u
#
# Renumber a user.
#	- Cameron Simpson <cs@zip.com.au> 19jun2005
#

passwd=/etc/passwd
trace=set-x

cmd=`basename "$0"`
usage="Usage: $cmd [-f passwdfile] login newuid"

badopts=

[ $# -gt 0 ] && [ "x$1" = x-f ] && { passwd=$2; shift; shift; }

if [ $# = 0 ]
then
  echo "$cmd: missing login" >&2
  badopts=1
else
  login=$1; shift
  if [ $# = 0 ]
  then
    echo "$cmd: missing newuid" >&2
    badopts=1
  else
    newuid=$1; shift
    [ $# = 0 ] || { echo "$cmd: extra arguments after newuid: $*" >&2
		    badopts=1
		  }
  fi

  case "$login" in
    '' | *[^a-z]* | *:* | *-* )
      echo "$cmd: bad login \"$login\"" >&2; badopts=1
      ;;
  esac
fi

[ -s "$passwd" ] || { echo "$cmd: $passwd: not a file" >&2; badopts=1; }

[ $badopts ] && { echo "$usage" >&2; exit 2; }

# look up login, note old uid
olduid=`awk -F: "\\$1 == \\"$login\\" {print \\$3}" "$passwd"` || exit 1
[ -n "$olduid" ] || { echo "$cmd: $passwd: no line for login \"$login\"" >&2
		      exit 1
		    }
homedir=`awk -F: "\\$1 == \\"$login\\" {print \\$6}" "$passwd"` || exit 1

# look up new uid, whinge if already in use
if grep "^[^:]*:[^:]*:$newuid:" "$passwd" >&2
then
  echo "$cmd: existing user above conflicts with new uid $newuid for $login" >&2
  exit 1
fi

$trace bsed "/^$login:[^:]*:$olduid:/{
		h
		s/:/-olduid:/
		x
		s/^\\($login:[^:]*\\):$olduid:/\\1:$newuid:/
		x
		G
	     }" "$passwd" \
|| exit 1

echo pwconv
echo rechown -f "$passwd" "$olduid" "$newuid" "$homedir/." ...

ask "Renumber the group \"$login\" to $newuid as well" \
&& renumgroup "$login" "$newuid"
