#!/bin/sh -u
#
# Rewrite the named file if the input differs.
#	- Cameron Simpson <cs@zip.com.au> 19may2000
#

: ${TMPDIR:=/tmp}
: ${DIFFOPTS='-c'}

cmd=`basename "$0"`
usage="Usage: $cmd [-0] [-v] filename [command args...]
	-0	Rewrite the file even if the input is empty.
	-d	Do a diff of the file changes.
	-v	Verbose."

rw0=
dodiff=
verbose=
diff=diff

badopts=

while [ $# -gt 0 ]
do
  case "$1" in
    -0)	rw0=1 ;;
    -d)	dodiff=1 ;;
    -v)	verbose=1 ;;
    --)	shift; break ;;
    -?*)echo "$cmd: unrecognised option: $1" >&2
	badopts=1
	;;
    *)	break ;;
  esac
  shift
done

if [ $# = 0 ]
then
  echo "$cmd: missing filename" >&2
  badopts=1
else
  file=$1; shift
  [ -f "$file" ] || { echo "$cmd: $file: not a regular file" >&2
		      badopts=1
		    }
  [ $# -gt 0 ] || set -- cat
fi

[ $badopts ] && { echo "$usage" >&2; exit 2; }

tmp=$TMPDIR/rwi$$
trap 'rm "$tmp"' 1 2 13 15

"$@" >"$tmp" || { rm -f "$tmp"; exit 1; }

[ $rw0 ] || [ -s "$tmp" ] || { echo "$cmd: empty input, rewrite aborted" >&2
			       rm -f "$tmp"
			       exit 1
			     }

cmp -s "$tmp" "$file" && { rm "$tmp"; exit 0; }

[ $verbose ] && echo "rewrite $file"
[ $dodiff  ] && $diff $DIFFOPTS "$file" "$tmp"
if cat "$tmp" >"$file"
then
    rm "$tmp"
    exit 0
else
    echo "$cmd: rewrite of $file fails, probably damaged" >&2
    echo "	rewrite content left in $tmp" >&2
    exit 1
fi
