#!/bin/sh
#
# Pop up an RFC.
#	- Cameron Simpson <cs@zip.com.au> 05nov1996
#

[ $# = 0 ] && { echo "Usage: $0 keys..." >&2; exit 2; }

rfcdir=/home/docs/Internet/rfc

xit=0

for key
do
    case $key in
	[0-9]*)
			## "http://freesoft.org/CIE/RFC/$key/index.htm"
			urlshow "http://www.faqs.org/rfcs/rfc$key.html"
			continue
			;;
	*)		rfcconnected "$key"
			continue
			;;
    esac
done

exit $xit
