#!/bin/sh
#
# Simple wrapper for find in the current directory.
#	- Cameron Simpson <cs@zip.com.au> 21jul2002
#

cmd=$0
usage="Usage: $cmd [.sfx] [command [args...]]"

sfx=
case "$1" in
    .?*)	sfx=$1; shift ;;
esac

[ $# = 0 ] || { set x -exec "$@" {} ';'; shift; }
[ -n "$sfx" ] && { set x -name "*$sfx" "$@"; shift; }

exec find . -type f "$@"
