#!/bin/sh
#
# Set up a gpg-agent in daemon mode, much like rig-ssh-agent.
#	- Cameron Simpson <cs@zip.com.au> 30mar2005
#

: ${LOGDIR:=$HOME/var/log}
: ${CONSOLE:=$LOGDIR/console}

cmd=$0
usage="Usage: $cmd [-f] [statefile]"

statefile=
force=1

badopts=

[ "x$1" = x-f ] && { force=1; shift; }

[ $# = 0 ] || { statefile=$1; shift; }

[ $# = 0 ] || { echo "$cmd: extra arguments: $*" >&2; badopts=1; }

[ $badopts ] && { echo "$usage" >&2; exit 2; }

[ -n "$statefile" ] || statefile=`gpg-agent-statefile` || exit 1

# bail if we've already got an agent
[ -z "$force" ] && eval `get-gpg-agent "$statefile"` && exit 0

unset GPG_AGENT_INFO
exec 2>>"$CONSOLE"
exec gpg-agent --daemon >"$statefile"
