#!/bin/sh
#
# Set up a urxvtd to run terminals. Report the control socket.
#	- Cameron Simpson <cs@zip.com.au> 10nov2005
#

exec 3>&1 1>&2
[ $# = 0 ] && exec </dev/null

: ${LOGDIR:=$HOME/var/log}
: ${ALERTLOG:=$LOGDIR/alert}

user=`whoami || id -un` || exit 1
RXVT_SOCKET=/tmp/urxvtd-socket-$user-$DISPLAY
export RXVT_SOCKET

lock=$RXVT_SOCKET

alog "$ALERTLOG" set-x lock -1 "$RXVT_SOCKET" set-x sh -xc 'rm -f "$RXVT_SOCKET"; exec urxvtd -o'

exec 1>&3 3>&-

[ $# = 0 ] && exec echo "$RXVT_SOCKET"
exec "$@"
