#!/bin/sh -u
#
# Set up an ssh-agent in daemon mode if needed.
#	- Cameron Simpson <cs@zip.com.au> 30jul2001
#

cmd=$0
usage="Usage: $cmd [-f] [statefile]"

statefile=
force=
hopt=

badopts=

[ $# -gt 0 ] && [ "x$1" = x-f ] && { force=1; shift; }
[ $# -gt 0 ] && [ "x$1" = x-h ] && { hopt=-h; shift; }

[ $# = 0 ] || { statefile=$1; shift; }

[ $# = 0 ] || { echo "$cmd: extra arguments: $*" >&2; badopts=1; }

[ $badopts ] && { echo "$usage" >&2; exit 2; }

[ -n "$statefile" ] || statefile=`ssh-agent-statefile` || exit 1

if [ $force ]
then
  # force unlock
  unlock -f "$statefile"
else
  eval `get-ssh-agent $hopt "$statefile"` && exit 0
fi

export statefile

exec \
  bgproc \
  lock -1 -a "$statefile" \
  rmthen -f "$statefile" \
  no-ssh-agent \
  set-x \
  ssh-agent \
  sh -c 'stash-ssh-agent "$statefile"; exec pause' \
  </dev/null
