#!/bin/sh
#
# Set up an ssh-agent in daemon mode.
#	- Cameron Simpson <cs@zip.com.au> 30jul2001
#

cmd=$0
usage="Usage: $cmd [-u] [statefile]"

state=
unlock=

badopts=

[ "x$1" = x-u ] && { unlock=1; shift; }

[ $# = 0 ] || { state=$1; shift; }

[ $# = 0 ] || { echo "$cmd: extra arguments: $*" >&2; badopts=1; }

[ $badopts ] && { echo "$usage" >&2; exit 2; }

[ -n "$state" ] || state=`ssh-agent-statefile` || exit 1

# force unlock
[ $unlock ] && { shift; set -x; unlock -f "$state"; }

exec \
  lock -1 -a "$state" \
  rmthen -f "$state" \
  env "state=$state" \
  no-ssh-agent \
  ssh-agent \
  sh -c 'stash-ssh-agent "$state"; exec pause' \
  </dev/null
