#!/bin/sh -u
#
# Set up a urxvtd to run terminals. Report the control socket.
#	- Cameron Simpson <cs@zip.com.au> 10nov2005
#

exec </dev/null 3>&1 1>&2

[ -n "$DISPLAY" ] || { echo "$0: no $DISPLAY, aborting" >&2; exit 1; }

: ${LOGDIR:=$HOME/var/log}
: ${ALERTLOG:=$LOGDIR/alert}
: ${USER:=`whoami || id -un`}
: ${HOST:=`hostname | sed 's/\..*//'`}
: ${RXVT_SOCKET:=/tmp/urxvtd-socket-$USER}
export RXVT_SOCKET

trace=set-x
lock=urxvtd-$USER-$HOST-$DISPLAY

$trace bgproc -l procmail -p "$lock" -- lock -1 "$lock" urxvtd -q 3>&-

exec >&3 3>&-
echo "$RXVT_SOCKET"
