#!/bin/sh
#
# Set up an ssh-agent in daemon mode.
#	- Cameron Simpson <cs@zip.com.au> 30jul2001
#

lock=ssh-agent-$HOST

# force unlock
[ "x$1" = x-f ] && { shift; unlock -f "$lock"; }

exec \
  con \
  lock -1 -a "$lock" \
  no-ssh-agent \
  ssh-agent \
  sh -c 'env|sed -n "s/^\\(SSH_[_A-Z]*\\)=\\(.*\\)/\\1='\\2'; export \\1;/p" >"$VARRUN/ssh-agent-$HOST"; exec pause' \
  </dev/null
