#!/bin/sh
#
# Consult my .ftprc file and construct my ftp directory.
#

cd

[ -r .ftprc ] || { echo "$0: no .ftp file" >&2 ; exit 1 ; }

ftpdir=/usr/spool/ftp/pub/$USER

[ -d "$ftpdir" ] || { echo "$0: no ftp directory for $USER" >&2 ; exit 1 ; }

rm -rf "$ftpdir"/*

makedir()
{
	_mode=$1
	shift
	for _dir
	do  needdir "$_dir" && chmod $_mode "$_dir" || exit 1
	done
}

exec <.ftprc
while read findopts
do
	( eval "exec find $findopts" ) |
	while read file
	do
		echo "$file ..." >&2
		case "$file"
		in
			/*)	echo "can't link full paths" >&2 ;;
			*)	if [ -d "$file" ]
				then
					makedir 755 "$file"
				else
					case "$file" in
						*/*)	dir="$ftpdir/"`exec expr x"$file" : x'\(.*\)/.*'`
							makedir 755 "$dir" &&
							{ ln "$file" "$ftpdir/$file" 2>/dev/null ||
							  cp "$file" "$ftpdir/$file"
							} ;;
						*)	{ ln "$file" "$ftpdir/$file" 2>/dev/null ||
							  cp "$file" "$ftpdir/$file"
							} ;;
					esac
					[ -f "$ftpdir/$file" ] && chmod 644 "$ftpdir/$file"
				fi
				;;
		esac
	done
done
