#!/bin/sh
#
# Dispatch a daemon mode fetchmail.
#	- Cameron Simpson <cs@zip.com.au> 14dec2003
#

: ${LOGDIR:=$HOME/var/log}

needhost "$HOMEHOST@home" || exit 1
cd
dofetchmail -l 65536
bgproc runfetchmail
