#!/bin/sh
#
# Dispatch a daemon mode fetchmail.
#	- Cameron Simpson <cs@zip.com.au> 14dec2003
#
needhost $HOMEHOST@home || exit 1
set -x
cd
fmopts=
case "$LOCATION" in
  home|sco|tw)	fmopts="$fmopts -l 65536" ;;
esac
acon fetchmail \
	-f "$HOME/.fetchmailrc" \
	$fmopts \
	-d 900 \
	--logfile "$HOME/var/log/fetchmail" \
	--nobounce --tracepolls --warnings 86400 \
	127.0.0.2 127.0.0.3
## have to debug with change to maildir
alog procmail lock -1 getmail-despool nice getmail-flush -p 300 spool
