#!/bin/sh
#
# Set up my freenet server.
# Current is test mode, so no advertising.
#	- Cameron Simpson <cs@zip.com.au> 29dec2000
#

needhost $HOMEHOST@home || exit 1
pwd
set -x
exec sh -x freenet_server -transient=yes -informWrite=no
