#!/bin/sh

cmd=$0

[ "x$HOST" = xzapff -o "x$HOST" = xamadeus ] \
	|| { echo "$cmd: not on zapff or amadeus, bailing" >&2; exit 1; }

if locked nntpcached
then
    echo "$cmd: lock for nntpcached already taken, bailing" >&2
    exit 1
fi

set -x
alog nntpcache lock nntpcached nntpcached -n -c $HOME/rc/nntpcache/nntpcache.config
