#!/bin/sh
# - Cameron Simpson <cs@zip.com.au> 22mar2001

SOURCE_HOST=${SOURCE_HOST:-$HOST}
case "$DISPLAY" in
	'')	;;
	:*)	SOURCE_DISPLAY=$SOURCE_HOST$DISPLAY ;;
	unix:*) SOURCE_DISPLAY=$SOURCE_HOST`expr "$DISPLAY" : '.*\(:.*\)'` ;;
	*)	SOURCE_DISPLAY=${SOURCE_DISPLAY:-$DISPLAY} ;;
esac
export SOURCE_HOST SOURCE_DISPLAY

[ $# = 0 ] && { echo "SOURCE_HOST=$SOURCE_HOST"
		echo "SOURCE_DISPLAY=$SOURCE_DISPLAY"
		echo "export SOURCE_HOST SOURCE_DISPLAY"
		exit 0
	      }

exec "$@"
