#!/bin/sh
#
# Dispatch the adzapper in proxy mode.
#	- Cameron Simpson <cs@zip.com.au> 01jul2004
#

set -x
##exec alog squid_redirect squid_redirect -P "8080:$SQUID"
rc=$HOME/tmp/squid.conf$$
envsub -p '\{\{([A-Z]\w*)\}\}' <$HOME/rc/squid/tplt >$rc
exec alog squid/cache.log squid -f "$rc" -D
