#!/bin/sh
#
# Make a slideshow directory - a dir full of symlinks to things to show.
# Emits shell; pipe through "sh -x"to actually do stuff.
#	- Cameron Simpson <cs@zip.com.au> 01aug2003
#

cmd=`basename "$0"`
usage="Usage: $cmd [pickim-options...] keywords...
  Suggestion: $cmd -w -o keywords..."

[ $# = 0 ] && { echo "$usage" >&2; exit 2; }

pickim "$@" \
| while read path
  do  lpath=`echo "$path" | tr -s / _ | sed 's/^_//'`
      echo "$lpath $path"
  done \
| updlinkforest
