#!/bin/sh -u
#
# Dispatch tcpio ssh tunnel according to input data.
# Input line format:
#	localaddr localport remotesite remotehost remoteport
# which sets up a "tcpio -a" to listening on the interface "localaddr"
# on port "localport", using rnc to forward connections via ssh to "remotesite"
# and thence via nc to the host "remotehost", port "remoteport".
#	- Cameron Simpson <cs@zip.com.au> 03may2005
#

user=
id=

cmd=`basename "$0"` || exit 1
usage="Usage: $cmd [-u user] [-i identity] < config
	-u user		Passed to rnc.
	-i identity	Passed to rnc. Default: \$HOME/.ssh/2any"

badopts=

while [ $# -gt 0 ]
do
  case $1 in
    -u)	user=$2; shift ;;
    -i)	id=$2; shift ;;
    --)	shift; break ;;
    -?*)echo "$cmd: unrecognised option: $1" >&2
	badopts=1
	;;
    *)	break ;;
  esac
  shift
done

[ $# = 0 ] || { echo "$cmd: extra arguments: $*" >&2; badopts=1; }

[ $badopts ] && { echo "$usage" >&2; exit 2; }

grep '^[^#]' \
| while read localaddr localport sshsite fwdhost fwdport
  do
    set-x \
    tcpio -a "$localaddr:$localport" \
      env ENVFILES=/etc/rc.mobile/env.sh syncenv - \
      rnc -l "$sshsite" -u sshtunnels -i /home/sshtunnels/.ssh/2any \
	  "$sshsite" "$fwdhost" "$fwdport" &
  done
