#!/bin/sh

cmd=$0

[ $# = 0 ] || { echo "Usage: $cmd" >&2; exit 2; }

set :5 -name "vnc:5@$HOST" -depth 24 -geometry 1400x1050

fontpath=unix/:7100
for fonttop in /usr/X11R6/lib/X11/fonts
do  for fontdir in $fonttop/*
    do
	if [ -f "$fontdir/fonts.dir" ]
	then
	    fontpath=$fontpath,$fontdir
	fi
    done
done

set-x vncserver $args -alwaysshared ## -fp unix:7100 ## "$fontpath"
