#!/bin/sh

num=:6
case $HOST@$SYSTEMID in
    zapff@cisra|amadeus@home)
		;;
    *)		echo "$0: nothing to rig for $HOST@$SYSTEMID" >&2
		exit 1
		;;
esac

case $1 in
    :*)	num=$1; shift ;;
esac

fontpath=
sep=
for fonttop in /usr/X11R6/lib/X11/fonts
do  for fontdir in $fonttop/*
    do
	if [ -f "$fontdir/fonts.dir" ]
	then
	    fontpath=$fontpath$sep$fontdir
	    sep=,
	fi
    done
done

set -x

lock -1 "vnc-$HOST$num@$SYSTEMID" \
	vnc "$num" \
		-depth 16 \
		-geometry 1600x1200 \
		-name "$HOST$num @ $SYSTEMID" \
		-alwaysshared \
		-localhost \
		-fp "$fontpath"

