#!/bin/sh
#
# Remove a background image altogether.
# See also nbg and bglist.
#	- Cameron Simpson <cs@zip.com.au>
#

file=`lbg -1`
if [ -s "$file" ] && { ls -ld "$file"; ask "rm $file"; }
then  rm -f "$file"
      sbg
fi
