#!/bin/sh
#
# Remote netcat.
#	- Cameron Simpson <cs@zip.com.au> 11jul2004
#

location=
keyfile=
remote=
target=
port=

cmd=`basename "$0"`
usage="Usage: $cmd [-l location] [-i keyfile] remote target port
	-i keyfile	Specify keyfile to use.
	-l location	Don't both with remote if \$LOCATION matches this."

badopts=

while :
do
  case $1 in
    -i)	keyfile=$2; shift ;;
    -l)	location=$2; shift ;;
    --)	shift; break ;;
    -?*)echo "$cmd: unrecognised option: $1" >&2; badopts=1 ;;
    *)	break ;;
  esac
  shift
done

if [ $# = 3 ]
then
    remote=$1 target=$2 port=$3
    shift; shift; shift
else
    echo "$cmd: expected: remote target port, found: $*" >&2
    badopts=1
fi

if [ -n "$keyfile" ] && [ ! -s "$keyfile" ]
then
    echo "$cmd: no keyfile: $keyfile" >&2
    badopts=1
fi

[ $badopts ] && { echo "$usage" >&2; exit 2; }

nccmd="exec nc $target $port"

if [ -n "$location" ] && [ "x$location" = "x$LOCATION" ]
then
    set sh -c "$nccmd"
else
    set -- "$remote" "exec nc $target $port"
    [ -n "$keyfile" ] && set -- -i "$keyfile" "$@"
    set -- sshb "$@"
    [ -n "$keyfile" ] && set -- no-ssh-agent "$@"
fi

set -x
exec "$@"
