#!/bin/sh
#
# Bundle up files in a mail spool.
#	- Cameron Simpson <cs@zip.com.au> 11feb1998
#
# Use catmaildir and gzip instead of tar. - cameron 27mar2000
#

cmd=`basename "$0"`

archdir=${MAILDIR:-$HOME/private/mail}/ARCHIVED
delay=14

usage="Usage: $cmd [-d archdir] [delay] dirs...
	-d archdir	Where to put archives. Default: $archdir
	delay		Age of items to archive in days. Default: $delay"

case $1 in
    -d)	archdir=$2; shift; shift ;;
esac

case $1 in
    [1-9]*)	delay=$1; shift ;;
esac

case "$archdir" in
    /*)	;;
    *) archdir=`pwd`/$archdir || exit $? ;;
esac

xit=0
for maildir
do  (
      cd "$maildir" || exit $?
      today=`basename "$maildir"`-`daycode`

      pwd; set -x

      # create archive
      mkdir "$today" || exit $?
      find . -type d -name "$today" -prune -o -type f -name '[1-9]*' -mtime "+$delay" -print \
      | xxargs mrg "$today/."
      rmdir "$today" 2>/dev/null && exit 0

      arch="$archdir/$today.um.gz"
      if [ -s "$arch" ]
      then
	echo "$cmd: $arch already exists" >&2
	exit 1
      else
	if catmaildir "$today" >"$arch" \
	&& [ -s "$arch" ] \
	&& filteredit "$arch" gzip -v
	then
	  rmr "$today"
	else
	  rm -f "$arch"
	  exit 1
	fi
      fi
    ) || xit=1
done

exit $xit
