#!/bin/sh
#
# Roll job times over. Run a report to stdout.
#	- Cameron Simpson <cs@zip.com.au> 29jul2003
#

scale=1.0
dir=timer

cmd=`basename "$0"`
usage="Usage: $cmd [-d dir] [scale]"

[ "x$1" = x-d ] && { dir=$2; shift; shift; }

case $1 in
  [0-9]*.[0-9]*) scale=$1; shift ;;
esac

[ $# = 0 ] || { echo "$usage" >&2; exit 2; }

wkdir=$HOME/var/idsets
cd "$wkdir" || exit 1

current=$wkdir/timer
[ -d "$current/." ] || { echo "$cmd: no current timers! ($current)" >&2; exit 1; }

saved=$current-`daycode`

[ -d "$saved/." ] && { echo "$cmd: $saved: already exists" >&2; exit 1; }

oldjob=`job`	|| { echo "$cmd: can't find current job" >&2; exit 1; }
job timekeeping	|| { echo "$cmd: can't switch to \"timekeeping\"" >&2; exit 1; }

cpdir "$current" "$saved" || exit 1

jobreport -d "$dir" "$scale"
for total in "$current/"*/total
do  [ -s "$total" ] && echo 0 >"$total"
done

job "$oldjob"
