#!/bin/sh -u
#
# Get or set the global/default root backdrop.
#	- Cameron Simpson <cs@zip.com.au> 20nov2000
#

cmd=$0
usage="Usage: $cmd [-] [imagefiles...]
	-	Do nothing. Recite fvwm actions."

badopts=

dasharg=
[ $# -gt 0 ] && [ "x$1" = x-  ] && { dasharg=$1; shift; }

[ $# = 0 ] && exec desktop 1 rootbg
exec deskbg $dasharg -d 1 "$@"
