#!/bin/sh
#
# Set the root backdrop.
#	- Cameron Simpson <cs@zip.com.au> 20nov2000
#

: ${LOGDIR:=$HOME/var/log}

cmd=$0
usage="Usage: $cmd [-s] [imagefile]
	-s	Synchronous."

[ -n "$DISPLAY" ] || { echo "$cmd: no \$DISPLAY!" >&2; exit 1; }

##con echo "$cmd $*"

opts=
sync=
perdesk=

badopts=
while :
do  case $1 in
	-s)	sync=1 opts="$opts -s" ;;
	--)	shift; break ;;
	-?*)	echo "$cmd: unrecognised option: $1" >&2
		badopts=1
		;;
	*)	break ;;
    esac
    shift
done

if [ $# = 0 ]
then
  bg=`lastvalue "rootbg-$HOST"` && [ -n "$bg" ] && [ -s "$bg" ] && echo "$bg"
  exit
fi

imagefile=$1; shift
[ $# = 0 ] || { echo "$cmd: extra arguments: $*" >&2
		badopts=1
	      }

[ $badopts ] && { echo "$usage" >&2; exit 2; }

isfile=1
case "$imagefile" in
  http://*)
    # one argument which is an URL
    exec withurl -C "$imagefile" "$0" $opts
    ;;
  X:* | - | *:- | \|* )
    # one argument which is a GraphicsMagick-ish name
    isfile=
    ;;
esac

if [ "$isfile" ]
then
  case "$imagefile" in
    /*) ;; *) imagefile=`pwd`/$imagefile ;;
  esac
fi

(
  (
    lastvalue rootbg "$rootbg"
    lastvalue "rootbg-$HOST" "$rootbg"
  ) &

  wall=`mkwall "$imagefile"` || exit 1
  fvwm-root --retain-pixmap "$wall" \
  && fvwmcmd \
       'setenv XSESSIONBG pixmap' \
       "ColorSet 1023 AspectPixmap $wall"
  exit
) &

[ $sync ] && wait
exit 0
