#!/bin/sh
#
# Make/attach a logged screened root session on a host.
#	- Cameron Simpson <cs@zip.com.au> 20may2002
#

cmd=$0
usage="Usage: $cmd [-N] [+N] [-X] hostname
       $cmd hostname command..."

badopts=
ssh=sshop1
sshopts=

newflag=-N

while :
do  case $1 in
      -X)	sshopts="$sshopts $1" ;;
      -N)	newflag=-N ;;
      +N)	newflag= ;;
      --)	shift; break ;;
      -?*)	echo "$cmd: unrecognised option: $1" >&2
		badopts=1
		;;
      *)	break ;;
    esac
    shift
done

if [ $# = 0 ]
then  echo "$cmd: missing hostname" >&2; badopts=1
else  host=$1; shift
fi

case "$host" in
    sunny|ivory)	ssh=ssho ;;
esac

[ $badopts ] && { echo "$usage" >&2; exit 2; }

[ $# -gt 0 ] && exec "$ssh" $sshopts "root@$host" "$*"

ext=

session=root@$host$ext

exec term -n "#$session" \
	scr -N "$session" \
	logscript "$session" \
	"$ssh" -t $sshopts "root@$host" \
		'. /etc/profile
		 [ -s /opt/config/shell/env-basic ] && . /opt/config/shell/env-basic
		 [ -f $HOME/.profile ] && . $HOME/.profile
		 TERM=vt100
		 PATH=$PATH:/opt/css/bin:/u/network/bin
		 MANPATH=$MANPATH:/opt/css/man:/u/network/man
		 PERL5LIB=${PERL5LIB:+"$PERL5LIB:"}/u/network/lib
		 export TERM PATH MANPATH PERL5LIB
		 [ -f /bin/zsh ] && { SHELL=/bin/zsh; export SHELL; }
		 exec $SHELL'
