#!/bin/sh
#
# Make/attach a logged screened root session on a host.
#	- Cameron Simpson <cs@zip.com.au> 20may2002
#

cmd=$0
usage="Usage: $cmd [-m msg] hostname"

badopts=
msg=

while :
do  case $1 in
      -m)	msg=$2; shift ;;
      --)	shift; break ;;
      -?*)	echo "$cmd: unrecognised option: $1" >&2
		badopts=1
		;;
      *)	break ;;
    esac
    shift
done

if [ $# = 0 ]
then  echo "$cmd: missing hostname" >&2; badopts=1
else  host=$1; shift
fi

[ $badopts ] && { echo "$usage" >&2; exit 2; }

[ $# -gt 0 ] && exec "$ssh" $sshopts "root@$host" "$*"

[ -z "$BUGSYSTEMS" ] \
|| [ -n "$msg" ] \
|| msg=`readbugline` \
|| { echo "$cmd: empty message rejected" >&2; exit 1; }

exec term -e logscript -u -m "$msg" ssho -v -x "root@$host"
