#!/bin/sh
#
# Make/attach a logged screened root session on a host.
#	- Cameron Simpson <cs@zip.com.au> 20may2002
#

cmd=$0
usage="Usage: $cmd [-N] hostname
       $cmd hostname command..."

badopts=
ssh=sshop1

newflag=-N
[ "x$1" = x-N ] && { newflag=$1; shift; }
[ "x$1" = x+N ] && { newflag=; shift; }

if [ $# = 0 ]
then  echo "$cmd: missing hostname" >&2; badopts=1
else  host=$1; shift
fi

case "$host" in
    sunny|ivory)	ssh=ssho ;;
esac

[ $badopts ] && { echo "$usage" >&2; exit 2; }

[ $# -gt 0 ] && exec "$ssh" "root@$host" "$*"

ext=

session=root@$host$ext

exec term -n "#$session" \
	scr -N "$session" \
	logscript "$session" \
	"$ssh" -t "root@$host" '. /etc/profile; [ -f $HOME/.profile ] && . $HOME/.profile; TERM=vt100; export TERM; [ -f /bin/zsh ] && { SHELL=/bin/zsh; export SHELL; }; exec $SHELL'
