#!/bin/sh -u
#
# Run a regular fetchmail. Pulled from rigfetchmail.
# Why not "fetchmail --daemon"? Because I want to tune options between
# runs, from outside.
#	- Cameron Simpson <cs@zip.com.au> 31dec2003
#

: ${LOGDIR:=$HOME/var/log}

trace=set-x

cmd=$0
usage="Usage: $cmd [fetchmail-options...]"

mypid=$$
while :
do
  eval "`syncenv $mypid`"
  : ${FM_LOGFILE:=$LOGDIR/fetchmail}
  $trace dofetchmail ${1+"$@"}
  echo "`date`: fetchmail done" | tee -a "$FM_LOGFILE" >&2

  eval "`syncenv $mypid`"
  : ${FM_LOGFILE:=$LOGDIR/fetchmail}
  killpidfile getmail_flush.pid
  fmdelay=${FM_DELAY:=300}
  bgproc -s -p fetchmail_sleep.pid $trace sleep "$fmdelay"
done
