#!/bin/sh -u
#
# Run a regular getmail, as for runfetchmail.
#	- Cameron Simpson <cs@zip.com.au> 18mar2006
#

: ${LOGDIR:=$HOME/var/log}

trace=set-x

cmd=$0
usage="Usage: $cmd [getmail-options...]"

mypid=$$
while :
do
  eval "`syncenv $mypid`"
  : ${GM_LOGFILE:=$LOGDIR/getmail}
  $trace dogetmail ${1+"$@"} >>"$GM_LOGFILE" 2>&1

  eval "`syncenv $mypid`"
  : ${GM_LOGFILE:=$LOGDIR/getmail}
  : ${GM_DELAY:=300}
  ( if [ "x$GM_DELAY" = x0 ]
    then  set -- pause
    else  set -- sleep "$GM_DELAY"
    fi
    exec bgproc -s -p getmail_sleep.pid "$@"
  )
done
