#!/bin/sh
#
# Create a temporary xpm file and set the background of an rxvt.
#	- Cameron Simpson <cs@zip.com.au> 31aug2000
#

# exit 0	## for a moment

cmd=`basename "$0"`
usage="Usage: $cmd imagefile"

badopts=

if [ $# -gt 0 ]
then
    if [ -f "$1" -a -s "$1" ]
    then
	src=$1; shift
	[ $# = 0 ] || { echo "$usage" >&2; exit 2; }
    else
	[ $# = 0 ] && set .
    fi
fi

if [ -z "$src" ]
then
    src=`bglist -r -n 1 "$@"`
    [ -n "$src" ] || { echo "$cmd: no INDEX entries matching: $*" >&2
		       exit 1
		     }
fi

# dropped "-d 0.6"
2png -s tty "$src" xpm2rxvt
