#!/bin/sh
#
# Create a temporary xpm file and set the background of an rxvt.
#	- Cameron Simpson <cs@zip.com.au> 31aug2000
#

# exit 0	## for a moment

cmd=`basename "$0"`
usage="Usage: $cmd [-l logfile] [{ptns...|imagefile}]"

badopts=

logf=$RXVTBGLOG
case $1 in
  -l)	logf=$2; shift; shift ;;
esac

if [ $# -gt 0 ]
then
    if [ -f "$1" -a -s "$1" ]
    then
	src=$1; shift
	[ $# = 0 ] || { echo "$usage" >&2; exit 2; }
    else
	[ $# = 0 ] && set .
    fi
fi

if [ -z "$src" ]
then
    src=`bglist -r -n 1 "$@"`
    [ -n "$src" ] || { echo "$cmd: no INDEX entries matching: $*" >&2
		       exit 1
		     }
fi

[ -n "$logf" ] || logf=`rxvtbglog`
[ -s "$logf" ] || ( # some shells bail here on failure
		    exec 2>/dev/null
		    echo "`date` pid=$$" >>"$logf"
		  )

# dropped "-d 0.6"
2xpm -s tty "$src" xpm2rxvt
[ -n "$logf" ] && [ -w "$logf" ] && echo "$src" >>"$logf"
