#!/bin/sh
#
# General wrapper for various shells to tweak SHELL to match.
#	- Cameron Simpson <cs@zip.com.au> 28feb1999
#

cmd=`basename "$0"`
shell=$cmd
usage="Usage: $cmd [args...]
	Exec selfnamed shell with \$SHELL set suitably.
	If the name is \"shell\", exec current \$SHELL with args."

case $shell-$SYSTEMID-$ARCH in
    shell-*)		[ -x "$SHELL" ] || { SHELL=/bin/sh; export SHELL; }
			exec "$SHELL" ${1+"$@"} ;;
    sh-*)		shell=/bin/sh ;;
    bash-*-sun.*.solaris) shell=/opt/bin/bash ;;
    bash-*)		shell=/bin/bash ;;
    ae-*)		shell=$HOME/bin/$ARCH/ae ;;
    ksh-*)		shell=/bin/ksh ;;
    *)			echo "$shell: no knowledge for $shell-$SYSTEMID-$ARCH" >&2
			exit 1
			;;
esac

[ -x "$shell" ] || shell=/bin/sh

# ugly hack to make shellrc work
SHELL=$shell; export SHELL

set -x
exec "$shell" ${1+"$@"}
