#!/bin/sh -ue
#
# Quick mount of PC share for archiving.
#	- Cameron Simpson <cs@zip.com.au> 10jan2003
#

mnt=
needdir=
fstype=cifs
user=`who am i | sed -e 's/[ 	].*//' -e 's/.*!//'` || user=${USER:-${LOGNAME:=`id -un`}}
: ${WORKGROUP:=${SYSTEMID:=WORKGROUP}}

cmd=`basename "$0"`
usage="Usage: $cmd [-t {cifs|smbfs}] [-d dir] [-u user] [-w workgroup] //pc/share"

badopts=

while [ $# -gt 0 ]
do
  case $1 in
    -d)	mnt=$2; shift ;;
    -u)	user=$2; shift ;;
    -w)	WORKGROUP=$2; shift ;;
    --)	shift; break ;;
    -?*)echo "$cmd: unrecognised option: $1" >&2; badopts=1 ;;
    *)	break ;;
  esac
  shift
done

[ -n "$user" ] \
	|| { echo "$cmd: can't guess user and no -u option" >&2
	     badopts=1
	   }
[ -n "$WORKGROUP" ] \
	|| { echo "$cmd: can't guess workgroup and no -w option" >&2
	     badopts=1
	   }

if [ $# = 0 ]
then
  echo "$cmd: missing //pc/share" >&2
  badopts=1
else
  share=$1; shift
  case "$share" in
    //*/*) [ -n "$mnt" ] || { mnt=/mnt`echo "$share" | tr -s / -`; needdir=1; } ;;
    *)	   echo "$cmd: bad PC share \"$share\", should look like //pc/share" >&2
	   badopts=1
	   ;;
  esac
  [ $# = 0 ] || { echo "$cmd: extra arguments: $*" >&2
		  badopts=1
		}
fi

[ $badopts ] && { echo "$usage" >&2; exit 2; }

set -x
[ $needdir ] && { needdir "$mnt" || exit 1; }
case $fstype in
  smbfs)
    mount -t smbfs -o "username=$user,workgroup=$WORKGROUP,uid=$user,fmask=644,dmask=755" "$share" "$mnt" ;;
  cifs)
    mount -t cifs -o "user=$user,workgroup=$WORKGROUP,uid=$user,file_mode=0644,dir_mode=0755" "$share" "$mnt" ;;
  *)
    echo "$cmd: unsupported -t option: $fstype" >&2
    exit 2
    ;;
esac
L "$mnt"
