#!/bin/sh -u
doit=1
[ $# -gt 0 ] && [ "x$1" = x-n ] && { doit=; shift; }
genv ZAP_POSTMATCH ZAP_PREMATCH SQUID_PEERS MKSQUIDPEERS_OPTS
eval "`syncenv -`"
[ -z "$doit" ] || { set -x; exec rigsquid_redirect ${1+"$@"}; }
