#!/usr/bin/perl
#
# Coalesce adjacent blank lines. Detab. Strip trailing whitespace.
# Nothing that tohers haven't done before me. Just can't find it.
#	- Cameron Simpson <cs@zip.com.au> 09may2002
#

use cs::Misc;

$hadblank=0;
while(defined($_=<>))
{ chomp;
  s/\s+$//;
  $_=detab($_);

  if (length)
  { print "\n" if $hadblank;
    $hadblank=0;
    $_.="\n";
    print;
  }
  elsif ($hadblank)
  {}
  else
  { $hadblank=1;
  }
}
