#!/bin/sh -u
#
# Kick of a port forward ssh.
#	- Cameron Simpson <cs@zip.com.au> 18jan2006
#

cf=$HOME/rc/ssh/config-pf
delay=120

[ $# -gt 0 ] || set -- $SSHPF_DFLT

set -x
for host
do
  ssh -f -F "$cf" "$host" "while echo .; do sleep $delay; done" >/dev/null
done
