#!/bin/sh -u
#
# Kick of a port forward ssh.
#	- Cameron Simpson <cs@zip.com.au> 18jan2006
#

: ${VARRUN:=$HOME/var/run}

cf=$HOME/rc/ssh/config-pf
delay=120

[ $# -gt 0 ] || set -- $SSHPF_DFLT

uid=`id -u` || exit 1
if [ "x$uid" != x0 ]
then
  qvarrun=`shqstr "$VARRUN"`
  qhome=`shqstr "$HOME"`
  qcmd=`shqstr "$0" ${1+"$@"}`
  shcmd=". /opt/css/env.sh; HOME=$qhome; VARRUN=$qvarrun; export HOME VARRUN; exec $qcmd"
  set -x
  exec sudo sh -c "$shcmd"
fi

pidfile=$VARRUN/sshpf.pid

killpidfile -w "$pidfile"
>"$pidfile" || :
for host
do
  while printf " " && sleep "$delay"; do :; done \
  | ( exec 3<&0
      pfx "$host" sshb -F "$cf" "$host" 'exec cat' >/dev/null <&3 3<&- &
      echo $! >>"$pidfile"
    ) &
done
