#!/bin/sh -u
#
# Kick of a port forward ssh.
#	- Cameron Simpson <cs@zip.com.au> 18jan2006
#

: ${OPTCSS:=/opt/css}
: ${VARRUN:=$HOME/var/run}

cf=$HOME/rc/ssh/config-pf
delay=120

[ $# -gt 0 ] || set -- $SSHPF_DFLT

uid=`id -u` || exit 1
if [ "x$uid" != x0 ]
then
  qcmd=`shqstr "$0" ${1+"$@"}`
  set -x
  exec sudo env "OPTCSS=$OPTCSS" "HOME=$HOME" "VARRUN=$VARRUN" sh -c ". \"\$OPTCSS/env.sh\"; exec $qcmd"
fi

pidfile=$VARRUN/sshpf.pid

killpidfile -w "$pidfile"
>"$pidfile" || :
for host
do
  while printf " " && sleep "$delay"; do :; done \
  | ( exec 3<&0
      pfx "$host" sshb -F "$cf" "$host" 'exec cat' >/dev/null <&3 3<&- &
      echo $! >>"$pidfile"
    ) &
done
