#!/bin/sh
#
# Stash the GnuPG environment state variables, as for stash-ssh-agent.
#	- Cameron Simpson <cs@zip.com.au> 30mar2005
#

cmd=$0
usage="Usage: $cmd [{-|statefile}]"

[ -n "$GPG_AGENT_INFO" ] || { echo "$cmd: no \$GPG_AGENT_INFO" >&2; exit 1; }

statefile=

badopts=

[ $# = 0 ] || { statefile=$1; shift; }

[ $# = 0 ] || { echo "$cmd: extra arguments: $*" >&2; badopts=1; }

[ $badopts ] && { echo "$usage" >&2; exit 2; }

[ -n "$statefile" ] || statefile=`gpg-agent-statefile` || exit 1

[ "x$statefile" = x- ] || exec >"$statefile"
echo "GPG_AGENT_INFO='$GPG_AGENT_INFO'; export GPG_AGENT_INFO;" \
|| { [ "x$statefile" = x- ] || rm -f "$statefile"; exit 1; }

[ "x$statefile" = x- ] && exit 0
exec chmod a+rx "$statefile"
