#!/bin/sh
#
# Copy a few rc files into the EZOS web tree.
#	- Cameron Simpson <cs@zip.com.au>
#

ezos=$HOME/@/ezos

set -x
exec rsync -avHP --delete --delete-excluded \
	--exclude=CVS/ \
	--include='/myke' \
	--include='/myke/*' \
	--include='/perl' \
	--include='/perl/cs' \
	--exclude='/perl/*' \
	--include='/x11' \
	--include='/x11/session' \
	--include='/x11/xenv.sh' \
	--include='/x11/fvwm' \
	--include='/x11/fvwm/rc' \
	--exclude='*' \
	$HOME/rc/. $ezos/html/cs/rc/.
