#!/bin/sh
#
# Update my sourceforge projects.
#	- Cameron Simpson <cs@zip.com.au> 23oct2002
#

cmd=`basename "$0"`
usage="Usage: $cmd [address]"

zapdir=$HOME/@/adzapper.sf

dotag=
dopost=
if [ $# = 0 ]
then
    if ask "Post to everyupdate"
    then
	addr=adzapper-everyupdate@lists.sourceforge.net
	dotag=1
	dopost=1
    fi
else
    addr=$1; shift
    dopost=1
    [ $# = 0 ] || { echo "$cmd: extra arguments after address: $*" >&2
		    exit 2
		  }
fi

set -x
cd $zapdir/html || exit 1
if ask "Run myke"
then
    myke _all || exit 1
fi

rsync -avHPW --delete --exclude=CVS/ $zapdir/html/. sf:adzapper/htdocs/.

if [ $dopost ]
then
    cd $zapdir/html/scripts || exit 1
    ( cd .. || exit 1
      echo New script attached.
      echo Diff since last public sync:
      echo
      cvs diff -r SYNCSF squid_redirect
      [ $dotag ] && cvs tag -F SYNCSF
    ) | mfiles "$addr" squid_redirect
fi
