#!/bin/sh
set -x
ezos=$HOME/@/ezos

# copy active CGIs to live cgi dir
rsync -avHP --delete --delete-excluded --exclude=CVS/ \
	--include=.cgienv.sh \
	--include=debug.cgi \
	--include=search.cgi \
	--include=search.cgi-pl \
	--exclude='*' \
	$HOME/bins/cgi-bin/. $ezos/cgi-bin/.
