#!/bin/sh
#
# Update my ezoshosting web site.
#	- Cameron Simpson <cs@zip.com.au> 11jan2003

needhost $HOMEHOST@home

ezos=$HOME/@/ezos
ezoscgi=$ezos/cgi-bin
ezoshtml=$ezos/html
ezoscss=$ezoshtml/cs/css

set -x

syncezos-rc

rsync -avHPW --delete \
		--exclude=CVS/ \
		--include=/cs --exclude=/cs/test/ \
		--include=/fay \
		--exclude=/* $ezoshtml/. ezos:public_html/.

##syncezos-cgi
##rsync -avHPW --delete --exclude=CVS/ $ezoscgi/. ezos:cgi-bin/.

putacc ezos
