#!/bin/sh
#
# Propagate the adzap script and pattern file.
#	- Cameron Simpson <cs@zip.com.au> 21apr1999
#

webdir=$HOME/public/adzap

script=scripts/squid_redirect
base=http://www.zip.com.au/~cs/adzap

cd "$webdir" || exit 1
pwd

set -u

news=`readdottext`

dodiff=1
commit=
[ $# = 0 ] && \
    { dodiff=1
      commit=1

      while read addr
      do  case "$addr" in
		''|\#*)	;;
		*)	set ${1+"$@"} "$addr" ;;
	  esac
      done < rc/users
    }

changetmp=/tmp/change.$$

saved=patterns-`datecode`.gz
savedpl=script-`datecode`.gz

if [ $commit ]
then
    if gzip -v -9 <rc/patterns >"$saved" \
    && gzip -v -9 <"$script" >"$savedpl"
    then 
	  PGPPASS=${PGPPASS-""}
	  [ -n "$PGPPASS" ] \
	  || { PGPPASS=`nread 'Enter PGP passphrase'` \
	    && [ -n "$PGPPASS" ]
	     } \
	  || { echo "$0: can't get \$PGPPASS" >&2; exit 1; }
	  export PGPPASS
	  if pgp -bsa "$saved" \
	  && pgp -bsa "$savedpl"
	  then  pgpsig=$saved.sig
		pgpplsig=$savedpl.sig
		mv "$saved.asc" "$pgpsig"
		mv "$savedpl.asc" "$pgpplsig"
	  else  echo "Signature fails, aborting." >&2
		rm -f "$saved"
		exit 1
	  fi
    else  echo "Release snapshot fails, aborting." >&2
	  exit 1
    fi
    chmod a+r "$saved" "$pgpsig"
    chmod a+r "$savedpl" "$pgpplsig"
fi

#[ $dodiff ] && { diff=$saved.diff
#		 cvs diff -r LAST rc/patterns >"$diff"
#		 chmod a+r "$diff"
#		 mv "$diff" "$webdir/."
#	       }

synczip

for user
do  echo "$user..."
    [ -n "$news" ] && \
	( echo "Update Synopsis:"
	  echo "$news"
	  echo
	  echo "The changelog is here:"
	  echo "	$base/cvslog.html"
	  echo

	  if [ $commit ]
	  then
	      echo "The source patterns for this relase may be found here, along with a PGP signature:"
	      echo "	$base/$saved"
	      echo "	$base/$pgpsig"
	      echo
	      echo "The script for this relase may be found here, along with a PGP signature:"
	      echo "	$base/$savedpl"
	      echo "	$base/$pgpplsig"
	      echo
	  fi
	  cat update-instructions.txt
	  echo
	  echo "Cheers,"
	  cat $HOME/rc/mail/signature
        ) | mailsubj -s 'synopsis of adzap update' "$user"
    mfiles "$user" "$script" </dev/null
done

[ $commit ] && cvs tag -F LAST

rm -f "$changetmp"
