#!/bin/sh

needhost amadeus@home kaper@cisra || exit 1

[ $# = 0 ] || exec syncstuff @newt "$@"

pfx small syncsmall @newt &
for d in s cvs ## mail im
do  pfx $d syncstuff @newt there/cameron@cskk.homeip.net/$d &
done

wait
