#!/bin/sh
#
# Rsync my account from one place to another.
# Usually I use putacc to call this, but occasionally getacc.
#	- Cameron Simpson <cs@zip.com.au> 29jun2004
#

cmd=$0
usage="Usage: $cmd from to"

syncset=acc

[ $# = 2 ] || { echo "$usage" >&2; exit 2; }
from=$1 to=$2

case "$syncset" in
  /* | ./* | ../* ) ;;
  *)  syncset=$HOME/rc/sync/$syncset ;;
esac

cd
pwd

set -x
exec \
  rsync -rlptHvPC --delete --exclude=CVS/ \
	"--include-from=$syncset" \
	"$from." "$to."
