#!/bin/sh
#
# Propagate the adzap script and pattern file.
#	- Cameron Simpson <cs@zip.com.au> 21apr1999
#

: ${TMPDIR:=/tmp}

ask "REALLY POST A MAJOR ANNOUNCEMENT" || exit 1

webdir=$HOME/@/adzapper.sf/html
script=scripts/squid_redirect
base=http://adzapper.sourceforge.net

cd "$webdir" || exit 1
pwd
myke || exit 1

set -u

tmpf=$TMPDIR/adzap$$
echo "Enter release announcement." >"$tmpf"
while :
do
  ${EDITOR:-vi} "$tmpf"
  cat "$tmpf"
  ask Ok to release && break
  ask Abort && exit 1
done
news=`cat "$tmpf"`

dodiff=1
commit=
if [ $# = 0 ]
then
    dodiff=1
    commit=1
    set adzapper-announce@lists.sourceforge.net
fi

changetmp=$TMPDIR/change.$$

saved=patterns-`datecode`.gz
savedpl=script-`datecode`.gz

if [ $commit ]
then
    if gzip -v -9 <rc/patterns >"$saved" \
    && gzip -v -9 <"$script" >"$savedpl"
    then 
	  PGPPASS=${PGPPASS-""}
	  [ -n "$PGPPASS" ] \
	  || { PGPPASS=`nread 'Enter PGP passphrase'` \
	    && [ -n "$PGPPASS" ]
	     } \
	  || { echo "$0: can't get \$PGPPASS" >&2; exit 1; }
	  export PGPPASS
	  if pgp -bsa "$saved" \
	  && pgp -bsa "$savedpl"
	  then  pgpsig=$saved.sig
		pgpplsig=$savedpl.sig
		mv "$saved.asc" "$pgpsig"
		mv "$savedpl.asc" "$pgpplsig"
	  else  echo "Signature fails, aborting." >&2
		rm -f "$saved"
		exit 1
	  fi
    else  echo "Release snapshot fails, aborting." >&2
	  exit 1
    fi
    chmod a+r "$saved" "$pgpsig"
    chmod a+r "$savedpl" "$pgpplsig"
fi

[ $dodiff ] && { diff=$saved.diff
		 cvs diff -r LAST rc/patterns >"$diff"
		 chmod a+r "$diff"
	       }

syncsf

for user
do  echo "$user..."
    [ -n "$news" ] && \
	( echo "Update Synopsis:"
	  echo "$news"
	  echo
	  echo "The changelog is here:"
	  echo "	$base/cvslog.html"
	  echo

	  if [ $commit ]
	  then
	      echo "The source patterns for this relase may be found here, along with a PGP signature:"
	      echo "	$base/$saved"
	      echo "	$base/$pgpsig"
	      echo
	      echo "The script for this relase may be found here, along with a PGP signature:"
	      echo "	$base/$savedpl"
	      echo "	$base/$pgpplsig"
	      echo
	  fi
	  cat update-instructions.txt
	  echo
	  echo "Cheers,"
	  cat $HOME/rc/mail/signature
        ) | mutt -s 'adzap update' -a "$script" "$user"
done

[ $commit ] && cvs tag -F LAST

rm -f "$changetmp"
