#!/bin/sh -u
#
# Emit output to re-source the environment files if they've been updated.
# Have to do them all if any are new because of ordering.
#	- Cameron Simpson <cs@zip.com.au> 25dec2004
#

: ${ENVFILES:="/etc/rc.mobile/env.sh $HOME/var/env.sh"}
: ${TMPDIR:=/tmp}

cmd=$0
usage="Usage: $cmd refpid [command [command-args...]]"

badopts=

if [ $# = 0 ]
then
    echo "$cmd: missing refpid" >&2
    badopts=1
else
    refpid=$1
    shift
fi

[ $badopts ] && { echo "$usage" >&2; exit 2; }

if [ "x$refpid" = x- ]
then  reffile=
else  reffile=$TMPDIR/env$refpid
fi
if [ $# -gt 0 ]
then
    eval `"$0" "$refpid"`
    exec "$@"
fi

envfiles=
for envpath in $ENVFILES
do
  if [ -d "$envpath/." ]
  then
    for envfile in "$envpath"/*
    do
      [ -f "$envfile" -a -s "$envfile" ] && envfiles="$envfiles $envfile"
    done
  else
    [ -f "$envpath" -a -s "$envpath" ] && envfiles="$envfiles $envpath"
  fi
done

if [ -n "$reffile" ]
then
  new=
  for testfile in "$0" $envfiles
  do
    if [ "$testfile" -nt "$reffile" ]
    then
      new=1
      break
    fi
  done
else
  new=1
fi

if [ $new ]
then
  [ -n "$reffile" ] && touch "$reffile"
  cat $envfiles
  echo "PATH='$PATH'; export PATH"	# just in case
fi
