#!/bin/sh

cmd=$0
usage="Usage: $cmd [user@host [syncstuff-options...]]"

needhost "$HOMEHOST@$SYSTEMID" || exit 1

if [ $# = 0 ]
then
    syncsmall_where=
    eval `winclausevars $HOME/rc/syncsmall $HOST@$SYSTEMID syncsmall`
    [ -n "$syncsmall_where" ] || { echo "$cmd: no default syncs for $HOST@$SYSTEMID" >&2; exit 1; }

    xit=0
    for h in $syncsmall_where
    do  ( set -x; exec syncsmall "$h" ) || xit=1
    done
    exit $xit
fi

case $1 in
    @?*)	who=`expr "x$1" : 'x@\(.*\)'`; shift ;;
    ?*@?*)	who=$1; shift ;;
    *)		echo "$cmd: missing user@host" >&2; exit 2 ;;
esac

set -x
exec syncstuff @small -o "to=$who" ${1+"$@"}
