#!/bin/sh

cmd=$0
usage="Usage: $cmd [user@host [syncstuff-options...]]"

if [ $# = 0 ]
then
    needhost kaper@cisra amadeus@home || exit 1
    case $HOST@$SYSTEMID in
      kaper@cisra)	set cameron@agricola cameron@agostino cameron@ivory cameron@upnp cameron@cvs.cgn @tw ;;
      amadeus@home)	set cameron2@alpha @cerebus cameron2@janus @ezos @tw @lexx @moya ;;
      *)	echo "$cmd: $HOST@$SYSTEMID: huh?" >&2; exit 1 ;;
    esac
    for h
    do  (set -x; exec pfx "$h" syncsmall "$h" ) &
    done
    wait
    exit 0
fi

case $1 in
    @?*)	who=`expr "x$1" : 'x@\(.*\)'`; shift ;;
    ?*@?*)	who=$1; shift ;;
    *)		echo "$cmd: missing user@host" >&2; exit 2 ;;
esac

set -x
exec syncstuff @small -o "to=$who" ${1+"$@"}
