#!/bin/sh -u
#
# Tag a stream (or streams) with a prefix.
#	- Cameron Simpson <cs@zip.com.au> 18may1999
#

usage="Usage: $0 fd[,fd...] pfx command [args...]"

[ $# -lt 3 ] && { echo "$usage" >&2; exit 2; }

fds=$1 pfx=$2
shift; shift

sedstr=`shqstr "s^$pfx: "` || exit 1

exec filter_fd "$fds" "exec sed $sedstr" "$@"
