#!/bin/sh
#
# Run a logged script session attached to the specified serial port.
#	- Cameron Simpson <cs@zip.com.au> 17may2002
#

cmd=`basename "$0"`
usage="Usage: $cmd [ttydev]"
[ $# =gt 1 ] && { echo "$usage" >&2; exit 2; }

dev=${1:-${TAP_DEV:-"/dev/ttyS0"}}
case "$dev" in /*) ;; *) dev=/dev/$dev ;; esac

speed=9600
parity=none

dev_=`echo "$dev" | tr / _`
lock=tap$dev_
session=$lock

if locked "$lock"
then
    exec scr "$session"
fi

logdir=${VARLOG:-$HOME/var/log}/tap
logfile=$logdir/$HOST-${dev_}-`datecode`

dl=`echo "$logfile"|entilde`
dlog "start tap $dev >>$dl"

{ echo
  echo "$HOST@$SYSTEMID - $dev"
  date
  echo
} >>"$logfile"

exec \
screen -h 102400 -S "$session" \
	lock "$lock" \
	env "tapoldSHELL=$SHELL" "SHELL=$0-shell" \
		"tapdev=$dev" "tapspeed=$speed" "tapparity=$parity" \
	script -a "$logfile"
