#!/bin/sh
#
# Run a logged script session attached to the specified serial port.
#	- Cameron Simpson <cs@zip.com.au> 17may2002
#

cmd=`basename "$0"`
usage="Usage: $cmd [ttydev]"
[ $# -gt 1 ] && { echo "$usage" >&2; exit 2; }

dev=${1:-${TAP_DEV:-"/dev/ttyS0"}}
case "$dev" in /*) ;; *) dev=/dev/$dev ;; esac

speed=9600
parity=none

dev_=`echo "$dev" | tr -s / _`

lock=tap$dev_
session=$lock

set -x
exec scr "logscript-$dev" set-x logscript "$session" screen "$dev" "$speed,cs8,-ixoff"
