#!/bin/sh
#
# Check the message on stdin to see if it's tracked by a message-id file.
# Exit true if so, false if not. Add this message to the message-id file if
# so in order to track this message's descendants too.
#	- Cameron Simpson <cs@zip.com.au> 16apr2002
#

cmd=$0
usage="Usage: $cmd idfiles... <mailitem"

badopts=

if [ $# = 0 ]
then
  echo "$cmd: missing idfiles" >&2
  badopts=1
fi

[ $badopts ] && { echo "$usage" >&2; exit 2; }

eval `mhdrs -sh | sed 's/^/HDR_/'`
idlist="$HDR_REFERENCES $HDR_IN_REPLY_TO"

[ -z "$idlist" ] && exit 1	# no refs => not in a thread

id="$HDR_MESSAGE_ID"
re='^('`printf '%s\n' "$idlist" | sed 'y/ /|/; s/\./\\\\./g'`')$'

##set -x

xit=1
for idfile
do
  case "$idfile" in
    ./* | /* ) ;;
    *)         idfile=$HOME/var/mail/threads/$idfile ;;
  esac
  [ -f "$idfile" ] || continue
  if egrep "$re" "$idfile" >/dev/null
  then
    echo "$HDR_MESSAGE_ID" >>"$idfile"
    xit=0
  fi
done

exit $xit
