#!/bin/sh
#
# Check the message on stdin to see if it's tracked by a message-id file.
# Exit true if so, false if not. Add this message to the message-id file if
# so in order to track this message's descendants too.
#	- Cameron Simpson <cs@zip.com.au> 16apr2002
#

cmd=$0
usage="Usage: $cmd idfile <mailitem"

badopts=

if [ $# = 0 ]
then  echo "$cmd: missing idfile" >&2; badopts=1
else  idfile=$1; shift
      if [ $# -gt 0 ]
      then
	echo "$cmd: extra arguments after idfile: $*" >&2
	badopts=1
      fi
fi

[ $badopts ] && { echo "$usage" >&2; exit 2; }

eval `mhdrs -sh | sed 's/^/HDR_/'`
set -- $HDR_REFERENCES $HDR_IN_REPLY_TO

[ $# = 0 ] && exit 1	# no refs => not in a thread

id="$HDR_MESSAGE_ID"
re='^('`echo "$*" | tr ' ' '|'`')$'
re=`echo "$re" | sed 's/\./\\\\./g'`

##set -x
egrep "$re" <"$idfile" >/dev/null || exit 1

echo "$HDR_MESSAGE_ID" >>"$idfile"
exit 0
