#!/bin/sh
#
# Emit a template for the named file on stdout.
#	- Cameron Simpson <cs@zip.com.au> 08apr1997
#

cmd=$0

tpltdir=$HOME/rc/tplt

FILE=$1
case $FILE in /*) ;; *) FILE=`pwd`/$FILE ;; esac

BASE=`basename "$FILE"`
PFX=`expr "x$BASE" : 'x\(.*\)\..*'` || PFX=$BASE
FILEDIR=`dirname "$FILE"`
FILEDIR=`cd "$FILEDIR"; pwd`
FILEPATH=$FILEDIR/$BASE

tpltenv=$FILEDIR/.tplt
[ -s "$tpltenv" ] && eval `sed -n 's/^\([A-Z][A-Z_0-9]*\)=.*/&; export \1;/p' "$tpltenv"`

DIRBASE=`basename "$FILEDIR"`
case $FILE in
    /*/scripts/*/*)
	PFX=`expr "x$FILEPATH" : 'x.*/scripts/\(.*\)/.*'`
	;;
    /*/s/java/*)
	classtail=`expr "x$FILEPATH" : 'x.*/s/java/\\(.*\\)/.*'|tr / .`
	JAVABASECLASS=au.com.zip.cs
	[ -n "$classtail" ] && JAVABASECLASS=$JAVABASECLASS.$classtail
	export JAVABASECLASS
	;;
esac

DATESTR=`date|awk '{print $3 $2 $6}'|tr '[A-Z]' '[a-z]'`

[ -n "$MYKEtarget" ] \
	|| [ ! -s Mykefile ] \
	|| MYKEtarget=`sed -n 's/^target.*= *\([^ ]*\).*/\1/p' Mykefile`

export FILE BASE PFX FILEDIR FILEPATH DIRBASE DATESTR MYKEtarget

tplt=
case $FILE in
  $PFX.h)
    tplt=csapp.h
    case "$MYKEtarget" in
      bin)	tplt=csapp.h ;;
      prc)	tplt=prcapp.h ;;
    esac
    ;;
  *.c)
    tplt=csapp.c ;;
  *.*)
    tplt=`expr "x$FILE" : 'x.*\.\(..*\)'`
    ;;
esac

[ -n "$tplt" ] || { echo "$cmd: no template for file $FILE" >&2; exit 1; }

case $tplt in
    /*)	;;
    *)	tplt=$tpltdir/$tplt ;;
esac

[ -s "$tplt" ] || { echo "$cmd: no template: $tplt" >&2; exit 1; }

exec envsub <"$tplt"
