#!/bin/sh -u
#
# =head1 NAME
#
# tracepid - trace a process id
#
# =head1 SYNOPSIS
#
# tracepid pid
#
# =head1 DESCRIPTION
#
# I<tracepid> traces the process specified by I<pid>.
# It calls the OS suitable tracing program
# such as ktrace(1) or strace(1).
#

: ${TMPDIR:=/tmp}

cmd=`basename "$0"` || cmd=$0
usage="Usage: $cmd pid
	pid	Process id to trace."

badopts=

while [ $# -gt 0 ]
do
  case $1 in
    --)	shift; break ;;
    -?*)echo "$cmd: unrecognised option: $1" >&2
	badopts=1
	;;
    *)	break ;;
  esac
  shift
done

if [ $# = 0 ]
then
  echo "$cmd: missing pid" >&2
  badopts=1
else
  pid=$1; shift
  [ $# = 0 ] || { echo "$cmd: extra arguments: $*" >&2; badopts=1; }
fi

[ $badopts ] && { echo "$usage" >&2; exit 2; }

os=`uname -s` || exit 1
case "$os" in
  OpenBSD)
    trfile=/tmp/$cmd.$$
    set -x
    trap 'ktrace -c -f "$trfile"; rm -f "$trfile"' 0 1 2 13 15
    ktrace -t c -f "$trfile" -p "$pid" || exit 1
    kdump -d -t c -f "$trfile" -l
    ;;
  *)
    strace -p "$pid" 2>&1
    ;;
esac

# =head1 SEE ALSO
#
# ktrace(1), strace(1), truss(1)
#
# =head1 AUTHOR
#
# Cameron Simpson E<lt>cs@zip.com.auE<gt>
#
