#!/bin/sh
#
# Take a mail message on stdin, file it in specific mail folders and
# note its message-id in a tracking file.
#	- Cameron Simpson <cs@zip.com.au> 25jul2004
#

: ${TMPDIR:=/tmp}

cmd=$0
usage="Usage: $0 [trackfile...] [+folder...] <mailitem"

[ $# = 0 ] && { echo "$usage" >&2; exit 2; }

tmpf=$TMPDIR/tmi$$
trap 'rm -f "$tmpf"' 0
trap 'rm -f "$tmpf"; exit 1' 1 2 13 15

cat >"$tmpf" || exit 1
exec </dev/null

xit=0

for arg
do
  case "$arg" in
    +*)	filemailitem -auto "$arg" <"$tmpf" || xit=1 ;;
    *)	if [ -f "$arg" ]
	then
	  thread-add "$arg" <"$tmpf" || xit=1
	else
	  echo "$cmd: not a file: $arg" >&2
	  xit=1
	fi
	;;
  esac
done

exit $xit
