#!/bin/sh
#
# Run a truss of a process keeping the last set of output lines in a rolling logfile.
#	- Cameron Simpson <cs@zip.com.au> 03jan2002
#

truss=truss
n=500

cmd=`basename "$0"`
usage="Usage: $cmd [-n nlines] logfile [truss-options...] command [args...]
	-n nlines	Number of lines in log file."

badopts=

if [ "x$1" = x-n ]
then
    n=$2
    shift; shift
fi

if [ $# -lt 1 ]
then  echo "$cmd: missing logfile" >&2; badopts=1
else  logfile=$1; shift
      if [ $# -lt 1 ]
      then  echo "$cmd: missing command" >&2; badopts=1
      fi
fi

[ $badopts ] && { echo "$usage" >&2; exit 2; }

# 0 ==> no limit on log file
if [ "$n" -eq 0 ]
then
    exec "$truss" "$@" 2>"$logfile"
fi

exec 3>&1

"$truss" "$@" 2>&1 1>&3 3>&- \
| while :
  do
    exec >"$logfile"
    count=0
    while [ "$count" -lt "$n" ]
    do  read line || exit 1
	echo "$line"
	count=`expr "$count" + 1`
    done
    rm -f "$logfile.1"
    mv "$logfile" "$logfile.1" \
    || { echo "$cmd: log rotate failed, aborting" >&2
	 exit 1
       }
  done
