#!/bin/sh
# - Cameron Simpson <cs@zip.com.au>
stty sane
stty intr '^?' erase '^h' kill '^x'
stty werase '^w' 2>/dev/null
stty susp '^z' 2>/dev/null
stty dsusp '^y' 2>/dev/null

# make linux consoles behave sanely
case "$ARCH" in
    *.x86.linux)
	case "`tty`" in
	    /dev/console | \
	    /dev/tty[0-9] | \
	    /dev/tty[0-9][0-9] | \
	    /dev/vc/[0-9] | \
	    /dev/vc/[0-9][0-9] )
		loadkeys "$SHDIR/keycodes.linux"
		# and because loadkeys sometimes doesn't ...
		stty intr '^c' erase '^?'
		;;
	esac
	;;
esac

[ $# = 0 ] || exec "$@"
