#!/bin/sh
#
# Emit the terminal size in columns and rows.
#	- Cameron Simpson <cs@zip.com.au> 15oct2000
#

if [ "x$1" = x-p ]
then
    ttysize \
    | { wh=`echo "$FONT_XY"|sed -n 's/\(.*\)x\(.*\)/w=\1 h=\2/p'`
	eval "w=0 h=0; $wh"
	read x y || exit 1
	echo "$x $w * p $y $h * p" | dc | tr '\012' ' '
	echo
      }
    exit 0
fi

stty -a </dev/tty \
| sed -n 's/.* rows \([0-9][0-9]*\); columns \([0-9][0-9]*\).*/\2 \1/p'
