#!/bin/sh
#
# Take a URL-Minder citation and return the relevant page.
#	- Cameron Simpson <cs@zip.com.au> 10feb1999
#

url=$1; shift

( echo "GET $url HTTP/1.0"; echo ) \
	| nc proxy 8080 \
	| sed -n 's/\015//g
		  /^Location:/!d
		  s/^Location: *//p
		  q'
