#!/usr/bin/perl -p
#
# Some email comes in with base64 Subject: lines without the RFC2047 markings.
# Decode and leave raw stuff there too in case of mistake.
#	- Cameron Simpson <cs@zip.com.au> 25jul2004
#

use cs::MIME::Base64;
s|^subject: *(([\w+/]{4})+[\w+/=]{4}) *$|"subject: ".cs::MIME::Base64::decode($1)." [$1]"|ei;
