#!/usr/bin/perl -p
#
# Replace control characters with printable forms.
#	- Cameron Simpson <cs@zip.com.au>
#

# trim ANSI escape sequences
s/\033\[[0-9;]*[a-zA-Z]//g;

# printify control characters
s/[\000-\010\013\015-\037\177-\377]/
	($sub=''),
	($c=unpack('C',$&)),
	( $c >= 0200 && (($sub.='M-'), $c-=0200)),
	( $sub .= '^'.( $c == 0177 ? '?' : pack('C',$c+64) ) ),
	$sub
	/eg;
