#!/usr/bin/perl
#
# Take a fontised string as appears in Subject: lines and attachment descriptions
# and convert it to raw form. See RFC2047.
#	- Cameron Simpson <cs@zip.com.au> 01feb2002
#
# -c chregexp: cameron 26jun2002
# -C; cameron 12jul2002
#

use Getopt::Std;

($::cmd=$0) =~ s:.*/::;
$::Usage="Usage: $::cmd [-r regexp] [strings...]
	-r regexp	Only modify strings matching regexp (case insensitive).
			Pass others through unchanged.
			Intended for modifying particular header lines.
	-c csregexp	Only unfontise if the charset matches chregexp.
	-C		RFC822 line continuations.
";

my $regexp;
my $csregexp = '';
my $linecont = 0;

{ my $badopts = 0;

  getopts('r:c:C') || ($badopts=1);
  $regexp=$::opt_r if defined $::opt_r;
  $csregexp=$::opt_c if defined $::opt_c;
  $linecont=$::Opt_C if defined $::opt_C;

  die $::Usage if $badopts;
}

if (@ARGV)
{ for my $arg (@ARGV)
  { $arg=unfontise($arg) if !defined($regexp) || $arg =~ /$regexp/oi;
    print "$arg\n";
  }
}
else
{
  my $line;
  my $arg;

  while (defined($arg=<STDIN>))
  { chomp($arg);
    if (defined $line && $linecont && $arg =~ /^[ \t]/)
    { $line.="\n$arg";
    }
    else
    { if (defined $line)
      { $line=unfontise($line) if !defined($regexp) || $line =~ /$regexp/oi;
	print "$line\n";
      }
      $line=$arg;
    }
  }

  if (defined $line)
  { $line=unfontise($line) if !defined($regexp) || $line =~ /$regexp/oi;
    print "$line\n";
  }
}

exit 0;

sub unfontise
{ local($_)=@_;

  my $dec = '';
  my $charset;
  my $enc;
  my $encwords;
  my $m;

  while (/=\?([^?]+)\?([QB])\?([^?]*)\?=/i)
  {
    ($charset,$enc,$encwords)=(uc($1),uc($2),$3);
    $m=$&;
    $dec.=$`;
    $_=$';

    if (length $csregexp && $charset !~ /^$csregexp$/oi)
    # don't touch this charset
    { $encwords=$m;
    }
    elsif ($enc eq 'Q')
    { $encwords =~ tr/_/ /;
      $encwords =~ s/=([\da-f][\da-f])/(($code=eval "0x$1") >= 32 && $code < 255 ? chr($code) : $&)/egi;
    }
    else
    { warn "$0: unsupported encoding: \"$enc\"";
    }

    $dec.=$encwords;
  }

  return $dec.$_;
}
