#!/bin/sh
#
# Mangled HTML to put URLs inline with the links for easy grabbing.
#	- Cameron Simpson <cs@zip.com.au> 17may2002
#

detab ${1+"$@"} \
| sed 's|</ *[Aa] *>|&|g' | tr '\015' '\012' \
| sed 's|<[Aa] [^>]*[Hh][Rr][Ee][Ff]=\([^ >]*\)[^>]*> *\(.*\)</[Aa]>|\2 \&lt;\1\&gt;|g' \
| w3m -dump -T text/html
