#!/bin/sh
#
# Mangle HTML to put URLs inline with the links for easy grabbing.
#	- Cameron Simpson <cs@zip.com.au> 17may2002
#

cmd=$0
usage="Usage: $cmd [-a] [-c] [files...]
	-a	No anchors - don't mangle HTML to show URLs.
	-c	Clean: run code through htclean."

mangle=1
cols=
clean=

badopts=
while :
do
  case "$1" in
    -a)  mangle= ;;
    -c)  clean=1 ;;
    --)  shift; break ;;
    -?*) echo "$cmd: unrecognised option: $1" >&2; badopts=1 ;;
    *)   break ;;
  esac
  shift
done

[ $badopts ] && { echo "$usage" >&2; exit 2; }

cols=`ttysize|awk '{print$1}'`
[ -n "$cols" ] && cols="-cols $cols"

detab ${1+"$@"} \
| if [ $clean ]; then htclean; else cat; fi \
| sed 's|</ *[Aa] *>|&|g' | tr '\015' '\012' \
| if [ $mangle ]
  then sed 's|<[Aa] [^>]*[Hh][Rr][Ee][Ff]=\([^ >]*\)[^>]*> *\(.*\)</[Aa]>|\2 \&lt;\1\&gt;|g'
  else cat
  fi \
| (: set -x; w3m $cols -dump -T text/html) \
| sed 's/[ 	][ 	]*$//'
