#!/bin/sh
#
# Kill the process holding a lock.
#	- Cameron Simpson <cs@zip.com.au> 13jul2000
# -f: remove the lock anyway.
#

cmd=$0

LOCKDIR=${LOCKDIR:-"$HOME/var/locks"}
export LOCKDIR

force=
[ "x$1" = x-f ] && { shift; force=1; }

sig=
case $1 in -*) sig=$1; shift ;; esac

xit=0

# see if we sent any signals
killed=

# things to remove
lockdirs=

for lock
do

  # convert as per cs::Lock module
  case $lock in
      *[/_]*)
	name=`sedstrs 's/_/__/g
		       s:///*:/:g
		       s:^/::
		       s:/$::
		       s:/:_:g' "$lock"`
	;;
      *)name=$lock ;;
  esac

  lockdir=$LOCKDIR/$name

  [ -d "$lockdir/." ] \
  || { echo "$cmd: no lock dir $lockdir" >&2
       xit=1
       continue
     }

  lockdirs="$lockdirs $lockdir"

  pidfile=$lockdir/$pid
  [ -s "$pidfile" ] || { echo "$cmd: no pid file for $lock"; xit=1; continue; }

  pid=`cat <"$pidfile"`
  [ -n "$pid" ] || { echo "$cmd: no pid in $pidfile" >&2; xit=1; continue; }

  kill $sig "$pid" && killed=1
done

# signalled anyone? give them a little time to tidy up
[ $killed ] && sleep 1

if [ -n "$lockdirs" ]
then
    for lockdir in $lockdirs
    do
	[ -d "$lockdir/." ] && (set -x; rm -rf "$lockdir")
    done
fi

exit $xit
