#!/bin/sh
#
# Wrapper for pdftohtml which makes a coarse attempt at paragraphing.
#	- Cameron Simpson <cs@zip.com.au> 01jun2002
#

cmd=`basename "$0"`
tmpdir=`mkdirn "/tmp/$cmd"` || exit 1

xit=1
trap 'rm -rf "$tmpdir"; exit $xit' 0 1 3 15

cat ${1+"$@"} >"$tmpdir/it.pdf" || exit 1

pdftohtml -stdout "$tmpdir/it.pdf" \
| sed -e 's/^ *<br>$/<P>/' -e 's/ *<br>$//' \
| unhtml

xit=0
