#!/bin/sh
#
# Take a URL-Minder Cancel URL and use it.
#	- Cameron Simpson <cs@zip.com.au> 28jan99
#

[ $# = 1 ] || { echo "Usage: $0 cancel-URL" >&2; exit 2; }

case $1 in
    [0-9]*[0-9])
	url="http://mindit.netmind.com/responder?OPERATION=cancel&REG=$1" ;;
    http://mindit.netmind.com/responder\?OPERATION=cancel\&*)
	url=$1 ;;
    *)	echo "$0: doesn't look right to me! $1" >&2
	exit 1
	;;
esac

httpget -o - "$1" &
