#!/bin/sh -u
#
# Rebuild css from my development copy.
#	- Cameron Simpson <cs@zip.com.au> 09apr1997
#

cssweb=$HOME/@/ezos/html/cs/css
cssdir=/opt/css
dosync=1
quick=

cmd=$0
usage="Usage: $cmd [-q] [-n] [pushhosts...]"

xit=0

needhost $HOMEHOST@home || exit 2

umask 22

[ $# -gt 0 ] && [ "x$1" = x-q ] && { quick=1; shift; }
[ $# -gt 0 ] && [ "x$1" = x-n ] && { dosync=; shift; }

if [ -z "$quick" ]
then
    ( cd $HOME/bin || exit 1
      exec myke _all
    ) || exit 1
    ( cd "$cssweb" || exit 1
      exec myke
    )
fi

set -x

if needdir $cssdir/bin
then
  rm -f $cssdir/bin/cs
  rsync -aH \
	--copy-links \
	--copy-unsafe-links \
	--delete \
	--delete-excluded \
	--exclude=CVS/ \
	--include=/0README.txt \
	--include=/CHANGELOG.txt \
	--include=/CHANGELOG.html \
	--exclude='/*/' \
	$HOME/bin/. $cssdir/bin/.

  rsync -aH \
	--copy-links \
	--copy-unsafe-links \
	--exclude=CVS/ \
	--exclude='defunct/' \
	$HOME/bin/synonyms/. $cssdir/bin/.
fi

if needdir $cssdir/lib/cs
then
  rsync -avH \
	--delete \
	--delete-excluded \
	--exclude=CVS/ \
	--include='*/' \
	--include='lib.js' \
	--include='*.pm' \
	--include='*.py' \
	--exclude='*' \
	$HOME/bin/cs/. $cssdir/lib/cs/.
fi

##if needdir $cssdir/lib
##then
##  rsync -avW $HOME/rc/java/au.com.zip.cs.jar $cssdir/lib/.
##fi

wait

if [ -d "$cssweb" ]
then
    if [ -z "$quick" ]
    then
      ( cd $cssdir/.. || exit 1
	set -- `find -H css -type f -print`
	[ $# = 0 ] && { echo "NO ARGS!" >&2; ls -ld css >&2; exit 1; }
	ls -tdr "$@" | tar chTf - - | gzip -v -n -9 >$cssweb/css.tar.gz
      )
      for d in man bin lib
      do
	rsync -avH --delete $cssdir/$d/. $cssweb/$d/.
      done
      ( cd "$cssweb/bin" || exit 1
	ln -s ../lib/cs .
      )
      ( cd "$cssweb" || exit 1
	myke _all
      )
    fi
fi

wait

if [ $dosync ]
then
  syncezos &
  for host
  do  pfx "$host:/opt/css" putcss "$host" &
  done
fi

wait
