#!/bin/sh
#
# Rebuild css from my development copy.
#	- Cameron Simpson <cs@zip.com.au> 09apr1997
#

cmd=$0
usage="Usage: $cmd [-q] [-n]"

xit=0

needhost amadeus@home || exit 2

umask 22

dosync=1
quick=
[ "x$1" = x-q ] && { quick=1; shift; }
[ "x$1" = x-n ] && { dosync=; shift; }

common=/u/syncopt/common/`echo "$SYSTEMID" | tr '[a-z]' '[A-Z]'`

if [ -z "$quick" ]
then
    ( cd $HOME/scripts || exit 1
      exec myke
    ) || exit 1
fi

set -x

if needdir $common/css/man
then
  rsync -avH \
	--delete \
	--delete-excluded \
	--include='/man[1-9]/' \
	--exclude='/*' \
	$HOME/man/cs/. $common/css/man/.
fi

if needdir $common/css/bin
then
  rsync -aHC \
	--copy-links \
	--copy-unsafe-links \
	--delete \
	--delete-excluded \
	--exclude='/synonyms/' \
	--include=/0README.txt \
	--include=/CHANGELOG.txt \
	--include=/CHANGELOG.html \
	--exclude='/*/' \
	--include='/cs/**.pm' \
	--include='/cs/**/' \
	--exclude='/cs/**' \
	$HOME/scripts/. $common/css/bin/.

  rsync -aHC \
	--copy-links \
	--copy-unsafe-links \
	$HOME/scripts/synonyms/. $common/css/bin/.
fi

if needdir $common/css/cgi-bin
then
  rsync -aHC \
	--copy-links \
	--copy-unsafe-links \
	--delete \
	--delete-excluded \
	--include='/.cgienv.sh' \
	--include='/*.cgi*' \
	--exclude='/*' \
	$HOME/scripts/cgi-bin/. $common/css/cgi-bin/.
fi

if needdir $common/css/cs
then
  rsync -avH \
	--delete \
	--delete-excluded \
	--include='*/' \
	--include='*.pm' \
	--exclude='*' \
	$HOME/scripts/cs/. $common/css/cs/.
fi

##if needdir $common/css/lib
##then
##  rsync -avW $HOME/rc/java/au.com.zip.cs.jar $common/css/lib/.
##fi

wait

cssweb=$HOME/there/cskk.ezoshosting.com/html/cs/css
if [ -d "$cssweb" ]
then
    ( cd $common || exit 1
      tar cf - css | gzip -v -9 >$cssweb/css.tar.gz
    )
    for d in cs man bin
    do
      rsync -avH --delete $common/css/$d/. $cssweb/$d/.
    done
fi

wait
