#!/bin/sh
#
# Rebuild css from my development copy.
#	- Cameron Simpson <cs@zip.com.au> 09apr1997
#

cmd=$0
usage="Usage: $cmd [-q] [-n]"

xit=0

needhost $HOMEHOST@home || exit 2

umask 22

dosync=1
quick=
[ "x$1" = x-q ] && { quick=1; shift; }
[ "x$1" = x-n ] && { dosync=; shift; }

cssdir=/opt/css

if [ -z "$quick" ]
then
    ( cd $HOME/scripts || exit 1
      exec myke
    ) || exit 1
    ( cd @/ezos/html/cs/css || exit 1
      exec myke
    )
fi

set -x

if needdir $cssdir/man
then
  rsync -avH \
	--delete \
	--delete-excluded \
	--exclude=CVS/ \
	--include='/man[1-9]/' \
	--exclude='/*' \
	$HOME/man/cs/. $cssdir/man/.
fi

if needdir $cssdir/bin
then
  rsync -aH \
	--copy-links \
	--copy-unsafe-links \
	--delete \
	--delete-excluded \
	--exclude=CVS/ \
	--exclude='defunct/' \
	--exclude='/synonyms/' \
	--include=/0README.txt \
	--include=/CHANGELOG.txt \
	--include=/CHANGELOG.html \
	--exclude='/*/' \
	--include='/cs/**.pm' \
	--include='/cs/**/' \
	--exclude='/cs/**' \
	$HOME/scripts/. $cssdir/bin/.

  rsync -aH \
	--copy-links \
	--copy-unsafe-links \
	--exclude=CVS/ \
	--exclude='defunct/' \
	$HOME/scripts/synonyms/. $cssdir/bin/.
fi

if needdir $cssdir/cgi-bin
then
  rsync -aH \
	--copy-links \
	--copy-unsafe-links \
	--delete \
	--delete-excluded \
	--exclude=CVS/ \
	--exclude='defunct/' \
	--include='/.cgienv.sh' \
	--include='/*.cgi*' \
	--exclude='/*' \
	$HOME/scripts/cgi-bin/. $cssdir/cgi-bin/.
fi

if needdir $cssdir/lib/cs
then
  rsync -avH \
	--delete \
	--delete-excluded \
	--exclude=CVS/ \
	--include='*/' \
	--include='*.pm' \
	--exclude='*' \
	$HOME/scripts/cs/. $cssdir/lib/cs/.
fi

##if needdir $cssdir/lib
##then
##  rsync -avW $HOME/rc/java/au.com.zip.cs.jar $cssdir/lib/.
##fi

wait

cssweb=$HOME/@/ezos/html/cs/css
if [ -d "$cssweb" ]
then
    ( cd $cssdir/.. || exit 1
      tar cf - css | gzip -v -9 >$cssweb/css.tar.gz
    )
    for d in man bin lib
    do
      rsync -avH --delete $cssdir/$d/. $cssweb/$d/.
    done
    ( cd "$cssweb/bin" || exit 1
      ln -s ../lib/cs .
    )
    ( cd "$cssweb" || exit 1
      myke _all
    )
fi

wait
