#!/usr/bin/perl
#
# Grep with cs::Upd display.
#	- Cameron Simpson <cs@zip.com.au> 1nov2000
#

BEGIN { use cs::DEBUG; cs::DEBUG::using(__FILE__);
      }

use strict vars;

use Getopt::Std;
use cs::Misc;
use cs::Upd;

$::Usage="Usage: $::cmd [-i] regexp [files...]\n";

my $badopts=0;
my $iflag='';
my $regexp;

getopts('i');
$iflag='i' if defined $::opt_i;

if (@ARGV < 1)
{ warn "$::cmd: missing regexp\n";
  $badopts=1;
}
else
{ $regexp=shift(@ARGV);
}

die "$::Usage" if $badopts;

my $sub = "sub match(){ /\$regexp/o$iflag }";
eval $sub;
die "$::cmd: eval\n\t$sub\n\tfails: $@" if $@;

my $hits=0;

while (<>)
{ chomp;
  if (match())
  { if (@ARGV) { $_="$ARGV:$.: $_"; }
    nl($_);
    $hits++;
  }
  else
  { if (@ARGV) { $_="$ARGV:$.: $_"; }
    out($_);
  }
}

out('');

exit($hits ? 0 : 1);
