#!/bin/sh -u
#
# Gather ssh host keys using ssh-keyscan(1) and incorporate into system tables.
#	- Cameron Simpson <cs@zip.com.au> 25jun2003
#

: ${TMPDIR:=/tmp}
: ${LOCALDOMAINS:=$HOSTDOMAIN}

cmd=`basename "$0"`
usage="Usage: $cmd {-a|hosts...}"

hlist=$TMPDIR/$cmd$$h
keys=$TMPDIR/$cmd$$k

badopts=
all=

if [ "x$1" = x-a ]
then
  shift; all=1
  [ $# = 0 ] || { echo "$cmd: extra arguments after -a: $*" >&2; badopts=1; }
else
  if [ $# = 0 ]
  then
    echo "$cmd: missing hosts" >&2; badopts=1
  fi
fi

[ $badopts ] && { echo "$usage" >&2; exit 2; }

# for CVS log
if [ $all ]
then  cvshostnames="all hosts"
else  cvshostnames=$*
fi

# generate host list
if [ $all ]
then
  hdbinfo ARCH \
  | awk '{print$1}' \
  | wired
else
  for host
  do  echo "$host"
  done
fi \
| while read host
  do  host "$host"
  done \
| sed -e '/^Host [^ ]* not found/d' \
      -e '/ mail is handled by /d' \
      -e 's/ is an alias for .*//' \
      -e 's/ has address / /' \
      -e 's/\.research\.canon\.com\.au//' \
| tr -s ' ' '\012' \
> "$hlist"

# gather keys
set -x
for type in rsa1 rsa dsa
do
  ssh-keyscan -f "$hlist" -t "$type" >"$keys-$type" &
done
wait
cvsmsg=${CVSEDIT_MSG:-"new ssh keys from $cvshostnames"}

xit=0

cvsedit -0 -m "$cvsmsg" ssh_known_hosts1 mergesshkeys "$LOCALDOMAINS" <"$keys-rsa1"	|| xit=1
cvsedit -0 -m "$cvsmsg" ssh_known_hosts2 mergesshkeys "$LOCALDOMAINS" <"$keys-rsa"	|| xit=1
cvsedit -0 -m "$cvsmsg" ssh_known_hosts2 mergesshkeys "$LOCALDOMAINS" <"$keys-dsa"	|| xit=1
cvsedit -f -m "$cvsmsg" ssh_known_hosts_all set-x cat ssh_known_hosts1 ssh_known_hosts2	|| xit=1

exit $xit
