#!/bin/sh
#
# Display URLs with a browser.
#	- Cameron Simpson <cs@zip.com.au>
#
# Added netscape -remote support.	cameron, 05may1995
# Removed mosaic support.		cameron, 10nov1997
# Netscape takes multiple -remote()s!	cameron, 10nov1997
# Jamie Zawinski's <jwz@netscape.com> netscape-remote.c used instead. - cameron, 16mar1999
# support some meta prefixes.		cameron 28mar2000
# Switch to mozilla-xremote-client.	cameron 26aug2002
# 

probe()
{ mozilla-xremote-client 'ping()'
}

popurl()
{ popurl_ret=0
  for url
  do
      [ -n "$URLLOG" ] && echo "urlshow $url" >>"$URLLOG"
      mozilla-xremote-client "openurl($url,new-window)" || popurl_ret=1
  done
  return $popurl_ret
}

cmd=`basename "$0"`
usage="Usage: $cmd [-a] [-c] [-s] [-t] [-i file] [URLs...]
	-a	Anonymous.
	-c	Clean.
	-p	Probe for running browser first.
	-i file	Read URLs from file; \"-\" means stdin."

doprobe=
subopts=
meta=
badopts=
while :
do  case "$1" in
	-[acst]) subopts="$subopts $1" ;;
    esac
    case $1 in
	-a)	meta="anon $meta" ;;
	-c)	meta="clean $meta" ;;
	-p)	doprobe=1 ;;
	-i)	input=$2; shift
		set x ${1+"$@"} "" `cat $input`; shift
		;;
	--)	shift; break ;;
	-?*)	echo "$cmd: $1: unrecognised option" >&2
		badopts=1
		;;
	*)	break ;;
    esac
    shift
done

[ $badopts ] && { echo "$usage" >&2; exit 1; }

if [ $anon ]; then anonpfx=http://anon.free.anonymizer.com/
              else anonpfx=
fi

if [ $# != 0 ]
then
    for url
    do  if [ "x$url" = x- ]
	then
	    cat
	else
	    echo "$url"
	fi
    done \
    | "$0" $subopts
    exit $?
fi

# ensure we have a browser
[ -z "$doprobe" ] || probe || { ns; sleep 3; }

sed -e 's/^[ 	][ 	]*//' \
    -e 's/^#.*//' \
    -e '/^$/d' \
    -e 's/^.*<\(.*\)>.*$/\1/' \
    -e 's/^.*(\(.*\)).*$/\1/' \
    -e 's/^[^a-z]*\([a-z][a-z]*:\/\/.*\)/\1/' \
    -e '/^[a-z][a-z]*:\/\//b ok' \
    -e '/^https:/b ok' \
    -e '/^file:/b ok' \
    -e '/^ftp:/b ok' \
    -e '/^news:/b ok' \
    -e '/^snews:/b ok' \
    -e 's/^/http:\/\//' \
    -e ':ok' \
| while read url
  do  
      url="$meta$url"
      metapfx=
      while :
      do  case "$url" in
	    search\ *|clean\ *|anon\ *)
	      metacmd=`expr "x$url" : 'x\([^ ]*\) .*'`
	      url=`expr "x$url" : 'x[^ ]*  *\(.*\)'`
	      case $metacmd in
		anon)	metapfx="http://anon.free.anonymizer.com/$metapfx" ;;
		clean)metapfx="http://web/~cameron/cgi-bin/htclean.cgi/$metapfx" ;;
		search)
		      engine=`expr "x$url" : 'x\([^ ]*\) .*'`
		      url="http://web/~cameron/cgi-bin/search.cgi?engine=$engine&query="`expr "x$url" : 'x[^ ]*  *\(.*\)'`
		      ;;
		*)	echo "$cmd: bogus meta command \"$metacmd\"" >&2
		      ;;
	      esac
	      ;;
	    *)break
	      ;;
	  esac
      done

      # escape stuff for OpenURL() call
      url=`echo "$url" | hexify`
      popurl "$url"
  done
