#!/bin/sh
#
# Display URLs with a browser.
#	- Cameron Simpson <cs@zip.com.au>
#
# Added netscape -remote support.	cameron, 05may1995
# Removed mosaic support.		cameron, 10nov1997
# Netscape takes multiple -remote()s!	cameron, 10nov1997
# Jamie Zawinski's <jwz@netscape.com> netscape-remote.c used instead. - cameron, 16mar1999
# support some meta prefixes.		cameron 28mar2000
# Switch to mozilla-xremote-client.	cameron 26aug2002
# 

cmd=`basename "$0"`
usage="Usage: $cmd [-a] [-c] [-s] [-t] [-i file] [URLs...]
	-a	Anonymous.
	-c	Clean.
	+c	Don't clean.
	-p	Probe for running browser first.
	-t	Open a new tab instead of a new window.
	-i file	Read URLs from file; \"-\" means stdin."

doprobe=
subopts=
doclean=
doanon=
popurl_mode=new-window

badopts=

while :
do  case "$1" in
	-[acst]) subopts="$subopts $1" ;;
    esac
    case $1 in
	-a)	doanon=1 ;;
	-c)	doclean=1 ;;
	+c)	doclean= ;;
	-p)	doprobe=1 ;;
	-t)	popurl_mode=new-tab ;;
	-i)	input=$2; shift
		set x ${1+"$@"} "" `cat $input`; shift
		;;
	--)	shift; break ;;
	-?*)	echo "$cmd: $1: unrecognised option" >&2
		badopts=1
		;;
	*)	break ;;
    esac
    shift
done

[ $badopts ] && { echo "$usage" >&2; exit 1; }

if [ $anon ]; then anonpfx=http://anon.free.anonymizer.com/
              else anonpfx=
fi

if [ $# != 0 ]
then
    for url
    do
      case "$url" in
	-)	cat ;;
	xclip)	xunclip | tr ' \011' '\012\012' ;;
	*)	echo "$url" ;;
      esac
    done \
    | "$0" $subopts
    exit $?
fi

probe()
{ mozilla-xremote-client 'ping()'
}

popurl()
{ popurl_ret=0
  for url
  do
      [ -n "$URLLOG" ] && echo "urlshow $url" >>"$URLLOG"
      ## lock mozilla-xremote-client
      if mozilla-xremote-client "openurl($url,$popurl_mode)"
      then  popurl_mode=new-tab
      else  popurl_ret=1
      fi
  done
  return $popurl_ret
}

# ensure we have a browser
if [ "$doprobe" ]
then
  probe \
  || { ns
       probed=
       while sleep 1
       do  probe && break
	   [ $probed ] || { probed=1; echo "waiting for mozilla ..."; }
       done
     }
fi

cleanurllist \
| while read url
  do  
    case "$url" in
      search\ *)
	metacmd=`expr "x$url" : 'x\([^ ]*\) .*'`
	url=`expr "x$url" : 'x[^ ]*  *\(.*\)'`
	case $metacmd in
	  search)
		engine=`expr "x$url" : 'x\([^ ]*\) .*'`
		url="http://web/~cameron/cgi-bin/search.cgi?engine=$engine&query="`expr "x$url" : 'x[^ ]*  *\(.*\)'`
		;;
	  *)	echo "$cmd: bogus meta command \"$metacmd\"" >&2
		;;
	esac
	;;
    esac
    [ $doclean ] && url="http://web/~cameron/cgi-bin/htclean.cgi/$url"
    [ $doanon  ] && url="http://anon.free.anonymizer.com/$url"

    # escape stuff for OpenURL() call
    url=`echo "$url" | hexify`
    popurl "$url"
    popurl_mode=new-tab
  done
