#!/bin/sh -u
#
# Display URLs with a browser.
#	- Cameron Simpson <cs@zip.com.au>
#
# Added netscape -remote support.	cameron, 05may1995
# Removed mosaic support.		cameron, 10nov1997
# Netscape takes multiple -remote()s!	cameron, 10nov1997
# Jamie Zawinski's <jwz@netscape.com> netscape-remote.c used instead. - cameron, 16mar1999
# support some meta prefixes.		cameron 28mar2000
# Switch to mozilla-xremote-client.	cameron 26aug2002
# 

: ${BROWSER_DISPLAY:=$DISPLAY}
: ${DISPLAY:=$BROWSER_DISPLAY}
export DISPLAY

cmd=`basename "$0"`
usage="Usage: $cmd [-a] [-c] [-d display] [-n windowname] [-s] [-t] [-i file] [URLs...]
	-a	Anonymous.
	-c	Clean.
	+c	Don't clean.
	-n windowname New window name, or window name for new tabs.
	-t	Open a new tab instead of a new window.
	-i file	Read URLs from file; \"-\" means stdin."

subopts=
doclean=
doanon=
name=
tflag=

browser=opera	## mozilla
browser=mozilla

badopts=

while [ $# -gt 0 ]
do
  case "$1" in
    -[acst]) subopts="$subopts $1" ;;
  esac
  case $1 in
      -a)	doanon=1 ;;
      -c)	doclean=1 ;;
      +c)	doclean= ;;
      -d)	DISPLAY=$2; export DISPLAY; shift ;;
      -n)	name=$2; shift ;;
      -t)	tflag=-t ;;
      -i)	input=$2; shift
		set x ${1+"$@"} "" `cat $input`; shift
		;;
      --)	shift; break ;;
      -?*)	echo "$cmd: $1: unrecognised option" >&2
		badopts=1
		;;
      *)	break
      		;;
  esac
  shift
done

[ $badopts ] && { echo "$usage" >&2; exit 1; }

[ -n "$BROWSER_DISPLAY" ] || { echo "$cmd: no \$BROWSER_DISPLAY!" >&2; exit 1; }

if [ $doanon ]; then anonpfx=http://anon.free.anonymizer.com/
              else anonpfx=
fi

if [ $# != 0 ]
then
    for url
    do
      case "$url" in
	-)	cat ;;
	xclip)	xclip -o | tr '\011' ' '; echo ;; # was cutbuffer
	*)	printf "%s\n" "$url" ;;
      esac
    done \
    | "$0" $subopts -n "$name"
    exit $?
fi

cleanurllist \
| \
{ exec 3>&1 1>&2
  while read url
  do  
    case "$url" in
      search\ *)
	metacmd=`expr "x$url" : 'x\([^ ]*\) .*'`
	url=`expr "x$url" : 'x[^ ]*  *\(.*\)'`
	case $metacmd in
	  search)
		engine=`expr "x$url" : 'x\([^ ]*\) .*'`
		url="http://web/~cameron/cgi-bin/search.cgi?engine=$engine&query="`expr "x$url" : 'x[^ ]*  *\(.*\)'`
		;;
	  *)	echo "$cmd: bogus meta command \"$metacmd\"" >&2
		;;
	esac
	;;
    esac
    [ $doclean ] && url="http://web/~cameron/cgi-bin/htclean.cgi/$url"
    [ $doanon  ] && url="$anonpfx/$url"

    printf "%s\n" "$url" >&3
  done \
} \
| case "$browser" in
    mozilla)
      set -x
      exec urlshow-mozilla $tflag ;;
    opera)
      set -x
      exec urlshow-opera $tflag -n "$name"
      ;;
    *)
      echo "$0: unsupported browser \"$browser\"" >&2
      exit 2
      ;;
  esac
