#!/bin/sh
#
# Autostart browser and show URLs. Backgrounds so the user can get on
# with things.
#	- Cameron Simpson <cs@zip.com.au>
#
# Catch "us -" and squirrel away stdin.	- cameron 25jun2001
# Shortcuts and foo.bar -> http://foo.bar/ - cameron 09aug2002
#

clean=
while :
do  case $1 in
      +c)	clean= ;;
      -c)	clean=1 ;;
      --)	shift; break ;;
      *)	break ;;
    esac
    shift
done

case $DISPLAY in
    :*)	id=$HOST$DISPLAY ;;
    *)	id=$DISPLAY ;;
esac

# translate shortcuts
first=1
for arg
do  case "$arg" in
	xclip)	set x `xunclip`; shift; first=; arg= ;;
	home)	arg=http://www.zip.com.au/~cs/ ;;
	jdk)	arg=file:///opt/j2sdk-sun-1.4.0-beta3/docs/api/overview-summary.html ;;
	rfcs)	arg=http://www.faqs.org/rfcs/rfc-titles.html ;;
	*/*)	;;
	*.*)	arg=http://$arg/ ;;
    esac
    [ -n "$arg" ] || continue
    if [ $first ]
    then  set x "$arg"; shift
    else  set x "$@" "$arg"; shift; first=
    fi
done

[ "x$*" = x- ] || exec </dev/null
if [ $clean ]
then
    for url
    do  htc "$url"
    done
else
    ## set -x
    bgstdin urlshow ${1+"$@"}
fi
