#!/bin/sh
#
# Autostart netscape and show URLs. Backgrounds so the user can get on
# with things.
#	- Cameron Simpson <cs@zip.com.au>
#
# Catch "us -" and squirrel away stdin.	- cameron 25jun2001
#

force=1
clean=
while :
do  case $1 in
      -f)	force=1 ;;
      +c)	clean= ;;
      -c)	clean=1 ;;
      --)	shift; break ;;
      *)	break ;;
    esac
    shift
done

# grab cut/paste buffer if no args
[ $# = 0 ] && { ( xclip -o; echo ) | "$0" -; exit $?; }

case $DISPLAY in
    :*)	id=$HOST$DISPLAY ;;
    *)	id=$DISPLAY ;;
esac

if [ $force ] || locked "netscape-$id"
then
    [ "x$*" = x- ] || exec </dev/null
    if [ $clean ]
    then
	for url
	do  htc "$url"
	done
    else
	bgstdin urlshow ${1+"$@"}
    fi
else
    echo "$0: no netscape lock active" >&2
    echo "	please retry when netscape is up, or use -f" >&2
    exit 1
fi
