#!/bin/sh
#
# Read a vcard from stdin, write it out prettily.
#	- Cameron Simpson <cs@zip.com.au> 14apr2001
#

[ $# = 0 ] || { echo "Usage: $0 < vcard" >&2; exit 2; }

( echo;exec cat ) \
| sed -n \
      -e '1,/^begin:vcard/d' \
      -e '/^end:vcard$/,$d' \
      -e '/^[a-z][a-z;]*:/!d' \
      -e 's/^\([a-z][a-z]*\);/\1_/' \
      -e "s/'/'\\''/g" \
      -e "s/:\\(.*\\)/='\\1'/" \
      -e 's/^/vcard_/p' \
| (eval "`cat`"
    n=$vcard_fn
    [ -n "$vcard_email_internet" ] && n="$n <$vcard_email_internet>"
    echo "$n"
    echo ${vcard_org:+      "Organisation: $vcard_org"}
    echo ${vcard_title:+    "Title:      $vcard_title"}
    echo ${vcard_adr:+      "Address:    $vcard_title"}
    echo ${vcard_url:+      "URL:        $vcard_url"}
    echo ${vcard_tel_cell:+ "Ph (Cell):  $vcard_tel_cell"}
    echo ${vcard_tel_work:+ "Ph (Work):  $vcard_tel_work"}
    echo ${vcard_tel_home:+ "Ph (Home):  $vcard_tel_home"}
    echo ${vcard_tel_fax:+  "Ph (Fax):   $vcard_tel_fax"}
    echo ${vcard_tel_pager:+"Ph (pager): $vcard_tel_pager"}
  ) \
| sed '/^ *$/d'
