#!/bin/sh -uex
#
# Wrapper for $EDITOR for vcs commits to append the changes for inquisition
# while composing the change report.
#	- Cameron Simpson <cs@zip.com.au> 09mar2002
#

cmd=$0
usage="usage: $cmd editfile"

report=$1
shift

cat "$VCS_COMMIT_DIFFS" >>"$report"

EDITOR=$VCS_COMMIT_EDITOR
export EDITOR

$EDITOR "$report" || exit 1

# toss blank lines and CVS: comments
bsed -s "/^$VCS_COMMIT_PREFIX */d; /^[ 	]*\$/d" "$report"

if [ -s "$report" ]
then
    headline=`sed 1q "$report"`
    ( cat "$report"
      echo
      cat "$VCS_COMMIT_DIFFS"
    ) \
    | buglog "commit: $headline" &
fi

exit $xit

