#!/bin/sh
#
# Generic handler for untyped data to be displayed inline (as for mailcap
# "copiousoutput' entries).
#	- Cameron Simpson <cs@zip.com.au> 24jul2002
#

cmd=$0
usage="Usage: $cmd [-cC] [file]
	-c	Use \"copiousoutput\" entries (default).
	-C	Don't use \"copiousoutput\" entries."

APPHELPER_SAVEMODE=no
export APPHELPER_SAVEMODE

copious=1
copflag=
[ "x$1" = x-c ] && { copflag=-c copious=1; shift; }
[ "x$1" = x-C ] && { copflag=-C copious=; shift; }

tmpf=${TMPDIR:-/tmp}/vu$$
trap '[ -f "$tmpf" ] && rm "$tmpf"' 0 1 15

if [ $# = 0 ]
then
    [ -t 0 ] && { echo "$cmd: won't read stdin from a terminal" >&2
		  exit 1
		}
    cat >"$tmpf" || exit 1
    file=$tmpf
else
    file=$1; shift
    [ $# = 0 ] || { echo "$cmd: extra arguments: $*" >&2
		    echo "$usage" >&2
		    exit 2
		  }
    case "$file" in
      http://*) wcat "$file" >"$tmpf"; file=$tmpf ;;
      /*) ;;
      *) file=./$file ;;
    esac
fi

# no idea? run plain file and bail out
mtype=`file2mime "$file"` || { ls -ld "$file"
			       file "$file"
			       exit 0
			     }

case "$mtype" in
    text/plain)
	case "$file" in
	  *.csv)	mtype=text/x-csv ;;
	esac
	;;
esac

if [ $copious ]
then  mcflag=-c
else  mcflag=+c
fi

# no action? bail out
action=`mailcap $mcflag -s "$file" "$mtype"`
[ -n "$action" ] || [ $copious ] || action=`mailcap -c -s "$file" "$mtype"`

# empty action in mailcap
[ -z "$action" ] && { echo "$mtype"; file "$file"; exit 0; }

eval "$action"
