#!/bin/sh
#
# Wrapper for the vnc programs.
#	- Cameron Simpson <cs@zip.com.au> 26jul1999
#
# Recode to act more like the "scr" script.
#       - Cameron Simpson <cs@zip.com.au> 03nov2006
#

trace=set-x
depth=24
geom=1280x1024

usage="Usage:
        $0              List local sessions.
        $0 NAME         Connect to session named NAME,
                        creating it is necessary.
        $0 host:        List remote sessions.
        $0 host:NAME    Connect to remote session named NAME,
                        creating it is necessary."
if [ $# = 0 ]
then
  # list sessions
  idset -i vnc -a | sort -n
  exit $?
fi

[ $# = 1 ] || { echo "$usage" >&2; exit 2; }

case "$1" in
  *:)   remote=`expr "x$1" : 'x\(.*\):'` || exit 1
        exec envssh "$remote" vnc
        ;;
  *:?*) remote=`expr "x$1" : 'x\(.*\):..*'` || exit 1
        name=`expr "x$1" : 'x.*:\(..*\)'` || exit 1
        exec envssh +t -f -n -Y "$remote" vnc "$name"
        ;;
esac

name=$1; shift

id=`idset -i vnc "$name"` || exit 1
pid=`idset -i vnc "$name" pid` || exit 1
if [ -z "$pid" ] || not kill -0 "$pid" 2>/dev/null
then
  $trace vncserver ":$id" -name "$name" -geometry "$geom" -depth "$depth" &
  idset -i vnc "$name" pid "$!" || exit 1
fi

exec $trace vncviewer ":$id"
