#!/bin/sh
#
# Gather up all of stdin and then run command.
# Useful for delaying the commencement of an especially expensive
# command (eg resource hungry or holds a lock for an excessive time)
# until its input is ready. (In fact, that's the only use I can think
# of for this script, but then that was what I needed.)
#	- Cameron Simpson <cs@zip.com.au> 25sep2000
#

cmd=`basename "$0"`
usage="Usage: $cmd command [args] <command-input"

[ $# = 0 ] && { echo "$cmd: missing command" >&2
		echo "$usage" >&2
		exit 2
	      }

tmpdir=${TMPDIR:-/tmp}
[ -d "$tmpdir/." ] || ( set -x; mkdir -p "$tmpdir" ) || exit 1

tmpf=$tmpdir/$cmd.$$
cat >"$tmpf" || exit 1

exec <"$tmpf"
rm -f "$tmpf"
exec "$@"
