#!/bin/sh

No such pseudo-hash field "HASH(0x835d950)" at /home/zapff/cameron/scripts/htforms line 89.
FORM NAME="shortcut"

FORM

FORM

FORM ACTION="/search/result.jhtml;$sessionid$J5MWQXIAABG0LS0Z2WLSDTA?_DARGS=%2Fsearch%2Fsearch.jhtml.2" METHOD="post"
NAME="errorPage" TYPE="hidden" VALUE="search.jhtml"
NAME="_D:errorPage" TYPE="hidden" VALUE=" "
NAME="hostname" TYPE="hidden" VALUE="garn.ext0.pacificaccess.com.au"
NAME="_D:hostname" TYPE="hidden" VALUE=" "
NAME="filePath" TYPE="hidden" VALUE="/cgi-bin/tmap_cgi"
NAME="_D:filePath" TYPE="hidden" VALUE=" "
NAME="port" TYPE="hidden" VALUE="6969"
NAME="_D:port" TYPE="hidden" VALUE=" "
NAME="blob" TYPE="hidden" VALUE=""
MAXLENGTH="10" NAME="streetNumber" SIZE="3" STYLE="width:50px" VALUE=""
NAME="_D:streetNumber" TYPE="hidden" VALUE=" "
MAXLENGTH="30" NAME="streetName" SIZE="12" STYLE="width:140px" VALUE=""
NAME="_D:streetName" TYPE="hidden" VALUE=" "
NAME="streetType" STYLE="width:120px" VALUE="" WIDTH="120"
