#!/bin/sh
#
# Pop up window list of selected windows.
#	- Cameron Simpson <cs@zip.com.au> 10aug2004
#

[ $# = 0 ] && { echo "Usage: $0 substr..." >&2; exit 2; }

ptns=
for ptn
do
  ptns="$ptns \"*$ptn*\""
done

exec fvwmcmd "WindowList ($ptns) Alphabetic SelectOnRelease NoGeometryWithInfo TitleForAllDesks"
