#!/bin/sh -u
#
# Fetch URL into file then run command with filename.
#	- Cameron Simpson <cs@zip.com.au> 12feb2003
#

: ${TMPDIR:=/tmp}

trace=

cmd=`basename "$0"` || exit 1
usage="Usage: $cmd [-1] [-end] [-c] [-h] URL command [args...]
	-1, -end Passed to arg1.
	-x	Trace execution of sub command.
	-c	Cache the fetched URL.
	-C	Cache the fetched URL; skip fetch if already cached.
	-h	Passed to httpget."

htopts=
docache=
trustcache=
arg1opts=

badopts=
while :
do  case $1 in
      -[0-9]*|-end|-discard)
		arg1opts="$arg1opts $1" ;;
      -x)	trace=set-x
		arg1opts="$arg1opts $1" ;;
      -c)	docache=1 trustcache= ;;
      -C)	docache=1 trustcache=1 ;;
      -h)	htopts="$htopts $1" ;;
      --)	shift; break ;;
      -?*)	echo "$cmd: unrecognised option: $1" >&2; badopts=1 ;;
      *)	break ;;
    esac
    shift
done

if [ $# = 0 ]
then
    echo "$cmd: missing URL" >&2
    badopts=1
else
    url=$1; shift
    [ $# -gt 0 ] || { echo "$cmd: missing command" >&2; badopts=1; }
fi

[ $badopts ] && { echo "$usage" >&2; exit 2; }

case "$url" in
    http://* | ftp://* ) ;;
    *)	echo "$cmd: bad URL \"$url\"" >&2; exit 2 ;;
esac

ext=`expr "x$url" : '.*\.\(..*\)'`
[ -n "$ext" ] || ext=bin

if [ $docache ]
then
    saveas=`urlcachename -p "$url"` || exit 1
else
    case "$url" in
      *[#?]*) url=`expr "x$url" : 'x\([^#?]*\)[#?].*'` ;;
    esac
    case "$url" in
      */)	base=index.html ;;
      *)	base=`basename "$url"` ;;
    esac
    tmpdir=`mkdirn "$TMPDIR/$cmd"` || exit 1
    tmpf=$tmpdir/$base
    trap 'rm -rf "$tmpdir"' 0 1 2 13 15
    saveas=$tmpf
fi

if [ $trustcache ] && [ -f "$saveas" -a -s "$saveas" ]
then  :
else
  set-x wget -q -O "$saveas" "$url" || exit 1
  ##httpget -f -o "$saveas" "$url" || exit 1
fi

$trace env "WITHURL_URL=$url" "WITHURL_FILE=$saveas" arg1 $arg1opts -- "$saveas" "$@"
xit=$?

exit $xit
