#!/bin/sh
#
# Fetch URL into file then run command with filename.
#	- Cameron Simpson <cs@zip.com.au> 12feb2003
#

cmd=`basename "$0"`
usage="Usage: $cmd [-h] URL command [args...]
	-h	Passed to httpget."

htopts=

badopts=
while :
do  case $1 in
      -h)	htopts="$htopts $1" ;;
      --)	shift; break ;;
      -?*)	echo "$cmd: unrecognised option: $1" >&2; badopts=1 ;;
      *)	break ;;
    esac
    shift
done

if [ $# = 0 ]
then
    echo "$cmd: missing URL" >&2
    badopts=1
else
    url=$1; shift
    [ $# -gt 0 ] || { echo "$cmd: missing command" >&2; badopts=1; }
fi

[ $badopts ] && { echo "$usage" >&2; exit 2; }

case "$url" in
    http://* | ftp://* ) ;;
    *)	echo "$cmd: bad URL \"$url\"" >&2; exit 2 ;;
esac

ext=`expr "x$url" : '.*\.\(..*\)'`
[ -n "$ext" ] || ext=bin

tmpf=${TMPDIR:-/tmp}/$cmd$$.$ext
trap 'rm -f "$tmpf"' 0 1 2 15

httpget -o "$tmpf" "$url" || exit 1

env WITHURL_URL=$url WITHURL_FILE=$tmpf "$@" "$tmpf"
xit=$?

rm -f "$tmpf"

exit $xit
