#!/bin/sh
#
# Fetch URL into file then run command with filename.
#	- Cameron Simpson <cs@zip.com.au> 12feb2003
#

cmd=`basename "$0"`
usage="Usage: $cmd [-c] [-h] URL command [args...]
	-c	Cache the fetched URL.
	-C	Cache the fetched URL; skip fetch if already cached.
	-h	Passed to httpget."

htopts=
docache=
trustcache=

badopts=
while :
do  case $1 in
      -c)	docache=1 trustcache= ;;
      -C)	docache=1 trustcache=1 ;;
      -h)	htopts="$htopts $1" ;;
      --)	shift; break ;;
      -?*)	echo "$cmd: unrecognised option: $1" >&2; badopts=1 ;;
      *)	break ;;
    esac
    shift
done

if [ $# = 0 ]
then
    echo "$cmd: missing URL" >&2
    badopts=1
else
    url=$1; shift
    [ $# -gt 0 ] || { echo "$cmd: missing command" >&2; badopts=1; }
fi

[ $badopts ] && { echo "$usage" >&2; exit 2; }

case "$url" in
    http://* | ftp://* ) ;;
    *)	echo "$cmd: bad URL \"$url\"" >&2; exit 2 ;;
esac

ext=`expr "x$url" : '.*\.\(..*\)'`
[ -n "$ext" ] || ext=bin

if [ $docache ]
then
    saveas=`urlcachename -p "$url"` || exit 1
else
    tmpf=${TMPDIR:-/tmp}/$cmd$$.$ext
    trap 'rm -f "$tmpf"' 0 1 2 15
    saveas=$tmpf
fi

if [ $trustcache ] && [ -f "$saveas" -a -s "$saveas" ]
then  :
else  httpget -f -o "$saveas" "$url" || exit 1
fi

env WITHURL_URL=$url WITHURL_FILE=$saveas "$@" "$saveas"
xit=$?

exit $xit
