#!/bin/sh

cd

. $HOME/rc/x11/xenv.sh

for fvbin in \
	/opt/fvwm-2.5.4/bin \
	/opt/fvwm-2.5.4cvs/bin \
	/opt/fvwm-2.5.3/bin \
	/opt/fvwm-2.5.1/bin \
	/opt/fvwm-2.4.4/bin \
	/opt/fvwm/bin \
	/opt/fvwm-2.3.23 \
	/opt/fvwm/bin \
	/opt/bin \
	/usr/X11R6/bin \
	/nowhere
do   fvwm=$fvbin/fvwm
     [ -f "$fvwm" ] && break
done

[ -f "$fvwm" ] || { echo "$0: no fvwm!" >&2; exit 1; }

PATH=$fvbin:$PATH
export PATH

exec >>$HOME/var/log/fv.out 2>$HOME/var/log/fv.err
exec "$fvwm" -cmd "PipeRead fvwmrc" ${1+"$@"}

##for f in "$FVWMEVLOG" "$FVWMCMDLOG"
##do  >"$f"; rm -f "$f"
##done
