#!/bin/sh -u
#
# Report the X11 extensions on the current display.
#	- Cameron Simpson <cs@zip.com.au> 07jun2006
# 

xdpyinfo ${1+"$@"} \
| sed -n '1,/^number of extensions:/d
          /^[a-z]/,$d
          s/^  *//p'
