#!/bin/sh

set -vx

echo "DISPLAY=$DISPLAY" >&2; xdpyinfo | wc >&2
case "$X11_DEPTH,$X11_CLASS" in
    ,)				type=Colour ;;	# guess, not recurse
    1,*)			type=Mono ;;
    *,StaticGray|*,GrayScale)	type=Grey ;;
    *)				type=Colour ;;
esac

cd $HOME/rc/x11 || exit $?
cat dflt/* \
| uncurly \
	'FG BG DIMFG DIMBG ALERT DIMALERT BRIGHT HILIGHT DIMHILIGHT
	 FONT_BIG FONT_NORMAL FONT_SMALL
	 HOME MAIL
	 X11 FULLX HALFX
	 TTY_HIGH TTY_WIDE FONT FONT_X FONT_Y PIX_HIGH' \
> $HOME/.Xdefaults

exec xrdb -nocpp -load $HOME/.Xdefaults

dpp ${1+"$@"} $X11/xinfo.dpp $X11/defaults \
      | xrdb -load -nocpp
