#!/bin/sh

case "$X11_DEPTH,$X11_CLASS" in
    ,)				exec setvar 'use x11' "$0" ${1+"$@"} ;;
    1,*)			type=Mono ;;
    *,StaticGray|*,GrayScale)	type=Grey ;;
    *)				type=Colour ;;
esac

cd $HOME/rc/x11 || exit $?

# set-x \
myke -u \
     -f Mykefile.${X11_X}x${X11_Y} \
     -f Mykefile.$type \
     -f Mykefile \
     "type=$type" _dflts
exec xrdb -nocpp -load $HOME/.Xdefaults

dpp ${1+"$@"} $X11/xinfo.dpp $X11/defaults \
      | xrdb -load -nocpp
