#!/bin/sh
#
# View a URL. Fetch and hand to something other than my web browser.
# Spurred into implementation by the Liberty Meadows comics strip,
# which is funny but too small, so XV to the rescue!
#	- Cameron Simpson <cs@zip.com.au> 12jun2001
#

exec </dev/null

cmd=$0
usage="Usage: $cmd [-f] [URL]"

force=
[ "x$1" = x-f ] && { force=1; shift; }
[ $# = 0 ] && { set -- `xclip -o` || exit 1; }
[ $# = 1 ] || { echo "$usage" >&2; exit 2; }

exec withurl "$1" xv
