#!/bin/sh -u
#
# List uninstalled stuff by diffing "yum list available" against rpm.
#	- Cameron Simpson <cs@zip.com.au> 14jun2005
#

: ${TMPDIR:=/tmp}

[ $# = 0 ] || { echo "Usage: $0" >&2; exit 2; }

exec </dev/null

tmpf=$TMPDIR/ym$$
yumout=${tmpf}y
rpmout=${tmpf}r
trap 'rm -f "$yumout" "$rpmout"' 0 1 2 13 15

yum list available | sed 's/\..*//' | sort -u >"$yumout" &
rpm -qa | sed 's/-[^-]*-[^-]*$//' | sort -u  >"$rpmout" &
wait
diffu "$rpmout" "$yumout" | sed -n '/-debuginfo$/d; s/^\+//p'
