#!/bin/sh
#
# Set up a SCSI Zip medium in a Solaris box.
#	- Cameron Simpson <cs@zip.com.au> 22oct96
#

scsitarget=5
partition=2
force=

usage="Usage: $0 [-d dev]
	-f	Force. Don't prompt before making filesystem.
	-s st	Specify SCSI target st (default $scsitarget).
	-p pt	Specify partition pt (default $partition)."

badopts=
while :
do
    case $1 in
	-f)	force=1 ;;
	-s)	scsitarget=$2; shift ;;
	-p)	partition=$2; shift ;;
	--)	shift; break ;;
	-?*)	echo "$0: unrecognised option: $1" >&2; badopts=1 ;;
	*)	break ;;
    esac
    shift
done

[ $# = 0 ] || { echo "$0: extra arguments: $*" >&2; badopts=1; }

[ $badopts ] && { echo "$usage" >&2; exit 2; }

dev=/dev/rdsk/c0t${scsitarget}d0s${partition}

set -x
newfs $dev && tunefs -o space -m 0 $dev
