#!/bin/sh
##exec nphssh "dsa-pop-${SYSTEMID}2zip" zip
set nc mail.zip.com.au 110
##case $SYSTEMID in
##    home)	;;
##    cisra)	set ssh upnp exec "$@" ;;
##esac
set ssh zip exec "$@"
set -x
exec "$@"
