#!/bin/sh
#
# List recursive diff of two dirs with some noise chopped.
#	- Cameron Simpson <cs@cskk.id.au> 22nov98
#

[ -t 1 ] || PAGER=cat
diffu -br ${1+"$@"} 2>&1 | grep -v '^Only in ' | ${PAGER:-less}
