#!/usr/bin/perl
#
# Sheet code for today (or an arbitrary number of seconds previous).
#	- Cameron Simpson <cs@cskk.id.au> 15jan97
#

use cs::Day;

$now=time;
$offset=0;

if (@ARGV && $ARGV[0] =~ /^\d+$/)
	{ $offset=shift(@ARGV)+0;
	}

$day = newgmt cs::Day ($now-$offset);
print $day->Code(), "\n";

exit 0;
