#!/bin/sh
#
# Watch a set of weblogs and report new links.
#	- Cameron Simpson <cs@cskk.id.au> 29jul2000
#

raw=

cmd=`basename "$0"`
usage="Usage: $cmd indexfile <weblogurls
	-f sedf	Sed script to filter the \"url title\" stage.
	-p perlf Perl-p script to filter the \"url title\" stage."

wlpopts=
case $1 in
    -[fp])	wlpopts="$wlpopts $1 $2"; shift; shift ;;
esac

badopts=

if [ $# = 0 ]
then
    echo "$cmd: missing indexfile" >&2
    badopts=1
else
    oldposts=$1; shift
    [ $# = 0 ] || { echo "$cmd: extra arguments: $*" >&2
		    badopts=1
		  }
fi

[ $badopts ] && { echo "$usage" >&2; exit 2; }

sed 's/#.*//' \
| grep '^http:' \
| sort -u \
| foreach -n 20 -i watchlinkpages $wlpopts "$oldposts" \
| shuffle
