#!/bin/sh
#
# Read some passwd lines from stdin.
# Construct a mapping from those lines to the uids from the NIS service.
# Walk the specified directories adjusting uids.
#	- Cameron Simpson <cs@zip.com.au> 30may2002
#

cmd=`basename "$0"`
[ $# = 0 ] && { echo "Usage: $cmd dirs..." >&2; exit 2; }

finduids=

awk -F: '{print $1, $3}' \
| { xit=0
    while read login olduid
    do  newuid=`ypmatch "$login" passwd | awk -F: '{print $3}'`
	[ -n "$newuid" ] || { echo "$cmd: no NIS mapping for \"$login\"" >&2
			      continue; xit=1
			      continue
			    }
	[ "x$olduid" = "x$newuid" ] && continue
	if [ -n "$finduids" ]
	then  finduids="$finduids -o -user $olduid"
	else  finduids="\\( -user $olduid"
	fi
    done
    [ $xit = 0 ] || { echo "$cmd: trouble mapping uids" >&2; exit 1; }
    [ -n "$finduids" ] || { echo "$cmd: nothing to remap!" >&2; exit 0; }
    finduids="$finduids \\)"
    eval "echo find $finduids -print"
    eval "find $* $finduids -links 1 -print | xargs echo chown $newuid"
  }
