#!/bin/sh
#
# Pick a simple disposable password to limited time use.
# - Cameron Simpson <cs@cskk.id.au>
#

words=/usr/share/dict/words
shuffle < "$words" \
| awk 'length < 8 {print}' \
| sed 2q \
| ( set -ue
    read w1
    read w2
    d=$(now|sed 's/.*\(.\)/\1/')
    echo $w1$d$w2
  )
