#!/bin/sh

case $SYSTEMID-$ARCH in
    *-linux.*.linux)	gmake=/usr/bin/make ;;
    *-sun.*.solaris)	gmake=/opt/bin/gmake ;;
    *)			gmake=/usr/local/bin/gmake ;;
esac

if [ -t 1 ]
then
    exec colourise "$gmake" ${1+"$@"}
else
    exec "$gmake" ${1+"$@"}
fi
