#!/bin/sh
#
# Run a Java program with some envvars present as properties (because getenv() is depreciated).
#	- Cameron Simpson <cs@zip.com.au> 12aug2002
#

[ $# = 0 ] && { echo "Usage: $0 args..." >&2; exit 2; }

props=au.com.zip.cs
tty=`tty`
set -x
exec ${JAVA_HOME:-"/opt/j2sdk-sun"}/bin/java \
	"-D$props.env.HOME=$HOME" \
	"-D$props.env.EDITOR=$EDITOR" \
	"-D$props.tty=$tty" \
	"$@"
