#!/bin/sh
#

mkdir=/bin/mkdir
"$mkdir" ${1+"$@"} || exit $?

[ -f "$PWDLOG" ] || exit 0

for wd
do  case $wd in
        -*)	continue ;;
	/*)	lwd=$wd ;;
	*)	lwd=$PWD/$wd ;;
    esac
    [ -d "$lwd/." ] && logpwd "$lwd"
done

exit 0
