#!/bin/sh
#

[ -n "$LUSER" ] && [ "x$LUSER" != "x$USER" ] \
	&& { echo "$0: LUSER($LUSER) != USER($USER), aborting" >&2
	     exit 1
	   }

# flush alert window when I read my important email
[ "x$*" = 'x-f +attn' ] && { clear | alert; }

case "$TERM" in
    xterm)
	if [ "x$HOST@$SYSTEMID" != xzipperii@zip ]
	then
	    TERM=rxvt; export TERM
	    unset TERMINFO
	    unset TERMCAP
	fi
	;;
esac

set -vx
for mutt in /opt/mutt-1.4i-patched/bin/mutt /opt/mutt/bin/mutt /usr/bin/mutt
do  [ -f "$mutt" ] && exec "$mutt" ${1+"$@"}
done

echo "$0: can't find a mutt installation!" >&2
exit 1
