#!/bin/sh
#

case $HOST in
    ivie)	echo "DON'T RUN MUTT OR ANY EMAIL ON IVIE!" >&2
		exit 1
		;;
esac

[ -n "$LUSER" ] && [ "x$LUSER" != "x$USER" ] \
	&& { echo "$0: LUSER($LUSER) != USER($USER), aborting" >&2
	     exit 1
	   }

# flush alert window when I read my important email
[ "x$*" = 'x-f +attn' ] && { alert ''; alert ''; alert ''; }

case "$TERM" in
    xterm)
	TERM=rxvt; export TERM
	unset TERMINFO
	unset TERMCAP
	;;
esac

exec /opt/mutt/bin/mutt ${1+"$@"}
