#!/bin/sh
#

case $HOST in
    ivie)	echo "DON'T RUN MUTT OR ANY EMAIL ON IVIE!" >&2
		exit 1
		;;
esac

[ -n "$LUSER" ] && [ "x$LUSER" != "x$USER" ] \
	&& { echo "$0: LUSER($LUSER) != USER($USER), aborting" >&2
	     exit 1
	   }

exec /usr/bin/mutt ${1+"$@"}
