#!/bin/sh
#
# Wrapper for otp-md5 which places the response into the cut buffer.
#	- Cameron Simpson <cs@cskk.id.au> 10nov2000
#

otp=$HOME/bin/$ARCH/otp-md5

if resp=`$otp ${1+"$@"}`
then
    [ -n "$DISPLAY" ] && echo "$resp" | xcut
    echo "$resp"
else
    echo "$resp"
    exit 1
fi
