#!/bin/sh
#

stdflags='-Ae +Sr +Wp +Zpe'
colourflags=+CF4
case $X11_DEPTH,$X11_CLASS in
    1,*)	;;
    *,*Gr[ae]y)	colourflags='+Cg' ;;
    *)		colourflags='+C3' ;;
esac

case "$1" in
    x[0-9]*)	n=`expr "$1" : 'x\(.*\)'`; shift
		stdflags="+Ss$n $stdflags"
		;;
esac

# +Cn use colours from default colour map
#
flags="$stdflags $colourflags"

exec nostubs xanim $flags ${1+"$@"}
