#!/bin/sh
#
# BudTool uses a csh wrapper, which has the usual stupidities.
# Purge the PATH before invoking so it doesn't choke.
#	- Cameron Simpson <cs@cskk.id.au> 19may99
#

PATH=/usr/budtool/bin:/usr/bin:/bin
export PATH

exec /usr/budtool/bin/xbt ${1+"$@"}
