#!/bin/sh

for xine in /opt/xine/bin/xine /usr/bin/xine
do  [ -x $xine ] && break
    xine=
done
[ -n "$xine" ] || exit 1

if mkdir test$$
then snapdir=`pwd`
     rmdir test$$
else snapdir=$HOME/private/im/vidcap
fi

set -x
bsed "s^gui.snapshotdir:.*gui.snapshotdir:$snapdir" $HOME/.xine/config
exec "$xine" ${1+"$@"}
