#!/bin/sh
#

xv=
for xvpath in /usr/local/bin/xv /usr/bin/xv /opt/bin/xv
do
  [ -x "$xvpath" ] && { xv=$xvpath; break; }
done
[ -n "$xv" ] || { echo "$0: no xv binary?" >&2; exit 1; }

case $1 in
    -display)	DISPLAY=$2; export DISPLAY; shift; shift ;;
esac

visual=	## "-visual $X11_CLASS"
browse=-lbrowse
case $X11_DEPTH,$X11_CLASS in
    1,*)	set x -fg white -bg black -hi white -lo black ${1+"$@"} ;;
    *,*Gr[ae]y)	visual=
		set x -mono -quick24 -fg grey70 -bg black -hi grey70 -lo grey30 ${1+"$@"} ;;
    *,TrueColor)set x -fg Green -bg Black -hi SlateGrey -lo SlateGrey ${1+"$@"} ;;
    *,*Color)	set x -quick24 -fg Green -bg Black -hi SlateGrey -lo SlateGrey ${1+"$@"} ;;
    *)		set x ${1+"$@"} ;;
esac
shift

set x -stdcmap +vsperfect $visual $browse ${1+"$@"}; shift

# transcribe dirs into subimages
first=1
for arg
do  [ $first ] && { set x; shift; first=; }
    if [ -d "$arg/." ]
    then
	set x ${1+"$@"} "$arg/"*.*
    else
	set x ${1+"$@"} "$arg"
    fi
    shift
done

exec rawx "$xv" ${1+"$@"}
