#!/bin/sh -ue
#
# Emit the next version number, updating the status file.
#       - Cameron Simpson <cs@zip.com.au> 05jan2009
#

cmd=$0
usage="Usage: $cmd versionlog"

[ $# = 1 ] || { echo "$usage" >&2; exit 2; }
logfile=$1
shift

set -ue

lastversion=`tail -1 <"$logfile" | sed 's/ .*//'`
[ -n "$lastversion" ]

today=`date +%Y%m%d`
if [ "x$lastversion" '<' "x$today" ]
then
  version=$today
else 
  if [ "x$lastversion" = "x$today" ]
  then
    version=${today}.2
  else
    case "$lastversion" in
      "$today".[1-9] )
        sfx=`expr "x$lastversion" : "x$today".'\([1-9][0-9]*\).*'`
        version=$today.`expr "$sfx" + 1`
        ;;
      *)
        echo "$cmd: can't compute next version from \"$lastversion\"" >&2
        exit 1
        ;;
    esac
  fi
fi

echo "$version"
