=head1 rlr - replace line range

=keywords edit

=head2 Overview

L<./bin/rlr> replaces a range of lines in a file
with data from another file or stdin.
The range is delimited by a pair of distinctive lines,
typically specially formatted comment lines in the file to be edited.

For example, the main index for this css package
is maintained with this incantation:

	mkpodindex -k -l hrefs \
	| rlr -f '<!--BEGIN AUTOPODINDEX-->' \
	      -t '<!--END AUTOPODINDEX-->' \
	      -i index.html -o index.html -

that places the output of C<mkpodindex>
into the middle of the F<index.html> file.
