#!/bin/sh -u
#
# Connect to my IMAP folder.
#	- Cameron Simpson <cs@zip.com.au> 09sep2003
#

: ${IMAP_SERVICE:=default}

cmd=`basename "$0"`
usage="Usage: $cmd [[user:pass@]server]"

fmrc=$HOME/.fetchmailrc
trace=set-x

[ $# = 0 ] || { IMAP_SERVICE=$1; shift; }

sv_user=
sv_pass=
case "$IMAP_SERVICE" in
  *:*@*)
    sv_user=`expr "x$IMAP_SERVICE" : 'x\([^:]*\):.*'`
    sv_pass=`expr "x$IMAP_SERVICE" : 'x[^:]*:\([^@]*\)@.*'`
    IMAP_SERVICE=`expr "x$IMAP_SERVICE" : 'x[^:]*:[^@]*@\(.*\)'`
    ;;
esac

[ -s "$fmrc" ] || { echo "$cmd: no $fmrc" >&2; exit 1; }

fm_user=
fm_pass=
fm_host=$IMAP_SERVICE
eval `fetchmailclause -f "$fmrc" "$IMAP_SERVICE" | sed -n 'y/	/ /; s/^\([^ ][^ ]*\) /sv_\1=/p'`
[ -n "${sv_user:=}" ] && fm_user=$sv_user
[ -n "${sv_pass:=}" ] && fm_pass=$sv_pass
[ -n "${sv_via:=}"  ] && fm_host=$sv_via

IMAP_FOLDERROOT=imaps://$fm_user@$fm_host/
export IMAP_FOLDERROOT

exec $trace mutt \
        -e "set folder=$IMAP_FOLDERROOT" \
	-e "set imap_pass=\"$fm_pass\"" \
	-f +INBOX
