#!/bin/sh
#
# Run an arbitrary command on my home machine.
#   - Cameron Simpson <cs@zip.com.au>
#

set -ue

: ${HOST:=$(hostname -s)}
: ${HOMEHOST:=}

cmd=$0
usage="Usage: $cmd [command [args...]]"

[ $# = 0 ] || set -- $(basename "$SHELL")

if [ -z "$HOMEHOST" ] || [ "x$HOST" = "x$HOMEHOST" ]
then
  exec "$@"
fi

sshto-proxy-command "$HOMEHOST" \
| \
{ read target proxy_command
  set -- "$target" "$@"
  [ -n "$proxy_command" ] && set -- -o "proxycommand=$proxy_command" "$@"
  set -x
  exec sshx "$@"
}
