#!/bin/sh
#
# Turn URL-escaped %xx markers into characters and then whitespace into
# underscores.
#       - Cameron Simpson <cs@cskk.id.au> 28nov2012
#

[ $# -gt 0 ] || set -- *'%'*
set -x
exec frename 's/%([\da-f][\da-f])/chr(hex($1))/eg; s/\s+/_/g' ${1+"$@"}
