#!/bin/sh
#
# Strip trailing "?..." from filenames, typical in items fetched with wget or the like.
#       - Cameron Simpson <cs@zip.com.au> 17may2014
#

[ $# -gt 0 ] || set -- *'?'*
set -x
exec frename 's/\?.*//' ${1+"$@"}
