#!/bin/sh
#
# Invoke brew in its self contained environment.
# Based on the article here:
# https://gist.github.com/pudquick/29bc95b6c49703992981864e48f8e341
# and the homebrew "untar anywhere" instructions here:
# https://docs.brew.sh/Installation
# - Cameron Simpson <cs@cskk.id.au> 04sep2022
#

set -ue

setx=:
late_setx='set -x'
case ${CPU:-$(uname -p)} in
  arm)  default_homebrewpath=/opt/homebrew ## $HOME/var/homebrew
        ;;
  *)    default_homebrewpath=/usr/local/var/homebrew
        ;;
esac
default_homebrewcore=$default_homebrewpath/core

[ $# -gt 0 ] && [ "x$1" = x-x ] && { setx='set -x' late_setx=:; shift; }

$setx

# git clone of git@github.com:Homebrew/brew
homebrewpath=${CS_HOMEBREW:-$default_homebrewpath}
homebrewpath_git=git@github.com:Homebrew/brew
# git clone of git@github.com:Homebrew/homebrew-core
homebrewcore=${CS_HOMEBREW_CORE:-$default_homebrewcore}
homebrewcore_git=git@github.com:Homebrew/homebrew-core

[ -d "$homebrewpath/bin" ] || \
{ ask "Clone $homebrewpath_git to $homebrewpath" \
  && git clone "$homebrewpath_git" "$homebrewpath"
} || exit 1

[ -d "$homebrewcore/.git" ] || \
{ ask "Clone $homebrewcore_git to $homebrewcore" \
  && git clone "$homebrewcore_git" "$homebrewcore"
} || exit 1

brewexe=$homebrewpath/bin/brew
[ -e "$brewexe" ] || { echo "$0: no $brewexe executable" >&2; exit 1; }

qargv=$( shqstr "$brewexe" ${1+"$@"} )

brewenv=$(
  env - \
    "HOME=$HOME" \
    "HOMEBREW_BREW_GIT_REMOTE=$homebrewpath" \
    "HOMEBREW_CORE_GIT_REMOTE=$homebrewcore" \
    "$brewexe" shellenv
)

$setx
cd "$homebrewpath"
exec env - \
    "HOME=$HOME" \
    "HOMEBREW_BREW_GIT_REMOTE=$homebrewpath" \
    "HOMEBREW_CORE_GIT_REMOTE=$homebrewcore" \
    sh -c "
      $brewenv
      $late_setx
      exec $qargv"
