#!/bin/sh
#
# Run command with default platform minimal environment, plus a little extra.
#       - Cameron Simpson <cs@zip.com.au> 03feb2014
#

set -ue

[ $# -gt 0 ] || set -- env

shcmd=`shqstr "$@"`

set -x
env - sh -c ". /etc/profile
             PATH=/opt/local/bin:/usr/local/bin:$PATH
             export PATH
             set -x
             $shcmd"
