#!/bin/sh
#
# Regenerate my procmailrc files from my cats2procmailrc categories files.
#       - Cameron Simpson <cs@zip.com.au>
#

cd $HOME/rc/mail || exit 1
[ -d cats ] || exit 1
case $# in
  0)	cvsedit "cats.$SYSTEMID" ;;
  1)	$EDITOR "cats/$1" ;;
  *)	echo "Usage: $0 [subfile]" >&2; exit 1;;
esac
touch cats.*
exec env NL='
' myke _all
