#!/bin/sh
#
# Simple script to poll checkip.dyndns.com for the current public IP address.
# - Cameron Simpson <cs@cskk.id.au> 10aug2024
#

wget -q --no-proxy -O - http://checkip.dyndns.com/ | sed -n 's/.*Current IP Address: *\([1-9][0-9.]*[0-9]\).*/\1/p'
