#!/bin/sh
#
# Add new email addresses from a mail message.
#       - Cameron Simpson <cs@zip.com.au> 26apr2008
#

set -ue

[ $# = 1 ] || { echo "Usage: $0 category <message" >&2; exit 2; }

: ${MAILDB:=$HOME/rc/mail/db.csv}
export MAILDB

maildb -m "$MAILDB" learn-addresses "$1"
