#!/bin/sh
#
# Add new email addresses from a mail message.
#       - Cameron Simpson <cs@cskk.id.au> 26apr2008
#

set -ue

cmd=$( basename "$0" )
usage="Usage: $cmd [-tmux] [-quick] category <message"

: ${TMPDIR:=/tmp}

set -x
tmuxbg=
quick=

badopts=

while [ $# -gt 0 ]
do
  case $1 in
    -tmux)  tmuxbg=1 ;;
    -quick) quick=1 ;;
    *)      break ;;
  esac
  shift
done

if [ $# = 0 ]
then
  echo "$cmd: missing category" >&2
  badopts=1
else
  category=$1
  shift
fi

if [ $# -gt 0 ]
then
  echo "$cmd: extra arguments: $*" >&2
  badopts=1
fi

[ $badopts ] && { echo "$usage" >&2; exit 2; }

if [ $tmuxbg ]
then
  tmpf=$TMPDIR/$cmd.$$
  cat >"$tmpf"
  session_name=$( tm pick-new-prefix-session "$cmd" )
  exec tmux new-session -s "$session_name" -d "set -x; $0 $category <'$tmpf'; rm '$tmpf'"
fi

: ${MAILDB:=$HOME/rc/mail/db.csv}
export MAILDB

if [ $quick ]
then
  set -x
  cs-maildb-add-email-quick "$category"
else
  set -x
  maildb -m "$MAILDB" learn-addresses --ungrouped "$category"
  ( maildb -m "$MAILDB" list-groups -AG
    maildb -m "$MAILDB" list-abbreviations -A
  ) | rewriteif -d "$HOME/rc/mutt/aliases-auto"
fi
