#!/usr/bin/env python
#
# Operate on my maildb.
# - Cameron Simpson <cs@cskk.id.au> 27apr2011
#

import sys
sys.path[:] = [ path for path in sys.path if path ]
from cs.app.maildb import main
sys.exit(main(sys.argv))
