#!/usr/bin/env python3
#
# Quick'n'dirty add addresses from a message to the end of the maildb.csv.
#   - Cameron Simpson <cs@zip.com.au> 18sep2016
# 

import os
import sys
from cs.csvutils import SharedCSVFile
from cs.logutils import X
from cs.mailutils import message_addresses, Message
from cs.nodedb.csvdb import write_csv_file

if sys.argv:
  groups = sys.argv
else:
  groups = ('known',)

csvpath = os.environ['MAILDB']
M = Message(sys.stdin, headersonly=True)
addresses = list(message_addresses(M, ['from', 'to', 'cc', 'bcc', 'reply-to']))
csv = SharedCSVFile(csvpath)
with csv.open() as fp:
  for realname, addr in addresses:
    write_csv_file(fp, [('ADDRESS', addr.lower(), {'GROUP': groups})])
