#!/bin/sh

: ${LOGDIR:=$HOME/var/log}
: ${XSESSIONID:=''}
: ${FVWM_PREFIX:=''}

cd
. $HOME/rc/x11/xenv.sh

# dispatch handler for event queue
evlogdir=$LOGDIR/lastvalue
if needdir "$evlogdir"
then
    evlog=$evlogdir/wm-eventlog-$XSESSIONID
    rm -f "$evlog"
    ##>"$evlog"
    ##( tail -f "$evlog" | fvwm-event - & )
fi

case "$OS,$DISPLAY" in
  darwin,/* | darwin,:0 | darwin,:0.* )
    ( quartz-wm --only-proxy & )
    ;;
esac

PATH=$PATH:$fv/bin
PYTHONPATH=$PYTHONPATH:$HOME/rc/python/Fvwmpy
export PATH PYTHONPATH

set -x
case ${VVNC_DEFAULT:-} in
  ?*)   exec twm ;;
  *)    exec fvwm -cmd "PipeRead cs-fvwmrc" ;;  ## ${1+"$@"}
esac

### set up FVWM log/fifo vars
##eval `rigfvwmvars`
##for f in "$FVWMEVLOG" "$FVWMCMDLOG"
##do  >"$f"; rm -f "$f"
##done
