#!/bin/sh
#
# Extract various archive formats.
#   - Cameron Simpson <cs@cskk.id.au> 17dec2002
#

set -ue

: ${TMPDIR:=/tmp}

cmd=`basename "$0"`
usage="Usage: $cmd [-t mimetype] [-|archive]"

mtype=
[ $# -gt 0 ] && [ "x$1" = x-t ] && { mtype=$2; shift; shift; }
[ $# = 0 ] && set -- -
[ $# = 1 ] || { echo "$usage" >&2; exit 2; }
file=$1; shift
[ "x$file" = x- ] && [ -t 0 ] && {
  echo "$cmd: won't read stdin from a tty" >&2
  exit 1
}

case "$mtype" in
  # special handling for tar data
  application/x-tar )
    case "$file" in
      -)    exec untar ;;
      *)    exec untar "$file" ;;
    esac
    ;;
  application/x-tar-bz2 | application/x-tar-gz )
    case "`uname -s`" in
      Darwin)
        # tar understands bz2 and gz directly without options
        case "$file" in
          -)    exec untar ;;
          *)    exec untar "$file" ;;
        esac
        ;;
    esac
    ;;
esac

case "$mtype" in
  # other types look up the mailcap
  ?*)
    unpack=`mailcap -s "$file" "$mtype" unpack` && exec sh -uexc "$unpack"
    decode=`mailcap -s "$file" "$mtype" decode` && {
      sh -uexc "$decode" | "$0" -
      exit $?
    }
    echo "$cmd: unhandled MIME type \"$mtype\"" >&2
    exit 1
    ;;
esac

# special handling for tar data
case "$file" in
  *.tar )
    case "$file" in
      -)    exec untar ;;
      *)    exec untar "$file" ;;
    esac
    ;;
  *.tar.gz | *.tar.bz2 )
    case "`uname -s`" in
      Darwin)
        # tar understands bz2 and gz directly without options
        case "$file" in
          -)    exec untar ;;
          *)    exec untar "$file" ;;
        esac
        ;;
    esac
    ;;
esac

# try to figure out the mime type

if [ "x$file" = x- ]
then
    # sniff stdin, re-exec
    tmpf=$TMPDIR/$cmd$$
    trap 'rm -f "$tmpf"' 0 1 2 13 15
    (umask 077; exec dd bs=1024 count=1 >"$tmpf") || exit 1
        mtype=`file2mime "$tmpf"` \
    || { echo "$cmd: stdin: no MIME type recognised" >&2
         exit 1
       }
    cat "$tmpf" - | "$0" -t "$mtype" -
    exit $?
fi

mtype=`file2mime "$file"` \
|| { echo "$cmd: $file: no MIME type recognised" >&2; exit 1; }

exec "$0" -t "$mtype" "$file"
