#!/bin/sh
#
# Edit something.
#   - Cameron Simpson <cs@cskk.id.au> 02jun2016
#

set -ue

: ${TMPDIR:=/tmp}
: ${FSTAGS_EDITOR:=vim-nowrap}

tmppfx=$TMPDIR/e.$$
trap 'rm -f -- "$tmppfx".*' 0 1 3 15

cmd=$0
usage="Usage:
  $0            Edit the clipboard.
  $0 dirname    Edit the filenames in a directory.
  $0 ...        Invoke editor on ..."

if [ $# = 0 ]
then
  tmpf=$tmppfx.txt
  pbpaste >"$tmpf"
  "$0" "$tmpf"
  [ -s "$tmpf" ] && pbcopy <"$tmpf"
else
  if [ $# = 1 ] && [ -d "$1/." ]
  then
    cd "$1"
    EDITOR="$FSTAGS_EDITOR" fstags edit
    ##erename -a
  else
    if [ -n "${ITERM_SESSION_ID:-}" ]
    then
      # subl ${1+"$@"}
      set-x open -n -W "$@"
    else
      $EDITOR "$@"
    fi
  fi
fi
