#!/bin/sh
#
# Edit something.
#   - Cameron Simpson <cs@zip.com.au> 02jun2016
#

set -ue

if [ $# = 1 ] && [ -d "$1/." ]
then
  erename "$1"/*
else
  if [ -n "${ITERM_SESSION_ID:-}" ]
  then
    subl ${1+"$@"}
  else
    $EDITOR ${1+"$@"}
  fi
fi
