#!/bin/sh
#
# Fix various things. - Cameron Simpson <cs@cskk.id.au> 10jan2025
#

cmd=$0
usage="Usage: $( basename "$cmd" ) [-n] [-q] [-x] [--] things...
  -n    No action. Recite actions.
  -q    Quiet. RUn actions without tracing.
  -x    Trace execution of actions.
  Known things:
    *.py  ruff check --fix"

trace=
[ -t 2 ] && trace=set-x

badopts=

while [ $# -gt 0 ]
do
  case $1 in
    -x) trace=set-x ;;
    -n) trace=echo ;;
    -q) trace= ;;
    --) shift; break ;;
    -?*)echo "$cmd: unrecognised option: $1" >&2
        badopts=1
        ;;
    *)  break ;;
  esac
  shift
done

[ $# -gt 0 ] || {
  echo "$cmd: missing things" >&2
  badopts=1
}

[ $badopts ] && { echo "$usage" >&2; exit 2; }

for thing
do
  case "$thing" in
    *.py)   set -- ruff check --fix "$thing" ;;
    *)      echo "$cmd: how to fix? $thing" >&2
            exit 1
            ;;
  esac
  $trace "$@"
done
