#!/bin/sh
#
# Format standard input like format.
# - Cameron Simpson <cs@cskk.id.au> 02mar2021
#

set -ue

cmd=$0
usage="Usage: $cmd [-n srcfile]"

srcfile=

badopts=

while [ $# -gt 0 ]
do
  case $1 in 
    -n) srcfile=$2; shift ;;
    --) shift; break ;;
    -?*)echo "$cmd: unrecognised option: $1" >&2
        badopts=1
        ;;
    *)  break ;;
  esac
  shift
done

[ $badopts ] && { echo "$usage" >&2; exit 2; }

tmpf=$TMPDIR/$$text
[ -z "$srcfile" ] || tmpf=$tmpf$( basename "$srcfile" )

trap 'rm -f "$tmpf"' 0 1 15

cat >"$tmpf"
format "$tmpf"
cat <"$tmpf"
