#!/bin/sh -ue
#
# Common getWizPnP incantation.
#       - Cameron Simpson <cs@cskk.id.au> 02jan2009
#

set -ue

doit=1
gwhost=${GETWIZ_HOST:-beyonwiz}
regexpopt=
trace=
[ -t 2 ] && trace=set-x

cmd=$0
usage="Usage: $cmd [-n] {index-name|/regexp} [...getwizpnp.pl-options....]
  regexp        Matches against \"servicename#longtitle#date\"
                in a case insensitive fashion.
                Dates are \"Mon.D.YYYY_HH.MM\"
  -h host       Fetch from host. Default from \$GETWIZ_HOST: $gwhost
  -n            No action. Recite matches.
  -x            trace final command execution."

badopts=

while [ $# -gt 0 ]
do
  case $1 in
    -h) gwhost=$2; shift ;;
    -n) doit= ;;
    -x) trace=set-x ;;
    --) shift; break ;;
    -?*)echo "$cmd: unrecognised option: $1" >&2; badopts=1 ;;
    *)  break ;;
  esac
  shift
done

if [ $# = 0 ]
then
  echo "$cmd: missing regexp" >&2
  badopts=1
else
  name=$1
  shift
  case "$name" in
    /*) name=`expr "x$name" : 'x.\(.*\)'`
        regexpopt=--regexp
        ;;
  esac
fi

[ $badopts ] && { echo "$usage" >&2; exit 2; }

set -- -H "$gwhost" --verbose --date --ts $regexpopt "$name" ${1+"$@"}
[ $doit ] || set -- --list ${1+"$@"}

perlscript=`which getWizPnP.pl`
unset http_proxy
unset ftp_proxy

exec $trace perl "$perlscript" ${1+"$@"}
