#!/bin/sh -ue
#
# Record a Git commit.
# - Cameron Simpson <cs@cskk.id.au> 15feb2020
#

set -ue

git log -r '@^..@' \
| \
{
  read _commit revision etc
  unhdr \
  | {
    read -r headline
    wdbase=$( basename "$(pwd)" )
    buglog -- "$wdbase $headline [$revision]" </dev/null
  }
}
