#!/bin/sh
#
# Switch to the desktop number specified.
# OSX recipe from:
#   http://superuser.com/questions/368026/can-i-use-a-terminal-command-to-switch-to-a-specific-space-in-os-x-10-6
# - Cameron Simpson <cs@cskk.id.au> 24jun2015
#

set -ue

cmd=$0
usage="Usage: $cmd desknum"

desknum=$1
shift

case "$OS" in
  darwin)
    case "$desknum" in
      1)    keycode=18 ;;
      2)    keycode=19 ;;
      3)    keycode=20 ;;
      4)    keycode=21 ;;
      5)    keycode=23 ;;
      6)    keycode=22 ;;
      7)    keycode=26 ;;
      8)    keycode=28 ;;
      9)    keycode=25 ;;
      10)   keycode=29 ;;
      *)    echo "$cmd: unsupported desknum: $desknum" >&2
            exit 1
            ;;
    esac
    osascript -e "tell application \"System Events\" to key code $keycode using control down"
    ;;
  *)fvwmcmd "GotoDesk 0 $desknum" &
    ;;
esac
