#!/bin/sh
#
# Convenience script for using pilfer.
#       - Cameron Simpson <cs@zip.com.au> 26dec2011
#

set -ue

usage="Usage: $0 url [selector] [pilfer-url-pre-actions...]"

selector=samedomain

[ $# -gt 0 ] || { echo "$usage" >&2; exit 2; }

url=$1
shift

if [ $# -gt 0 ]
then
  case $1 in
    samedomain | is* )
      selector=$1; shift ;;
  esac
fi

set -x
exec pilfer url "$url" per save_dir= new_dir hrefs samescheme $selector ${1+"$@"} unique save
