#!/bin/sh
#
# Pull from another checkout, merge its tip with ours even across a branch.
#   - Cameron Simpson <cs@zip.com.au> 08sep2014
#

set -ue

cmd=$( basename "$0" )
usage="Usage: $cmd other-checkout"

badopts=

trace=
[ -t 2 ] && trace=set-x

if [ $# = 0 ]
then
  echo "$cmd: missing other-checkout" >&2
  badopts=1
else
  ocheckout=$1
  shift
  if [ ! -d "$ocheckout/." ]
  then
    echo "$cmd: other-checkout not a directory: $ocheckout" >&2
    badopts=1
  fi
fi

if [ $# -gt 0 ]
then
  echo "$cmd: extra arguments after other-checkout: $*" >&2
  badopts=1
fi

[ $badopts ] && { echo "$usage" >&2; exit 2; }

branch=$( hg branch )
obranch=$( incd "$ocheckout" hg branch )

$trace hg fetch "$ocheckout"
if [ "x$branch" != "x$obranch" ]
then
  $trace hg merge "$obranch"
  $trace hg commit -m "merge $obranch ==> $branch"
fi
