#!/bin/sh -ue
#
# Record a Mercurial commit.
#       - Cameron Simpson <cs@cskk.id.au> 25apr2007
#

set -ue

revision=$HG_NODE

hg log -r "$revision" --template='{branch} {desc}\n' --limit 1 \
| \
{ read -r branch headline
  wdbase=$( basename "$(pwd)" )
  dlog log "base=$wdbase" vcs.type=hg "vcs.branch=$branch" "$headline"
}
