#!/bin/sh
#
# Patch /etc/hosts (by default) with 127.0.0.n addresses with names from standard input.
# - Cameron Simpson <cs@cskk.id.au> 10apr2016
#

set -ue
gen-localaddr-hosts | hosts-patch-known -m 'LOCAL ADDRESSES' ${1+"$@"}
