#!/bin/sh
#
# Convenience script to open the portforwarded IBM Integrated
# Management Module HTTP console.
#       - Cameron Simpson <cs@zip.com.au> 18oct2010
#

[ $# -gt 0 ] || { echo "Usage: $0 hosts..." >&2; exit 2; }

set -ue

for host
do
  urlshow "http://$1-mon.local:8000/"
done
