#!/bin/sh
#
# Start a shell on the primary docker service.
# - Cameron Simpson <cs@cskk.id.au> 07apr2020
#

set -ue

cmd=$0
usage="Usage: $cmd [servicename]"

badopts=

if [ $# -gt 1 ]
then
  service=$1
  shift
  set -- -n "$service" ${1+"$@"}
fi

[ $# = 0 ] || {
  echo "$cmd: extra arguments: $*" >&2
  badopts=1
}

[ $badopts ] && { echo "$usage" >&2; exit 2; }

set -x
exec dk ${1+"$@"} exec
