#!/bin/sh
#
# Lowercase a bunch of pathnames.
#	- Cameron Simpson <cs@cskk.id.au>
#

rnopts=
while :
do
  case $1 in
    --)		shift; break ;;
    -?*)	rnopts="$rnopts $1" ;;
    *)		break ;;
  esac
  shift
done

[ $# -gt 0 ] || {
  echo "Usage: $0 filenames..."
  exit 2
}

set -x
exec frename $rnopts -- \
	'if (m:[^/]+$:)
	 { $lhs=$`;
       $_=$&;
	   s/\%([0-9a-f][0-9a-f])/chr(hex($1))/ieg;
	   tr/_&A-Z/-+a-z/;
	   s/[-\s]+/-/g;
	   s/^-/_/;
	   $_=$lhs.$_;
	 }
	' ${1+"$@"}
