#!/bin/sh
#
# Lint the named files.
#   - Cameron Simpson <cs@cskk.id.au> 22apr2017
#

set -ue

trace=
[ -t 2 ] && trace=set-x

cmd=$0
usage="Usage: $cmd filenames..."

[ $# -gt 0 ] || { echo "$cmd: missing filenames" >&2; echo "$usage" >&2; exit 2; }

xit=0

for lintfile
do
  case "$lintfile" in
    *.json)
      $trace json-pprint <"$lintfile" 2>&1 >/dev/null || xit=1
      ;;
    *.go)
      $trace go tool vet -all -shadowstrict "$lintfile" || xit=1
      ;;
    *.php)
      { $trace php -l "$lintfile" \
        && $trace phpcs --standard=PSR2 --report=emacs "$lintfile"
      } || xit=1
      ;;
    *.py)
      { $trace python3 -m py_compile "$lintfile" \
        && $trace pyflakes "$lintfile" \
        && $trace pep8 --ignore=E111,E114,E124,E126,E201,E202,E265,E266,E301,E302,E501,E731,W503 "$lintfile" \
        && $trace pylint --disable=bad-whitespace,invalid-name "$lintfile"
      } || xit=1
      ;;
    *)echo "$cmd: no lint for $lintfile"
      ;;
  esac
done

exit $xit
