#!/bin/sh -ue
#
# Record a Mercurial commit.
#       - Cameron Simpson <cs@cskk.id.au> 25apr2007
#

set -ue

revision=$HG_NODE

hg log -r "$revision" --template='{desc}\n' --limit 1 \
| \
{ read -r headline
  dlog_tags=$( dlog-category )
  [ -z "$dlog_tags" ] || {
    wdbase=$( basename "$(pwd)" )
    dlog -c "$dlog_tags" -- "$wdbase: $headline [$revision]" </dev/null
  }
  exec dlog "commit $headline [$revision]" <
}
