#!/bin/sh -ue
#
# Record a Git commit.
# - Cameron Simpson <cs@cskk.id.au> 15feb2020
#

set -ue

git log -r '@^..@' \
| \
{
  read _commit revision etc
  unhdr \
  | \
  { read -r headline
    dlog_tags=$( fstags ls -d -o '{cs.dlog}' . )
    [ -z "$dlog_tags" ] || {
      wdbase=$( basename "$(pwd)" )
      dlog "$dlog_tags: $wdbase: $revision: $headline" </dev/null
    }
    exec buglog "commit $revision: $headline"
  }
}
