#!/bin/sh -ue
#
# Record a Mercurial commit.
#       - Cameron Simpson <cs@cskk.id.au> 25apr2007
#

set -ue

revision=$HG_NODE

hg log -r "$revision" --template='{desc}\n' --limit 1 \
| \
{ read -r headline
  dlog_tags=$( fstags ls -d -o '{tags[cs.dlog]}' . )
  [ -z "$dlog_tags" ] || {
    wdbase=$( basename "$(pwd)" )
    dlog "$dlog_tags: $wdbase: $headline [$revision]" </dev/null
  }
  exec buglog "commit $headline [$revision]"
}
