#!/bin/sh
#
# Read a mail folder.
# Sync with remote copies first.
# Run self remotely if no local folder.
#       - Cameron Simpson <cs@zip.com.au>
#

set -ue

: ${MAILDIR:=$HOME/mail}
: ${MAIL_EXPIRE_FORMAT:='%Y'}           # versus, say, %Y-%m
: ${MAIL_IMAPSYNC:=}
: ${MAILBOX:=$MAILDIR/INBOX}
: ${SENDMESG_FCC:=spool-out}
export SENDMESG_FCC

cmd=`basename "$0"`
usage="Usage: $cmd [-f] [-I imapsync] [-q] [foldername]
  -C dir Change directory to dir. Default from \$HOME: $HOME
        Implies -l.
  -I imapsync
        Specify remote IMAP for use with imap-sync(1cs).
        Default from \$MAIL_IMAPSYNC: $MAIL_IMAPSYNC
        Supply empty string to prevent sync.
  -l    Run locally. Default is to run remote if not on home machine
        and no local folder.
  -q    Quick imap-sync.
  -r rhost Run remotely, on rhost.
  foldername Default from \$MAILBOX: $MAILBOX"

badopts=

cdto=$HOME
trace=set-x
runlocal=
rhost=$SYSTEMID
imapsyncopts=
foldername=$MAILBOX

while [ $# -gt 0 ]
do
  case "$1" in
    -C) cdto=$2; shift; runlocal=1 ;;
    -I) MAIL_IMAPSYNC=$2; export MAIL_IMAPSYNC; shift ;;
    -l) runlocal=1 ;;
    -r) runlocal= rhost=$2 ;;
    -q) imapsyncopts="$imapsyncopts $1" ;;
    --) shift; break ;;
    -?*)echo "$cmd: unrecognised option: $1" >&2; badopts=1 ;;
    *)  break ;;
  esac
  shift
done

if [ $# -gt 0 ]
then
  foldername=$1
  shift
  [ $# = 0 ] || { echo "$cmd: extra arguments after foldername: $*" >&2
                  badopts=1
                }
fi

case "$foldername" in
  /*) maildir=$foldername ;;
  *)  maildir=$MAILDIR/$foldername ;;
esac
_foldername=`printf '%s\n' "$foldername" | tr / _`
bfoldername=`basename "$foldername"`
old=OLD/`date "+$MAIL_EXPIRE_FORMAT"`
omaildir=$MAILDIR/$old/$bfoldername

# update where to take copies - presumes sendmail=sendmesg-fcc in muttrc
SENDMESG_FCC="$maildir $SENDMESG_FCC"

case "$runlocal" in
  '') # not set - infer from environment
      # not at home? run remote, unless local folder present
      if needhost "$MAILHOMEHOST@$SYSTEMID"
      then  runlocal=1
      else  runlocal=
            { ismbox "$maildir" || ismaildir "$maildir"; } && runlocal=1
      fi
      ;;
esac

if [ $runlocal ] && not ismbox "$maildir" && not ismaildir "$maildir"
then
  echo "$cmd: not a maildir: $maildir" >&2
  badopts=1
fi

[ $badopts ] && { echo "$usage" >&2; exit 2; }

[ $runlocal ] || exec $trace sshx -E -t "$rhost" mailfolder -l -- "$foldername"

cd "$cdto"

if ismbox "$omaildir"
then
  :
else
  ismaildir "$omaildir" || >>"$omaildir"        ## $trace maildir "$omaildir"
fi

[ -n "$MAIL_IMAPSYNC" ] \
&& $trace imap-sync $imapsyncopts "$MAILDIR" "$MAIL_IMAPSYNC" "$foldername" "$old/$foldername" out spool spool-in spool-out

$trace mutt -f "$maildir" -e "set header_cache='$HOME/var/mutt/header-cache+$_foldername'; fcc-hook . $maildir; save-hook . $omaildir"
