#!/usr/bin/env python3
#
# Run the cs.onttags module command line mode.
# - Cameron Simpson <cs@cskk.id.au> 30nov2019
#

import os
import sys
sys.path[:] = [ path for path in sys.path if path ]
from cs.onttags import main
sys.exit(main(sys.argv))
