#!/bin/sh
#
# Push my account to other places.
#	- Cameron Simpson <cs@cskk.id.au>
#

set -ue

cmd=`basename "$0"` || cmd=$0
usage="Usage: $cmd [-f] [-n] [login@]hostname...
  -f  Force. Override source host check.
  -n  No action. Passed to rsync."

hARCH=$ARCH

force=
rsopts=

badopts=

while [ $# -gt 0 ]
do
  case $1 in
    -f)	force=1 ;;
    -n) rsopts="$rsopts $1" ;;
    --)	shift; break ;;
    -?*)echo "$cmd: unrecognised option: $1" >&2; badopts=1 ;;
    *)	break ;;
  esac
  shift
done

[ $# = 0 ] && {
  echo "$cmd: missing login@hostname" >&2
  badopts=1
}

[ $badopts ] && { echo "$usage" >&2; exit 2; }

[ $force ] || needhost -v $HOMEHOST@home || exit 1

(
  set -x
  cd || exit 1
  for hostlist
  do
    syncacc '' "$hostlist:" $rsopts &
  done
  wait
)
