#!/bin/sh
#
# Install local CSS to remote CSS.
#	- Cameron Simpson <cs@cskk.id.au> 18jan2004
#

set -ue

cmd=`basename "$0"` || cmd=$0
usage="Usage: $cmd [-d dstdir] hostlists..."

: ${OPTCSS:=/opt/css}

async=1
srcdir=$OPTCSS
dstdir=$OPTCSS
[ $# -gt 0 ] && [ "x$1" = x-d ] && { dstdir=$2; shift; shift; }
[ $# = 0 ] && { echo "$usage" >&2; exit 2; }

for hostlist
do
  mrsync -iO -aH --delete --delete-excluded --exclude=/release '--exclude=*.pyc' "$srcdir/." "$hostlist:$dstdir/."
done
