#!/bin/sh
#
# Trite convenience wrapper for cs-release.
# - Cameron Simpson <cs@cskk.id.au> 10apr2020
#

set -ue

cmd=$0
usage="Usage: $cmd [module op]"

module=
if [ $# -gt 0 ]
then
  case "$1" in
    cs.*)
      module=$1; shift
      ;;
  esac
  [ -z "$module" ] || {
    [ $# -gt 0 ] || set -- check
    set -- "$@" "$module"
  }
fi

set -x
exec cs-release "$@"
