#!/bin/sh
#
# Construct an unbound.conf(5) file then dispatch unbound(8).
#       - Cameron Simpson <cs@zip.com.au> 26jul2012
#

set -ue

cmd=`basename "$0"`
usage="Usage: $cmd [upstream-forwards...]"

: ${VARRUN:=$HOME/var/run}
: ${LOGDIR:=$HOME/var/log}
: ${UNBOUND_DNS_UPSTREAM:=}     # server set, eg: opennic

me=`id -un`
trace=set-x
pidfile=$VARRUN/unbound.pid
wkdir=$HOME/var/unbound
cf=$wkdir/unbound.conf
log=$LOGDIR/unbound.log
localzones="l local"
localnets="127 192.168 172.16 10.0"
cnames=$HOME/rc/dns/cnames
host_conf=$HOME/rc/dns/unbound.conf-fleet
outgoing_if=$( netstat -rn | awk '$1 == "default" { print $6 }' )
if [ -z "$outgoing_if" ]
then
  netstat -rn >&2
  echo >&2
  echo "$cmd: no outbound interface" >&2
  exit 1
fi
outgoing_ip=$( ifconfig "$outgoing_if" | sed -n 'y/	/ /; s/.* inet  *\([1-9][0-9.]*[0-9]\) .*/\1/p' )
if [ -z "$outgoing_ip" ]
then
  echo "$cmd: no inet addr on interface $outgoing_if" >&2
  ifconfig "$outgoing_if" >&2
  exit 1
fi

# default upstream DNS servers
if [ $# -gt 0 ]
then  lastvalue unbound "$*"
else  set -- `lastvalue unbound`
      echo "$cmd: using lastvalue unbound: $*" >&2
fi

for d in "$VARRUN" "$wkdir" "$LOGDIR"
do  [ -d "$d/." ] || $trace mkdir "$d"
done

tmppfx=$TMPDIR/$cmd.$$
tmpcf=$tmppfx.conf
tmplocal=$tmppfx.local.txt
tidy(){
  rm -f -- "$tmppfx".*
}
trap tidy 0 1 3 15

exec 3>&1 1>"$tmpcf" </dev/null

cat <<X
server:
  directory: "$wkdir"
  do-ip6: no
  username: "$me"
  logfile: "$log"
  pidfile: "$pidfile"
  log-queries: yes
  verbosity: 2      # uncomment and increase to get more logging.
  outgoing-interface: "$outgoing_ip"
  ## # default is "3 2 1 0 0"
  ## target−fetch−policy: "−1 −1 −1 −1 −1"
X

cat "$host_conf"

( while read ip hosts
  do
    case "$ip" in
      '' | \#* ) continue ;;
    esac
    for host in $hosts
    do
      for zone in $localzones
      do
        case "$host" in
          *.$zone)
            hostbase=`basename "$host" ".$zone"`
            echo "$ip $hostbase"
            ;;
          *.*) ;;
          *)echo "$ip $host" ;;
        esac
      done
    done
  done
) </etc/hosts >"$tmplocal"

# forward mappings
for zone in $localzones
do
  echo
  echo "local-zone: \"$zone.\" static"
  awk '{print $2, $1}' <"$tmplocal" \
  | sort -u \
  | \
  while read host ip
  do
    case "$ip" in
      *::*) echo "  local-data: \"$host.$zone. 10 IN AAAA $ip\"" ;;
      *)    echo "  local-data: \"$host.$zone. 10 IN A $ip\"" ;;
    esac
  done
done

# reverse mappings
for zone in $localnets
do
  echo
  echo "local-zone: \"$zone.in−addr.arpa.\" static"
  sort -u <"$tmplocal" \
  | \
  while read ip host
  do
    case "$ip" in
      $zone.*)
        in_addr=
        for octet in `echo $ip | tr . '\012' | reverse`
        do  in_addr=$in_addr$octet.
        done
        for lzone in $localzones
        do
          echo "  local-data: \"${in_addr}in-addr.arpa. 10 IN PTR $host.$lzone.\""
        done
        ;;
    esac
  done
done

if [ -s "$cnames" ]
then
  echo 'local-zone: "cname." static'
  while read cname name
  do
    ipaddrs=`host "$name" | sed -n 's/[^ ][^ ]* has address \([0-9][0-9.]*\)$/\1/p'`
    for ipaddr in $ipaddrs
    do
      echo "  local-data: \"${cname}.cname. 10 IN A ${ipaddr}\""
    done
  done <"$cnames"
fi

if [ $# -gt 0 ]
then
  cat <<X
  forward-zone:
    name: "."
X
  for dnsup
  do
    case "$dnsup" in
      [a-z]*)
        resolv=$HOME/rc/dns/resolv-$dnsup.conf
        $trace sed -n 's/ *#.*//; s/^nameserver  *//p' "$resolv" | shuffle
        ;;
      *)$trace echo "$dnsup"
        ;;
    esac
  done \
  | while read dnsip
    do  echo "    forward-addr: $dnsip"
    done
fi

exec >&3 3>&-

$trace rewriteif -d "$cf" <"$tmpcf"
$trace rm -f "$tmpcf"

set -x
cd "$wkdir"
$trace unbound-checkconf "$cf"
[ ! -f "$pidfile" ] || $trace killpidfile "$pidfile"

tidy
exec $trace sudo $trace unbound -c "$cf"
