#!/bin/sh
#
# Transcode media files.
#   - Cameron Simpson <cs@zip.com.au> 27aug2016
#

set -ue

cmd=$(basename "$0")
usage="Usage: $cmd [-d workdir] media-files..."

trace=set-x
ripped=RIPPED
unripped=UNRIPPED
workdir=.

badopts=

while [ $# -gt 0 ]
do
  case $1 in
    -d) workdir=$2; shift ;;
    --) shift; break ;;
    -?*)echo "$cmd: unrecognised option: $1" >&2
        badopts=1
        ;;
    *)  break ;;
  esac
  shift
done

if [ $# = 0 ]
then
  echo "$cmd: missing media-files" >&2
  badopts=1
fi

if [ ! -d "$workdir/." ]
then
  echo "$cmd: missing workdir: $workdir" >&2
  badopts=1
fi

[ $badopts ] && { echo "$usage" >&2; exit 2; }

wd=$( pwd )

xit=0

for f
do
  f0=$f
  case "$f" in
    /*) ;;
    *)  f=$wd/$f ;;
  esac
  case "$f" in
      *.tvwiz)  set -- beyonwiz mconvert "$f" ;;
      *)        echo "$cmd: unsupported format: $f" >&2
                xit=1
                continue
                ;;
  esac
  if time $trace incd "$workdir" "$@"
  then  mvto=$ripped/$f0
  else  mvto=$unripped/$f0; xit=1
  fi
  mvtodir=$( dirname "$mvto" )
  [ -d "$mvtodir" ] || $trace mkdir "$mvtodir"
  $trace mv -i "$f" "$mvto"
done

exit $xit
