#!/bin/sh
#

set -ue

trace=set-x

: ${HOST:=`hostname -s`}

cmd=$0
usage="Usage: $cmd [-h host] [interfaces...]
  -h host   Local hostname. Default: $HOST"

dir=$HOME/var/rrd/$HOST

[ -d "$dir" ] || $trace mkdir "$dir"

if [ $# = 0 ]
then  netstat -ib
else  for iface
      do  netstat -ib -I "$iface"
      done
fi \
| awk '
    NR > 1 && !seen[$1] && $7 > 0 && $10 > 0 {
        print $1, $7, $10
        seen[$1]=1
    }' \
| \
{
  xit=0
  while read iface bytes_in bytes_out
  do
    rrdfile=$dir/$iface.rrd
    [ -s "$rrdfile" ] || {
      echo "$cmd: $iface: missing RRD file: $rrdfile" >&2
      xit=1
      continue
    }
    $trace rrdtool update "$rrdfile" -t bytes_in:bytes_out "N:$bytes_in:$bytes_out"
  done
  exit $xit
}
