#!/bin/sh
#

set -ue

trace=set-x
rrdstep=10
rrdslots=3153600
create=
host=${HOST:-`hostname -s`}

cmd=$0
usage="Usage: $cmd [-c] [-h host] [--] [interfaces...]
  -c        Create missing RRD tables.
  -h host   Local hostname. Default: $HOST"

badopts=

while [ $# -gt 0 ]
do
  case $1 in
    -c) create=1 ;;
    -h) host=$2; shift ;;
    --) shift; break ;;
    -?*)echo "$cmd: unrecognised option: $1" >&2; badopts=1 ;;
    *)  break ;;
  esac
  shift
done

[ $badopts ] && { echo "$usage" >&2; exit 2; }

dir=$HOME/var/rrd/$HOST

[ -d "$dir" ] || $trace mkdir "$dir"

if [ $# = 0 ]
then  netstat -ib
else  for iface
      do  netstat -ib -I "$iface"
      done
fi \
| awk '
    NR > 1 && !seen[$1] && $7 > 0 && $10 > 0 {
        print $1, $7, $10
        seen[$1]=1
    }' \
| \
{
  xit=0
  while read iface bytes_in bytes_out
  do
    rrdfile=$dir/$iface.rrd
    [ -s "$rrdfile" ] \
    || \
    if [ $create ]
    then
      $trace rrdtool create "$rrdfile" --step "$rrdstep" DS:bytes_in:COUNTER:10:0:U DS:bytes_out:COUNTER:10:0:U "RRA:MAX:0.5:1:$rrdslots"
    else
      echo "$cmd: $iface: missing RRD file: $rrdfile" >&2
      xit=1
      continue
    fi
    $trace rrdtool update "$rrdfile" -t bytes_in:bytes_out "N:$bytes_in:$bytes_out"
  done
  exit $xit
}
