#!/usr/bin/env python3
#
# Shorten a path (the current directory by default) using various criteria.
# - Cameron Simpson <cs@cskk.id.au>
#

import sys

sys.path[:] = [path for path in sys.path if path]
from cs.fs import shortpath

print(shortpath(sys.argv[1], collapseuser=True, foldsymlinks=True))
