#!/bin/sh
#
# Set the screenshot save directory. - Cameron Simpson <cs@cskk.id.au> 28feb2018
#

set -ue

: ${OS:=$(uname -s | tr '[A-Z]' '[a-z]')}

lastvalue=screenshot_dir

cmd=$0
usage="Usage: $cmd [dir]"

badopts=

# no dir? recite current location
[ $# = 0 ] && exec defaults read com.apple.screencapture location

[ $# = 1 ] || { echo "$usage" >&2; exit 2; }
dir=$1; shift

[ -d "$dir/." ] || {
  echo "$cmd: not a directory: $dir" >&2
  exit 1
}

case "$dir" in
  /*) ;; *) dir=$(pwd)/$dir ;;
esac

set -x
lastvalue "$lastvalue" "$dir"
case "$OS" in
  darwin)
    defaults write com.apple.screencapture location "$dir"
    killall SystemUIServer
    ;;
esac
