#!/bin/sh
# TODO: shorthand for "pf ssh"
set -ue
sshopts=
while [ $# -gt 0 ]
do
  case $1 in
    -o) sshopts="$sshopts $1 $2"; shift ;;
    -v) sshopts="$sshopts $1" ;;
    --) shift; break ;;
    -?*)echo "$0: unsupported option: $1"; exit 2 ;;
    *)  break ;;
  esac
  shift
done
sshhost=$1; shift
set -x
exec ssh -F "$HOME/.ssh/config" $sshopts -- "$sshhost-pf" ${1+"$@"}
