#!/bin/sh
#
# Copy a few rc files into the EZOS web tree.
#	- Cameron Simpson <cs@zip.com.au>
#

ezos=$HOME/@/ezos

rrcpath=$ezos/html/cs/rc

pfx "$rrcpath" \
  rsync -i -rptlH --delete --delete-excluded \
	--exclude=CVS/ \
	--include='/mail' \
	--include='/mail/mailcap' \
	--include='/mail/mutt' \
	--exclude='/mail/*' \
	--include='/myke' \
	--include='/myke/*' \
	--include='/perl' \
	--include='/perl/cs' \
	--exclude='/perl/*' \
	--include='/shell' \
	--exclude='/shell/**/hist*' \
	--include='/shell/**' \
	--include='/x11' \
	--include='/x11/session' \
	--include='/x11/xenv.sh' \
	--include='/x11/fvwm' \
	--include='/x11/fvwm/rc' \
	--exclude='*' \
	$HOME/rc/. "$rrcpath/."
