#!/bin/sh
#
# Rsync my account from one place to others.
# Usually I use putacc to call this, but occasionally getacc.
#	- Cameron Simpson <cs@cskk.id.au> 29jun2004
#

set -ue

trace=set-x

cmd=$0
usage="Usage: $cmd from to [rsync-options...]"

syncset=acc

[ $# -ge 2 ] || { echo "$usage" >&2; exit 2; }
from=$1 to=$2; shift; shift

case "$to" in
  *:)   tohosts=`expr "x$to" : 'x\(.*\):'` ;;
  *)    tohosts= ;;
esac

case "$syncset" in
  /* | ./* | ../* ) ;;
  *)  syncset=$HOME/rc/sync/$syncset ;;
esac

cd || exit 1

stripslashes=`shqstr sed '/\/$/d; /^\.L\.\.[Tt]\.\.\.\.\.\. .* -> /d'`

# dosync files_from from to [rsync-options...]
dosync_files()
{ [ $# -ge 3 ] || { echo "$cmd: dosync_files expects at least 3 args" >&2; exit 1; }
  _ds_files=$1
  _ds_from=$2
  _ds_to=$3
  shift; shift; shift
  dosync "$_ds_from" "$_ds_to" "--files-from=$_ds_files" "$@"
}

# dosync from to [rsync-options...]
dosync()
{ [ $# -ge 2 ] || { echo "$cmd: dosync expects at least 2 args" >&2; exit 1; }
  _ds_from=$1
  _ds_to=$2
  shift; shift

  $trace \
    mrsync -rptOHCi --delete \
        '--no-implied-dirs' \
        '--exclude=.DS_Store' \
        '--exclude=.zsh_history' \
        '--exclude=.*.swp' \
        '--exclude=*~' \
        '--exclude=*.tmp' \
        '--exclude=CVS/' \
        '--exclude=*.pyc' \
        '--exclude=__pycache__/' \
        ${1+"$@"} \
        "$_ds_from." "$_ds_to." \
  | fgrep -v ': skipping non-regular file "'
}

# common files
dosync_files "$syncset" "$from" "$to" ${1+"$@"} &

# host specific files
for host in $(hostlist "$tohosts")
do
  ss=$syncset-$host
  [ ! -s "$ss" ] || dosync_files "$ss" "$from" "$host:" ${1+"$@"} &
done

# var subtree
dosync "${from}" "${to}" \
    --include=/bin-local/ \
    --include=/tmp/ \
    --include=/p \
    --include=/private/ \
    --include=/var/ \
    --include=/var/locks/ \
    --include=/var/log/ \
    --include=/var/flags/ \
    --include=/var/haproxy/ \
    --include=/var/idsets/ \
    --include=/var/m4conv/ \
    --include=/var/run/ \
    --include=/var/tmux/ \
    --include=/var/vagrant/ \
    --include=/var/venv/ \
    '--exclude=*' &

wait
