#!/bin/sh
#
# Update my ezoshosting web site.
#	- Cameron Simpson <cs@zip.com.au> 11jan2003

cmd=`basename "$0"`

needhost $HOMEHOST@home

ezos=$HOME/@/ezos
ezoscgi=$ezos/cgi-bin
ezoshtml=$ezos/html
ezoscss=$ezoshtml/cs/css

##syncezos-rc

pfx "$cmd ezos:public_html" \
  qrsync -rptlH --delete \
		--exclude=CVS/ \
		--include=/cs --exclude=/cs/test/ --exclude=/cs/css/optcss \
		--include=/fay \
		--exclude=/* $ezoshtml/. ezos:public_html/.
putcss -d optcss ezos

##syncezos-cgi
##qrsync -aHPW --delete --exclude=CVS/ $ezoscgi/. ezos:cgi-bin/.

putacc ezos
