#!/usr/bin/env python3
#
# My timesheet automation.
# - Cameron Simpson <cs@cskk.id.au> 09nov2021
#

import os
import sys
sys.path[:] = [ path for path in sys.path if path ]
from cs.ts import main
sys.exit(main(sys.argv))
