#!/bin/sh
# - Cameron Simpson <cs@cskk.id.au>
# make linux consoles behave sanely
case "$ARCH" in
  *.x86.linux)
    case "`tty`" in
      /dev/console | \
      /dev/tty[0-9] | \
      /dev/tty[0-9][0-9] | \
      /dev/vc/[0-9] | \
      /dev/vc/[0-9][0-9] )
        loadkeys "$SHDIR/keycodes.linux"
        ;;
    esac
    ;;
esac

stty sane
stty eof '^d'
stty intr '^c' erase '^?' kill '^u'
stty werase '^w' 2>/dev/null
stty susp '^z' 2>/dev/null
stty dsusp '^y' 2>/dev/null
[ -z "${STTY:-}" ] || stty $STTY

[ $# = 0 ] || exec "$@"
