#!/bin/sh

set -ue

: "${VQPATH:=$HOME/dl/v:$HOME/v:$HOME/vv:$HOME/media/video}"

vqpaths=
for d in $( echo "$VQPATH" | tr : ' ' )
do  [ -d "$d" ] && vqpaths="$vqpaths $d/."
done
[ -n "$vqpaths" ] || {
  echo "$0: no directories found to search" >&2
  exit 1
}

[ $# -gt 0 ] || {
  echo "$0: missing words" >&2
  echo "Usage: $0 words..." >&2
  exit 2
}

word1=$1; shift

for vqpath in $vqpaths
do
  if [ -d "$vqpath/." ]
  then
    if [ $# = 0 ]
    then  find "$vqpath" -iname "*${word1}*"
    else  find "$vqpath" -iname "*${word1}*" | grepall -i "$word1" "$@"
    fi
  else
    grepall -i "$word1" ${1+"$@"} < "$vqpath"
  fi
done \
| sort
