#!/bin/sh
#
# Create, push, and discard a WIP branch for visibility.
# - get the current diff, quit if empty
# - stash, make which branch, patch, commit, push
# - switch back, unstash, delete branch
#
# - Cameron Simpson <cs@cskk.id.au> 08nov2025
#

set -ue

cmd=$0
trace=
[ -t 2 ] && trace=set-x

tmppfx=${TMPDIR:-/tmp}/wip-$$
trap 'set -x; rm -f "$tmppfx"*' 0 1 15
diff=$tmppfx.diff

git diff >"$diff"
[ -s "$diff" ] || {
  echo "$cmd: no current diff"
  exit 0
}

modified=$( $trace git status --porcelain | $trace awk '$1 == "M" { print $2 }' )
[ -n "$modified" ] || {
  echo "$cmd: nothing in the modified list but diff not empty?" >&2
  exit 1
}
mfok=1
for mf in $modified
do  [ -f "$mf" ] || {
      echo "$cmd: modified $mf: not a file?" >&2
      mfok=
    }
done
[ $mfok ] || exit 1

branch=$( git branch --show-current )
case "$branch" in
  *:*)  echo "$cmd: cannot use a branch with a colon: $branch" >&2
        exit 1
        ;;
esac
wip_branch=$branch-WIP-noci

if $trace git stash
then
  $trace git co -b "$wip_branch"
  $trace patch -p1 <"$diff"
  $trace git commit -m "WIP for $branch as of `date`" -- $modified
  $trace git push --atomic --force origin "+$branch:refs/heads/$wip_branch"
  $trace git co "$branch"
  $trace git stash pop
  $trace git branch -f -d "$wip_branch"
fi
