#!/bin/sh
#
# Select random screencaps and set MacOS desktop to selection.
# - Cameron Simpson <cs@cskk.id.au> 24dec2022
#

set -ue

cmd=$( basename "$0" )
usage="Usage: $cmd word"

badopts=

if [ $# = 0 ]
then
  echo "$cmd: missing word" >&2
  badopts=1
else
  word=$1; shift
  case "$word" in
    .* | */*) echo "$cmd: slashes and leading dots forbidden in word: $word" >&2; badopts=1 ;;
  esac
  [ $# = 0 ] || { echo "$cmd: extra arguments: $*" >&2; badopts=1; }
fi

[ $badopts ] && { echo "$usage" >&2; exit 2; }

rd=$HOME/im/wp/$word/random

set -x
[ -d "$rd" ] || set-x mkdir "$rd"
cd "$rd"
rm -f ./*.png
ln -s $( find ~/im/screencaps/*"$word"*/ -type f -name \*.png | shuffle | sed 128q ) .
spaces wp . "$rd"
